import { describe,it,expect } from 'vitest';
import { certificateCases,certificateChecks,acceptableCertificate,diagnosisCase,appliedQuestion,appliedScore } from './appliedCrypto';
import { initial,normalizeSave,reward } from './core';
import { canStudyChallenge,lessonMission } from './lessons';
describe('applied cryptographic trust',()=>{
 it('requires all independent checks, not merely matching signature',()=>{const valid=certificateCases[0];expect(acceptableCertificate(valid)).toBe(true);for(const c of certificateCases.slice(1))expect(acceptableCertificate(c)).toBe(false);expect(certificateChecks(certificateCases.find(c=>c.id==='other')!).integrity).toBe(true);expect(certificateChecks(certificateCases.find(c=>c.id==='revoked')!).time).toBe(true)});
 it('checks both time boundaries and detects edits without losing other failures',()=>{const c=certificateCases[0];expect(acceptableCertificate(c,1)).toBe(true);expect(acceptableCertificate(c,10)).toBe(true);expect(acceptableCertificate(c,0)).toBe(false);expect(acceptableCertificate(c,11)).toBe(false);const checks=certificateChecks({...c,trusted:false,status:'unknown'},11,true);expect(checks).toEqual({integrity:false,identity:true,chain:false,purpose:true,time:false,status:false});expect(acceptableCertificate(c,5,true)).toBe(false)});
 it('does not confuse unknown status with revoked and varies diagnosis by difficulty',()=>{const unknown=certificateCases.find(c=>c.id==='unknown')!;expect(unknown.status).not.toBe('revoked');expect(acceptableCertificate(unknown)).toBe(false);expect(['easy','normal','hard'].map(d=>diagnosisCase(d as 'easy'|'normal'|'hard').id)).toEqual(['changed','other','unknown']);for(const d of ['easy','normal','hard'] as const)for(const k of ['purpose','diagnosis','key','content'] as const){const q=appliedQuestion(k,d);expect(q.options[q.correct].pt).toBeTruthy();expect(q.explain.en).toBeTruthy()}});
 it('gates the mission and reinforcement using separate prerequisites',()=>{expect(canStudyChallenge('m18',{},false)).toBe(false);expect(canStudyChallenge('m18',{m17:75},false)).toBe(true);expect(canStudyChallenge('m18',{},true)).toBe(true);expect(canStudyChallenge('m18',{m17:100},true,true)).toBe(false);for(const id of ['m18','s18a','s18b'])expect(lessonMission(id)).toBe('m18')});
 it('migrates v12 and preserves best rewards, denying new IDs under old versions',()=>{const old={...reward(initial,'m17',100,'hard',false),version:12,avatar:3,lang:'en',placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:21});s=reward(s,'m18',75,'easy',false);s=reward(s,'m18',100,'hard',false);expect(s.xp).toBe(400);expect(normalizeSave({...s,version:12})).toBeNull();expect(normalizeSave(s)).toEqual(s);expect(reward(s,'m18',100,'hard',false)).toEqual(s);expect(reward(s,'s18b',50,'hard',true)).toEqual(s);expect(appliedScore([true,true,false,true])).toBe(75);expect(appliedScore([])).toBe(0)});
});
