import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export type CertificateCase={id:string;label:Bilingual;identity:string;trusted:boolean;purpose:boolean;from:number;until:number;status:'good'|'revoked'|'unknown';intact:boolean};
const base={identity:'secretaria.nexus.example',trusted:true,purpose:true,from:1,until:10,status:'good' as const,intact:true};
export const certificateCases:CertificateCase[]=[
 {id:'valid',label:b('Relatório esperado','Expected report'),...base},
 {id:'changed',label:b('Documento alterado','Changed document'),...base,intact:false},
 {id:'expired',label:b('Certificado vencido','Expired certificate'),...base,until:4},
 {id:'other',label:b('Outra identidade','Another identity'),...base,identity:'cantina.nexus.example'},
 {id:'revoked',label:b('Chave comprometida','Compromised key'),...base,status:'revoked'},
 {id:'unknown',label:b('Estado indisponível','Unavailable status'),...base,status:'unknown'},
 {id:'untrusted',label:b('Cadeia não aprovada','Unapproved chain'),...base,trusted:false},
 {id:'purpose',label:b('Uso incompatível','Incompatible use'),...base,purpose:false}
];
export function certificateChecks(c:CertificateCase,day=5,changed=false){return {integrity:c.intact&&!changed,identity:c.identity===base.identity,chain:c.trusted,purpose:c.purpose,time:day>=c.from&&day<=c.until,status:c.status==='good'}}
export function acceptableCertificate(c:CertificateCase,day=5,changed=false){return Object.values(certificateChecks(c,day,changed)).every(Boolean)}
export const checkNames:Record<keyof ReturnType<typeof certificateChecks>,Bilingual>={integrity:b('Assinatura sobre este documento','Signature over this document'),identity:b('Identidade esperada','Expected identity'),chain:b('Cadeia aprovada pela escola','School-approved chain'),purpose:b('Finalidade: assinar relatório','Purpose: sign report'),time:b('Validade no dia consultado','Validity on checked day'),status:b('Estado de revogação conhecido e regular','Known, good revocation status')};
export const appliedScore=(xs:boolean[])=>xs.length?Math.round(xs.filter(Boolean).length/xs.length*100):0;
export const diagnosisCase=(d:Difficulty)=>certificateCases.find(c=>c.id===({easy:'changed',normal:'other',hard:'unknown'}[d]))!;
const make=(prompt:[string,string],options:[string,string][],correct:number,why:[string,string],hint:[string,string]):Question=>q(...prompt,options,correct,why,hint);
export function appliedQuestion(kind:'purpose'|'diagnosis'|'key'|'content',d:Difficulty):Question{
 if(kind==='purpose')return make(d==='easy'?['Assinar um relatório esconde seu conteúdo?','Does signing a report hide its contents?']:['O relatório contém dados pessoais e precisa ter origem e integridade verificáveis. Qual plano combina os objetivos?','The report contains personal data and needs verifiable origin and integrity. Which plan combines the goals?'],[['Assinar apenas; a assinatura também torna o texto secreto.','Sign only; the signature also makes the text secret.'],['Proteger a confidencialidade com cifragem e acesso adequado; usar assinatura para origem/integridade com validação de confiança.','Protect confidentiality with encryption and suitable access; use a signature for origin/integrity with trust validation.'],['Publicar o hash junto ao arquivo em qualquer canal e dispensar controle de acesso.','Publish the hash beside the file anywhere and skip access control.']],1,['Assinatura não oculta o texto. Confidencialidade, integridade e origem são objetivos diferentes; o plano precisa atender a cada finalidade. Um hash sem referência confiável não autentica o remetente.','A signature does not hide text. Confidentiality, integrity and origin are different goals; the plan must meet each purpose. A hash without a trusted reference does not authenticate the sender.'],['Pense em envelope fechado e selo: cada um atende a uma necessidade.','Think of a closed envelope and a seal: each meets a different need.']);
 if(kind==='diagnosis'){
  const why:Record<Difficulty,[string,string]>={easy:['O conteúdo recebido foi alterado: a assinatura original não verifica este documento. Não aceite como íntegro; peça uma versão verificável pelo canal conhecido.','Received content changed: the original signature does not verify this document. Do not accept its integrity; request a verifiable version via a known channel.'],normal:['A assinatura pode corresponder à chave apresentada, mas a identidade não é a secretaria esperada. Confira remetente e finalidade antes de aceitar.','The signature may match the presented key, but its identity is not the expected school office. Check sender and purpose before acceptance.'],hard:['Estado desconhecido não comprova revogação nem regularidade. Neste fluxo, suspenda a aceitação e obtenha informação verificável pelo procedimento da equipe.','Unknown status proves neither revocation nor good standing. In this workflow pause acceptance and obtain verifiable information through the team’s procedure.']};
  return make(['Compare os dados do relatório acima. Qual decisão respeita todas as verificações?','Compare the report data above. Which decision respects all checks?'],[['Aceitar porque a conexão usa HTTPS.','Accept because the connection uses HTTPS.'],['Declarar que a assinatura identifica com certeza a pessoa ao teclado.','Declare the signature certainly identifies the person at the keyboard.'],['Não aceitar automaticamente; tratar a verificação pendente ou falha pelo canal conhecido.','Do not accept automatically; address the pending or failed check through a known channel.']],2,why[d],['Proteção da conexão não substitui verificar o documento e o contexto do certificado.','Connection protection does not replace document and certificate context checks.']);
 }
 if(kind==='key')return make(d==='hard'?['A chave privada de assinatura pode ter sido copiada ontem. Trocar o certificado hoje torna todos os relatórios antigos confiáveis?','A signing private key may have been copied yesterday. Does changing the certificate today make all old reports trustworthy?']:['Há suspeita de cópia da chave privada da secretaria. Qual plano atende ao risco?','The school office’s private key may have been copied. Which plan addresses the risk?'],[['Continuar assinando com a chave antiga até vencer.','Keep signing with the old key until expiry.'],['Compartilhar a chave privada com os leitores para conferirem a assinatura.','Share the private key with readers to verify the signature.'],['Interromper o uso comprometido, acionar revogação e substituição segura, comunicar verificadores e avaliar documentos afetados.','Stop compromised use, initiate revocation and secure replacement, notify verifiers and assess affected documents.']],2,['A chave privada deve ser protegida. A resposta inclui substituir a confiança e avaliar o passado: rotação não apaga assinaturas fraudulentas nem prova quais documentos foram afetados. A pública serve para verificar.','The private key needs protection. Response includes replacing trust and assessing history: rotation neither erases forged signatures nor proves which documents were affected. The public key is used for verification.'],['Separe conter o uso futuro de investigar o que ocorreu antes.','Separate containing future use from investigating what happened before.']);
 return make(['O relatório passa pelas verificações do modelo, mas pede enviar sua senha. O que concluir?','The report passes the model’s checks but asks you to send your password. What should you conclude?'],[['Não enviar a senha; confirmar o pedido pelo canal conhecido. Assinatura não garante conteúdo seguro ou autorização para qualquer ação.','Do not send the password; confirm via a known channel. A signature does not guarantee safe content or authorization for every action.'],['Enviar a senha porque todo conteúdo assinado é seguro.','Send the password because all signed content is safe.'],['Declarar que qualquer assinatura válida impede uso de uma chave roubada.','Declare any valid signature prevents use of a stolen key.']],0,['Validação trata documento, chave e confiança conforme o modelo. O pedido ainda precisa ser avaliado; a chave também pode ter sido usada indevidamente antes da detecção.','Validation addresses document, key and trust according to the model. The request still needs assessment; the key might also have been misused before detection.'],['Pense na ação pedida, além do selo.','Think about the requested action as well as the seal.']);
}
export const appliedQuestions:Record<Difficulty,Question[]>=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,[appliedQuestion('purpose',d),appliedQuestion('key',d),appliedQuestion('content',d)]])) as Record<Difficulty,Question[]>;
export const appliedReview=review(['Um arquivo veio por HTTPS, a assinatura corresponde à chave, mas o certificado identifica a cantina e você esperava a secretaria. Qual conclusão combina as camadas?','A file arrived over HTTPS and its signature matches the key, but the certificate identifies the cafeteria and you expected the school office. Which conclusion combines the layers?'],[['HTTPS e assinatura dispensam conferir identidade.','HTTPS and a signature remove the need to check identity.'],['A conexão está protegida e a assinatura corresponde à chave, mas falta a identidade esperada; verificar pelo canal conhecido antes de aceitar.','The connection is protected and the signature matches the key, but expected identity is missing; check via a known channel before acceptance.'],['A assinatura torna todos os dados secretos e prova autorização.','The signature makes all data secret and proves authorization.'],['A divergência prova quem fez um ataque.','The mismatch proves who carried out an attack.']],1,[['São controles diferentes. Uma conexão protegida pode transportar um documento que não atende à identidade esperada.','These are different controls. A protected connection can carry a document that does not meet expected identity.'],['Você conserva o que foi verificado e reconhece o que falta, sem transformar uma camada em autorização total.','You preserve what was verified and recognize what is missing without turning one layer into complete authorization.'],['Assinatura não oferece confidencialidade por si só nem autoriza qualquer ação.','A signature alone provides neither confidentiality nor authorization for any action.'],['Divergência justifica verificação, não identifica automaticamente autoria humana.','A mismatch warrants checking, not automatic human attribution.']]);
export const appliedFollowup=review(['Após suspeita de vazamento da chave privada, o documento antigo ainda tem assinatura que verifica. Qual resposta evita confiança indevida?','After suspected private-key leakage, an old document still has a signature that verifies. Which response avoids misplaced trust?'],[['Aceitar todo documento antigo e apenas trocar o nome da chave.','Accept every old document and merely rename the key.'],['Publicar a chave privada para todos compararem.','Publish the private key for everyone to compare.'],['Interromper o uso suspeito e seguir revogação/substituição; avaliar período e documentos afetados, sem considerar rotação prova de autenticidade histórica.','Stop suspect use and follow revocation/replacement; assess the affected period and documents without treating rotation as proof of historical authenticity.'],['Declarar todos os arquivos fraudulentos sem investigar.','Declare all files fraudulent without investigation.']],2,[['Renomear não muda material criptográfico nem resolve o possível uso indevido.','Renaming changes neither cryptographic material nor possible misuse.'],['Divulgar a chave privada amplia o comprometimento. Verificadores usam a pública.','Disclosing the private key broadens compromise. Verifiers use the public key.'],['A matemática pode continuar verificando enquanto a confiança na chave foi afetada. Contenção e avaliação do passado atendem problemas distintos.','The mathematics can still verify while trust in the key is affected. Containment and historical assessment address distinct problems.'],['Suspeita não torna todas as hipóteses fatos. Registre limites e investigue.','Suspicion does not make every hypothesis factual. Record limitations and investigate.']]);
