import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import type { Lesson } from './lessons';

export type AccessDemo={session:boolean;tab:boolean;grant:boolean;access:boolean};
export type AccessAction='close'|'open'|'logout'|'expire-session'|'revoke'|'expire-token';
export const newAccessDemo=():AccessDemo=>({session:true,tab:true,grant:true,access:true});
export function accessTransition(s:AccessDemo,a:AccessAction):AccessDemo {
 switch(a){case 'close':return {...s,tab:false};case 'open':return {...s,tab:true};case 'logout':case 'expire-session':return {...s,session:false};case 'revoke':return {...s,grant:false};case 'expire-token':return {...s,access:false};default:return s}
}
export type TokenCard={id:string;kind:'access'|'id'|'refresh';audience:string;scope:string;live:boolean;verified:boolean;label:Bilingual};
export function tokenCards(d:Difficulty,extra=false):TokenCard[]{
 const audience=extra?'photos-api':'calendar-api';const scope=extra?'photos.selected.read':'calendar.read';
 const all:TokenCard[]=[{id:'identity',kind:'id',audience:'study-client',scope:'openid',live:true,verified:true,label:b('ID token · Identidade','ID token · Identity')},{id:'access',kind:'access',audience,scope,live:true,verified:true,label:b('Access token · Recurso solicitado','Access token · Requested resource')},{id:'refresh',kind:'refresh',audience:'authorization-server',scope,live:true,verified:true,label:b('Refresh token · Renovação','Refresh token · Renewal')}];
 if(d!=='easy')all.push({id:'other',kind:'access',audience:'mail-api',scope,live:true,verified:true,label:b('Access token · Outro destinatário','Access token · Other audience')});
 if(d==='hard')all.push({id:'expired',kind:'access',audience,scope,live:false,verified:true,label:b('Access token · Prazo encerrado','Access token · Expired')});
 return all;
}
export function usableToken(token:TokenCard|undefined,audience:string,scope:string){return !!token&&token.kind==='access'&&token.audience===audience&&token.scope===scope&&token.live&&token.verified}
export function tokenReason(token:TokenCard):Bilingual {
 if(token.kind==='id')return b('ID token informa ao cliente OIDC sobre a autenticação. Ele não substitui o access token desta API.','An ID token informs the OIDC client about authentication. It does not replace this API’s access token.');
 if(token.kind==='refresh')return b('Refresh token é apresentado ao servidor de autorização para obter novos tokens, não à API de fotos ou calendário.','A refresh token is presented to the authorization server to obtain new tokens, not to the photos or calendar API.');
 if(!token.live)return b('O prazo terminou. Mesmo com destinatário correto, esse candidato não atende à verificação de validade.','The lifetime ended. Even with the correct audience, this candidate fails the validity check.');
 if(token.id==='other')return b('Este access token foi destinado a mail-api. Um recurso não deve aceitar um token destinado a outro.','This access token was intended for mail-api. A resource should not accept a token intended for another.');
 return b('Este candidato tem finalidade access, destinatário e escopo corretos, prazo vigente e verificação aprovada no cenário. Em sistemas reais, o servidor precisa validar tudo isso.','This candidate has the access purpose, correct audience and scope, a live lifetime and approved verification in the scenario. In real systems the server must validate all of these.');
}
export type ScopeCase={app:Bilingual;purpose:Bilingual;required:string[];options:{id:string;label:Bilingual}[]};
const sc=(id:string,pt:string,en:string)=>({id,label:b(pt,en)});
export function scopeCase(d:Difficulty,extra=false):ScopeCase{
 if(extra)return {app:b('FotoResumo','PhotoSummary'),purpose:b(d==='hard'?'Ler e criar legendas somente nas fotos selecionadas. Não apagar fotos nem ler toda a galeria.':'Ler somente as fotos selecionadas para montar uma prévia. Não editar nem apagar.',d==='hard'?'Read and create captions only on selected photos. Do not delete photos or read the entire gallery.':'Read only selected photos to build a preview. Do not edit or delete.'),required:d==='hard'?['photos.selected.read','photos.selected.write']:['photos.selected.read'],options:[sc('photos.all.read','Ler toda a galeria','Read the whole gallery'),sc('photos.selected.read','Ler fotos selecionadas','Read selected photos'),sc('photos.delete','Apagar fotos','Delete photos'),sc('photos.selected.write','Editar fotos selecionadas','Edit selected photos'),sc('mail.read','Ler e-mails','Read email')]};
 if(d==='hard')return {app:b('Resumo da Equipe','Team Summary'),purpose:b('Ler os arquivos selecionados e gravar o resumo nesses arquivos. Não ler todos os arquivos nem apagar itens.','Read selected files and write the summary into those files. Do not read every file or delete items.'),required:['files.selected.read','files.selected.write'],options:[sc('files.all.read','Ler todos os arquivos','Read all files'),sc('files.selected.write','Gravar nos arquivos selecionados','Write into selected files'),sc('files.delete','Apagar arquivos','Delete files'),sc('files.selected.read','Ler arquivos selecionados','Read selected files'),sc('mail.read','Ler e-mails','Read email')]};
 return {app:b('Agenda de Estudos','Study Planner'),purpose:b(d==='easy'?'Mostrar os próximos eventos do calendário. Não criar, mudar ou apagar eventos.':'Ler o calendário e criar horários de estudo. Não apagar eventos nem ler e-mails.',d==='easy'?'Show upcoming calendar events. Do not create, change or delete events.':'Read the calendar and create study time slots. Do not delete events or read email.'),required:d==='easy'?['calendar.read']:['calendar.read','calendar.create'],options:[sc('calendar.create','Criar eventos','Create events'),sc('calendar.read','Ler calendário','Read calendar'),sc('calendar.delete','Apagar eventos','Delete events'),sc('mail.read','Ler e-mails','Read email')]};
}
export function scopesCorrect(chosen:string[],scenario:ScopeCase){return chosen.length===scenario.required.length&&new Set(chosen).size===chosen.length&&scenario.required.every(s=>chosen.includes(s))}
export function authScore(correct:boolean[]){return correct.length?Math.round(correct.filter(Boolean).length/correct.length*100):0}
export function sessionQuestion(d:Difficulty,extra=false):Question {
 const situations={easy:extra?b('Você terminou de consultar o e-mail no computador compartilhado da biblioteca. Qual ação encerra a sessão atual no serviço?','You finished checking email on the shared library computer. Which action ends the current session at the service?'):b('Você abriu o portal da escola em um computador compartilhado. Antes de sair, como encerrar a sessão atual?','You opened the school portal on a shared computer. Before leaving, how should you end the current session?'),normal:b('Você perdeu um aparelho que mantinha sua conta conectada. Do dispositivo confiável, qual ação trata a sessão daquele aparelho?','You lost a device that kept your account signed in. From a trusted device, which action addresses that device’s session?'),hard:b('A equipe confirmou um incidente que envolve várias sessões da conta. Qual ação trata essas sessões conforme o plano?','The team confirmed an incident involving multiple account sessions. Which action addresses those sessions according to the plan?')};
 return q(situations[d].pt,situations[d].en,[[d==='easy'?'Usar Sair no serviço':'Revogar as sessões afetadas nos controles oficiais',d==='easy'?'Use Sign out at the service':'Revoke affected sessions through official controls'],['Fechar somente a aba neste computador','Only close this computer’s tab'],['Remover apenas o ícone do aplicativo','Only remove the app icon']],0,['Fechar a aba não garante invalidar uma sessão no servidor. Use Sair ou os controles oficiais para sessões afetadas. Em um incidente, siga também as orientações de recuperação da equipe.','Closing a tab does not guarantee invalidating a server session. Use Sign out or official controls for affected sessions. During an incident, also follow the team’s recovery guidance.'],['A sessão existe no serviço; a aba é apenas uma forma de acessá-lo.','The session exists at the service; the tab is only a way to access it.']);
}
export function grantQuestion(d:Difficulty):Question {
 return q(d==='hard'?'Você saiu da conta, mas um app conectado ainda tem autorização para solicitar acesso. A equipe decidiu remover essa autorização. O que fazer?':'Você não usa mais um app conectado que recebeu acesso ao calendário. Como remover sua autorização?',d==='hard'?'You signed out, but a connected app still has authorization to request access. The team decided to remove it. What should you do?':'You no longer use a connected app that received calendar access. How do you remove its authorization?', [['Fechar a aba e supor que o acesso acabou','Close the tab and assume access ended'],['Revogar a autorização do app pelos controles oficiais e conferir o efeito','Revoke the app authorization through official controls and check the effect'],['Enviar seu refresh token ao suporte do app','Send your refresh token to the app’s support']],1,['Sair da sessão e retirar a autorização do app são ações distintas. Revogue pelo serviço oficial. Tokens já emitidos podem continuar até expirar, conforme a arquitetura; dados já copiados não são apagados automaticamente. Nunca compartilhe tokens.','Signing out and removing app authorization are distinct actions. Revoke through the official service. Issued tokens may remain until expiration depending on architecture; copied data is not automatically erased. Never share tokens.'],['Quem recebeu a permissão: sua sessão ou um aplicativo conectado?','Who received permission: your session or a connected application?']);
}
export const authQuestions:Record<Difficulty,Question[]>=Object.fromEntries((['easy','normal','hard'] as const).map(d=>[d,[sessionQuestion(d),grantQuestion(d),q('Um app precisa consultar calendário. Qual credencial tem essa finalidade?','An app needs to query a calendar. Which credential has that purpose?',[['ID token para o cliente','ID token for the client'],['Access token válido para a API e o escopo necessários','Valid access token for the required API and scope'],['Refresh token enviado diretamente ao calendário','Refresh token sent directly to the calendar']],1,['Access token atende ao recurso autorizado; ID token comunica autenticação ao cliente OIDC; refresh token pede novos tokens ao servidor de autorização.','An access token serves the authorized resource; an ID token communicates authentication to the OIDC client; a refresh token requests new tokens from the authorization server.'],['Finalidade, destinatário, escopo e validade precisam combinar.','Purpose, audience, scope and validity must match.'])]])) as Record<Difficulty,Question[]>;
const concept=(pt:string,en:string,textPt:string,textEn:string,sitPt:string,sitEn:string,whyPt:string,whyEn:string,actPt:string,actEn:string)=>({title:b(pt,en),text:b(textPt,textEn),example:b(sitPt,sitEn),walkthrough:{situation:b(sitPt,sitEn),reasoning:b(whyPt,whyEn),action:b(actPt,actEn)}});
export const authLesson:Lesson={id:'m12',intro:b('Você entra no portal da escola e navega sem digitar a senha a cada página. Depois conecta um app à agenda. Como esses acessos continuam funcionando? Vamos separar identidade, sessão e autorização usando exemplos do seu dia a dia.','You sign in to the school portal and browse without typing your password on every page. Then you connect an app to your calendar. How do these accesses keep working? Let’s separate identity, session and authorization through everyday examples.'),practice:b('Feche e reabra a aba fictícia; depois use Sair e compare. Nos cartões, veja a finalidade de cada token. Por fim, escolha só os escopos da tarefa e revogue a autorização: observe que o token emitido não some automaticamente nesta simulação.','Close and reopen the fictional tab; then use Sign out and compare. On the cards, inspect each token’s purpose. Finally, choose only task scopes and revoke authorization: notice that the issued token does not automatically disappear in this simulation.'),concepts:[
 concept('Sessão: continuar depois de entrar','Session: continuity after sign-in','Autenticação verifica quem entrou. Uma sessão mantém o contexto desse acesso; o serviço precisa encerrá-la ou expirá-la conforme suas regras.','Authentication verifies who signed in. A session preserves that access context; the service must end or expire it according to its rules.','Você consulta o portal na biblioteca, fecha a aba e outra pessoa reabre o endereço.','You check the portal at the library, close the tab and another person reopens the address.','Fechar a janela não garante que o servidor invalidou a sessão. Pense em sair de uma sala sem devolver o crachá: a analogia explica continuidade, não todas as regras de um serviço.','Closing the window does not guarantee that the server invalidated the session. Think of leaving a room without returning the badge: the analogy explains continuity, not every service rule.','Use Sair no serviço e confira o encerramento. Em aparelho perdido, use os controles oficiais de sessões a partir de um dispositivo confiável.','Use Sign out at the service and check termination. For a lost device, use official session controls from a trusted device.'),
 concept('Cookie não é sinônimo de senha','A cookie is not the same as a password','Um cookie pode transportar um identificador de sessão. Secure restringe envio a conexões seguras; HttpOnly limita acesso por JavaScript; SameSite ajuda a controlar envio entre sites. São camadas com limites.','A cookie may carry a session identifier. Secure restricts sending to secure connections; HttpOnly limits JavaScript access; SameSite helps control cross-site sending. These are layers with limits.','Um suposto suporte pede que você copie “dados de sessão” do navegador para resolver um erro.','Supposed support asks you to copy browser “session data” to fix an error.','Um identificador pode permitir reaproveitar um acesso sem conhecer sua senha. Essas proteções são configuradas pelo serviço; o aluno não deve desativá-las para atender uma mensagem.','An identifier may enable reuse of access without knowing your password. The service configures these protections; learners should not disable them to satisfy a message.','Não compartilhe cookies, tokens ou capturas que os revelem. Confirme o pedido pelo canal oficial; a aula não pede nenhum dado do seu navegador.','Do not share cookies, tokens or screenshots revealing them. Verify through the official channel; this lesson requests no browser data.'),
 concept('Três tokens, três tarefas','Three tokens, three tasks','Access token é para acessar um recurso autorizado. ID token informa autenticação ao cliente OpenID Connect. Refresh token solicita novos tokens ao servidor de autorização. Não são intercambiáveis.','An access token accesses an authorized resource. An ID token informs an OpenID Connect client about authentication. A refresh token requests new tokens from the authorization server. They are not interchangeable.','Seu app de estudos precisa ler a agenda e continuar funcionando depois que um token de acesso expira.','Your study app needs to read the calendar and continue after an access token expires.','É como ter credenciais com destinatários diferentes: a API recebe o access token; o servidor de autorização pode receber o refresh token. Um ID token não é uma permissão genérica para todas as APIs.','It resembles credentials with different recipients: the API receives the access token; the authorization server may receive the refresh token. An ID token is not generic permission for every API.','Confira finalidade, destinatário, prazo e escopo. Proteja todos os tokens; este jogo mostra apenas cartões fictícios, não valores para copiar.','Check purpose, audience, lifetime and scope. Protect all tokens; this game displays only fictional cards, not values to copy.'),
 concept('JWT: ler não é validar','JWT: reading is not validating','JWT é um formato de claims, informações como emissor, destinatário e prazo. Um JWT assinado normalmente não oculta esses dados. Decodificar seu conteúdo não confirma assinatura ou validade; nem todo token é JWT.','JWT is a format for claims, information such as issuer, audience and expiry. A signed JWT normally does not hide these data. Decoding content does not verify signature or validity; not every token is a JWT.','Um cartão mostra aud: mail-api, mas o app quer acessar o calendário. O texto parece bem formado.','A card shows aud: mail-api, but the app wants calendar access. The text looks well formed.','aud indica o destinatário esperado; exp indica expiração. Uma credencial legível ou bem formada ainda pode ser destinada a outro recurso ou estar vencida.','aud indicates the expected audience; exp indicates expiry. A readable or well-formed credential may still target another resource or be expired.','Na bancada, compare as informações fornecidas. Em um sistema real, a validação exige configuração e bibliotecas confiáveis no serviço, não apenas ler os campos.','On the workbench, compare the supplied information. In a real system validation requires trusted service configuration and libraries, not simply reading fields.'),
 concept('OAuth: delegar com limites','OAuth: delegate with limits','OAuth permite autorizar um app a acessar recursos sem entregar a ele sua senha do serviço. Escopos descrevem o acesso solicitado; confira app, finalidade e o que cada permissão permite.','OAuth allows authorizing an app to access resources without handing it your service password. Scopes describe requested access; check the app, purpose and what each permission allows.','Um organizador só precisa mostrar os próximos compromissos, mas pede também apagar eventos e ler e-mails.','An organizer only needs to show upcoming appointments but also requests deleting events and reading email.','Escopo é o alcance da autorização. Mais acesso não torna a função melhor; dar leitura de calendário não exige permitir exclusão ou consultar sua caixa de entrada.','Scope is the extent of authorization. More access does not improve the function; calendar reading does not require deletion or inbox access.','Conceda só o necessário ou recuse o app se não puder limitar. Na prática, confirme o serviço de autorização e a origem do app antes de aceitar.','Grant only what is necessary or decline the app if access cannot be limited. In practice, confirm the authorization service and app source before accepting.'),
 concept('Login e autorização do app são distintos','Sign-in and app authorization differ','OAuth trata autorização; OpenID Connect acrescenta autenticação. Sair da conta não garante remover o grant, a autorização de um app. Revogação e efeitos em tokens emitidos dependem do serviço.','OAuth concerns authorization; OpenID Connect adds authentication. Signing out does not guarantee removing the grant, an app’s authorization. Revocation and effects on issued tokens depend on the service.','Você parou de usar o organizador e saiu do portal, mas ele ainda aparece nos aplicativos conectados.','You stopped using the organizer and signed out of the portal, but it still appears among connected applications.','Sessão, autorização e tokens têm ciclos diferentes. Retirar a autorização não apaga dados já copiados, e certos tokens emitidos podem continuar até expirar.','Sessions, authorization and tokens have different lifecycles. Removing authorization does not erase copied data, and some issued tokens may remain until expiry.','Revogue pelos controles oficiais e confira o efeito. Para desenvolver integrações, use orientações atuais, como código de autorização com PKCE, que protege a troca desse código; não improvise um fluxo de login.','Revoke through official controls and check the effect. For building integrations use current guidance, such as authorization code with PKCE, which protects that code exchange; do not improvise a sign-in flow.')
 ],checklist:[b('Separe entrar, manter sessão e conceder acesso ao app.','Separate sign-in, maintaining a session and granting app access.'),b('Não compartilhe tokens; confira finalidade e validade.','Do not share tokens; check purpose and validity.'),b('Limite escopos e revise sessões e apps conectados.','Limit scopes and review sessions and connected apps.')],quiz:{prompt:b('Você saiu do portal, mas não usa mais um app que recebeu acesso ao calendário. O que ainda deve conferir?','You signed out of the portal but no longer use an app that received calendar access. What should you still check?'),options:[b('A autorização do app, revogando pelos controles oficiais quando necessário.','The app’s authorization, revoking through official controls when needed.'),b('Nada: fechar qualquer aba remove toda autorização.','Nothing: closing any tab removes all authorization.'),b('Enviar o refresh token ao app para pedir a exclusão.','Send the refresh token to the app to request deletion.')],correct:0,feedback:[b('Isso trata a permissão delegada. Confira também os efeitos em tokens e dados já obtidos; eles não são automaticamente apagados.','This addresses delegated permission. Also check effects on tokens and already obtained data; they are not automatically erased.'),b('A aba, a sessão e o grant são coisas diferentes. A autorização pode continuar existindo depois de sair.','The tab, session and grant are different things. Authorization may remain after signing out.'),b('Tokens são credenciais sensíveis. Use controles oficiais; não entregue um token a quem pedir.','Tokens are sensitive credentials. Use official controls; do not hand a token to someone requesting it.')]},sources:[{label:'OWASP · Sessions',url:'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html'},{label:'RFC 6749 · OAuth',url:'https://www.rfc-editor.org/info/rfc6749/'},{label:'RFC 9700 · OAuth security',url:'https://www.rfc-editor.org/info/rfc9700/'},{label:'OpenID Connect Core',url:'https://openid.net/specs/openid-connect-core-1_0.html'},{label:'RFC 7519 · JWT',url:'https://www.rfc-editor.org/info/rfc7519/'},{label:'RFC 7009 · Revocation',url:'https://www.rfc-editor.org/info/rfc7009/'}]};
