import { b, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export const alerts=[
 {id:'backup',title:b('A01 · Cópia noturna','A01 · Nightly copy'),severity:b('Alta · 40 eventos','High · 40 events'),evidence:b('02:00 UTC · svc-backup leu a pasta de materiais no servidor de backup. A regra detectou muitas leituras.','02:00 UTC · svc-backup read the materials folder on the backup server. The rule detected many reads.')},
 {id:'grades',title:b('A02 · Portal de notas','A02 · Grades portal'),severity:b('Média · 4 eventos','Medium · 4 events'),evidence:b('09:10–09:13 UTC · Conta administrativa: falhas de login, sucesso de origem nova e exportação de notas na mesma sessão. Sem mudança autorizada conhecida. Destino da exportação ainda desconhecido.','09:10–09:13 UTC · Admin account: login failures, success from a new origin and grade export in the same session. No known authorized change. Export destination still unknown.')},
 {id:'sensor',title:b('A03 · Sensor silencioso','A03 · Silent sensor'),severity:b('Sem alerta de ataque','No attack alert'),evidence:b('Notebook da secretaria: último registro às 08:00 UTC. Agora são 10:00 UTC; o coletor esperava um sinal a cada 5 minutos. Estado do aparelho e do agente desconhecido.','Office laptop: last record at 08:00 UTC. It is now 10:00 UTC; the collector expected a signal every 5 minutes. Device and agent status unknown.')}
];
export function triage(id:string,verified:boolean){
 if(id==='grades')return b('Investigar primeiro neste cenário: conta privilegiada, notas sensíveis e sequência inesperada. Escale à equipe responsável e preserve registros. A sessão não identifica a pessoa e exportação não prova saída de dados.','Investigate first in this scenario: privileged account, sensitive grades and unexpected sequence. Escalate to the responsible team and preserve records. The session does not identify the person and export does not prove data left.');
 if(id==='sensor')return b('Verificar a lacuna de visibilidade: saúde do agente, aparelho e caminho de coleta. Ausência de alerta com sensor sem comunicação não demonstra segurança.','Check the visibility gap: agent health, device and collection path. No alert from a disconnected sensor does not demonstrate safety.');
 if(id==='backup')return verified?b('Atividade esperada confirmada: horário, conta, pasta e operação coincidem com a mudança verificada. Menor prioridade nesta fila; documente a correspondência e siga o procedimento de encerramento. Não desative a regra globalmente.','Confirmed expected activity: time, account, folder and operation match the verified change. Lower priority in this queue; document the match and follow the closure procedure. Do not disable the rule globally.'):b('Contexto pendente: o nome svc-backup e o horário não bastam. Verifique autorização e escopo antes de classificar como atividade esperada.','Context pending: the svc-backup name and time are insufficient. Check authorization and scope before classifying as expected activity.');
 return b('Selecione um alerta conhecido.','Select a known alert.');
}
export type BlueKind='priority'|'context'|'visibility'|'handoff';
const scenarios:Record<BlueKind,[string,string][]>= {
 priority:[['A01 tem 40 eventos de uma cópia autorizada verificada; A02 tem 4, mas envolve notas e acesso administrativo inesperado. Qual investigar primeiro?','A01 has 40 events from a verified authorized copy; A02 has 4 but involves grades and unexpected admin access. Which should be investigated first?'],['A01 corresponde à cópia autorizada. A02 correlaciona login inesperado e exportação de notas. A severidade do fornecedor prioriza A01. Qual decisão contextual é melhor?','A01 matches the authorized copy. A02 correlates unexpected login and grade export. Vendor severity ranks A01 higher. Which contextual decision is best?'],['O SIEM classificou A01 como alto e A02 como médio. A01 tem escopo autorizado verificado; A02 envolve conta privilegiada, ativo sensível e sequência inesperada. Há uma analista disponível. Qual prioridade é defensável?','The SIEM rated A01 high and A02 medium. A01 has verified authorized scope; A02 involves a privileged account, sensitive asset and unexpected sequence. One analyst is available. Which priority is defensible?']],
 context:[['O nome da conta é svc-backup. Isso basta para encerrar A01?','The account is named svc-backup. Is that enough to close A01?'],['Há um chamado de backup para 02:00, mas você ainda não verificou conta nem pasta. Pode encerrar A01?','There is a backup ticket for 02:00, but you have not checked account or folder. May you close A01?'],['O chamado autoriza copiar materiais; o alerta mostra acesso adicional a notas, fora do escopo. Como tratar a coincidência de horário?','The ticket authorizes copying materials; the alert shows additional grade access outside scope. How should the matching time be treated?']],
 visibility:[['O sensor do notebook parou de enviar registros. Zero alertas significa que está seguro?','The laptop sensor stopped sending records. Does zero alerts mean it is safe?'],['O painel mostra zero ataques, mas o último sinal do agente foi há duas horas. Qual ação ajuda a interpretar o painel?','The dashboard shows zero attacks, but the agent last reported two hours ago. Which action helps interpret it?'],['O SIEM não recebeu eventos de um ativo crítico, enquanto outras fontes seguem normais. A direção quer declarar ausência de incidentes. Qual avaliação respeita a cobertura?','The SIEM received no events from a critical asset while other sources remain normal. Management wants to declare no incidents. Which assessment respects coverage?']],
 handoff:[['A02 registra exportação, mas o destino é desconhecido. O que informar à próxima analista?','A02 records an export but the destination is unknown. What should you tell the next analyst?'],['A conta administrativa teve login e exportação na mesma sessão. Pode acusar o dono da conta de roubo?','The admin account logged in and exported in the same session. May you accuse its owner of theft?'],['O plantão termina com login inesperado, exportação confirmada, destino e autoria desconhecidos. A contenção precisa de autorização prevista no plano. Qual passagem de caso é adequada?','The shift ends with unexpected login, confirmed export, unknown destination and actor. Containment needs authorization specified by the plan. Which handoff is appropriate?']]
};
const choices:Record<BlueKind,[string,string][]>= {
 priority:[['A01, pois quantidade e rótulo sempre determinam o risco.','A01, because count and label always determine risk.'],['A02: investigar a sequência e o impacto potencial; verificar também a cobertura de A03 e registrar por que A01 é esperado.','A02: investigate sequence and potential impact; also check A03 coverage and record why A01 is expected.'],['Encerrar todos: poucos eventos nunca indicam risco.','Close all: few events never indicate risk.']],
 context:[['Encerrar qualquer evento no mesmo horário.','Close any event at the same time.'],['Desativar a regra para todas as contas.','Disable the rule for all accounts.'],['Conferir conta, horário, recurso e operação com a autorização; investigar divergências e documentar o resultado.','Compare account, time, resource and operation with authorization; investigate mismatches and document the result.']],
 visibility:[['Verificar saúde do sensor e coleta; declarar a lacuna e usar fontes complementares disponíveis.','Check sensor and collection health; state the gap and use available complementary sources.'],['Declarar segurança porque não houve alerta.','Declare safety because there was no alert.'],['Apagar registros antigos para melhorar o painel.','Delete old records to improve the dashboard.']],
 handoff:[['Afirmar autoria pelo nome da conta e apagar os logs.','Assert attribution from the account name and delete logs.'],['Registrar horários UTC, ativo, sessão, fatos, hipóteses e lacunas; preservar evidências e encaminhar ações pelo plano autorizado.','Record UTC times, asset, session, facts, hypotheses and gaps; preserve evidence and route actions through the authorized plan.'],['Desligar toda a escola automaticamente e afirmar exfiltração.','Automatically shut down the entire school and assert exfiltration.']]
};
const explanations:Record<BlueKind,[string,string]>= {
 priority:['Prioridade de triagem combina contexto, impacto potencial e evidência. Contagem e severidade ajudam, mas não substituem essa análise. A ordem é deste cenário, não uma regra universal.','Triage priority combines context, potential impact and evidence. Count and severity help but do not replace analysis. This order belongs to this scenario, not a universal rule.'],
 context:['Uma mudança só explica o que está em seu escopo. Coincidir no horário ou no nome não autoriza acessos extras. Atividade esperada pode acionar uma regra corretamente; documente antes de encerrar.','A change only explains what is in its scope. Matching time or name does not authorize extra access. Expected activity can correctly trigger a rule; document before closing.'],
 visibility:['É como uma câmera desconectada: uma tela vazia não prova que ninguém passou. Verifique se o monitoramento funciona e informe o período sem cobertura.','Like a disconnected camera, an empty screen does not prove nobody passed. Check whether monitoring works and report the coverage gap.'],
 handoff:['A conta usada não prova quem agiu. Exportar dentro do portal não prova transferência externa. A passagem precisa dizer o que foi observado e o que falta verificar, com ações proporcionais e responsáveis.','The account used does not prove who acted. Exporting inside the portal does not prove external transfer. Handoff must state observations and verification gaps, with proportionate actions and owners.']
};
export function blueQuestion(kind:BlueKind,d:Difficulty):Question{return q(...scenarios[kind][{easy:0,normal:1,hard:2}[d]],choices[kind],{priority:1,context:2,visibility:0,handoff:1}[kind],explanations[kind],['Compare evidência, contexto e limite da conclusão.','Compare evidence, context and conclusion limits.'])}
export const blueQuestions=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,(['priority','context','visibility'] as BlueKind[]).map(k=>blueQuestion(k,d))])) as Record<Difficulty,Question[]>;
export const blueReview=review(['Uma cópia autorizada gera 80 leituras. Uma conta privilegiada faz 3 eventos inesperados nas notas. O notebook da secretaria está sem sinal há duas horas. Qual plano melhor usa o tempo do plantão?','An authorized copy generates 80 reads. A privileged account produces 3 unexpected grade events. The office laptop has not reported for two hours. Which plan best uses shift time?'],[['Investigar só o maior número.','Investigate only the largest count.'],['Priorizar a sequência nas notas, verificar a lacuna de coleta e registrar a correspondência da cópia autorizada.','Prioritize the grade sequence, check the collection gap and record the authorized copy match.'],['Encerrar tudo que não tenha severidade alta.','Close anything without high severity.'],['Declarar roubo e autoria pelo nome da conta.','Declare theft and attribution from the account name.']],1,[['Volume não mede sozinho impacto ou urgência.','Volume alone does not measure impact or urgency.'],['Você considerou ativo sensível, comportamento inesperado, cobertura e autorização; preserve os limites da análise.','You considered sensitive assets, unexpected behavior, coverage and authorization; preserve analysis limits.'],['O rótulo pode perder contexto do ativo e a lacuna de coleta.','The label may miss asset context and the collection gap.'],['Os registros não provam destino externo nem identidade da pessoa.','Records prove neither external destination nor the person’s identity.']]);
export const blueFollowup=review(['Um chamado autoriza backup de materiais às 02:00. A conta também leu notas às 02:01. O sensor não registrou o destino da cópia. Qual conclusão é sustentada?','A ticket authorizes a materials backup at 02:00. The account also read grades at 02:01. The sensor did not record the copy destination. Which conclusion is supported?'],[['Tudo é autorizado pelo horário.','Everything is authorized by the time.'],['Sem destino registrado, nada aconteceu.','Without a destination record, nothing happened.'],['A leitura das notas excede o escopo; preservar e investigar essa divergência, deixando destino e autoria em aberto.','Grade reads exceed scope; preserve and investigate this mismatch, leaving destination and attribution open.'],['O dono da conta roubou as notas com certeza.','The account owner certainly stole the grades.']],2,[['O escopo também inclui recurso e operação.','Scope also includes resource and operation.'],['Falta de registro pode ser limitação de cobertura.','Missing records may be a coverage limitation.'],['Você distinguiu fato, autorização e lacuna sem inventar evidência.','You distinguished fact, authorization and gap without inventing evidence.'],['Conta e leitura não demonstram autoria nem saída dos dados.','Account and reads demonstrate neither attribution nor data leaving.']]);
