import AnswerSelection from './AnswerSelection';
import { useEffect, useRef, useState } from 'react';
import { Cloud, FileText, ShieldCheck } from 'lucide-react';
import { useSave, type Difficulty } from './core';
import type { Question } from './content';
import { riskyShare, audienceNames, actorNames, accessReason, cloudAccess, reasonText, shareTask, shareCorrect, accessCase, responsibilityQuestion, incidentQuestion, cloudScore, responsibilityRows, type ShareConfig, type CloudActor, type CloudAction, type ServiceModel } from './cloudSecurity';
function useText(){const lang=useSave(s=>s.save.lang);return (pt:string,en:string)=>lang==='pt'?pt:en}
const actors:CloudActor[]=['nova','orion','lina','iris','visitor'];
const actionNames={read:['Ler','Read'],edit:['Editar','Edit'],reshare:['Criar nova concessão','Create a new grant']} as const;
function PolicySummary({config}:{config:ShareConfig}){const lang=useSave(s=>s.save.lang);const tx=useText();return <div className="cloud-summary"><Cloud size={24}/><div><strong>{audienceNames[config.audience][lang]}</strong><p>{config.role==='read'?tx('Leitura','Read'):tx('Edição','Edit')} · {config.days?`${config.days} ${tx('dia(s)','day(s)')}`:tx('Sem prazo','No expiry')} · {config.delegates?tx('Novas concessões habilitadas','New grants enabled'):tx('Sem novas concessões','No new grants')}</p>{config.audience==='named'&&<small>{config.recipients.map(a=>actorNames[a][lang].split(' · ')[0]).join(', ')||tx('Nenhum destinatário','No recipient')}</small>}</div></div>}
function ShareControls({config,set,disabled=false}:{config:ShareConfig;set:(c:ShareConfig)=>void;disabled?:boolean}){const lang=useSave(s=>s.save.lang);const tx=useText();return <><div className="cloud-controls"><label>{tx('Público do link','Link audience')}<select value={config.audience} disabled={disabled} onChange={e=>set({...config,audience:e.target.value as ShareConfig['audience']})}>{Object.entries(audienceNames).map(([id,name])=><option key={id} value={id}>{name[lang]}</option>)}</select></label><label>{tx('Papel dos destinatários','Recipient role')}<select value={config.role} disabled={disabled} onChange={e=>set({...config,role:e.target.value as ShareConfig['role']})}><option value="read">{tx('Somente ler','Read only')}</option><option value="edit">{tx('Ler e editar','Read and edit')}</option></select></label><label>{tx('Prazo desta concessão','This grant’s lifetime')}<select value={config.days} disabled={disabled} onChange={e=>set({...config,days:Number(e.target.value) as ShareConfig['days']})}><option value="0">{tx('Sem prazo','No expiry')}</option><option value="1">{tx('1 dia','1 day')}</option><option value="7">{tx('7 dias','7 days')}</option></select></label></div>{config.audience==='named'&&<fieldset className="cloud-recipients"><legend>{tx('Destinatários identificados selecionados','Selected identified recipients')}</legend>{(['orion','lina','iris'] as CloudActor[]).map(a=><label className="lesson-toggle" key={a}><input type="checkbox" checked={config.recipients.includes(a)} disabled={disabled} onChange={()=>set({...config,recipients:config.recipients.includes(a)?config.recipients.filter(x=>x!==a):[...config.recipients,a]})}/>{actorNames[a][lang]}</label>)}</fieldset>}<label className="lesson-toggle cloud-delegate"><input type="checkbox" checked={config.delegates} disabled={disabled} onChange={e=>set({...config,delegates:e.target.checked})}/>{tx('Permitir que editores criem novas concessões no serviço','Allow editors to create new grants in the service')}</label><PolicySummary config={config}/></>}
function AccessTester({config,revoked=false}:{config:ShareConfig;revoked?:boolean}){
 const lang=useSave(s=>s.save.lang);const tx=useText();const [actor,setActor]=useState<CloudActor>('visitor');const [action,setAction]=useState<CloudAction>('read');const [elapsed,setElapsed]=useState(0);const reason=accessReason(config,actor,action,elapsed,revoked);const allowed=cloudAccess(config,actor,action,elapsed,revoked);
 return <div className="cloud-test"><h3>{tx('Quem consegue fazer o quê?','Who can do what?')}</h3><div className="cloud-controls"><label>{tx('Identidade de teste','Test identity')}<select value={actor} onChange={e=>setActor(e.target.value as CloudActor)}>{actors.map(a=><option value={a} key={a}>{actorNames[a][lang]}</option>)}</select></label><label>{tx('Ação de teste','Test action')}<select value={action} onChange={e=>setAction(e.target.value as CloudAction)}>{Object.entries(actionNames).map(([id,n])=><option value={id} key={id}>{n[lang==='pt'?0:1]}</option>)}</select></label><label>{tx('Relógio fictício','Fictional clock')}<select value={elapsed} onChange={e=>setElapsed(Number(e.target.value))}><option value="0">{tx('Agora · dia 0','Now · day 0')}</option><option value="2">{tx('Após 2 dias','After 2 days')}</option><option value="8">{tx('Após 8 dias','After 8 days')}</option></select></label></div><div className={'feedback '+(allowed?'good':'')} role="status"><ShieldCheck size={22}/><strong>{allowed?tx('Acesso permitido neste modelo','Access allowed in this model'):tx('Acesso bloqueado neste modelo','Access blocked in this model')}</strong><p>{reasonText[reason][lang]}</p></div><p className="permission-note">{tx('Um arquivo e uma concessão; sem grupos, links adicionais ou permissões herdadas. Identidades fornecidas, sem login real. Acesso muda ao vivo; dados, relógio e ações são fictícios.','One file and one grant; no groups, additional links or inherited permissions. Supplied identities, no real login. Access updates live; data, clock and actions are fictional.')}</p></div>;
}
function ConfigureShare({difficulty,sideIndex=-1,onFinish}:{difficulty:Difficulty;sideIndex?:number;onFinish:(ok:boolean)=>void}){
 const lang=useSave(s=>s.save.lang);const tx=useText();const task=shareTask(difficulty,sideIndex);const [config,setConfig]=useState(riskyShare);const [review,setReview]=useState(false);const correct=shareCorrect(config,task.target);
 return <><h2>{tx('Ajuste o compartilhamento pela finalidade','Set sharing to fit its purpose')}</h2><div className="cloud-file"><FileText size={24}/><div><strong>{task.file[lang]}</strong><p>{task.purpose[lang]}</p></div></div><p>{tx('A configuração inicial dá acesso excessivo. Ajuste os quatro controles e a lista, quando necessária. Confira o acesso de cada identidade antes de confirmar.','The initial configuration grants excessive access. Adjust the four controls and list when needed. Check each identity’s access before confirming.')}</p><ShareControls config={config} set={setConfig} disabled={review}/><AccessTester config={config}/>{review&&<div className={'feedback '+(correct?'good':'')} role="status"><strong>{correct?tx('Compartilhamento adequado à tarefa.','Sharing fits the task.'):tx('Vamos comparar com a finalidade.','Let’s compare with the purpose.')}</strong><p>{task.purpose[lang]}</p><PolicySummary config={task.target}/><p>{tx('Público, destinatários, papel, prazo e delegação precisam combinar. Leitura ainda pode permitir cópias; este modelo não promete impedir capturas.','Audience, recipients, role, lifetime and delegation must fit. Reading may still allow copies; this model does not promise to prevent screenshots.')}</p></div>}<button className="primary" onClick={()=>review?onFinish(correct):setReview(true)}>{review?tx('Concluir etapa','Complete stage'):tx('Confirmar compartilhamento','Confirm sharing')}</button></>;
}
function AccessDiagnosis({difficulty,onFinish}:{difficulty:Difficulty;onFinish:(ok:boolean)=>void}){
 const lang=useSave(s=>s.save.lang);const tx=useText();const c=accessCase(difficulty);const [choice,setChoice]=useState<boolean|null>(null);const [review,setReview]=useState(false);const allowed=cloudAccess(c.config,c.actor,c.action,c.elapsed);const reason=accessReason(c.config,c.actor,c.action,c.elapsed);
 return <><h2>{tx('O link permite esta ação?','Does this link permit this action?')}</h2><PolicySummary config={c.config}/><div className="cloud-file"><strong>{actorNames[c.actor][lang]}</strong><p>{actionNames[c.action][lang==='pt'?0:1]} · {tx('dia','day')} {c.elapsed}</p></div><p>{tx('A pessoa tem o link. Considere identidade, público, papel e prazo nesta concessão única.','The person has the link. Consider identity, audience, role and lifetime for this single grant.')}</p><div className="choices">{[true,false].map(v=><button className={'choice '+(choice===v?'selected':'')} key={String(v)} aria-pressed={choice===v} disabled={review} onClick={()=>setChoice(v)}>{v?tx('Permite','Allows'):tx('Bloqueia','Blocks')}<AnswerSelection selected={choice===v}/></button>)}</div>{review&&<div className={'feedback '+(choice===allowed?'good':'')} role="status"><strong>{allowed?tx('A ação é permitida neste modelo.','The action is allowed in this model.'):tx('A ação é bloqueada neste modelo.','The action is blocked in this model.')}</strong><p>{reasonText[reason][lang]}</p></div>}<button className="primary" disabled={choice===null} onClick={()=>review?onFinish(choice===allowed):setReview(true)}>{review?tx('Concluir etapa','Complete stage'):tx('Conferir acesso','Check access')}</button></>;
}
export function CloudDecision({question,onFinish}:{question:Question;onFinish:(ok:boolean)=>void}){const lang=useSave(s=>s.save.lang);const tx=useText();const [choice,setChoice]=useState<number|null>(null);const [review,setReview]=useState(false);return <><h2>{question.prompt[lang]}</h2><div className="choices">{question.options.map((o,i)=><button key={i} className={'choice '+(choice===i?'selected ':'')+(review?(i===question.correct?'correct':choice===i?'incorrect':''):'')} disabled={review} aria-pressed={choice===i} onClick={()=>setChoice(i)}><span className="choice-letter">{String.fromCharCode(65+i)}</span><span>{o[lang]}</span><AnswerSelection selected={choice===i}/></button>)}</div>{review&&<div className={'feedback '+(choice===question.correct?'good':'')} role="status"><strong>{choice===question.correct?tx('Boa avaliação.','Good assessment.'):tx('Vamos revisar.','Let’s review.')}</strong><p>{question.explain[lang]}</p></div>}<button className="primary" disabled={choice===null} onClick={()=>review?onFinish(choice===question.correct):setReview(true)}>{review?tx('Concluir etapa','Complete stage'):tx('Confirmar decisão','Confirm decision')}</button></>}
function ResponsibilityDemo(){const lang=useSave(s=>s.save.lang);const tx=useText();const [model,setModel]=useState<ServiceModel>('saas');return <><h2>{tx('Quem cuida de cada camada?','Who cares for each layer?')}</h2><label className="cloud-model">{tx('Tipo de serviço','Service model')}<select value={model} onChange={e=>setModel(e.target.value as ServiceModel)}><option value="saas">SaaS · {tx('editor online pronto','ready online editor')}</option><option value="paas">PaaS · {tx('plataforma para seu código','platform for your code')}</option><option value="iaas">IaaS · {tx('máquina virtual','virtual machine')}</option></select></label><div className="cloud-layers">{responsibilityRows(model).map(row=><div key={row.label.en}><strong>{row.label[lang]}</strong><span>{row.owner[lang]}</span></div>)}</div><p className="permission-note">{tx('Comparação simplificada. Há tarefas compartilhadas e variações por produto. Confira a matriz do serviço contratado antes de atribuir responsabilidades.','Simplified comparison. Some tasks are shared and products vary. Check the contracted service matrix before assigning responsibilities.')}</p></>}
export function CloudLessonDemo(){
 const tx=useText();const [tab,setTab]=useState(0);const [config,setConfig]=useState(riskyShare);const [revoked,setRevoked]=useState(false);
 return <><div className="lesson-options"><button className="secondary" aria-pressed={tab===0} onClick={()=>setTab(0)}>{tx('Compartilhar e testar','Share and test')}</button><button className="secondary" aria-pressed={tab===1} onClick={()=>setTab(1)}>{tx('Responsabilidades','Responsibilities')}</button></div><div hidden={tab!==0}><h2>{tx('Bancada do arquivo na nuvem','Cloud file workbench')}</h2><div className="cloud-file"><FileText size={24}/><div><strong>{tx('Boletim fictício · sem dados reais','Fictional report · no real data')}</strong><p>{tx('Compare público, permissão e prazo. Teste Orion, Lina e Iris; todos têm o link, mas suas identidades são diferentes.','Compare audience, permission and time. Test Orion, Lina and Iris; they all have the link, but their identities differ.')}</p></div></div><ShareControls config={config} set={setConfig}/><div className="lesson-options"><button className="secondary" aria-pressed={revoked} onClick={()=>setRevoked(!revoked)}>{revoked?tx('Reabrir concessão fictícia','Reopen fictional grant'):tx('Encerrar concessão fictícia','End fictional grant')}</button><button className="text-button" onClick={()=>{setConfig(riskyShare());setRevoked(false)}}>{tx('Reiniciar configuração','Reset configuration')}</button></div><AccessTester config={config} revoked={revoked}/><p className="lesson-observation">{tx('Encerrar remove esta concessão, preservando o acesso da dona. Em um serviço real, confira outros links e permissões. Uma cópia baixada ou captura continua fora deste controle.','Ending removes this grant, preserving owner access. In a real service check other links and permissions. A downloaded copy or screenshot remains outside this control.')}</p></div><div hidden={tab!==1}><ResponsibilityDemo/></div></>;
}
export function CloudMission({difficulty,id,onFinish}:{difficulty:Difficulty;id:string;onFinish:(score:number)=>void}){
 const tx=useText();const [stage,setStage]=useState(0);const [scores,setScores]=useState<boolean[]>([]);const heading=useRef<HTMLDivElement>(null);const kinds=id==='s14a'?['share0','share1']:id==='s14b'?['responsibility','incident']:['responsibility','share','access','incident'];const kind=kinds[stage];
 useEffect(()=>{if(stage){heading.current?.focus();heading.current?.scrollIntoView({block:'start',behavior:'auto'})}},[stage]);
 function done(ok:boolean){const all=[...scores,ok];if(stage===kinds.length-1)onFinish(cloudScore(all));else{setScores(all);setStage(stage+1)}}
 return <section className="challenge-panel cloud-panel"><div className="crypto-progress" tabIndex={-1} ref={heading}><span>{tx('NUVEM · ACESSO COM PROPÓSITO','CLOUD · PURPOSEFUL ACCESS')}</span><strong>{stage+1} / {kinds.length}</strong></div><div className="bar"><i style={{width:(stage+1)/kinds.length*100+'%'}}/></div>{kind.startsWith('share')?<ConfigureShare key={stage} difficulty={difficulty} sideIndex={kind==='share0'?0:kind==='share1'?1:-1} onFinish={done}/>:kind==='access'?<AccessDiagnosis key={stage} difficulty={difficulty} onFinish={done}/>:<CloudDecision key={stage} question={kind==='responsibility'?responsibilityQuestion(difficulty):incidentQuestion(difficulty)} onFinish={done}/>}</section>;
}
