import { b, type Bilingual, type Difficulty } from './core';
import { q } from './content';
import type { Lesson } from './lessons';
export type Audience='public'|'org'|'named';
export type CloudActor='nova'|'orion'|'lina'|'iris'|'visitor';
export type CloudAction='read'|'edit'|'reshare';
export type ShareConfig={audience:Audience;role:'read'|'edit';days:0|1|7;delegates:boolean;recipients:CloudActor[]};
export const actorNames:Record<CloudActor,Bilingual>={nova:b('Nova · proprietária','Nova · owner'),orion:b('Orion · aluno identificado','Orion · identified student'),lina:b('Lina · aluna identificada','Lina · identified student'),iris:b('Iris · convidada externa identificada','Iris · identified external guest'),visitor:b('Visitante · sem identificação','Visitor · unidentified')};
export const audienceNames:Record<Audience,Bilingual>={public:b('Qualquer pessoa com o link','Anyone with the link'),org:b('Pessoas da escola identificadas','Identified school members'),named:b('Somente pessoas selecionadas','Selected people only')};
export const riskyShare=():ShareConfig=>({audience:'public',role:'edit',days:0,delegates:true,recipients:['orion','lina','iris']});
export function accessReason(c:ShareConfig,actor:CloudActor,action:CloudAction,elapsed:number,revoked=false){
 if(actor==='nova')return 'owner';
 if(revoked)return 'revoked';
 if(c.days!==0&&elapsed>=c.days)return 'expired';
 if(c.audience==='named'&&(actor==='visitor'||!c.recipients.includes(actor)))return 'identity';
 if(c.audience==='org'&&actor!=='orion'&&actor!=='lina')return 'organization';
 if(action==='edit'&&c.role!=='edit')return 'role';
 if(action==='reshare'&&(c.role!=='edit'||!c.delegates))return 'delegation';
 return 'allowed';
}
export function cloudAccess(c:ShareConfig,actor:CloudActor,action:CloudAction,elapsed:number,revoked=false){return ['owner','allowed'].includes(accessReason(c,actor,action,elapsed,revoked))}
export const reasonText={owner:b('Nova é dona do arquivo. Encerrar este compartilhamento não remove o acesso da proprietária.','Nova owns the file. Ending this share does not remove owner access.'),revoked:b('Este compartilhamento foi encerrado. O modelo não tem outra permissão para o destinatário. Cópias já obtidas não são apagadas.','This share ended. The model has no other permission for the recipient. Previously obtained copies are not erased.'),expired:b('O prazo do compartilhamento terminou. Isso encerra esta concessão; não apaga o arquivo nem cópias.','The sharing period ended. This ends this grant; it does not erase the file or copies.'),identity:b('A identidade não está na lista. Ter o link não basta quando o acesso é para pessoas selecionadas.','The identity is not on the list. Having the link is insufficient for selected-person access.'),organization:b('A identidade não pertence à escola neste cenário. Um link da organização não é acesso público.','The identity does not belong to the school in this scenario. An organization link is not public access.'),role:b('O papel permite ler, mas não editar. Ler não impede capturas ou cópias já obtidas.','The role permits reading, not editing. Reading does not prevent screenshots or already obtained copies.'),delegation:b('Criar novas concessões exige edição e delegação habilitada neste modelo. Encaminhar o link existente não muda seu público.','Creating new grants requires edit and enabled delegation in this model. Forwarding the existing link does not change its audience.'),allowed:b('Público, identidade, prazo e ação permitem este acesso. Isso não avalia se o conteúdo ou o pedido é confiável.','Audience, identity, time and action permit this access. This does not assess content or request trustworthiness.')};
export type ShareTask={file:Bilingual;purpose:Bilingual;target:ShareConfig};
const task=(file:Bilingual,purpose:Bilingual,target:ShareConfig):ShareTask=>({file,purpose,target});
export function shareTask(d:Difficulty,sideIndex=-1):ShareTask{
 if(sideIndex===0)return task(b('Cardápio público da feira','Public fair menu'),b('A escola aprovou este cardápio sem dados pessoais para divulgação pública. Qualquer pessoa com o link pode apenas ler, sem prazo e sem criar novas concessões.','The school approved this menu without personal data for public distribution. Anyone with the link may only read, with no expiry and no new grants.'),{audience:'public',role:'read',days:0,delegates:false,recipients:[]});
 if(sideIndex===1)return task(b('Rascunho da apresentação','Presentation draft'),b(d==='hard'?'Somente Iris identificada deve editar por 1 dia. Não permitir novas concessões.':'Somente Orion identificado deve editar por 1 dia. Não permitir novas concessões.',d==='hard'?'Only identified Iris may edit for 1 day. Do not permit new grants.':'Only identified Orion may edit for 1 day. Do not permit new grants.'),{audience:'named',role:'edit',days:1,delegates:false,recipients:[d==='hard'?'iris':'orion']});
 if(d==='hard')return task(b('Comprovante para revisão externa','Receipt for external review'),b('Somente Iris identificada deve ler por 1 dia, sem editar nem criar novas concessões. Orion e Lina não participam desta revisão.','Only identified Iris may read for 1 day, without editing or creating new grants. Orion and Lina are not part of this review.'),{audience:'named',role:'read',days:1,delegates:false,recipients:['iris']});
 if(d==='normal')return task(b('Trabalho da dupla','Pair assignment'),b('Somente Orion e Lina identificados devem editar por 7 dias, sem criar novas concessões. A convidada Iris não participa.','Only identified Orion and Lina may edit for 7 days, without creating new grants. Guest Iris is not involved.'),{audience:'named',role:'edit',days:7,delegates:false,recipients:['orion','lina']});
 return task(b('Boletim do aluno','Student report'),b('Somente Orion identificado deve ler por 7 dias. Não editar nem criar novas concessões; Lina e Iris não devem receber acesso.','Only identified Orion may read for 7 days. No editing or new grants; Lina and Iris must not receive access.'),{audience:'named',role:'read',days:7,delegates:false,recipients:['orion']});
}
export function shareCorrect(c:ShareConfig,t:ShareConfig){return c.audience===t.audience&&c.role===t.role&&c.days===t.days&&c.delegates===t.delegates&&(t.audience!=='named'||(new Set(c.recipients).size===c.recipients.length&&c.recipients.length===t.recipients.length&&t.recipients.every(a=>c.recipients.includes(a))))}
export const cloudScore=(scores:boolean[])=>scores.length?Math.round(scores.filter(Boolean).length/scores.length*100):0;
export function accessCase(d:Difficulty){const config=shareTask(d).target;return d==='easy'?{config,actor:'lina' as CloudActor,action:'read' as CloudAction,elapsed:0}:d==='normal'?{config,actor:'orion' as CloudActor,action:'edit' as CloudAction,elapsed:0}:{config,actor:'iris' as CloudActor,action:'read' as CloudAction,elapsed:2}}
export function responsibilityQuestion(d:Difficulty){return q(d==='easy'?'A escola usa um editor online (SaaS). Quem decide quais alunos podem abrir um boletim?':d==='normal'?'A equipe alugou uma máquina virtual (IaaS). Quem atualiza o sistema operacional instalado nela?':'A equipe publica código próprio numa plataforma gerenciada (PaaS). Quem deve cuidar das permissões e da segurança desse código?',d==='easy'?'The school uses an online editor (SaaS). Who decides which students may open a report?':d==='normal'?'The team rents a virtual machine (IaaS). Who updates its installed operating system?':'The team publishes its own code on a managed platform (PaaS). Who must care for permissions and that code’s security?', [['A equipe cliente cuida dessas configurações e tarefas','The customer team handles these settings and tasks'],['Sempre o provedor, sem ação do cliente','Always the provider, without customer action'],['Ninguém, a nuvem cuida de tudo sozinha','Nobody, the cloud handles everything on its own']],0,['A divisão depende do serviço. Dados, identidades e permissões continuam exigindo cuidados do cliente; numa VM, também o sistema convidado. Consulte as responsabilidades do serviço contratado.','The division depends on the service. Data, identities and permissions still require customer care; in a VM, so does the guest OS. Check the contracted service responsibilities.'],['O que a equipe consegue e precisa administrar neste serviço?','What can and must the team administer in this service?'])}
export function incidentQuestion(d:Difficulty){return q(d==='hard'?'Os registros indicam leitura de um arquivo interno por um link aberto. Você pode conter o acesso. Qual resposta combina contenção e investigação?':'Você percebe que um boletim interno foi compartilhado como público. Qual é a melhor resposta inicial?',d==='hard'?'Logs indicate an internal file was read through an open link. You can contain access. Which response combines containment and investigation?':'You notice an internal report was shared publicly. What is the best initial response?', [['Apagar todos os registros e dizer que nada aconteceu','Erase every log and say nothing happened'],['Restringir ou encerrar o acesso possível, preservar registros e avisar a equipe responsável','Restrict or end access where possible, preserve records and notify the responsible team'],['Ativar criptografia e manter o mesmo link público','Enable encryption and keep the same public link']],1,['Contenha a exposição e preserve indícios para a equipe avaliar alcance e próximos passos. Revogar o link não apaga cópias; criptografia não substitui autorização. Não prometa que ninguém abriu o arquivo sem verificar.','Contain exposure and preserve evidence so the team can assess scope and next steps. Revoking a link does not erase copies; encryption does not replace authorization. Do not promise nobody opened the file without checking.'],['Reduza novos acessos e permita avaliar o que já ocorreu.','Reduce new access and enable assessment of what already happened.'])}
export const cloudQuestions=Object.fromEntries(['easy','normal','hard'].map(d=>[d,[responsibilityQuestion(d as Difficulty),incidentQuestion(d as Difficulty),q('Um arquivo criptografado foi publicado com leitura pública. A criptografia por si só remove esse acesso?','An encrypted file was published with public read access. Does encryption alone remove that access?', [['Sim, criptografia sempre substitui permissões','Yes, encryption always replaces permissions'],['Não, autorização de leitura e criptografia são controles distintos','No, read authorization and encryption are distinct controls'],['Sim, se o nome do link for longo','Yes, if the link name is long']],1,['O serviço pode entregar o conteúdo a quem recebeu autorização. Corrija o público e as permissões; planeje também proteção, registros e recuperação.','The service may deliver content to authorized readers. Correct audience and permissions; also plan protection, logs and recovery.'],['Quem o serviço deixa ler?','Whom does the service allow to read?'])]])) as Record<Difficulty,ReturnType<typeof q>[]>;
export type ServiceModel='iaas'|'paas'|'saas';
export function responsibilityRows(model:ServiceModel){return [{label:b('Segurança física do datacenter','Physical datacenter security'),owner:b('Provedor','Provider')},{label:b('Dados, contas e escolhas de acesso','Data, accounts and access choices'),owner:b('Cliente, usando os controles do serviço','Customer, using service controls')},{label:b('Sistema operacional que sustenta o app','Operating system supporting the app'),owner:model==='iaas'?b('Cliente: sistema convidado da VM','Customer: VM guest OS'):b('Provedor: camada gerenciada','Provider: managed layer')},{label:b('Aplicação','Application'),owner:model==='saas'?b('Provedor opera o app; cliente configura seu uso','Provider operates the app; customer configures its use'):b('Cliente cuida do código e configurações próprios','Customer cares for own code and settings')}]}
function concept(title:Bilingual,text:Bilingual,situation:Bilingual,reasoning:Bilingual,action:Bilingual){return {title,text,example:situation,walkthrough:{situation,reasoning,action}}}
export const cloudLesson:Lesson={id:'m14',intro:b('Você já usa nuvem quando abre um documento online ou guarda fotos num serviço. Os computadores ficam com o provedor, mas alguém ainda precisa decidir quem entra, o que pode fazer e como recuperar os dados. Vamos praticar isso com arquivos fictícios.','You already use cloud when opening an online document or storing photos in a service. Computers are with the provider, but someone must still decide who enters, what they may do and how to recover data. Let’s practice with fictional files.'),practice:b('Comece com o boletim aberto demais. Restrinja o público, escolha os destinatários e teste leitura e edição. Avance o relógio ou encerre o compartilhamento para ver o efeito. Compare também quem cuida de cada camada em SaaS, PaaS e IaaS.','Start with an overshared report. Restrict audience, choose recipients and test reading and editing. Advance the clock or end sharing to see the effect. Also compare who cares for each layer in SaaS, PaaS and IaaS.'),concepts:[
 concept(b('1 · Nuvem: serviço, não lugar mágico','1 · Cloud: a service, not magic'),b('Nuvem usa recursos de um provedor acessados por rede. SaaS entrega um aplicativo; PaaS oferece uma plataforma para seu código; IaaS oferece infraestrutura, como máquinas virtuais.','Cloud uses provider resources accessed over a network. SaaS delivers an app; PaaS offers a platform for your code; IaaS offers infrastructure such as VMs.'),b('Escrever num editor online lembra usar uma sala pronta. Publicar seu próprio app exige mais escolhas. Alugar uma VM exige também cuidar do sistema que você instalou.','Writing in an online editor resembles using a ready room. Publishing your own app requires more choices. Renting a VM also requires caring for the OS you installed.'),b('Quanto mais camadas você administra, mais tarefas precisa assumir. O serviço específico e o contrato definem os detalhes.','The more layers you administer, the more tasks you take on. The specific service and contract define details.'),b('Identifique o tipo de serviço antes de concluir quem atualiza, configura ou recupera cada parte.','Identify the service type before deciding who updates, configures or recovers each part.')),
 concept(b('2 · Responsabilidade compartilhada','2 · Shared responsibility'),b('O provedor protege camadas que opera. O cliente cuida dos dados, identidades e configurações sob seu controle. A divisão muda conforme o serviço.','The provider protects layers it operates. The customer cares for data, identities and settings under its control. The division changes by service.'),b('A escola usa um app de boletins. O provedor mantém a infraestrutura; a escola escolhe quem pode ver a nota de cada aluno.','The school uses a report app. The provider maintains infrastructure; the school chooses who may see each student’s grades.'),b('Uma infraestrutura protegida ainda pode entregar um arquivo a muita gente se o cliente abrir o acesso. Nenhuma das partes resolve tudo sozinha.','Protected infrastructure can still deliver a file to many people if the customer opens access. Neither party handles everything alone.'),b('Confira a matriz do serviço e atribua responsáveis por contas, permissões, atualizações e recuperação.','Check the service matrix and assign owners for accounts, permissions, updates and recovery.')),
 concept(b('3 · Link e identidade são diferentes','3 · Link and identity differ'),b('Um link público pode chegar a qualquer pessoa. Um acesso para identidades selecionadas exige que o serviço reconheça um destinatário autorizado. “Da organização” ainda pode incluir muitas pessoas.','A public link may reach anyone. Selected-identity access requires the service to recognize an authorized recipient. “Organization” may still include many people.'),b('Você manda o boletim de Orion a ele. Se o link for público, pode ser encaminhado a Lina. Se só Orion identificado tiver acesso, possuir o link não basta para Lina.','You send Orion his report. A public link can be forwarded to Lina. If only identified Orion has access, having the link is insufficient for Lina.'),b('Endereço difícil de adivinhar não equivale a autorização. O público precisa combinar com a finalidade do arquivo.','A hard-to-guess address is not authorization. Audience must fit file purpose.'),b('Use pessoas específicas para dados internos e teste com uma identidade que não deveria entrar. Um cardápio aprovado para divulgação pode ser público.','Use specific people for internal data and test with an identity that should not enter. A menu approved for distribution may be public.')),
 concept(b('4 · Menor privilégio e prazo','4 · Least privilege and time'),b('Ler, editar e criar novos acessos têm efeitos diferentes. Conceda o necessário à tarefa e revise prazo e destinatários; recursos disponíveis variam entre serviços.','Reading, editing and creating new access have different effects. Grant what the task needs and review time and recipients; available features vary by service.'),b('Iris só precisa conferir um comprovante por um dia. Permitir edição, acesso de toda a escola e duração ilimitada amplia a exposição sem ajudar a revisão.','Iris only needs to review a receipt for one day. Editing, whole-school access and unlimited duration expand exposure without helping review.'),b('Permissão de leitura não impede capturas ou cópias. Proibir novas concessões no app não impede alguém de encaminhar o link que já existe.','Read permission does not prevent screenshots or copies. Preventing new grants in the app does not stop someone forwarding an existing link.'),b('Selecione destinatários, papel e prazo adequados. Na bancada, “novas concessões” controla delegação no serviço fictício, não todas as formas de compartilhar.','Select suitable recipients, role and time. In the workbench “new grants” controls delegation in the fictional service, not all sharing methods.')),
 concept(b('5 · Proteção e recuperação em camadas','5 · Layered protection and recovery'),b('Criptografia, autorização e cópias de recuperação atendem necessidades diferentes. Sincronização pode propagar uma exclusão; verifique versões, retenção e restauração.','Encryption, authorization and recovery copies meet different needs. Sync can propagate deletion; check versions, retention and restoration.'),b('Uma pasta sincronizada foi apagada e sumiu também do outro computador. Ter duas telas mostrando a mesma pasta não significava ter um backup independente.','A synced folder was deleted and also disappeared from the other computer. Two screens showing the same folder did not mean an independent backup existed.'),b('Criptografar não corrige um público excessivo. Disponibilidade do provedor não promete recuperação de toda exclusão ou configuração errada.','Encryption does not correct excessive audience. Provider availability does not promise recovery from every deletion or misconfiguration.'),b('Restrinja acessos, proteja contas e planeje recuperação. Confira os recursos do serviço e teste restauração com dados de treino.','Restrict access, protect accounts and plan recovery. Check service features and test restoration with practice data.')),
 concept(b('6 · Conter e entender uma exposição','6 · Contain and understand exposure'),b('Se um arquivo interno ficar aberto, reduza novos acessos, preserve registros e acione a equipe responsável. Avalie alcance sem apagar indícios nem prometer que a exposição acabou completamente.','If an internal file is open, reduce new access, preserve logs and involve the responsible team. Assess scope without erasing evidence or promising exposure has fully ended.'),b('Você percebe que a planilha da turma usa “qualquer pessoa”. Encerra o link possível e avisa a escola, mantendo as informações de quando e como ocorreu.','You notice the class spreadsheet uses “anyone”. You end the link where possible and notify the school, keeping information on when and how it happened.'),b('Revogar uma concessão não apaga cópias nem outras permissões. Registros ajudam a avaliação, mas sua ausência não prova que ninguém abriu.','Revoking a grant erases neither copies nor other permissions. Logs help assessment, but their absence does not prove nobody opened it.'),b('Revise também acessos diretos, grupos e outros links no serviço real. Siga o fluxo de incidente da organização.','Also review direct access, groups and other links in the real service. Follow the organization’s incident process.'))
 ],checklist:[b('Identifique serviço e responsabilidades.','Identify service and responsibilities.'),b('Escolha público, destinatários, papel e prazo pela finalidade.','Choose audience, recipients, role and time by purpose.'),b('Teste acesso e recuperação; preserve registros se houver exposição.','Test access and recovery; preserve logs if exposure occurs.')],quiz:{prompt:b('Você encerrou um link público. Isso apaga uma cópia que alguém já baixou?','You ended a public link. Does that erase a copy someone already downloaded?'),options:[b('Sim, o provedor apaga todas as cópias externas.','Yes, the provider erases every external copy.'),b('Não. Encerra essa concessão; cópias e outros acessos precisam de avaliação.','No. It ends that grant; copies and other access need assessment.'),b('Sim, se o arquivo estiver criptografado no serviço.','Yes, if the file is encrypted in the service.')],correct:1,feedback:[b('A revogação atua na concessão no serviço, não controla uma cópia já obtida fora dele.','Revocation acts on the service grant, not a copy already obtained outside it.'),b('Correto. Contenha novos acessos e permita que a equipe avalie a exposição.','Correct. Contain new access and let the team assess exposure.'),b('Criptografia no serviço não apaga automaticamente uma cópia recebida por alguém.','Service encryption does not automatically erase a copy received by someone.')]},sources:[{label:'Microsoft · Shared responsibility',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/shared-responsibility'},{label:'AWS · Shared responsibility',url:'https://aws.amazon.com/compliance/shared-responsibility-model/'},{label:'Microsoft · Sharing links',url:'https://support.microsoft.com/en-us/onedrive/share-files-and-folders-in-microsoft-onedrive'},{label:'Google Drive · Stop or limit sharing',url:'https://support.google.com/drive/answer/2494893'},{label:'AWS S3 · Block public access',url:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html'}]};
