import { describe, expect, it } from 'vitest';
import { riskyShare, cloudAccess, accessReason, shareTask, shareCorrect, accessCase, cloudScore, responsibilityRows, cloudLesson } from './cloudSecurity';
import { initial, normalizeSave, reward } from './core';
import { lessonMission, canStudyChallenge } from './lessons';
describe('closed cloud sharing laboratory',()=>{
 it('separates public, organization and identified-recipient access',()=>{const c=shareTask('easy').target;expect(cloudAccess(c,'orion','read',0)).toBe(true);for(const a of ['lina','iris','visitor'] as const)expect(cloudAccess(c,a,'read',0)).toBe(false);expect(cloudAccess({...c,audience:'org'},'lina','read',0)).toBe(true);expect(cloudAccess({...c,audience:'org'},'iris','read',0)).toBe(false);expect(cloudAccess({...c,audience:'public'},'visitor','read',0)).toBe(true)});
 it('requires editing and explicit delegation for creating new grants',()=>{const c=shareTask('normal').target;expect(cloudAccess(c,'orion','edit',0)).toBe(true);expect(cloudAccess(c,'orion','reshare',0)).toBe(false);expect(cloudAccess({...c,delegates:true},'orion','reshare',0)).toBe(true);expect(cloudAccess({...c,role:'read',delegates:true},'orion','reshare',0)).toBe(false);expect(cloudAccess({...c,role:'read'},'orion','edit',0)).toBe(false)});
 it('expires exactly at lifetime and revokes recipients without affecting the owner',()=>{const c=shareTask('hard').target;expect(cloudAccess(c,'iris','read',0)).toBe(true);expect(accessReason(c,'iris','read',1)).toBe('expired');expect(cloudAccess({...c,days:0},'iris','read',800)).toBe(true);expect(accessReason(c,'iris','read',0,true)).toBe('revoked');for(const action of ['read','edit','reshare'] as const)expect(cloudAccess(c,'nova',action,800,true)).toBe(true)});
 it('requires correct purpose, recipients and controls without duplicates or extras',()=>{for(const d of ['easy','normal','hard'] as const){const target=shareTask(d).target;expect(shareCorrect(target,target)).toBe(true);expect(shareCorrect({...target,recipients:[...target.recipients].reverse()},target)).toBe(true);expect(shareCorrect(riskyShare(),target)).toBe(false);expect(shareCorrect({...target,recipients:[...target.recipients,'visitor']},target)).toBe(false);expect(shareCorrect({...target,recipients:[...target.recipients,target.recipients[0]]},target)).toBe(false);expect(shareCorrect({...target,days:0},target)).toBe(false);expect(shareCorrect({...target,delegates:true},target)).toBe(false)}});
 it('permits deliberately public material and changes diagnosis by difficulty',()=>{const c=shareTask('easy',0).target;expect(c.audience).toBe('public');expect(cloudAccess(c,'visitor','read',0)).toBe(true);expect(cloudAccess(c,'visitor','edit',0)).toBe(false);expect(['easy','normal','hard'].map(d=>{const c=accessCase(d as 'easy'|'normal'|'hard');return cloudAccess(c.config,c.actor,c.action,c.elapsed)})).toEqual([false,true,false])});
 it('changes guest OS ownership with service model while keeping customer data choices',()=>{expect(responsibilityRows('iaas')[2].owner.en).toContain('Customer');expect(responsibilityRows('paas')[2].owner.en).toContain('Provider');expect(responsibilityRows('saas')[2].owner.en).toContain('Provider');for(const m of ['iaas','paas','saas'] as const)expect(responsibilityRows(m)[1].owner.en).toContain('Customer')});
 it('migrates v8 while protecting old ID limits and best XP rewards',()=>{const old={...reward(initial,'m13',100,'hard',false),version:8,avatar:2,lang:'en',placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:21});s=reward(s,'m14',75,'easy',false);s=reward(s,'m14',100,'hard',false);s=reward(s,'s14a',100,'normal',true);expect(s.xp).toBe(450);expect(reward(s,'s14b',50,'hard',true)).toEqual(s);expect(reward(s,'m14',100,'hard',false)).toEqual(s);expect(normalizeSave({...s,version:8})).toBeNull();expect(normalizeSave(s)).toEqual(s);expect(cloudScore([true,true,false,true])).toBe(75);expect(cloudScore([true,false])).toBe(50)});
 it('routes new lessons and maintains campaign and reinforcement prerequisites',()=>{for(const id of ['m14','s14a','s14b'])expect(lessonMission(id)).toBe('m14');expect(canStudyChallenge('m14',{},false)).toBe(false);expect(canStudyChallenge('m14',{m13:75},false)).toBe(true);expect(canStudyChallenge('m14',{},true)).toBe(true);expect(canStudyChallenge('m14',{},true,true)).toBe(false);expect(canStudyChallenge('m14',{m14:75},false,true)).toBe(true);for(const c of cloudLesson.concepts)for(const lang of ['pt','en'] as const){expect(c.walkthrough?.situation[lang]).toBeTruthy();expect(c.walkthrough?.reasoning[lang]).toBeTruthy();expect(c.walkthrough?.action[lang]).toBeTruthy()}});
});
