import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import type { Lesson } from './lessons';
export type ShellConfig={directory:string;file:string;filter:boolean;relative:boolean};
export type ShellState={cwd:string;located:boolean;listed:boolean;moved:boolean;read:boolean;filtered:boolean};
export function shellConfig(d:Difficulty,extra=false):ShellConfig{return {directory:extra?'docs':'logs',file:extra?(d==='easy'?'team guide.txt':'team [guide].txt'):(d==='easy'?'access log.txt':'access [review].txt'),filter:d==='hard',relative:d!=='easy'}}
export function newShell():ShellState{return {cwd:'C:\\NEXUS',located:false,listed:false,moved:false,read:false,filtered:false}}
export function absoluteFile(c:ShellConfig){return `C:\\NEXUS\\${c.directory}\\${c.file}`}
export function shellCommands(c:ShellConfig){const path=c.relative?c.file:absoluteFile(c);return ['Get-Location','Get-ChildItem',`Set-Location ${c.directory}`,`Get-Content -LiteralPath '${path}'`,...(c.filter?[`Select-String -SimpleMatch 'DENIED' -LiteralPath '${path}'`]:[]),'help']}
export function shellGoals(s:ShellState,c:ShellConfig){return [{label:b('Identificar a pasta atual','Identify the current folder'),done:s.located},{label:b('Listar os itens','List the items'),done:s.listed},...(c.relative?[{label:b('Entrar na pasta do arquivo','Enter the file’s folder'),done:s.moved}]:[]),{label:b('Ler o arquivo indicado','Read the specified file'),done:s.read},...(c.filter?[{label:b('Filtrar os registros DENIED','Filter DENIED records'),done:s.filtered}]:[])]}
export function shellReady(s:ShellState,c:ShellConfig){return shellGoals(s,c).every(g=>g.done)}
export function runShell(s:ShellState,input:string,c:ShellConfig):{state:ShellState;output:Bilingual;ok:boolean}{
 const raw=input.trim();const cmd=raw.toLowerCase();const out=(pt:string,en:string,state=s,ok=true)=>({state,output:b(pt,en),ok});
 if(raw.length>180)return out('Entrada muito longa. Use um dos comandos listados.','Input too long. Use one of the listed commands.',s,false);
 if(cmd==='help')return out('Lista fechada: '+shellCommands(c).join(' | '),'Closed list: '+shellCommands(c).join(' | '));
 if(cmd==='get-location')return out(s.cwd+'\nEste é o caminho atual da simulação.',s.cwd+'\nThis is the simulation’s current path.',{...s,located:true});
 if(cmd==='get-childitem')return out(s.cwd==='C:\\NEXUS'?'logs/\ndocs/':c.file,s.cwd==='C:\\NEXUS'?'logs/\ndocs/':c.file,{...s,listed:true});
 if(cmd===`set-location ${c.directory}`){if(s.cwd!=='C:\\NEXUS')return out('Você já está na pasta. Use Get-Location para conferir.','You are already in the folder. Use Get-Location to check.',s,false);return out(`Pasta atual: C:\\NEXUS\\${c.directory}. Caminhos relativos partem daqui.`,`Current folder: C:\\NEXUS\\${c.directory}. Relative paths start here.`,{...s,cwd:`C:\\NEXUS\\${c.directory}`,moved:true})}
 const read=`Get-Content -LiteralPath '${c.relative?c.file:absoluteFile(c)}'`.toLowerCase();const filter=`Select-String -SimpleMatch 'DENIED' -LiteralPath '${c.relative?c.file:absoluteFile(c)}'`.toLowerCase();
 if(cmd===read||(c.filter&&cmd===filter)){
  if(c.relative&&s.cwd!==`C:\\NEXUS\\${c.directory}`)return out('Arquivo não encontrado nesta pasta. O caminho relativo depende de onde você está; confira e entre na pasta indicada.','File not found in this folder. The relative path depends on where you are; check and enter the specified folder.',s,false);
  if(cmd===filter&&!s.read)return out('Leia primeiro o arquivo inteiro para entender o contexto. Depois aplique o filtro.','Read the entire file first to understand context. Then apply the filter.',s,false);
  const content=c.directory==='logs'?'09:10 Orion ALLOWED\n09:11 Visitor DENIED\n09:12 Nova ALLOWED':'GUIDE: Read before changing settings\nDENIED: Unapproved admin request\nGUIDE: Ask the team when unsure';
  return out(cmd===filter?content.split('\n').filter(l=>l.includes('DENIED')).join('\n')+'\nFiltro literal; um resultado não prova ataque.':content+'\nLeitura fictícia: os registros não foram alterados.',cmd===filter?content.split('\n').filter(l=>l.includes('DENIED')).join('\n')+'\nLiteral filter; one result does not prove an attack.':content+'\nFictional reading: records were not changed.',{...s,read:true,filtered:s.filtered||cmd===filter});
 }
 return out('Comando fora da lista ou argumentos diferentes. Nada foi executado. Confira aspas, caminho e parâmetros; use help.','Command outside the list or different arguments. Nothing was executed. Check quotes, path and parameters; use help.',s,false);
}
export type BlockId='set'|'read'|'success'|'pattern'|'ignore';
export function scriptBlocks(d:Difficulty,file:string):{id:BlockId;label:Bilingual;code:string}[]{return [
 {id:'success',label:b('Anunciar sucesso','Announce success'),code:"'LEITURA OK'"},
 {id:'read',label:b('Ler caminho literal e parar no erro','Read literal path and stop on error'),code:'Get-Content -LiteralPath $arquivo -ErrorAction Stop'},
 {id:'set',label:b('Definir o arquivo','Define the file'),code:`$arquivo = '${file}'`},
 ...(d!=='easy'?[{id:'pattern' as const,label:b('Tratar o nome como padrão','Treat the name as a pattern'),code:'Get-Content -Path $arquivo -ErrorAction Stop'}]:[]),
 ...(d==='hard'?[{id:'ignore' as const,label:b('Ignorar erro de leitura','Ignore reading errors'),code:'Get-Content -LiteralPath $arquivo -ErrorAction SilentlyContinue'}]:[])
];}
export function scriptCorrect(ids:BlockId[]){return ids.length===3&&ids[0]==='set'&&ids[1]==='read'&&ids[2]==='success'}
export function scriptCode(ids:BlockId[],d:Difficulty,file:string){const blocks=scriptBlocks(d,file);return 'try {\n'+ids.map(id=>'  '+blocks.find(b=>b.id===id)!.code).join('\n')+"\n} catch {\n  'LEITURA FALHOU'\n}"}
export function scriptTrace(ids:BlockId[],exists:boolean):Bilingual[]{let defined=false;let read=false;const trace:Bilingual[]=[];
 for(const id of ids){if(id==='set'){defined=true;trace.push(b('Variável arquivo definida.','File variable defined.'))}else if(id==='success'){trace.push(read?b('LEITURA OK: emitido depois da leitura.','LEITURA OK: emitted after reading.'):b('Sucesso anunciado antes de ler: mensagem enganosa.','Success announced before reading: misleading message.'))}else if(id==='pattern'){trace.push(b('Path trata colchetes como padrão. O exemplo exige um nome literal; não confirma leitura do arquivo desejado.','Path treats brackets as a pattern. The example requires a literal name; it does not confirm reading the intended file.'));break}else if(id==='ignore'){trace.push(b('SilentlyContinue pode deixar a sequência seguir apesar da falha. Aqui falta interromper e tratar o erro.','SilentlyContinue may let the sequence proceed despite failure. Stopping and handling the error is missing here.'));break}else if(!defined||!exists){trace.push(b(!defined?'Variável não definida: a leitura falha e vai para catch.':'Arquivo ausente: ErrorAction Stop leva a falha para catch.',!defined?'Variable undefined: reading fails and enters catch.':'File absent: ErrorAction Stop sends the failure to catch.'));trace.push(b('LEITURA FALHOU. O restante do try não acontece.','LEITURA FALHOU. The rest of try does not happen.'));break}else{read=true;trace.push(b('Arquivo literal lido na simulação.','Literal file read in the simulation.'))}}
 if(!ids.length)trace.push(b('Adicione blocos para observar a sequência.','Add blocks to observe the sequence.'));return trace;
}
const common=[q('Por que conferir a pasta atual antes de usar um caminho relativo?','Why check the current folder before using a relative path?',[['Porque o caminho parte da localização atual','Because the path starts from the current location'],['Porque ler sempre apaga arquivos','Because reading always deletes files'],['Porque o nome nunca importa','Because the name never matters']],0,['O mesmo caminho relativo pode apontar para lugares diferentes conforme a localização atual.','The same relative path may point to different places depending on the current location.'],['Confira Get-Location.','Check Get-Location.']),q('O arquivo tem colchetes no nome. Qual parâmetro pede o nome exato no PowerShell?','The file name has brackets. Which parameter requests the exact name in PowerShell?',[['LiteralPath','LiteralPath'],['Path sempre ignora padrões','Path always ignores patterns'],['Qualquer comando sem conferir','Any command without checking']],0,['LiteralPath não interpreta o caminho como padrão de curingas. Aspas também mantêm um argumento literal com espaços quando você escreve o nome.','LiteralPath does not interpret the path as a wildcard pattern. Quotes also keep a literal argument with spaces together when you write the name.'],['Nome literal e padrão não são a mesma coisa.','A literal name and a pattern are different.']),q('Um script deve anunciar leitura concluída. Qual ordem atende ao objetivo?','A script must announce completed reading. Which order meets the goal?',[['Anunciar antes de tentar','Announce before attempting'],['Definir arquivo, ler com tratamento de erro e anunciar após sucesso','Define file, read with error handling and announce after success'],['Ocultar todo erro e sempre anunciar','Hide every error and always announce']],1,['Uma mensagem de sucesso precisa refletir uma operação concluída. Trate falhas e teste também o caminho de erro.','A success message must reflect a completed operation. Handle failures and also test the error path.'],['O que acontece se o arquivo não existir?','What happens if the file does not exist?'])];
export const commandQuestions:Record<Difficulty,Question[]>={easy:common,normal:common,hard:common};
const ms='https://learn.microsoft.com/en-us/powershell/';
export const commandLesson:Lesson={id:'m11',intro:b('Um comando descreve uma ação; seus argumentos indicam como e sobre qual recurso agir. Entenda o alvo e a saída antes de automatizar.','A command describes an action; its arguments specify how and on which resource to act. Understand the target and output before automating.'),concepts:[
 {title:b('Localizar, listar, ler','Locate, list, read'),text:b('Get-Location mostra a localização atual. Get-ChildItem lista itens. Get-Content lê conteúdo. Set-Location muda a localização; não move os arquivos.','Get-Location shows the current location. Get-ChildItem lists items. Get-Content reads content. Set-Location changes location; it does not move files.'),example:b('Você entra em logs e lê access log.txt. Mudar de pasta muda a base dos caminhos relativos.','You enter logs and read access log.txt. Changing folders changes the base of relative paths.')},
 {title:b('Caminho e argumento','Path and argument'),text:b('Um caminho absoluto inclui a base; um relativo depende da pasta atual. Ao escrever um nome com espaços no PowerShell, use aspas para mantê-lo no mesmo argumento.','An absolute path includes its base; a relative one depends on the current folder. When writing a name with spaces in PowerShell, use quotes to keep it in the same argument.'),example:b("Get-Content -LiteralPath 'access log.txt' pede um nome literal. O parâmetro LiteralPath não interpreta colchetes como curingas.","Get-Content -LiteralPath 'access log.txt' requests a literal name. LiteralPath does not interpret brackets as wildcards.")},
 {title:b('Filtrar sem perder o contexto','Filter without losing context'),text:b('Select-String procura texto. SimpleMatch pede correspondência literal em vez de uma expressão regular. Leia o contexto antes de concluir algo sobre o resultado.','Select-String searches text. SimpleMatch requests literal matching instead of a regular expression. Read context before drawing conclusions from the result.'),example:b('Um registro DENIED pode ser um controle funcionando. A palavra sozinha não comprova um ataque.','A DENIED record may be a control working. The word alone does not prove an attack.')},
 {title:b('Script: sequência e falha','Script: sequence and failure'),text:b('Defina o alvo antes de usá-lo. Em PowerShell, try/catch trata erros terminantes; ErrorAction Stop pode tornar um erro não terminante tratável nesse fluxo. Anuncie sucesso depois da ação concluída.','Define the target before using it. In PowerShell, try/catch handles terminating errors; ErrorAction Stop can make a non-terminating error catchable in that flow. Announce success after the action completes.'),example:b('Se o arquivo estiver ausente, o exemplo entra em catch e mostra LEITURA FALHOU. A mensagem LEITURA OK depois da leitura não é emitida.','If the file is absent, the example enters catch and shows LEITURA FALHOU. The LEITURA OK message after reading is not emitted.')},
 {title:b('Conheça a linguagem e a origem','Know the language and source'),text:b('Este exemplo usa PowerShell. Outros shells têm regras diferentes. Confira scripts antes de executar, limite privilégios e teste em um ambiente apropriado.','This example uses PowerShell. Other shells have different rules. Review scripts before running, limit privileges and test in an appropriate environment.'),example:b('Copiar um comando desconhecido para um terminal real pode alterar dados. Nossa bancada aceita só ações fictícias de consulta.','Copying an unknown command into a real terminal may change data. Our workbench only accepts fictional inspection actions.')}
],checklist:[b('Confira localização, alvo e argumentos.','Check location, target and arguments.'),b('Leia a saída e preserve o contexto.','Read output and preserve context.'),b('Teste sucesso e falha antes de automatizar.','Test success and failure before automating.')],quiz:{prompt:common[2].prompt,options:common[2].options,correct:1,feedback:[b('Anunciar antes da operação pode mostrar sucesso sem que nada tenha sido lido.','Announcing before the operation may show success without anything being read.'),b('Isso. Defina o alvo, trate a leitura e anuncie apenas após o sucesso.','Correct. Define the target, handle reading and announce only after success.'),b('Ocultar erros não faz uma operação falha funcionar.','Hiding errors does not make a failed operation work.')]},sources:[{label:'Microsoft · comandos e caminhos',url:ms+'module/microsoft.powershell.management/get-location?view=powershell-7.5'},{label:'Microsoft · Get-Content',url:ms+'module/microsoft.powershell.management/get-content?view=powershell-7.5'},{label:'Microsoft · Select-String',url:ms+'module/microsoft.powershell.utility/select-string?view=powershell-7.5'},{label:'Microsoft · aspas',url:ms+'module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.5'},{label:'Microsoft · try/catch',url:ms+'module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.5'}]};
