import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import type { Lesson } from './lessons';

export const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
/** Historical A–Z toy cipher, deliberately unsuitable for protecting real data. */
export function caesar(text:string,shift:number):string {
 const n=((Math.trunc(shift)%26)+26)%26;
 return text.replace(/[A-Za-z]/g,c=>{const offset=c>='a'&&c<='z'?97:65;return String.fromCharCode((c.charCodeAt(0)-offset+n)%26+offset)});
}
export type CipherTask={kind:'cipher';plain:Bilingual;shift:number;clue:Bilingual};
export type HashSample={text:string;digest:string};
export type HashTask={kind:'hash';reference:string;samples:HashSample[];explain:Bilingual;hint:Bilingual};
export type KeyTask={kind:'key';question:Question};
export type CryptoTask=CipherTask|HashTask|KeyTask;
const cipher=(pt:string,en:string,shift:number,clue:Bilingual):CipherTask=>({kind:'cipher',plain:b(pt,en),shift,clue});
export const cipherTasks:Record<Difficulty,CipherTask[]>={
 easy:[cipher('ABRA O COFRE','OPEN THE VAULT',3,b('A original virou D. A mensagem avançou 3 posições; desfaça o mesmo número.','Original A became D. The message moved forward 3 positions; undo the same number.')),cipher('GUARDE A CHAVE','STORE THE KEY',5,b('A original virou F. Conte as posições de A até F.','Original A became F. Count the positions from A to F.')),cipher('LEIA O AVISO','READ THE NOTICE',2,b('A original virou C. Conte as posições de A até C.','Original A became C. Count the positions from A to C.'))],
 normal:[cipher('PROTEJA AS CHAVES','PROTECT THE KEYS',7,b('Na calibração, a letra A foi enviada como H. O mesmo deslocamento foi usado em toda a mensagem.','In calibration, A was sent as H. The same shift was used throughout the message.')),cipher('CONFIRA A ORIGEM','CHECK THE SOURCE',11,b('A calibração registrou A como L. O alfabeto volta a A depois de Z.','Calibration recorded A as L. The alphabet wraps to A after Z.')),cipher('REVISE O ACESSO','REVIEW ACCESS',9,b('A calibração registrou A como J. Desfaça o deslocamento.','Calibration recorded A as J. Undo the shift.'))],
 hard:[cipher('VERIFIQUE A ORIGEM','VERIFY THE SOURCE',19,b('Na calibração, C original virou V. O deslocamento é fixo e o alfabeto é circular.','In calibration, original C became V. The shift is fixed and the alphabet is circular.')),cipher('CONFIRME A ASSINATURA','CONFIRM THE SIGNATURE',23,b('Na calibração, D original virou A após passar por Z. Conte o avanço circular.','In calibration, original D became A after passing Z. Count the circular forward shift.')),cipher('PROTEJA A CHAVE PRIVADA','PROTECT THE PRIVATE KEY',17,b('Na calibração, J original virou A após passar por Z. Conte o avanço circular.','In calibration, original J became A after passing Z. Count the circular forward shift.'))]
};
const raw:Record<Difficulty,HashSample[]>={
 easy:[{text:'NEXUS|arquivo=manual|versao=2',digest:'1b1540e9720503245a6764685b79f56e59ddd3cd566959c824fa58db8e3a2cc9'},{text:'NEXUS|arquivo=manual|versao=3',digest:'3c38376d0f325438b579cb532c9548552cf8dddd8fc2ec74883923c8063e5d8c'},{text:'NEXUS|arquivo=manual|versao=2.',digest:'134d29799233a302d980c97ce12f75704fc88ef3585e27a831a8f3367e7274d2'}],
 normal:[{text:'NEXUS|release=4|mode=read',digest:'1fa4cd6d9f2c3e7c5ff2b5aeb0b9c5e03b5a33d3d65c1c2728bded3ea4894dda'},{text:'NEXUS|release=4|mode=write',digest:'6577944ab5a030a582ef4ae259f69bd4b2e3234fc7bdf0b016514388a07b5b35'},{text:'NEXUS|release=5|mode=read',digest:'691c63f64a137bd0b02892ff8b201dbe764e002fb4afc40eb1385df2b1634a78'}],
 hard:[{text:'NEXUS|access=read|expires=2026-12-01',digest:'7666d2b9e4c44b9ea899027f4dbd31a4c40c5d704856f7e8497643f0591cc5d9'},{text:'NEXUS|access=read|expires=2026-12-01\n',digest:'43b68763195031a0bab4b75d08caf9cb03055178af1a2d78297ae6d0a99004e0'},{text:'NEXUS|access=write|expires=2026-12-01',digest:'4096d8ca1cd6811bdc201097eb524e0fedee1b777dccee65ad8ce748e202ad4a'}]
};
export const hashTasks:Record<Difficulty,HashTask>=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map((d,i)=>[d,{kind:'hash',reference:raw[d][0].digest,samples:[raw[d][(i+1)%3],raw[d][(i+2)%3],raw[d][i%3]],hint:b('Compare os 64 caracteres com a referência. Um ponto ou uma quebra de linha também altera os bytes.','Compare all 64 characters with the reference. A period or line break also changes the bytes.'),explain:b('A referência veio de um canal autenticado da NEXUS. O arquivo com o mesmo SHA-256 corresponde à referência neste caso. Isso não demonstra que o conteúdo seja inofensivo.','The reference came from an authenticated NEXUS channel. The file with the same SHA-256 matches the reference in this case. This does not show that its content is harmless.')}])) as Record<Difficulty,HashTask>;
export function hashChoice(task:HashTask,index:number|null):boolean{return index!==null&&task.samples[index]?.digest===task.reference}

export const cryptoQuestions:Record<Difficulty,Question[]>={
 easy:[q('Qual ferramenta ajuda a esconder o conteúdo de um arquivo?','Which tool helps hide file content?',[[ 'Cifragem com proteção adequada da chave','Encryption with appropriate key protection'],['Renomear o arquivo','Rename the file'],['Um hash público do arquivo','A public hash of the file']],0,['Cifragem protege confidencialidade. Nome e hash não escondem o conteúdo.','Encryption protects confidentiality. Names and hashes do not hide content.'],['Quem precisa conseguir ler o conteúdo?','Who needs to be able to read the content?']),q('As duas partes usam a mesma chave secreta. Qual é o modelo?','Both parties use the same secret key. Which model is this?',[[ 'Criptografia simétrica','Symmetric cryptography'],['Chave pública de qualquer pessoa','Anyone’s public key'],['Assinatura sem chave','A signature without a key']],0,['No modelo simétrico, a chave secreta precisa ser protegida por todos os participantes autorizados.','In the symmetric model, all authorized participants must protect the secret key.'],['A chave é compartilhada e secreta.','The key is shared and secret.']),q('Uma assinatura digital válida esconde o texto?','Does a valid digital signature hide the text?',[[ 'Sim, sempre','Yes, always'],['Não; assinatura e cifragem atendem objetivos diferentes','No; signatures and encryption serve different goals'],['Sim, se o arquivo tiver nome longo','Yes, if the filename is long']],1,['Assinatura permite verificar integridade e origem vinculada à chave. Para esconder conteúdo, é necessária proteção de confidencialidade.','A signature verifies integrity and origin linked to the key. Hiding content requires confidentiality protection.'],['Verificar origem é diferente de esconder conteúdo.','Verifying origin differs from hiding content.'])],
 normal:[q('O arquivo mudou e seu SHA-256 ficou diferente da referência confiável. O que fazer?','The file changed and its SHA-256 differs from a trusted reference. What should you do?',[[ 'Investigar a divergência antes de usar','Investigate the mismatch before use'],['Ignorar porque o nome não mudou','Ignore it because the name did not change'],['Descriptografar o hash para recuperar o original','Decrypt the hash to recover the original']],0,['O hash identifica uma divergência de bytes neste cenário. Ele não é um arquivo cifrado para desfazer.','The hash identifies a byte mismatch in this scenario. It is not an encrypted file to reverse.'],['Compare conteúdo e referência.','Compare content and reference.']),q('Você precisa ler dados cifrados com sua chave pública. Qual chave correspondente deve ficar protegida?','You need to read data encrypted with your public key. Which corresponding key must stay protected?',[[ 'Sua chave privada','Your private key'],['A chave pública de um colega','A colleague’s public key'],['O nome do arquivo','The filename']],0,['Neste modelo de cifragem assimétrica, a privada do destinatário recupera o conteúdo e não deve ser compartilhada.','In this asymmetric encryption model, the recipient’s private key recovers the content and must not be shared.'],['Pública e privada formam um par.','Public and private keys form a pair.']),q('O checksum foi entregue pelo mesmo site suspeito que entregou o arquivo. Qual limitação existe?','The checksum came from the same suspicious site as the file. What limitation exists?',[[ 'Não há limitação','There is no limitation'],['Um invasor pode substituir os dois; confirme uma referência confiável','An attacker can replace both; verify a trusted reference'],['Todo hash é secreto','Every hash is secret']],1,['Comparar com uma referência controlada pelo atacante não autentica a origem. A confiança na referência importa.','Comparing an attacker-controlled reference does not authenticate origin. Trust in the reference matters.'],['Quem controla a referência?','Who controls the reference?'])],
 hard:[q('Você quer confidencialidade e detecção de alterações em mensagens. O que considerar?','You want confidentiality and change detection in messages. What should you consider?',[[ 'Um protocolo adequado com cifragem autenticada e gestão de chaves','An appropriate protocol with authenticated encryption and key management'],['Somente uma cifra de deslocamento','Only a shift cipher'],['Somente Base64','Only Base64']],0,['Sistemas reais precisam de protocolos, modos e chaves adequados. Cifra de César e codificação Base64 não atendem esse objetivo.','Real systems need appropriate protocols, modes and keys. Caesar ciphers and Base64 encoding do not meet this goal.'],['Esconder e detectar alterações são dois requisitos.','Hiding content and detecting changes are two requirements.']),q('Uma assinatura verifica com uma chave desconhecida enviada pelo próprio remetente suspeito. O que falta?','A signature verifies with an unknown key supplied by the suspicious sender. What is missing?',[[ 'Uma associação confiável entre a chave e a identidade esperada','A trusted link between the key and expected identity'],['Um nome de arquivo maior','A longer filename'],['Publicar sua chave privada','Publishing your private key']],0,['A verificação matemática com uma chave não comprova a identidade esperada sem uma vinculação confiável.','Mathematical verification with a key does not establish the expected identity without a trusted binding.'],['Como essa chave foi associada à identidade?','How was the key associated with the identity?']),q('Uma chave privada foi exposta. Qual resposta corresponde ao risco?','A private key was exposed. Which response matches the risk?',[[ 'Seguir o processo de revogação/rotação e avaliar o impacto','Follow revocation/rotation procedures and assess impact'],['Renomear o arquivo da chave e continuar','Rename the key file and continue'],['Publicar a chave para confirmar quem tem acesso','Publish the key to confirm who has access']],0,['Uma cópia pode continuar nas mãos de terceiros. Rotação, revogação quando aplicável e avaliação precisam seguir o plano.','Others may retain a copy. Rotation, revocation where applicable and assessment need to follow the plan.'],['Mudar o nome não elimina cópias já feitas.','Renaming does not eliminate existing copies.'])]
};
const mainKeys:Record<Difficulty,Question[]>={
 easy:[q('Nova quer enviar uma mensagem que só Orion possa abrir. Neste modelo assimétrico, qual chave usa para cifrar?','Nova wants to send a message only Orion can open. In this asymmetric model, which key encrypts it?',[[ 'Pública de Orion','Orion’s public key'],['Privada de Nova','Nova’s private key'],['Pública de Nova','Nova’s public key']],0,['Use a pública do destinatário, verificada por um canal confiável. Orion mantém a privada correspondente para recuperar o conteúdo.','Use the recipient’s public key, verified through a trusted channel. Orion keeps the corresponding private key to recover the content.'],['Escolha a chave do destinatário, não a do remetente.','Choose the recipient’s key, not the sender’s.']),q('Orion assinou um relatório. Qual chave Nova usa para verificar a assinatura?','Orion signed a report. Which key does Nova use to verify the signature?',[[ 'Privada de Nova','Nova’s private key'],['Pública de Orion, vinculada à identidade dele','Orion’s public key, bound to his identity'],['Privada de Orion, enviada por chat','Orion’s private key, sent by chat']],1,['Orion assina com sua privada; Nova verifica com a pública correspondente, obtida de forma confiável. A privada não é compartilhada.','Orion signs with his private key; Nova verifies with the corresponding public key, obtained reliably. The private key is not shared.'],['Verificar não exige receber o segredo de quem assinou.','Verification does not require the signer’s secret.'])],
 normal:[q('Um parceiro confirmou sua chave pública no canal cadastrado. Para enviar conteúdo confidencial a ele, qual chave usar neste modelo?','A partner confirmed its public key through the registered channel. To send confidential content to it, which key is used in this model?',[[ 'Sua privada de assinatura','Your private signing key'],['A pública do parceiro destinada à cifragem','The partner’s public key designated for encryption'],['A pública de qualquer outro parceiro','Any other partner’s public key']],1,['A chave pública de cifragem precisa corresponder ao destinatário. Ele usa a privada correspondente; sua privada de assinatura tem outra função.','The encryption public key must match the recipient. They use the corresponding private key; your private signing key serves another role.'],['Observe a finalidade e o dono da chave.','Watch the key’s purpose and owner.']),q('O relatório assinado veio de Nova. Você já validou a chave pública de assinatura dela. Qual operação fazer?','The signed report came from Nova. You already validated her public signing key. What operation should you perform?',[[ 'Verificar a assinatura com essa pública e o relatório recebido','Verify the signature with that public key and received report'],['Cifrar o relatório com a pública de Orion para validar Nova','Encrypt the report with Orion’s public key to validate Nova'],['Solicitar a privada de Nova','Request Nova’s private key']],0,['A verificação liga o conteúdo à assinatura e à chave validada. Assinatura não torna o conteúdo secreto nem necessariamente inofensivo.','Verification links the content to the signature and validated key. A signature does not make content secret or necessarily harmless.'],['Assinatura se verifica; conteúdo se cifra.','Signatures are verified; content is encrypted.'])],
 hard:[q('Você validou a identidade do destinatário e sua chave específica para cifragem. Qual decisão atende ao modelo de confidencialidade assimétrica?','You validated the recipient’s identity and encryption-specific key. Which decision fits asymmetric confidentiality?',[[ 'Usar sua privada de assinatura como se fosse cifragem','Use your private signing key as though it were encryption'],['Distribuir a privada do destinatário à equipe inteira','Distribute the recipient’s private key to the entire team'],['Usar a pública de cifragem do destinatário em um esquema adequado','Use the recipient’s encryption public key in an appropriate scheme']],2,['Chave, finalidade e protocolo precisam combinar. O destinatário protege a privada. Não improvise protocolos nem reutilize chaves indiscriminadamente.','Key, purpose and protocol must match. The recipient protects the private key. Do not improvise protocols or indiscriminately reuse keys.'],['A finalidade da chave importa além de ser pública ou privada.','The key’s purpose matters beyond being public or private.']),q('Você recebeu um pacote assinado por Orion e já confirmou sua chave pública de assinatura. O que conferir?','You received a package signed by Orion and already confirmed his public signing key. What should you check?',[[ 'A assinatura sobre os bytes recebidos com a pública validada','The signature over received bytes with the validated public key'],['Só o nome do pacote','Only the package name'],['Se a privada de Orion está anexada','Whether Orion’s private key is attached']],0,['A verificação deve abranger o conteúdo recebido e usar a chave apropriada. Confirme também validade e política de confiança aplicáveis.','Verification must cover the received content and use the appropriate key. Also check applicable validity and trust policies.'],['Vincule conteúdo, assinatura e chave de confiança.','Link content, signature and trusted key.'])]
};
export function cryptoTasks(d:Difficulty,id:string):CryptoTask[]{
 if(id==='s9a')return cipherTasks[d].slice(1);
 if(id==='s9b')return cryptoQuestions[d].slice(1).map(question=>({kind:'key',question}));
 return [cipherTasks[d][0],hashTasks[d],...mainKeys[d].map(question=>({kind:'key' as const,question}))];
}
export function cryptoScore(answers:boolean[]):number{return answers.length?Math.round(answers.filter(Boolean).length/answers.length*100):0}

export const cryptoLesson:Lesson={id:'m9',intro:b('Esconder uma mensagem, detectar uma mudança e verificar quem assinou são objetivos diferentes. Escolha a ferramenta para cada um.','Hiding a message, detecting a change and verifying who signed are different goals. Choose the tool for each one.'),concepts:[
 {title:b('Cifragem: proteger o conteúdo','Encryption: protect content'),text:b('Cifrar transforma texto legível em conteúdo protegido por uma chave. Decifrar recupera o original com a chave adequada. Em sistemas reais, use protocolos e bibliotecas reconhecidos.','Encryption transforms readable text into content protected by a key. Decryption recovers the original with the appropriate key. In real systems, use recognized protocols and libraries.'),example:b('A cifra histórica de César troca A por D quando avança 3 letras. Ela é reversível, mas tem pouquíssimas opções e não protege dados reais.','The historical Caesar cipher replaces A with D when shifting 3 letters. It is reversible but has very few possibilities and does not protect real data.')},
 {title:b('Hash: comparar os bytes','Hash: compare bytes'),text:b('SHA-256 gera um resumo de tamanho fixo. O mesmo conteúdo gera o mesmo resumo; uma mudança normalmente altera o resultado. Hash não é uma cifragem que você desfaz para ler o original.','SHA-256 generates a fixed-size digest. The same content produces the same digest; a change normally alters the result. A hash is not encryption that you reverse to read the original.'),example:b('Um ponto extra no arquivo muda seu SHA-256. Compare com a referência de um canal confiável; se arquivo e referência vierem do atacante, a comparação não confirma a origem.','An extra period in the file changes its SHA-256. Compare with a reference from a trusted channel; if both file and reference come from an attacker, the comparison does not confirm origin.')},
 {title:b('Chaves: compartilhada ou em par','Keys: shared or paired'),text:b('Na cifragem simétrica, as partes usam a mesma chave secreta. No modelo assimétrico de cifragem, o par tem pública e privada: cifra-se para o destinatário com sua pública, e ele usa a privada correspondente.','In symmetric encryption, parties use the same secret key. In the asymmetric encryption model, a pair has public and private keys: encrypt for the recipient using their public key, and they use the corresponding private key.'),example:b('Nova confirma a pública de Orion antes de enviar. Orion mantém sua privada protegida. Chaves públicas precisam de uma ligação confiável com a identidade esperada.','Nova confirms Orion’s public key before sending. Orion protects his private key. Public keys need a trusted link to the expected identity.')},
 {title:b('Assinatura: verificar conteúdo e origem','Signature: verify content and origin'),text:b('O remetente assina com sua privada de assinatura. Quem recebe verifica com a pública correspondente e confiável. Assinatura não esconde o conteúdo e não garante que ele seja inofensivo.','The sender signs with their private signing key. The recipient verifies with the corresponding trusted public key. A signature does not hide content or guarantee that it is harmless.'),example:b('Orion assina um aviso; Nova verifica com a pública de Orion. Se também precisar de sigilo, a assinatura sozinha não atende esse requisito.','Orion signs a notice; Nova verifies with Orion’s public key. If confidentiality is also needed, the signature alone does not meet that requirement.')}
 ],checklist:[b('Separe sigilo, integridade e verificação de origem.','Separate confidentiality, integrity and origin verification.'),b('Compare hashes com uma referência confiável.','Compare hashes with a trusted reference.'),b('Proteja chaves secretas e privadas; confirme a finalidade da chave.','Protect secret and private keys; confirm the key’s purpose.')],quiz:{prompt:b('Você quer conferir a origem de um relatório sem pedir o segredo de quem o assinou. O que usar?','You want to check a report’s origin without requesting the signer’s secret. What should you use?'),options:[b('A pública de assinatura do remetente, vinculada de forma confiável.','The sender’s public signing key, reliably bound to their identity.'),b('A privada do remetente, enviada junto do relatório.','The sender’s private key, sent with the report.'),b('Uma cifra de César no nome do arquivo.','A Caesar cipher on the filename.')],correct:0,feedback:[b('A pública permite verificar a assinatura e o conteúdo recebido. A confiança na associação entre chave e identidade também é necessária.','The public key lets you verify the signature and received content. Trust in the key-to-identity association is also necessary.'),b('A privada deve continuar protegida. Compartilhá-la permitiria que outras pessoas assinassem como o titular da chave.','The private key must stay protected. Sharing it would allow others to sign as its owner.'),b('Trocar letras no nome não verifica origem nem protege o relatório. Escolha uma assinatura adequada.','Shifting filename letters neither verifies origin nor protects the report. Choose an appropriate signature.')]},sources:[{label:'NIST FIPS 180-4 · SHA',url:'https://csrc.nist.gov/pubs/fips/180-4/upd1/final'},{label:'NIST FIPS 197 · AES',url:'https://csrc.nist.gov/pubs/fips/197/final'},{label:'NIST FIPS 186-5 · Signatures',url:'https://csrc.nist.gov/pubs/fips/186-5/final'},{label:'NIST · Key management',url:'https://csrc.nist.gov/projects/key-management/key-management-guidelines'}]};
