import {describe,it,expect} from 'vitest';
import {modules,questionsFor} from './curriculum';
import {initial,reward,normalizeSave,validSave,type Difficulty} from './core';
describe('expanded fundamentals curriculum',()=>{
 it('has twenty-four topics, two side quests each and complete bilingual content',()=>{expect(modules).toHaveLength(25);for(const m of modules){expect(m.quests).toHaveLength(2);expect(m.title.pt).toBeTruthy();expect(m.title.en).toBeTruthy();for(const d of ['easy','normal','hard'] as Difficulty[]){const questions=questionsFor(m.id,d);expect(questions).toHaveLength(3);for(const q of questions){expect(q.correct).toBeGreaterThanOrEqual(0);expect(q.correct).toBeLessThan(q.options.length);for(const lang of ['pt','en'] as const){expect(q.prompt[lang]).toBeTruthy();expect(q.explain[lang]).toBeTruthy();expect(q.hint[lang]).toBeTruthy();expect(q.options.every(o=>!!o[lang])).toBe(true)}}}}});
 it('selects different reinforcement scenarios for the two side quests',()=>{for(const number of [4,5,6,7]){const a=questionsFor(`s${number}a`,'normal');const b=questionsFor(`s${number}b`,'normal');expect(a).toHaveLength(2);expect(b).toHaveLength(2);expect(a[0].prompt).not.toEqual(b[0].prompt)}});
 it('assesses all seven topics without completing missions',()=>expect(questionsFor('placement','easy')).toHaveLength(7));
 it('migrates legacy saves without losing XP, completions or identity',()=>{const old={...reward(initial,'m1',100,'easy',false),version:1,lang:'en',avatar:2,placement:true};const upgraded=normalizeSave(JSON.parse(JSON.stringify(old)));expect(upgraded).toEqual({...old,version:22});expect(validSave(upgraded)).toBe(true)});
 it('round trips the maximum full campaign reward',()=>{let save=initial;for(const m of modules){save=reward(save,m.id,100,'hard',false);for(const letter of ['a','b'])save=reward(save,`s${m.label.replace(/^0/,'')}${letter}`,100,'hard',true)}expect(save.xp).toBe(7500);expect(normalizeSave(JSON.parse(JSON.stringify(save)))).toEqual(save)});
 it('rejects impossible rewards and incomplete passing data in imports',()=>{expect(normalizeSave({...initial,completed:{m4:40},earned:{m4:50},xp:50})).toBeNull();expect(normalizeSave({...initial,completed:{s5b:100},earned:{s5b:200},xp:200})).toBeNull();expect(normalizeSave({...initial,version:1,completed:{m7:100},earned:{m7:100},xp:100})).toBeNull()});
});
