import { b, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export const detectionTools=[
 {id:'sigma',name:'Sigma',focus:b('Registros de eventos','Event logs'),example:b('Descrever uma seleção em logs do portal. É preciso mapear os campos, converter para o ambiente e testar a consulta resultante.','Describe a selection in portal logs. Map fields, convert for the environment and test the resulting query.')},
 {id:'yara',name:'YARA',focus:b('Padrões em arquivos ou memória','Patterns in files or memory'),example:b('Procurar padrões de conteúdo em uma amostra autorizada. Uma correspondência pede análise; não confirma sozinha que o arquivo é malicioso.','Look for content patterns in an authorized sample. A match requires analysis; it does not alone confirm a malicious file.')},
 {id:'suricata',name:'Suricata',focus:b('Tráfego de rede','Network traffic'),example:b('Aplicar regras ao tráfego que o sensor consegue observar. Visibilidade, protocolo e criptografia limitam o conteúdo disponível.','Apply rules to traffic the sensor can observe. Visibility, protocol and encryption limit available content.')}
];
export interface DetectionRule{privilegedOnly:boolean;excludeApproved:boolean;feed:boolean}
export const defaultRule:DetectionRule={privilegedOnly:false,excludeApproved:false,feed:true};
export const samples=[
 {id:'R1',event:'export',privileged:true,approved:true,expected:false,description:b('Exportação administrativa autorizada: conta, horário, recurso e operação conferidos.','Authorized admin export: account, time, resource and operation verified.')},
 {id:'R2',event:'export',privileged:true,approved:false,expected:true,description:b('Exportação administrativa inesperada, fora de mudança verificada.','Unexpected admin export, outside verified change.')},
 {id:'R3',event:'login',privileged:true,approved:false,expected:false,description:b('Login administrativo; não houve exportação neste registro.','Admin login; no export in this record.')},
 {id:'R4',event:'export',privileged:false,approved:false,expected:true,description:b('Exportação inesperada por conta comum. O objetivo da regra também inclui esse caso.','Unexpected export by a standard account. The rule objective includes this case too.')},
 {id:'R5',event:'export',privileged:null,approved:false,expected:true,description:b('Exportação inesperada; o campo de privilégio não foi coletado.','Unexpected export; the privilege field was not collected.')}
];
export type DetectionOutcome='caught'|'noise'|'missed'|'clear'|'unknown';
export function evaluateDetection(sample:typeof samples[number],rule:DetectionRule):DetectionOutcome{
 if(!rule.feed)return 'unknown';
 if(sample.event!=='export'||rule.excludeApproved&&sample.approved)return sample.expected?'missed':'clear';
 if(rule.privilegedOnly&&sample.privileged===null)return 'unknown';
 const match=!rule.privilegedOnly||sample.privileged===true;
 return match?(sample.expected?'caught':'noise'):(sample.expected?'missed':'clear');
}
export function detectionReport(rule:DetectionRule){const results=samples.map(s=>({sample:s,outcome:evaluateDetection(s,rule)}));return {results,caught:results.filter(r=>r.outcome==='caught').length,noise:results.filter(r=>r.outcome==='noise').length,missed:results.filter(r=>r.outcome==='missed').length,unknown:results.filter(r=>r.outcome==='unknown').length};}
export const outcomeLabels={caught:b('Detectado · caso esperado','Detected · target case'),noise:b('Ruído · atividade autorizada','Noise · authorized activity'),missed:b('Não detectado · caso esperado','Missed · target case'),clear:b('Sem alerta · fora do objetivo','No alert · outside objective'),unknown:b('Lacuna · não avaliável','Gap · cannot assess')};
export type DetectionKind='source'|'scope'|'test'|'coverage';
const prompts:Record<DetectionKind,[string,string][]>= {
 source:[['Você quer detectar exportações inesperadas nos logs do portal. Qual referência é mais adequada para descrever essa lógica?','You want to detect unexpected exports in portal logs. Which reference best describes this logic?'],['Há logs do portal, uma amostra de arquivo e tráfego de rede. Como escolher a ferramenta por evidência?','You have portal logs, a file sample and network traffic. How do you choose a tool by evidence?'],['Uma regra Sigma foi escrita para um portal diferente, com outros nomes de campos. Qual plano evita tratar o formato como uma detecção pronta?','A Sigma rule was written for another portal with different field names. Which plan avoids treating the format as a ready detection?']],
 scope:[['O objetivo é detectar qualquer exportação inesperada. Qual ajuste mantém esse objetivo sem perder exportações por contas comuns?','The goal is to detect any unexpected export. Which adjustment keeps this goal without missing standard-account exports?'],['O filtro de privilégio reduz alertas, mas deixa passar R4, uma exportação inesperada por conta comum. Qual ajuste respeita o objetivo?','The privilege filter reduces alerts but misses R4, an unexpected standard-account export. Which adjustment respects the goal?'],['R1 é uma exportação administrativa com autorização completa; R4 é inesperada, por conta comum. A proposta exclui todas as contas comuns para reduzir alertas. Qual revisão é defensável?','R1 is an admin export with full authorization; R4 is unexpected from a standard account. The proposal excludes every standard account to reduce alerts. Which revision is defensible?']],
 test:[['A regra disparou no teste suspeito. Que outro exemplo você deve testar?','The rule fired on a suspicious test. What other example should you test?'],['Após adicionar uma exceção, o total de alertas caiu. Isso basta para aprovar a mudança?','After adding an exception, total alerts fell. Is that enough to approve the change?'],['A nova regra não gera ruído em R1, mas perde R4. Como avaliar a mudança sem confundir silêncio com qualidade?','The new rule produces no R1 noise but misses R4. How do you assess it without confusing silence with quality?']],
 coverage:[['O coletor parou. A regra não gerou alertas. Podemos afirmar que ela detectou tudo?','The collector stopped. The rule produced no alerts. Can we say it detected everything?'],['R5 não tem o campo de privilégio exigido pelo filtro. Qual conclusão é adequada?','R5 lacks the privilege field required by the filter. Which conclusion is appropriate?'],['O painel caiu a zero alertas após uma mudança no parser, que deixou de preencher campos. Qual ação deve anteceder qualquer conclusão sobre segurança?','The dashboard fell to zero alerts after a parser change stopped populating fields. Which action should precede any security conclusion?']]
};
const choices:Record<DetectionKind,[string,string][]>= {
 source:[['Usar o mesmo texto de regra nas três ferramentas sem adaptação.','Use the same rule text in all three tools without adaptation.'],['Sigma para lógica em logs; mapear campos e testar no ambiente. YARA atende padrões de conteúdo; Suricata, tráfego observado.','Sigma for log logic; map fields and test in the environment. YARA addresses content patterns; Suricata, observed traffic.'],['Escolher pelo número de alertas prometido.','Choose by promised alert count.']],
 scope:[['Manter apenas contas administrativas; contas comuns nunca representam risco.','Keep only admin accounts; standard accounts never pose risk.'],['Excluir todas as exportações para zerar o painel.','Exclude all exports to empty the dashboard.'],['Incluir exportações inesperadas de contas comuns e administrativas; excluir apenas a atividade com autorização completa verificada.','Include unexpected standard and admin exports; exclude only fully verified authorized activity.']],
 test:[['Testar casos esperados, atividade autorizada e campos ausentes; comparar ruído, perdas e cobertura com o objetivo documentado.','Test target cases, authorized activity and missing fields; compare noise, misses and coverage against the documented goal.'],['Aprovar quando cair o total de alertas, mesmo perdendo casos.','Approve when alert count drops, even if cases are missed.'],['Testar apenas um exemplo que já funcionava.','Test only one example that already worked.']],
 coverage:[['Interpretar ausência de alerta como ausência de risco.','Interpret no alerts as no risk.'],['Verificar coleta, parser e campos; declarar a lacuna, testar após corrigir e usar fontes complementares disponíveis.','Check collection, parser and fields; state the gap, test after repair and use available complementary sources.'],['Trocar o nome da regra e declarar cobertura completa.','Rename the rule and declare complete coverage.']]
};
const why:Record<DetectionKind,[string,string]>= {
 source:['O tipo de evidência orienta a ferramenta. Sigma é um formato para lógica em registros, não um SIEM instalado. Conversão e campos precisam ser validados; as ferramentas se complementam.','Evidence type guides the tool. Sigma is a format for log logic, not an installed SIEM. Conversion and fields need validation; tools complement each other.'],
 scope:['Uma exceção precisa preservar o objetivo. Conta comum pode exportar dados; excluir por privilégio perde R4. Autorização deve corresponder ao evento completo, não apenas ao nome da conta.','An exception must preserve the goal. Standard accounts can export data; a privilege exclusion misses R4. Authorization must match the whole event, not just an account name.'],
 test:['Menos alertas pode significar menos ruído ou mais perdas. Teste positivos e negativos conhecidos e lacunas; o conjunto didático não demonstra cobertura universal nem ausência de ataques.','Fewer alerts can mean less noise or more misses. Test known positives, negatives and gaps; the educational dataset demonstrates neither universal coverage nor no attacks.'],
 coverage:['Uma regra depende de dados utilizáveis. Sem fonte ou campo necessário, declare uma lacuna; não transforme resultado não avaliável em evidência de segurança.','A rule depends on usable data. Without the necessary source or field, declare a gap; do not turn an unassessable result into safety evidence.']
};
export function detectionQuestion(kind:DetectionKind,d:Difficulty):Question{return q(...prompts[kind][{easy:0,normal:1,hard:2}[d]],choices[kind],{source:1,scope:2,test:0,coverage:1}[kind],why[kind],['Leia o objetivo, a fonte e o que o filtro pode excluir.','Read the goal, source and what the filter may exclude.'])}
export const detectionQuestions=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,(['source','scope','test'] as DetectionKind[]).map(k=>detectionQuestion(k,d))])) as Record<Difficulty,Question[]>;
export const detectionReview=review(['Uma regra deve encontrar qualquer exportação inesperada. Após restringir a administradores, ela acerta R2, perde R4 e não avalia R5 por campo ausente. Os alertas caíram. Qual avaliação é melhor?','A rule should find any unexpected export. After restricting to admins, it catches R2, misses R4 and cannot assess R5 due to a missing field. Alerts fell. Which assessment is best?'],[['A mudança melhorou porque há menos alertas.','The change improved because there are fewer alerts.'],['A conta comum é segura por definição.','The standard account is safe by definition.'],['O filtro perdeu cobertura do objetivo; rever o escopo, corrigir o campo e testar casos autorizados e inesperados antes de aprovar.','The filter lost goal coverage; review scope, repair the field and test authorized and unexpected cases before approval.'],['R5 deve contar como um teste aprovado.','R5 should count as a passed test.']],2,[['Queda pode esconder perdas e lacunas.','A decrease may hide misses and gaps.'],['Privilégio não determina sozinho o risco.','Privilege alone does not determine risk.'],['Você comparou a regra com o objetivo e separou perda de detecção e falta de dados.','You compared the rule with its goal and separated detection misses from missing data.'],['Campo ausente impede avaliar a condição exigida.','A missing field prevents assessment of the required condition.']]);
export const detectionFollowup=review(['Um chamado cobre exportação de materiais, mas não de notas. A equipe exclui todos os eventos dessa conta e converte uma regra Sigma sem testar os campos. Qual mudança preserva melhor a detecção?','A ticket covers materials exports but not grades. The team excludes all account events and converts a Sigma rule without testing fields. Which change best preserves detection?'],[['Limitar a exceção à conta, recurso, operação e janela verificados; validar campos e regressão com casos dentro e fora do escopo.','Limit the exception to verified account, resource, operation and window; validate fields and regression using in-scope and out-of-scope cases.'],['Excluir a conta inteira porque tem um chamado.','Exclude the entire account because it has a ticket.'],['Trocar Sigma por YARA e assumir que logs são arquivos maliciosos.','Replace Sigma with YARA and assume logs are malicious files.'],['Manter a regra sem testes pois converteu sem erro.','Keep the rule untested because conversion returned no error.']],0,[['Exceção precisa ser específica; conversão bem-sucedida não prova funcionamento nos dados reais do ambiente.','Exceptions must be specific; successful conversion does not prove operation on the environment’s actual data.'],['O chamado não autoriza outras operações ou recursos.','The ticket does not authorize other operations or resources.'],['A evidência e a finalidade são diferentes; trocar nomes não resolve o escopo.','Evidence and purpose differ; swapping names does not resolve scope.'],['Sintaxe e comportamento são verificações diferentes.','Syntax and behavior are different checks.']]);
