import { describe, it, expect } from 'vitest';
import { defaultRule, detectionReport, evaluateDetection, samples, detectionQuestion } from './detection';
import { initial, reward, normalizeSave } from './core';
import { canStudyChallenge, lessonMission } from './lessons';
describe('educational detection rules',()=>{
 it('compares the broad rule against labelled target and authorized examples',()=>{expect(detectionReport(defaultRule)).toMatchObject({caught:3,noise:1,missed:0,unknown:0});expect(evaluateDetection(samples[2],defaultRule)).toBe('clear')});
 it('limits authorization exclusion to the fully verified sample',()=>{const report=detectionReport({...defaultRule,excludeApproved:true});expect(report).toMatchObject({caught:3,noise:0,missed:0,unknown:0});expect(report.results.filter(r=>r.outcome==='caught').map(r=>r.sample.id)).toEqual(['R2','R4','R5'])});
 it('reveals a nonprivileged miss separately from a missing-field gap',()=>{const report=detectionReport({...defaultRule,privilegedOnly:true,excludeApproved:true});expect(report).toMatchObject({caught:1,noise:0,missed:1,unknown:1});expect(report.results[3].outcome).toBe('missed');expect(report.results[4].outcome).toBe('unknown');expect(report.results[2].outcome).toBe('clear')});
 it('never interprets absent collection as clean results regardless of filters',()=>{for(const privilegedOnly of [true,false])for(const excludeApproved of [true,false])expect(detectionReport({privilegedOnly,excludeApproved,feed:false})).toMatchObject({caught:0,noise:0,missed:0,unknown:5})});
 it('provides distinct scenarios at all difficulties and preserves progression',()=>{for(const kind of ['source','scope','test','coverage'] as const){const qs=(['easy','normal','hard'] as const).map(d=>detectionQuestion(kind,d));expect(new Set(qs.map(q=>q.prompt.pt)).size).toBe(3);for(const q of qs){expect(q.options[q.correct].en).toBeTruthy();expect(q.explain.pt).toBeTruthy()}}expect(canStudyChallenge('m22',{},false)).toBe(false);expect(canStudyChallenge('m22',{m21:75},false)).toBe(true);expect(canStudyChallenge('m22',{},true)).toBe(true);expect(canStudyChallenge('m22',{},true,true)).toBe(false);for(const id of ['m22','s22a','s22b'])expect(lessonMission(id)).toBe('m22');expect(lessonMission('m022')).toBeNull()});
 it('migrates v16, rejects new historical IDs and pays improvements only',()=>{const old={...reward(initial,'m21',100,'hard',false),version:16,lang:'en',avatar:3,placement:true};let save=normalizeSave(old)!;expect(save).toEqual({...old,version:21});save=reward(save,'m22',100,'hard',false);save=reward(save,'s22a',100,'normal',true);expect(save.xp).toBe(450);expect(normalizeSave({...save,version:16})).toBeNull();expect(normalizeSave(save)).toEqual(save);expect(reward(save,'m22',100,'hard',false)).toEqual(save);expect(reward(save,'s22b',50,'hard',true)).toEqual(save)});
});
