import { b, type Bilingual } from './core';

// Scenario, recommended decision, two plausible but insufficient decisions,
// causal explanation and two incorrect interpretations. All cases are fictional.
type Row = [Bilingual,Bilingual,Bilingual,Bilingual,Bilingual,Bilingual,Bilingual];
export const advancedCases:Record<string,Row> = {
m1:[
b('A senha de uma loja vazou. Seu e-mail usa a mesma senha, tem MFA e mantém sessões abertas. Você ainda consegue entrar. Qual plano reduz o risco imediato e evita repetição?','A shop password leaked. Your email reuses it, has MFA and active sessions. You can still sign in. Which plan reduces immediate risk and recurrence?'),
b('Trocar as senhas reutilizadas por exclusivas, revisar e encerrar sessões suspeitas e conferir recuperação e MFA.','Replace reused passwords with unique ones, review and revoke suspicious sessions, and check recovery and MFA.'),
b('Trocar só a senha da loja: o MFA já protege todas as sessões do e-mail.','Change only the shop password: MFA already protects every email session.'),
b('Trocar a senha do e-mail e manter as sessões e a recuperação sem revisão.','Change the email password and leave sessions and recovery unchecked.'),
b('MFA reduz riscos, mas não torna segura uma senha vazada nem garante que sessões existentes sejam encerradas.','MFA reduces risk, but does not make a leaked password safe or guarantee existing sessions are revoked.'),
b('A presença de MFA prova que nenhum acesso indevido ocorreu.','Having MFA proves no unauthorized access occurred.'),
b('Uma troca de senha sempre revoga todas as sessões em qualquer serviço.','Changing a password always revokes all sessions on every service.')],
m2:[
b('Uma mensagem chega na conversa antiga de um fornecedor conhecido. Pede mudança de conta bancária hoje; o domínio parece correto. A equipe não aprovou a mudança. Como agir?','A message arrives in an old thread with a known supplier. It requests a bank-account change today; the domain looks right. The team has not approved it. What should you do?'),
b('Suspender o pagamento e confirmar a mudança por contato independente já cadastrado, seguindo o processo financeiro.','Pause payment and verify through an independently stored contact, following the financial process.'),
b('Responder à mesma conversa pedindo confirmação e pagar se a resposta chegar.','Reply to the same thread asking for confirmation and pay if a reply arrives.'),
b('Aceitar porque o domínio correto e o histórico da conversa comprovam autorização.','Accept because the correct domain and thread history prove authorization.'),
b('Uma conta legítima pode ser comprometida; identidade aparente não comprova autorização para mudar o pagamento.','A legitimate account can be compromised; apparent identity does not prove authorization to change payment.'),
b('Mensagens numa conversa antiga não podem ser fraudulentas.','Messages in an old thread cannot be fraudulent.'),
b('O remetente pode autorizar sozinho qualquer alteração financeira.','The sender alone can authorize any financial change.')],
m3:[
b('Um anúncio leva a nexus-suporte.example, com HTTPS válido. O serviço conhecido é nexus.example. O site pede instalar uma extensão para abrir o boleto. Qual decisão combina as pistas?','An ad leads to nexus-suporte.example with valid HTTPS. The known service is nexus.example. The site asks you to install an extension to view a bill. Which decision combines the clues?'),
b('Não instalar; acessar o endereço conhecido por caminho independente e confirmar a cobrança.','Do not install; access the known address independently and verify the bill.'),
b('Instalar porque HTTPS garante que a extensão pertence ao serviço esperado.','Install because HTTPS guarantees the extension belongs to the expected service.'),
b('Digitar os dados sem instalar a extensão, pois a conexão continua criptografada.','Enter the data without installing the extension, since the connection is encrypted.'),
b('HTTPS protege a conexão com aquele domínio; não prova que ele é a organização esperada nem legitima o pedido.','HTTPS protects the connection to that domain; it does not prove it is the expected organization or legitimize the request.'),
b('Um certificado válido identifica automaticamente a empresa que você procurava.','A valid certificate automatically identifies the company you were looking for.'),
b('Evitar a instalação elimina o risco de entregar dados ao domínio errado.','Avoiding installation eliminates the risk of giving data to the wrong domain.')],
m4:[
b('Você vai publicar uma planilha sem nomes, mas com bairro, idade exata e data de atendimento. Numa linha há só uma pessoa daquele bairro. A finalidade é mostrar tendências mensais. Qual versão publicar?','You will publish a nameless spreadsheet with neighborhood, exact age and appointment date. One row describes the only person from that neighborhood. The purpose is monthly trends. Which version should be published?'),
b('Agregar por mês e faixas amplas, tratar grupos pequenos e revisar o risco de reidentificação antes de publicar.','Aggregate by month and broad ranges, handle small groups, and review reidentification risk before publishing.'),
b('Publicar como está, pois remover nomes já anonimiza cada linha.','Publish as is, since removing names anonymizes every row.'),
b('Trocar nomes por códigos estáveis e manter todos os detalhes para facilitar comparação pública.','Replace names with stable codes and keep every detail for public comparison.'),
b('Combinações de atributos podem identificar alguém; a finalidade de tendências não exige exposição individual.','Attribute combinations can identify someone; trends do not require individual exposure.'),
b('Dados sem nome nunca são pessoais.','Data without names are never personal.'),
b('Um código estável impede qualquer ligação com outras bases.','A stable code prevents all links to other datasets.')],
m5:[
b('O endpoint avisa sobre execução suspeita e arquivos mudando rapidamente. O usuário quer conectar um disco de backup e reiniciar. Há equipe de resposta disponível. Qual primeira sequência?','The endpoint reports suspicious execution and rapidly changing files. The user wants to connect a backup disk and reboot. A response team is available. What is the first sequence?'),
b('Conter a conexão conforme o procedimento, acionar a equipe e preservar evidências; manter o backup separado.','Contain connectivity according to procedure, contact the team and preserve evidence; keep the backup separate.'),
b('Conectar o backup para salvar tudo antes de avisar a equipe.','Connect the backup to save everything before notifying the team.'),
b('Reinstalar imediatamente e depois tentar reconstruir os registros.','Reinstall immediately and then try to reconstruct the records.'),
b('Contenção limita propagação; preservar evidências apoia a análise e separar o backup protege a recuperação.','Containment limits spread; preserving evidence supports analysis and separating backups protects recovery.'),
b('Todo backup conectado fica imune a alterações do sistema suspeito.','Every connected backup is immune to changes by the suspect system.'),
b('Reinstalar preserva automaticamente as evidências voláteis.','Reinstalling automatically preserves volatile evidence.')],
m6:[
b('Um app de lanterna da loja oficial pede acessibilidade e leitura de notificações para funcionar. Seu celular recebe códigos de acesso. Qual análise é mais adequada?','A flashlight app from the official store demands accessibility and notification access. Your phone receives login codes. Which analysis is appropriate?'),
b('Recusar permissões sem relação com a função, revisar o app e escolher uma alternativa que use apenas o necessário.','Refuse unrelated permissions, review the app and choose an alternative using only what is necessary.'),
b('Conceder tudo: estar na loja oficial torna as permissões proporcionais.','Grant everything: being in the official store makes the permissions proportionate.'),
b('Conceder acessibilidade e desligar notificações visuais, sem rever o acesso do app.','Grant accessibility and hide visual notifications without reviewing app access.'),
b('Origem e permissões são verificações diferentes; acesso desnecessário pode expor conteúdo sensível.','Source and permissions are different checks; unnecessary access can expose sensitive content.'),
b('Ocultar notificações da tela revoga automaticamente a permissão do app.','Hiding on-screen notifications automatically revokes app permission.'),
b('Toda função disponível numa loja é necessária para qualquer aplicativo.','Every feature available in a store is necessary for any app.')],
m7:[
b('A sincronização replica arquivos apagados. Existe backup separado de ontem, mas a chave de recuperação só está no computador que falhou. O serviço precisa voltar em quatro horas. Qual lacuna testar primeiro?','Sync replicates deleted files. A separate backup from yesterday exists, but its recovery key is only on the failed computer. The service must return within four hours. Which gap should be tested first?'),
b('Recuperar acesso autorizado à chave por uma cópia protegida e testar restauração com dados e dependências.','Recover authorized key access through a protected copy and test restoration of data and dependencies.'),
b('Aumentar a frequência da sincronização e considerar o serviço recuperável.','Increase sync frequency and consider the service recoverable.'),
b('Confiar na existência do backup; confirmar o tamanho é suficiente para cumprir o prazo.','Trust that the backup exists; checking size is enough to meet the deadline.'),
b('Uma cópia só atende à recuperação se puder ser acessada e restaurada dentro dos objetivos, incluindo chaves e dependências.','A copy supports recovery only if accessible and restorable within objectives, including keys and dependencies.'),
b('Sincronização sempre preserva versões apagadas indefinidamente.','Sync always preserves deleted versions indefinitely.'),
b('O tamanho do arquivo prova que a restauração funciona.','File size proves restoration works.')],
m8:[
b('O DNS do portal aponta para um IP novo. A porta 443 responde, mas o certificado não corresponde ao nome. Não há mudança aprovada no inventário. Qual próximo passo?','Portal DNS points to a new IP. Port 443 responds, but the certificate does not match the name. Inventory has no approved change. What next?'),
b('Preservar as observações e comparar DNS, certificado e registro de mudança antes de enviar credenciais.','Preserve observations and compare DNS, certificate and change records before sending credentials.'),
b('Ignorar o certificado porque a porta 443 está aberta.','Ignore the certificate because port 443 is open.'),
b('Declarar comprometimento confirmado apenas porque o IP mudou.','Declare confirmed compromise solely because the IP changed.'),
b('As pistas mostram uma inconsistência a investigar; porta aberta não autentica o destino e mudança de IP não prova invasão.','The clues show an inconsistency to investigate; an open port does not authenticate a destination and an IP change does not prove compromise.'),
b('A porta 443 prova que o servidor pertence à organização.','Port 443 proves the server belongs to the organization.'),
b('Qualquer mudança de IP é evidência suficiente de ataque.','Any IP change is sufficient evidence of attack.')],
m9:[
b('Um pacote e seu hash chegaram no mesmo site não verificado. Os hashes coincidem. A equipe precisa confirmar origem e integridade. Que informação ainda falta?','A package and its hash came from the same unverified site. The hashes match. The team needs origin and integrity assurance. What is still missing?'),
b('Uma referência autenticada ou assinatura validada com chave confiável e correspondente ao pacote.','An authenticated reference or signature validated with a trusted key matching the package.'),
b('Só repetir o cálculo com o mesmo hash publicado naquele site.','Just recalculate using the same hash published on that site.'),
b('Criptografar o pacote recebido para provar quem o criou.','Encrypt the received package to prove who created it.'),
b('Um invasor pode substituir arquivo e hash juntos; integridade relativa a uma referência não confiável não comprova origem.','An attacker can replace file and hash together; integrity relative to an untrusted reference does not prove origin.'),
b('Qualquer hash correto identifica o autor do arquivo.','Any matching hash identifies the file author.'),
b('Criptografar depois do download autentica retroativamente a origem.','Encrypting after download retroactively authenticates the source.')],
m10:[
b('Um prestador precisa ler um relatório por dois dias. O grupo dele também tem edição na pasta inteira. Você dá um link de leitura com expiração. O risco foi resolvido?','A contractor needs to read one report for two days. Their group also has edit access to the entire folder. You give a read-only expiring link. Is the risk resolved?'),
b('Não: revisar permissões efetivas e herdadas, limitar o grupo e testar acesso com a identidade do prestador.','No: review effective and inherited permissions, limit the group and test access as the contractor.'),
b('Sim: a permissão mais restrita de qualquer link sempre domina todos os outros acessos.','Yes: the most restrictive permission on any link always overrides all other access.'),
b('Sim, desde que o prestador prometa usar apenas o link novo.','Yes, provided the contractor promises to use only the new link.'),
b('O acesso efetivo pode vir de outras concessões; alterar um link não remove automaticamente permissões do grupo.','Effective access may come from other grants; changing one link does not automatically remove group permissions.'),
b('Expiração de um link revoga toda associação a grupos.','Link expiration revokes every group membership.'),
b('Promessas de uso substituem o controle de acesso efetivo.','Usage promises replace effective access control.')],
m11:[
b('No terminal simulado, um host suspeito tem registros ainda não coletados. O comando de limpeza remove os arquivos; a contenção de rede mantém o disco. Qual sequência apoia resposta e investigação?','In the simulated terminal, a suspect host has logs not yet collected. Cleanup deletes files; network containment preserves disk. Which sequence supports response and investigation?'),
b('Conferir o alvo, conter conforme procedimento, coletar e registrar evidências antes da limpeza autorizada.','Check the target, contain according to procedure, collect and record evidence before authorized cleanup.'),
b('Limpar primeiro para reduzir o alerta e só depois coletar os registros restantes.','Clean first to reduce the alert, then collect remaining logs.'),
b('Executar o comando no primeiro host listado para ganhar tempo.','Run the command on the first listed host to save time.'),
b('Comandos alteram estado; alvo correto, ordem das ações e preservação precisam ser considerados juntos.','Commands change state; correct target, action order and preservation must be considered together.'),
b('Apagar registros não afeta a possibilidade de investigar.','Deleting logs does not affect investigation.'),
b('Hosts de nomes semelhantes têm sempre o mesmo papel.','Similarly named hosts always have the same role.')],
m12:[
b('Uma pessoa autenticada abre o boletim de outro aluno ao trocar o identificador. O sistema exige MFA no login. Qual correção atua na falha demonstrada?','An authenticated person opens another student’s report by changing its identifier. Login requires MFA. Which fix addresses the demonstrated flaw?'),
b('Validar no servidor a autorização da identidade para cada objeto solicitado, incluindo testes de acesso negado.','Validate server-side authorization for each requested object, including denied-access tests.'),
b('Adicionar mais um fator no login e manter o acesso por identificador.','Add another login factor and retain identifier-based access.'),
b('Ocultar o identificador na interface e manter a API sem validação de dono.','Hide the identifier in the interface and keep the API without ownership validation.'),
b('Autenticação confirma identidade; autorização decide quais recursos essa identidade pode acessar.','Authentication confirms identity; authorization decides which resources that identity may access.'),
b('Uma identidade autenticada tem direito a todos os objetos do sistema.','An authenticated identity is entitled to all system objects.'),
b('Um identificador escondido elimina a necessidade de autorização.','A hidden identifier removes the need for authorization.')],
m13:[
b('SPF, DKIM e DMARC passam numa mensagem que pede exportar dados para um endereço externo novo. A mudança não consta no processo. Qual conclusão é sustentada?','SPF, DKIM and DMARC pass on a message requesting data export to a new external address. The change is absent from the process. Which conclusion is supported?'),
b('Os controles de e-mail passaram, mas o pedido ainda exige verificar autorização e finalidade por canal independente.','Email controls passed, but the request still needs authorization and purpose verified through an independent channel.'),
b('O pedido é seguro, pois a autenticação de e-mail valida o conteúdo e a finalidade.','The request is safe because email authentication validates content and purpose.'),
b('O resultado prova falsificação; bloquear o domínio inteiro sem investigar.','The result proves spoofing; block the entire domain without investigating.'),
b('Autenticação de domínio não garante intenção legítima nem exclui comprometimento de uma conta autorizada.','Domain authentication does not guarantee legitimate intent or rule out compromise of an authorized account.'),
b('DMARC aprova todas as operações solicitadas no corpo da mensagem.','DMARC approves every operation requested in the message body.'),
b('Controles aprovados provam que a conta remetente nunca foi comprometida.','Passing controls prove the sending account was never compromised.')],
m14:[
b('Você revogou um link público na nuvem. Uma colaboradora já baixou o arquivo, e um grupo externo continua com edição direta. Qual acompanhamento é necessário?','You revoked a public cloud link. A collaborator already downloaded the file and an external group still has direct edit access. What follow-up is needed?'),
b('Revisar as demais concessões e tratar a exposição e as cópias já distribuídas pelo processo da organização.','Review other grants and address exposure and already distributed copies through the organization’s process.'),
b('Encerrar o caso: revogar um link apaga todos os downloads e acessos diretos.','Close the case: revoking a link deletes all downloads and direct access.'),
b('Criar outro link público com senha sem rever o grupo externo.','Create another password-protected public link without reviewing the external group.'),
b('Revogação atua naquela concessão; não recolhe cópias baixadas nem remove automaticamente acessos independentes.','Revocation affects that grant; it does not retrieve downloaded copies or automatically remove independent access.'),
b('O provedor sempre elimina qualquer cópia fora da nuvem após revogação.','The provider always deletes every off-cloud copy after revocation.'),
b('Senha em um link novo substitui todas as permissões já existentes.','A password on a new link replaces all existing permissions.')],
m15:[
b('A rede de visitantes deve alcançar o portal HTTPS, mas não o banco interno. A aplicação interna ainda depende desse banco. Qual política preserva o serviço e reduz exposição?','Guest networking must reach the HTTPS portal but not the internal database. The internal application still depends on that database. Which policy preserves service and reduces exposure?'),
b('Permitir os fluxos necessários entre origens e destinos definidos, negar os demais e testar também as dependências internas.','Allow necessary flows between defined sources and destinations, deny the rest and test internal dependencies too.'),
b('Bloquear toda conexão ao banco, inclusive a aplicação autorizada.','Block every database connection, including the authorized application.'),
b('Mover visitantes para outra sub-rede sem adicionar controles entre as redes.','Move guests to another subnet without adding controls between networks.'),
b('Separação de endereços não impõe política sozinha; regras devem limitar caminhos sem quebrar fluxos autorizados.','Address separation alone does not enforce policy; rules must limit paths without breaking authorized flows.'),
b('Estar em sub-redes diferentes impede automaticamente todo tráfego entre elas.','Being in separate subnets automatically prevents all traffic between them.'),
b('Disponibilidade é irrelevante se a regra bloqueia qualquer ameaça possível.','Availability is irrelevant if a rule blocks every possible threat.')],
m16:[
b('Um log marca 10:05 UTC e outro 07:05 no fuso UTC−3. Eles mostram a mesma conta, mas os relógios não foram verificados. Qual relato preserva a qualidade da investigação?','One log says 10:05 UTC and another 07:05 in UTC−3. They show the same account, but clocks have not been checked. Which account preserves investigation quality?'),
b('Normalizar os horários, registrar a incerteza dos relógios e correlacionar contexto antes de afirmar a sequência.','Normalize timestamps, record clock uncertainty and correlate context before asserting a sequence.'),
b('Afirmar três horas entre os eventos usando apenas os números exibidos.','Assert three hours between events using only the displayed numbers.'),
b('Concluir que a mesma pessoa executou ambos porque o nome da conta coincide.','Conclude the same person performed both because the account name matches.'),
b('Fusos podem representar o mesmo instante; conta e horário isolados não comprovam identidade humana nem causalidade.','Time zones may represent the same instant; account and time alone do not prove human identity or causality.'),
b('A ordem visual dos logs sempre é a ordem real dos fatos.','Visual log order is always the real event order.'),
b('Uma conta compartilhada identifica sem ambiguidade quem a usou.','A shared account unambiguously identifies who used it.')],
m17:[
b('Um serviço abre o arquivo autorizado e depois precisa processar entradas externas. Continua como administrador porque iniciou assim. Qual desenho reduz o impacto de uma falha no processamento?','A service opens an authorized file and then processes external input. It remains an administrator because it started that way. Which design reduces the impact of a processing flaw?'),
b('Reduzir privilégios para a tarefa e restringir recursos acessíveis, testando as operações realmente necessárias.','Reduce privileges for the task and restrict accessible resources, testing truly necessary operations.'),
b('Manter administrador e confiar que um nome de processo conhecido evita abuso.','Keep administrator privileges and trust that a familiar process name prevents abuse.'),
b('Mover o executável de pasta sem alterar sua identidade ou privilégios.','Move the executable to another folder without changing identity or privileges.'),
b('O dano possível depende dos privilégios e recursos do processo, não apenas de seu nome ou localização.','Potential damage depends on process privileges and resources, not only its name or location.'),
b('Um processo legítimo não pode ser usado para executar uma ação indevida.','A legitimate process cannot be used for an unauthorized action.'),
b('Mudar o caminho do executável revoga automaticamente seus privilégios.','Changing the executable path automatically revokes its privileges.')],
m18:[
b('Um documento tem assinatura matematicamente válida. O certificado do signatário foi revogado e não há evidência confiável do instante da assinatura. A política exige confiança atual. Como relatar?','A document has a mathematically valid signature. The signer’s certificate was revoked and no trusted signing-time evidence exists. Policy requires current trust. How should this be reported?'),
b('Separar integridade criptográfica de confiança: a assinatura verifica, mas a aceitação pela política não está satisfeita.','Separate cryptographic integrity from trust: the signature verifies, but policy acceptance is not satisfied.'),
b('Aceitar sem ressalvas: validade matemática ignora revogação e política.','Accept without qualification: mathematical validity overrides revocation and policy.'),
b('Declarar que o documento foi certamente adulterado por causa da revogação.','Declare the document certainly tampered with because of revocation.'),
b('Verificação matemática e decisão de confiança são diferentes; revogação não prova adulteração do conteúdo.','Mathematical verification and trust decisions differ; revocation does not prove content tampering.'),
b('Qualquer assinatura verificável deve ser aceita em qualquer contexto.','Every verifiable signature must be accepted in every context.'),
b('Revogar um certificado altera os bytes dos documentos anteriores.','Revoking a certificate changes the bytes of earlier documents.')],
m19:[
b('O formulário limita a busca no navegador, mas a API monta SQL concatenando o texto recebido. O aluno pode chamar a API diretamente. Qual combinação atua na causa e verifica a correção?','The form limits search input in the browser, but the API builds SQL by concatenating received text. A student can call the API directly. Which combination addresses the cause and checks the fix?'),
b('Usar consultas parametrizadas no servidor, validar o contexto e testar que entradas são tratadas como dados.','Use server-side parameterized queries, validate context and test that inputs are treated as data.'),
b('Reforçar só a validação JavaScript do formulário e manter a concatenação na API.','Strengthen only form JavaScript validation and retain API concatenation.'),
b('Remover aspas de qualquer entrada e considerar a consulta segura em todos os contextos.','Remove quotes from every input and consider the query safe in every context.'),
b('Controles do navegador podem ser contornados; parametrização separa dados da estrutura da consulta no servidor.','Browser controls can be bypassed; parameterization separates data from server-side query structure.'),
b('Uma validação visual protege todas as chamadas diretas à API.','Visual validation protects all direct API calls.'),
b('Remover um caractere substitui sempre a separação entre código e dados.','Removing one character always replaces separation of code and data.')],
m20:[
b('Uma auditoria exige evidência de recuperação. O plano existe, mas nunca foi testado. Há backup de ontem e responsáveis definidos. Qual evidência fecha melhor essa lacuna?','An audit requires recovery evidence. A plan exists but was never tested. Yesterday’s backup and named owners exist. Which evidence best closes the gap?'),
b('Registrar um teste de restauração com resultados, tempos, dependências, problemas encontrados e ações dos responsáveis.','Record a restore test with results, timings, dependencies, issues and owners’ actions.'),
b('Apresentar apenas o plano assinado como prova de que o serviço volta no prazo.','Present only the signed plan as proof that the service returns on time.'),
b('Listar os nomes das ferramentas como prova de eficácia de recuperação.','List tool names as proof of recovery effectiveness.'),
b('Frameworks organizam resultados e responsabilidades; existência de documento ou ferramenta não demonstra eficácia operacional.','Frameworks organize outcomes and responsibilities; a document or tool does not demonstrate operational effectiveness.'),
b('Um documento aprovado comprova automaticamente todos os resultados previstos.','An approved document automatically proves every intended outcome.'),
b('Quantidade de ferramentas equivale à qualidade da recuperação.','Tool count equals recovery quality.')],
m21:[
b('O SOC recebe dois alertas: falhas de login em uma conta de teste e acesso bem-sucedido incomum a uma conta privilegiada num servidor crítico. A janela de manutenção está aberta, mas ainda não foi correlacionada. Qual prioridade?','The SOC receives two alerts: failed logins to a test account and unusual successful access by a privileged account on a critical server. A maintenance window is open but not yet correlated. What is the priority?'),
b('Priorizar o acesso privilegiado pelo impacto, correlacionar a manutenção e preservar dados; manter o outro alerta em triagem.','Prioritize privileged access by impact, correlate maintenance and preserve data; keep the other alert in triage.'),
b('Descartar o acesso privilegiado porque toda atividade na janela é autorizada.','Discard privileged access because all activity in the window is authorized.'),
b('Priorizar apenas o maior número de falhas, ignorando criticidade e sucesso do acesso.','Prioritize only the highest failure count, ignoring criticality and successful access.'),
b('Prioridade combina impacto, evidência e contexto; uma janela autorizada não aprova automaticamente toda ação.','Priority combines impact, evidence and context; an authorized window does not automatically approve every action.'),
b('O maior volume sempre representa o maior risco, independentemente do ativo.','The highest volume always represents the highest risk, regardless of asset.'),
b('Uma janela de manutenção elimina a necessidade de conferir identidade e ação.','A maintenance window removes the need to check identity and action.')],
m22:[
b('Uma regra gera muitos alertas durante backup autorizado. Fora da janela, o mesmo padrão em outro destino deve continuar detectável. Qual ajuste e teste são adequados?','A rule generates many alerts during authorized backup. Outside the window, the same pattern toward another destination must remain detectable. Which adjustment and test fit?'),
b('Restringir a exceção ao contexto autorizado e testar eventos benignos e ameaças fora desse contexto antes de publicar.','Restrict the exception to authorized context and test benign events and threats outside that context before publishing.'),
b('Desativar a regra inteira para eliminar falsos positivos.','Disable the entire rule to eliminate false positives.'),
b('Excluir permanentemente qualquer tráfego de backup, independentemente de identidade e destino.','Permanently exclude all backup traffic regardless of identity and destination.'),
b('Reduzir ruído não deve criar ponto cego; testes precisam medir tanto falsos positivos quanto ameaças perdidas.','Reducing noise must not create a blind spot; tests need to measure false positives and missed threats.'),
b('Uma regra sem alertas prova ausência de ameaças.','A rule with no alerts proves absence of threats.'),
b('Toda atividade rotulada como backup é autorizada.','All activity labeled as backup is authorized.')],
m23:[
b('Dois fluxos TLS vão ao mesmo serviço compartilhado: backup aprovado e envio desconhecido. O sensor só vê horário, origem, destino e volume. Qual ação evita certeza indevida e bloqueio excessivo?','Two TLS flows go to the same shared service: approved backup and unknown transfer. The sensor sees only time, source, destination and volume. Which action avoids unwarranted certainty and excessive blocking?'),
b('Correlacionar identidade, janela e registros do endpoint; preservar o backup aprovado e encaminhar o desconhecido à triagem.','Correlate identity, window and endpoint records; preserve approved backup and route the unknown transfer to triage.'),
b('Bloquear o serviço compartilhado inteiro: volume alto prova exfiltração nos dois fluxos.','Block the entire shared service: high volume proves exfiltration in both flows.'),
b('Liberar ambos: TLS garante que o conteúdo é legítimo.','Allow both: TLS guarantees the content is legitimate.'),
b('Metadados apoiam hipóteses, mas não revelam por si só o conteúdo nem a autorização de cada fluxo.','Metadata supports hypotheses but alone reveals neither content nor authorization of each flow.'),
b('Criptografia de transporte é um atestado de intenção legítima.','Transport encryption certifies legitimate intent.'),
b('Destino compartilhado significa que todos os fluxos têm a mesma finalidade.','A shared destination means all flows have the same purpose.')],
m24:[
b('O host foi isolado e as evidências foram preservadas. O serviço limpo já funciona em teste, mas a credencial comprometida permanece ativa e o teste usou só a página inicial. A operação pede reconexão agora. Qual decisão?','The host is isolated and evidence preserved. The clean service works in testing, but the compromised credential is still active and only the homepage was tested. Operations requests reconnection now. What should you decide?'),
b('Tratar a credencial e a causa, validar funções e dependências críticas e autorizar retorno monitorado pelos critérios do plano.','Address the credential and cause, validate critical functions and dependencies and authorize monitored return against plan criteria.'),
b('Reconectar: abrir a página inicial comprova recuperação completa.','Reconnect: opening the homepage proves complete recovery.'),
b('Apagar as evidências para liberar espaço e reconectar antes de revisar a credencial.','Delete evidence to free space and reconnect before reviewing the credential.'),
b('Disponibilidade parcial não encerra o incidente; recuperação precisa de causa tratada, critérios verificáveis e monitoramento.','Partial availability does not close the incident; recovery requires the cause addressed, verifiable criteria and monitoring.'),
b('Isolar um host revoga automaticamente todas as credenciais comprometidas.','Isolating a host automatically revokes all compromised credentials.'),
b('Uma única página funcionando comprova integridade de todas as dependências.','One working page proves the integrity of every dependency.')],
};
advancedCases.a1=[
b('No Tower Defense, o firewall amplo preservou 100 de integridade, mas bloqueou portal e backup autorizados. O orçamento permite firewall seletivo, sensor de assinatura e triagem. Qual configuração equilibra os objetivos do modelo?','In Tower Defense, the broad firewall preserved 100 integrity but blocked the authorized portal and backup. Budget allows a selective firewall, signature sensor and triage. Which configuration balances the model’s goals?'),
b('Firewall seletivo para administração proibida, sensor para o padrão conhecido e triagem do desconhecido; preservar portal e backup.','Selective firewall for prohibited administration, a sensor for the known pattern and triage for unknown traffic; preserve portal and backup.'),
b('Manter o firewall amplo: integridade máxima comprova que todos os objetivos foram cumpridos.','Keep the broad firewall: maximum integrity proves every objective was met.'),
b('Remover toda defesa para evitar falsos positivos e melhorar somente a entrega de fluxos.','Remove every defense to avoid false positives and improve only flow delivery.'),
b('A nota combina proteção e continuidade; triagem trata incerteza sem afirmar que o fluxo desconhecido é malicioso.','Scoring combines protection and continuity; triage addresses uncertainty without claiming an unknown flow is malicious.'),
b('Todo fluxo encaminhado à triagem já é uma ameaça confirmada.','Every flow routed to triage is already a confirmed threat.'),
b('Bloquear todos os fluxos mantém automaticamente a disponibilidade dos serviços.','Blocking every flow automatically maintains service availability.')];
advancedCases.a2=[
b('No CTF, Lia deve ler o boletim 17 e não o 18. Após a correção, ambas as solicitações retornam 403. Nenhum dado vazou no teste. A flag de correção completa deveria ser concedida?','In the CTF, Lia should read report 17 but not 18. After the fix, both requests return 403. No data leaked in the test. Should the complete-fix flag be awarded?'),
b('Não: testar a política para permitir o boletim próprio e negar o alheio, sem expor dados privados.','No: test the policy to allow the own report and deny the other report without exposing private data.'),
b('Sim: negar qualquer acesso resolve segurança e preserva todas as funções previstas.','Yes: denying every access solves security and preserves all intended functions.'),
b('Sim, se o navegador esconder o erro; o servidor pode continuar negando ambos.','Yes, if the browser hides the error; the server can keep denying both.'),
b('Uma correção deve cumprir a política inteira: bloquear o acesso indevido e preservar o acesso legítimo.','A fix must fulfill the whole policy: block unauthorized access and preserve legitimate access.'),
b('Testes negativos substituem todos os testes de uso autorizado.','Negative tests replace all authorized-use tests.'),
b('Ocultar o código de resposta altera a autorização aplicada pelo servidor.','Hiding the response code changes server-side authorization.')];
