import { describe, expect, it } from 'vitest';
import { aligned, mailResult, mailCases, diagnosisCorrect, emailScore, challengeCases, emailLesson } from './emailSecurity';
import { initial, normalizeSave, reward } from './core';
import { lessonMission, canStudyChallenge } from './lessons';
describe('email origin simulation',()=>{
 it('requires a passed AND aligned check on either route',()=>{const c=mailCases[4];for(const spfPass of [false,true])for(const dkimPass of [false,true]){expect(mailResult({...c,spfPass,dkimPass}).pass).toBe(spfPass||dkimPass)}expect(mailResult(mailCases[2])).toEqual({pass:false,spf:false,dkim:false,basis:'neither'});expect(mailResult(mailCases[0]).basis).toBe('spf');expect(mailResult(mailCases[1]).basis).toBe('dkim')});
 it('distinguishes exact alignment and supplied organizational domains',()=>{expect(aligned('news.nexus.example','nexus.example','relaxed')).toBe(true);expect(aligned('news.nexus.example','nexus.example','strict')).toBe(false);expect(aligned('NEXUS.EXAMPLE','nexus.example','strict')).toBe(true);for(const d of ['nexus.example.evil.example','evil.nexus.example','unknown.example'])expect(aligned(d,'nexus.example','relaxed')).toBe(false)});
 it('keeps SPF and DKIM alignment modes independent',()=>{const c=mailCases[3];expect(mailResult(c).pass).toBe(false);expect(mailResult({...c,aspf:'relaxed'}).basis).toBe('spf');expect(mailResult({...c,adkim:'relaxed'}).basis).toBe('dkim')});
 it('requires both correct diagnosis and route rather than awarding lucky results',()=>{expect(diagnosisCorrect(mailCases[0],'pass','spf')).toBe(true);expect(diagnosisCorrect(mailCases[0],'pass','both')).toBe(false);expect(diagnosisCorrect(mailCases[0],'fail','spf')).toBe(false);expect(diagnosisCorrect(mailCases[2],'fail','neither')).toBe(true)});
 it('covers forwarding, unaligned passes and strict mode in challenge variations',()=>{for(const d of ['easy','normal','hard'] as const)for(const side of [false,true])expect(challengeCases(d,side)).toHaveLength(2);expect(challengeCases('hard')[1].aspf).toBe('strict');expect(emailScore([true,false,true,true])).toBe(75);expect(emailScore([true,false])).toBe(50)});
 it('migrates v7 progress and admits new IDs only in v8 with best rewards',()=>{const old={...reward(initial,'m12',100,'hard',false),version:7,avatar:3,lang:'en',placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:22});s=reward(s,'m13',75,'easy',false);s=reward(s,'m13',100,'hard',false);s=reward(s,'s13a',100,'normal',true);expect(s.xp).toBe(450);expect(reward(s,'s13b',50,'hard',true)).toEqual(s);expect(reward(s,'m13',100,'hard',false)).toEqual(s);expect(normalizeSave({...s,version:7})).toBeNull();expect(normalizeSave(s)).toEqual(s)});
 it('preserves lesson access and campaign prerequisites',()=>{for(const id of ['m13','s13a','s13b'])expect(lessonMission(id)).toBe('m13');expect(canStudyChallenge('m13',{},false)).toBe(false);expect(canStudyChallenge('m13',{m12:100},false)).toBe(true);expect(canStudyChallenge('m13',{},true)).toBe(true);expect(canStudyChallenge('m13',{},true,true)).toBe(false)});
 it('explains six everyday cases, reasoning and actions in both languages',()=>{expect(emailLesson.concepts).toHaveLength(6);for(const lang of ['pt','en'] as const)for(const c of emailLesson.concepts){expect(c.walkthrough?.situation[lang]).toBeTruthy();expect(c.walkthrough?.reasoning[lang]).toBeTruthy();expect(c.walkthrough?.action[lang]).toBeTruthy()}});
});
