import { b, type Bilingual, type Difficulty } from './core';
import { q } from './content';
import type { Lesson } from './lessons';

export type Alignment='relaxed'|'strict';
export type MailCase={id:string;title:Bilingual;context:Bilingual;from:string;spf:string;dkim:string;spfPass:boolean;dkimPass:boolean;aspf:Alignment;adkim:Alignment};
// Closed fictional inventory. Organizational domains are supplied by the scenario,
// never guessed by splitting labels. This is not a DNS/DMARC implementation.
const inventory:Record<string,string>={'nexus.example':'nexus.example','news.nexus.example':'nexus.example','relay.example':'relay.example'};
export function aligned(a:string,z:string,mode:Alignment){a=a.toLowerCase();z=z.toLowerCase();return !!inventory[a]&&!!inventory[z]&&(mode==='strict'?a===z:inventory[a]===inventory[z])}
export function mailResult(c:MailCase){const spf=c.spfPass&&aligned(c.spf,c.from,c.aspf);const dkim=c.dkimPass&&aligned(c.dkim,c.from,c.adkim);return {pass:spf||dkim,spf,dkim,basis:spf&&dkim?'both':spf?'spf':dkim?'dkim':'neither'} as const}
export function diagnosisCorrect(c:MailCase,result:string,basis:string){const r=mailResult(c);return result===(r.pass?'pass':'fail')&&basis===r.basis}
export const mailCases:MailCase[]=[
 {id:'spf',title:b('O aviso da biblioteca','The library notice'),context:b('O portal enviou o prazo do seu livro. O receptor verificou o servidor de envio; a assinatura DKIM falhou neste exemplo.','The portal sent your book deadline. The receiver checked the sending server; the DKIM signature failed in this example.'),from:'nexus.example',spf:'nexus.example',dkim:'nexus.example',spfPass:true,dkimPass:false,aspf:'relaxed',adkim:'relaxed'},
 {id:'forward',title:b('O convite encaminhado','The forwarded invitation'),context:b('Você encaminhou um convite para outra caixa. O novo servidor não passou em SPF; a assinatura DKIM coberta permaneceu válida e alinhada.','You forwarded an invitation to another mailbox. The new server failed SPF; the covered DKIM signature remained valid and aligned.'),from:'nexus.example',spf:'relay.example',dkim:'news.nexus.example',spfPass:false,dkimPass:true,aspf:'relaxed',adkim:'relaxed'},
 {id:'unrelated',title:b('O nome conhecido, outra origem','Familiar name, different origin'),context:b('A mensagem mostra “Equipe NEXUS”. SPF e DKIM passaram para relay.example, um domínio diferente do From visível.','The message displays “NEXUS Team”. SPF and DKIM passed for relay.example, a different domain from the visible From.'),from:'nexus.example',spf:'relay.example',dkim:'relay.example',spfPass:true,dkimPass:true,aspf:'relaxed',adkim:'relaxed'},
 {id:'strict',title:b('O boletim do subdomínio','The subdomain newsletter'),context:b('O boletim usa news.nexus.example para enviar e assinar, mas o From é nexus.example. O dono exige comparação exata nas duas rotas.','The newsletter uses news.nexus.example to send and sign, but From is nexus.example. The owner requires exact comparison on both routes.'),from:'nexus.example',spf:'news.nexus.example',dkim:'news.nexus.example',spfPass:true,dkimPass:true,aspf:'strict',adkim:'strict'},
 {id:'both',title:b('Duas rotas consistentes','Two consistent routes'),context:b('O aviso de matrícula tem SPF e DKIM válidos para o mesmo domínio do From. Ainda precisamos avaliar o pedido no conteúdo.','The enrollment notice has valid SPF and DKIM for the same domain as From. We still need to assess the content request.'),from:'nexus.example',spf:'nexus.example',dkim:'nexus.example',spfPass:true,dkimPass:true,aspf:'relaxed',adkim:'relaxed'}
];
export function challengeCases(d:Difficulty,side=false){return side?(d==='easy'?[mailCases[1],mailCases[4]]:d==='normal'?[mailCases[2],mailCases[0]]:[mailCases[3],mailCases[1]]):d==='easy'?[mailCases[0],mailCases[2]]:d==='normal'?[mailCases[1],mailCases[4]]:[mailCases[1],mailCases[3]]}
export const emailScore=(correct:boolean[])=>correct.length?Math.round(correct.filter(Boolean).length/correct.length*100):0;
export function emailQuestion(d:Difficulty,kind:'spf'|'content'|'policy'|'rollout'){
 const qs={
 spf:q('Você recebe “Biblioteca NEXUS”. SPF=pass para relay.example. O que esse resultado informa?','You receive “NEXUS Library”. SPF=pass for relay.example. What does this result tell you?', [['O servidor está autorizado para o domínio do envelope verificado','The server is authorized for the checked envelope domain'],['O nome Biblioteca foi confirmado como pessoa confiável','The Library name was confirmed as a trustworthy person'],['Todos os anexos estão livres de malware','All attachments are free of malware']],0,['SPF consulta a autorização do IP de envio para o domínio do envelope (MAIL FROM neste cenário). Não valida o nome exibido nem garante o From visível.','SPF checks sending-IP authorization for the envelope domain (MAIL FROM in this scenario). It does not validate the display name or guarantee the visible From.'],['Compare o endereço do envelope com o From, não só o apelido na tela.','Compare the envelope address with From, not just the display name.']),
 content:q(d==='hard'?'Um fornecedor passa em DMARC e pede trocar a conta bancária “em segredo”. Qual próximo passo?':'Um aviso passa em DMARC e pede seu código de MFA por e-mail. O que fazer?',d==='hard'?'A supplier passes DMARC and requests a bank-account change “in secret”. What comes next?':'A notice passes DMARC and asks for your MFA code by email. What should you do?', [['Atender porque DMARC passou','Comply because DMARC passed'],['Confirmar por um contato já conhecido, sem enviar segredos ou efetuar a mudança','Confirm through a previously known contact, without sending secrets or making the change'],['Responder com senha e código para testar','Reply with password and code to test']],1,['DMARC trata a origem do domínio, não a intenção. Uma conta comprometida também pode enviar mensagens autenticadas. Use um canal independente já conhecido e reporte o pedido suspeito.','DMARC addresses domain origin, not intent. A compromised account can also send authenticated messages. Use an independent, previously known channel and report the suspicious request.'],['Autenticação da origem e segurança do pedido são perguntas distintas.','Origin authentication and request safety are distinct questions.']),
 policy:q('DMARC falhou e a política publicada é p=none. Isso garante bloqueio?','DMARC failed and the published policy is p=none. Does that guarantee blocking?', [['Sim, none apaga automaticamente a mensagem','Yes, none automatically deletes the message'],['Sim, qualquer falha prova fraude','Yes, any failure proves fraud'],['Não. O dono não expressa preferência de tratamento; o receptor decide com outros sinais','No. The owner expresses no handling preference; the receiver decides using other signals']],2,['None não solicita quarentena nem rejeição. Quarantine sinaliza suspeita e reject sinaliza uso do domínio considerado inválido pelo dono; o receptor combina a política com outras análises. Falhas também podem ocorrer em encaminhamentos legítimos.','None requests neither quarantine nor rejection. Quarantine signals suspicion and reject signals domain use considered invalid by the owner; the receiver combines policy with other analysis. Failures can also occur in legitimate forwarding.'],['Uma política publicada é um sinal para o receptor, não um botão de apagar.','A published policy is a signal to the receiver, not a delete button.']),
 rollout:q('A escola usa um serviço terceirizado para enviar boletins. Antes de endurecer DMARC, o que a equipe deve verificar?','The school uses a third-party newsletter sender. Before tightening DMARC, what should the team check?', [['Se os fluxos legítimos autenticam e alinham; analisar relatórios e impacto de encaminhamentos','Whether legitimate flows authenticate and align; analyze reports and forwarding impact'],['Se o remetente tem um logotipo bonito','Whether the sender has a pretty logo'],['Desativar toda verificação permanentemente','Permanently disable every check']],0,['O terceiro pode passar SPF/DKIM para o próprio domínio e ainda falhar em alinhamento com o From da escola. A equipe deve configurar o envio autorizado, avaliar relatórios e fluxos indiretos antes de mudar a política.','A third party may pass SPF/DKIM for its own domain yet fail alignment with the school From. The team should configure authorized sending, assess reports and indirect flows before changing policy.'],['Passar uma verificação não basta: compare também os domínios.','Passing a check is insufficient: compare the domains too.'])
 };return qs[kind];
}
export const emailQuestions=Object.fromEntries(['easy','normal','hard'].map(d=>[d,[emailQuestion(d as Difficulty,'spf'),emailQuestion(d as Difficulty,'content'),emailQuestion(d as Difficulty,'policy')]])) as Record<Difficulty,ReturnType<typeof emailQuestion>[]>;
function concept(title:Bilingual,text:Bilingual,situation:Bilingual,reasoning:Bilingual,action:Bilingual){return {title,text,example:situation,walkthrough:{situation,reasoning,action}}}
export const emailLesson:Lesson={id:'m13',intro:b('Pense no e-mail como uma entrega: há o nome na mensagem, o endereço no envelope e uma assinatura. SPF, DKIM e DMARC ajudam o receptor a conferir a origem. Vamos olhar cada parte sem precisar configurar um servidor.','Think of email as a delivery: there is a name on the message, an envelope address and a signature. SPF, DKIM and DMARC help the receiver check origin. Let’s examine each part without configuring a server.'),practice:b('Compare os cinco avisos fictícios, desligue uma verificação e altere o alinhamento. Observe por que uma rota válida pode bastar e por que duas verificações aprovadas podem falhar em DMARC.','Compare five fictional notices, turn off a check and change alignment. Observe why one valid route can suffice and why two passed checks can fail DMARC.'),concepts:[
 concept(b('1 · Nome, From e envelope','1 · Name, From and envelope'),b('O nome exibido é um rótulo. From é o endereço visível do autor. MAIL FROM é o remetente do envelope usado pelo transporte; podem ser diferentes.','The display name is a label. From is the visible author address. MAIL FROM is the transport envelope sender; they may differ.'),b('Chega “Secretaria da Escola”, mas o endereço visível é aviso@nexus.example e o envelope usa relay.example. Como numa encomenda, a etiqueta e o remetente da logística são pistas distintas.','“School Office” arrives, but the visible address is notice@nexus.example and the envelope uses relay.example. As with a parcel, the label and logistics sender are distinct clues.'),b('Um nome conhecido pode ser digitado por qualquer remetente. Abra os detalhes; o nome sozinho não prova identidade.','Anyone can type a familiar display name. Open the details; the name alone does not prove identity.'),b('Confira o domínio após @ e avalie se o pedido faz sentido. Nunca mande senha ou código de acesso por causa de um nome familiar.','Check the domain after @ and assess whether the request makes sense. Never send a password or access code because a name looks familiar.')),
 concept(b('2 · SPF: quem pode enviar','2 · SPF: who may send'),b('SPF compara o IP do servidor que entrega a mensagem com a autorização publicada para o domínio do envelope. Aqui usamos MAIL FROM não vazio.','SPF compares the delivering server IP with published authorization for the envelope domain. Here we use a nonempty MAIL FROM.'),b('A biblioteca contrata um serviço de avisos. O serviço passa SPF para relay.example: é como um veículo autorizado pela transportadora.','The library hires a notification service. It passes SPF for relay.example: like a vehicle authorized by the carrier.'),b('Isso não confirma automaticamente o domínio nexus.example no From, a pessoa que escreveu nem a segurança de um anexo. Encaminhar pode mudar o servidor e causar falha SPF legítima.','This does not automatically confirm nexus.example in From, the writer or attachment safety. Forwarding can change the server and cause legitimate SPF failure.'),b('Leia “pass para qual domínio?”. A equipe administradora confere os remetentes autorizados; você confere contexto e origem antes de agir.','Ask “pass for which domain?”. Administrators check authorized senders; you check context and origin before acting.')),
 concept(b('3 · DKIM: assinatura do domínio','3 · DKIM: domain signature'),b('DKIM verifica uma assinatura criptográfica ligada ao domínio d=. A verificação cobre as partes assinadas dos cabeçalhos e do corpo, conforme a assinatura.','DKIM verifies a cryptographic signature linked to the d= domain. Verification covers signed header and body parts according to the signature.'),b('Um convite assinado por news.nexus.example é encaminhado sem mudar as partes cobertas. A assinatura pode continuar válida mesmo com SPF falhando no novo servidor.','An invitation signed by news.nexus.example is forwarded without changing covered parts. The signature can remain valid even if SPF fails on the new server.'),b('A assinatura válida relaciona a mensagem ao domínio assinante. Não avalia a honestidade do conteúdo; alterar partes cobertas pode invalidá-la.','A valid signature relates the message to the signing domain. It does not assess content honesty; changing covered parts may invalidate it.'),b('Compare d= com o domínio do From e continue avaliando links, anexos e pedidos. No laboratório os resultados são fornecidos pelo receptor fictício.','Compare d= with the From domain and continue assessing links, attachments and requests. Lab results are supplied by the fictional receiver.')),
 concept(b('4 · DMARC: uma rota alinhada basta','4 · DMARC: one aligned route suffices'),b('DMARC passa se SPF passa e alinha com From OU se alguma assinatura DKIM passa e alinha com From. Relaxado compara domínios organizacionais; estrito exige domínio idêntico.','DMARC passes if SPF passes and aligns with From OR some DKIM signature passes and aligns with From. Relaxed compares organizational domains; strict requires identical domains.'),b('From é nexus.example e DKIM válido usa news.nexus.example. No inventário fictício, os dois têm domínio organizacional nexus.example. Relaxado alinha; estrito não.','From is nexus.example and valid DKIM uses news.nexus.example. In the fictional inventory both have organizational domain nexus.example. Relaxed aligns; strict does not.'),b('SPF e DKIM aprovados apenas para relay.example não alinham com nexus.example. Já uma única rota aprovada e alinhada pode fazer DMARC passar.','SPF and DKIM passed only for relay.example do not align with nexus.example. Conversely, a single passed, aligned route can make DMARC pass.'),b('Faça duas perguntas em cada rota: passou? Alinha? Depois combine com OU. O modelo fornece os domínios organizacionais; sistemas reais precisam determiná-los corretamente.','Ask two questions on each route: passed? Aligned? Then combine with OR. The model supplies organizational domains; real systems must determine them correctly.')),
 concept(b('5 · Política: orientação ao receptor','5 · Policy: guidance to the receiver'),b('p=none não expressa preferência de tratamento. Quarantine considera falhas suspeitas; reject considera inválido o uso do domínio. O receptor avalia outros sinais e decide o tratamento.','p=none expresses no handling preference. Quarantine considers failures suspicious; reject considers domain use invalid. The receiver assesses other signals and decides handling.'),b('A escola começa observando relatórios e percebe boletins legítimos sem alinhamento. Bloquear sem revisar pode prejudicar alunos e encaminhamentos.','The school starts observing reports and discovers legitimate newsletters without alignment. Blocking without review can harm students and forwarding.'),b('Política não é garantia de entrega ou rejeição. Na especificação atual, o receptor não deve rejeitar somente por p=reject, sem outras análises.','Policy does not guarantee delivery or rejection. In the current specification, the receiver must not reject solely because of p=reject without other analysis.'),b('A equipe revisa relatórios, terceiros e fluxos indiretos antes de mudar a política. Um aluno pode reportar uma mensagem legítima barrada pelo canal oficial.','The team reviews reports, third parties and indirect flows before changing policy. A student can report blocked legitimate mail through the official channel.')),
 concept(b('6 · Origem aprovada, pedido suspeito','6 · Origin approved, suspicious request'),b('DMARC aprovado não declara que uma mensagem é segura. Uma conta comprometida ou um domínio malicioso também pode enviar e-mail autenticado.','DMARC pass does not declare a message safe. A compromised account or malicious domain can also send authenticated email.'),b('Um professor conhecido pede seu código de MFA “para liberar a nota”. Mesmo com origem aprovada, esse segredo permite acesso à sua conta.','A familiar teacher asks for your MFA code “to release a grade”. Even with approved origin, that secret permits account access.'),b('Você precisa avaliar o pedido além da origem. Pressa, segredo, pagamento inesperado e solicitação de credenciais merecem verificação independente.','You need to assess the request as well as origin. Urgency, secrecy, unexpected payment and credential requests require independent verification.'),b('Abra o portal por endereço conhecido ou fale com o professor por um contato anterior. Não use apenas o telefone ou link da própria mensagem suspeita.','Open the portal at a known address or contact the teacher through a previous contact. Do not rely only on the phone number or link in the suspicious message.'))
 ],checklist:[b('Leia From, envelope e d= separadamente.','Read From, envelope and d= separately.'),b('DMARC: uma rota aprovada E alinhada basta.','DMARC: one passed AND aligned route suffices.'),b('Confirme pedidos incomuns por um canal independente conhecido.','Confirm unusual requests through a known independent channel.')],quiz:{prompt:b('SPF falhou no encaminhamento, mas DKIM passou e alinha com From. E DMARC?','SPF failed on forwarding, but DKIM passed and aligns with From. What about DMARC?'),options:[b('Passa pela rota DKIM; o conteúdo ainda precisa de avaliação.','Passes through DKIM; content still needs assessment.'),b('Falha porque as duas verificações devem passar.','Fails because both checks must pass.'),b('Passa e garante que o pedido é seguro.','Passes and guarantees a safe request.')],correct:0,feedback:[b('Isso! Uma rota válida e alinhada basta; continue avaliando o pedido.','Yes! One valid, aligned route suffices; continue assessing the request.'),b('A combinação é OU, não E entre as duas rotas. DKIM válido e alinhado basta aqui.','The combination is OR, not AND between the two routes. Valid, aligned DKIM suffices here.'),b('DMARC não avalia intenção, anexos nem uma conta comprometida.','DMARC does not assess intent, attachments or a compromised account.')]},sources:[{label:'RFC 7208 · SPF',url:'https://www.rfc-editor.org/rfc/rfc7208.html'},{label:'RFC 6376 · DKIM',url:'https://www.rfc-editor.org/rfc/rfc6376.html'},{label:'RFC 9989 · DMARC (2026)',url:'https://www.rfc-editor.org/rfc/rfc9989.html'}]};
