import { useEffect, useState } from 'react';
import { useSave, type Difficulty } from './core';
import { CloudDecision } from './CloudGames';
import { alteredText,evidenceText,newForensicCase,forensicAction,forensicQuestion,type ForensicAction } from './forensics';

export function ForensicLessonDemo({onReady}:{onReady?:()=>void}){
 const lang=useSave(s=>s.save.lang),tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const [state,setState]=useState(newForensicCase),[feedback,setFeedback]=useState<ReturnType<typeof forensicAction>|null>(null),[hashes,setHashes]=useState<string[]|null>(null),[hashError,setHashError]=useState(false);
 useEffect(()=>{let active=true;const hash=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(n=>n.toString(16).padStart(2,'0')).join('');Promise.all([hash(evidenceText),hash(alteredText)]).then(h=>{if(active)setHashes(h)}).catch(()=>{if(active)setHashError(true)});return()=>{active=false}},[]);
 const actions:[ForensicAction,string,string][]=[['capture','Coletar com contexto','Collect with context'],['copy','Criar cópia de trabalho','Create working copy'],['alter','Alterar só a cópia','Alter only the copy'],['verify','Comparar SHA-256','Compare SHA-256'],['transfer','Entregar a Nova','Transfer to Nova']];
 return <section className="bt-board"><h2>{tx('Bancada forense · Evidência FV-25','Forensic bench · Evidence FV-25')}</h2><p>{tx('Autorização fictícia FV-25: preservar este registro do portal NEXUS para apurar a alteração da nota 17. Origem: log de aplicação; responsável: Lia; método: exportação simulada somente leitura às 10:10 UTC. A coleta anterior e a precisão do relógio não foram verificadas. Nenhum arquivo do seu dispositivo é acessado.','Fictional authority FV-25: preserve this NEXUS portal record to investigate the change to grade 17. Source: application log; custodian: Lia; method: simulated read-only export at 10:10 UTC. Earlier collection and clock accuracy are not verified. No device files are accessed.')}</p><p>{tx('Tutorial: tente entregar primeiro. Colete, copie e compare. Altere só a cópia e tente entregar de novo. Para corrigir, crie outra cópia do original, compare e entregue. Não há cronômetro; experimente os erros e leia seus motivos.','Tutorial: try transfer first. Collect, copy and compare. Alter only the copy and try transfer again. To recover, create another copy from the original, compare and transfer. There is no timer; try mistakes and read why they fail.')}</p>
 <div className="traffic-route" aria-hidden="true"><span>FV-25</span><div><b>{state.captured?'→':'○'}</b></div><span>{state.copy?'COPY':'—'}</span><div><b>{state.verified?'✓':'?'}</b></div><span>NOVA</span></div>
 <p>{tx('Original preservado','Original preserved')}: {state.captured?'✓':'○'} · {tx('Cópia verificada','Copy verified')}: {state.verified?'✓':'○'} · {tx('Entrega registrada','Transfer recorded')}: {state.transferred?'✓':'○'}</p>
 {state.captured&&<article><h3>{tx('Original protegido: a referência permanece','Protected original: reference stays unchanged')}</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{evidenceText}</pre><p style={{overflowWrap:'anywhere'}}>SHA-256: {hashes?.[0]||tx('Calculando…','Computing…')}</p></article>}
 {state.copy&&<article><h3>{tx('Cópia de trabalho','Working copy')}</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{state.altered?alteredText:evidenceText}</pre><p style={{overflowWrap:'anywhere'}}>SHA-256: {hashes?.[state.altered?1:0]||tx('Calculando…','Computing…')}</p></article>}
 <div className="challenge-actions">{actions.map(([action,pt,en])=><button className="secondary" key={action} disabled={state.transferred||action==='verify'&&!hashes} onClick={()=>{const next=forensicAction(state,action);setState(next.state);setFeedback(next)}}>{tx(pt,en)}</button>)}<button className="text-button" onClick={()=>{setState(newForensicCase());setFeedback(null)}}>{tx('Reiniciar bancada','Reset bench')}</button></div>
 {hashError&&<p className="error-message" role="alert">{tx('O navegador não permitiu SHA-256. Abra o jogo por HTTPS ou localhost num navegador compatível.','The browser did not allow SHA-256. Open via HTTPS or localhost in a compatible browser.')}</p>}
 {feedback&&<div role="status" className={'feedback '+(feedback.ok?'good':'')}><p>{feedback.message[lang]}</p></div>}
 <h3>{tx('Histórico e cadeia de custódia do caso','Case history and chain of custody')}</h3><p>{tx('Horários do modelo são simulados; a entrega registra destinatário Nova e finalidade análise. A referência é o SHA-256 exibido do original; uma nova cópia nunca troca essa referência.','Model times are simulated; transfer records recipient Nova and purpose analysis. The reference is the displayed original SHA-256; a new copy never replaces it.')}</p><ol>{state.custody.map((e,i)=><li key={i}>{e.time} · {e.actor} · FV-25 · {actions.find(a=>a[0]===e.action)?.[lang==='pt'?1:2]}</li>)}</ol>
 <details><summary>{tx('Comparar horário e interpretação','Compare time and interpretation')}</summary><p>{tx('Portal: 10:05 UTC, conta professor, alteração da nota 17. Estação: 07:05 UTC−3, mesma conta, sessão aberta. Normalize: ambos equivalem a 10:05 UTC. Sem verificar relógios e outras fontes, não afirme ordem exata nem qual pessoa usou a conta.','Portal: 10:05 UTC, professor account, grade 17 changed. Workstation: 07:05 UTC−3, same account, open session. Normalize: both equal 10:05 UTC. Without clock checks and other sources, do not assert exact order or which person used the account.')}</p></details>
 {onReady&&<button className="primary" disabled={!state.transferred} onClick={onReady}>{tx('Concluir preservação e analisar as pistas','Complete preservation and analyze clues')}</button>}
 </section>;
}
export function ForensicMission({id,difficulty,onFinish}:{id:string;difficulty:Difficulty;onFinish:(score:number)=>void}){
 const lang=useSave(s=>s.save.lang);
 const short=id.startsWith('s'),sequence=id.endsWith('b')?[2,1]:short?[0,1]:[0,1,2];
 const [stage,setStage]=useState(short?0:-1),[correct,setCorrect]=useState(0);
 if(stage===-1)return <ForensicLessonDemo onReady={()=>{setCorrect(1);setStage(0)}}/>;
 return <section className="challenge-panel"><p>{lang==='pt'?'Análise das evidências':'Evidence analysis'} · {stage+1}/{sequence.length}</p><CloudDecision key={stage} question={forensicQuestion(sequence[stage],difficulty)} onFinish={ok=>{const total=correct+(ok?1:0);if(stage+1===sequence.length)onFinish(Math.round(total/(sequence.length+(short?0:1))*100));else{setCorrect(total);setStage(stage+1)}}}/></section>;
}
