import { b, type Difficulty } from './core';
import type { Lesson } from './lessons';
import type { Question } from './content';
import type { TeachingUnit } from './teachingUnits';
import type { ExperimentGuide } from './experimentGuides';

export const evidenceText='2026-10-09T10:05:00Z account=professor action=grade-change record=17';
export const alteredText=evidenceText+'\nanalyst-note=edited';
export type ForensicAction='capture'|'copy'|'alter'|'verify'|'transfer';
export type ForensicState={captured:boolean;copy:boolean;altered:boolean;verified:boolean;transferred:boolean;custody:{actor:string;action:ForensicAction;time:string}[]};
export function newForensicCase():ForensicState{return {captured:false,copy:false,altered:false,verified:false,transferred:false,custody:[]}}
export function forensicAction(state:ForensicState,action:ForensicAction):{state:ForensicState;ok:boolean;message:ReturnType<typeof b>}{
 const fail=(pt:string,en:string)=>({state,ok:false,message:b(pt,en)});
 if(state.transferred)return fail('Caso encaminhado. Reinicie a bancada para outro experimento.','Case transferred. Reset the bench for another experiment.');
 if(action!=='capture'&&!state.captured)return fail('Primeiro registre a coleta autorizada e a origem. Não há evidência preservada ainda.','First record authorized collection and origin. No evidence has been preserved yet.');
 if((action==='alter'||action==='verify')&&!state.copy)return fail('Crie uma cópia de trabalho antes de analisar. O original preservado não será editado.','Create a working copy before analysis. The preserved original will not be edited.');
 if(action==='transfer'&&(!state.verified||state.altered))return fail('Encaminhamento bloqueado: a cópia precisa coincidir com a referência preservada e ter verificação atual.','Transfer blocked: the copy must match the preserved reference and have a current verification.');
 if(action==='verify'&&state.altered)return fail('SHA-256 diverge: a cópia foi alterada. Registre a divergência e crie outra cópia do original preservado; não substitua o hash de referência.','SHA-256 differs: the copy was altered. Record the discrepancy and create a new copy from the preserved original; do not replace the reference hash.');
 const next={...state,custody:[...state.custody,{actor:action==='transfer'?'Lia → Nova':'Lia',action,time:new Date(Date.UTC(2026,9,9,10,10)+state.custody.length*60000).toISOString()}]} ;
 if(action==='capture'){if(state.captured)return fail('Coleta já registrada; o original permanece protegido.','Collection already recorded; the original remains protected.');next.captured=true}
 if(action==='copy'){next.copy=true;next.altered=false;next.verified=false}
 if(action==='alter'){next.altered=true;next.verified=false}
 if(action==='verify')next.verified=true;
 if(action==='transfer')next.transferred=true;
 return {state:next,ok:true,message:action==='verify'?b('Os bytes da cópia coincidem com a referência SHA-256. Isso verifica integridade relativa à coleta; não prova autoria nem veracidade do log.','Copy bytes match the SHA-256 reference. This verifies integrity relative to collection; it does not prove authorship or log truth.'):action==='transfer'?b('Entrega registrada: Lia → Nova, para análise, com origem, horário, método e referência. A cadeia documenta o percurso; não elimina lacunas anteriores à coleta.','Transfer recorded: Lia → Nova, for analysis, with origin, time, method and reference. The chain documents handling; it does not eliminate gaps before collection.'):b('Ação registrada no caso fictício. Confira o estado e a cadeia abaixo antes de avançar.','Action recorded in the fictional case. Check state and custody below before proceeding.')};
}
type Quiz=Lesson['quiz'];
export const forensicQuizzes:Quiz[]=[
{prompt:b('A cópia de um log tem SHA-256 diferente da referência registrada na coleta. Qual próximo passo preserva a análise?','A log copy has a SHA-256 different from the reference recorded at collection. Which next step preserves analysis?'),options:[b('Registrar a divergência e obter uma nova cópia do original preservado.','Record the discrepancy and obtain a new copy from the preserved original.'),b('Trocar o hash de referência pelo da cópia para passar na conferência.','Replace the reference hash with the copy hash to pass the check.'),b('Culpar o titular da conta: qualquer divergência prova autoria.','Blame the account holder: any mismatch proves authorship.'),b('Ignorar a diferença se o arquivo ainda abre.','Ignore the difference if the file still opens.')],correct:0,feedback:[b('Preserve a referência e documente o problema. Compare uma nova cópia antes de usar seus resultados.','Preserve the reference and document the issue. Compare a new copy before using its results.'),b('Trocar a referência esconde a divergência e quebra a comparação com o que foi coletado.','Replacing the reference hides the mismatch and breaks comparison with collected data.'),b('Divergência indica diferença de bytes, não quem alterou o conteúdo ou por quê.','Mismatch indicates different bytes, not who changed content or why.'),b('Abrir o arquivo não verifica sua integridade. Uma pequena mudança pode alterar a interpretação.','Opening a file does not verify integrity. A small change may alter interpretation.')]},
{prompt:b('Nova recebe um pendrive sem identificação, horário ou responsável. O arquivo tem um hash válido. Qual lacuna continua?','Nova receives a USB drive without identification, time or custodian. The file has a valid hash. Which gap remains?'),options:[b('Apenas o formato: converter o arquivo resolve a rastreabilidade.','Only format: converting the file resolves traceability.'),b('Origem e cadeia de custódia: registrar quem coletou, de onde, quando e como ocorreu cada entrega.','Origin and custody: record who collected it, where, when and how each transfer occurred.'),b('Nenhuma: ter um hash completo reconstrói todas as entregas anteriores.','None: a complete hash reconstructs all earlier transfers.'),b('É preciso publicar o log inteiro para tornar a cadeia confiável.','The entire log must be published to make custody trustworthy.')],correct:1,feedback:[b('Conversão altera a representação e não recupera contexto ausente.','Conversion changes representation and does not recover missing context.'),b('Integridade e rastreabilidade são complementares. Registre as lacunas sem inventar um histórico anterior.','Integrity and traceability complement each other. Record gaps without inventing prior history.'),b('Hash não registra responsáveis nem transferências. Uma referência sem origem ainda tem limitações.','A hash records neither custodians nor transfers. A reference without origin remains limited.'),b('Divulgar registros pode expor dados; controle de acesso e documentação apoiam a custódia.','Publishing records can expose data; access control and documentation support custody.')]},
{prompt:b('O portal registra 10:05 UTC e a estação 07:05 UTC−3 para a mesma conta. Os relógios não foram verificados. O que é possível afirmar?','The portal records 10:05 UTC and the workstation 07:05 UTC−3 for the same account. Clocks have not been checked. What can be stated?'),options:[b('Há exatamente três horas entre os eventos.','There are exactly three hours between events.'),b('O nome da conta identifica com certeza a pessoa responsável.','The account name certainly identifies the responsible person.'),b('Os horários normalizados coincidem; a sequência e autoria exigem correlação e verificação dos relógios.','Normalized timestamps match; sequence and authorship need correlation and clock checks.'),b('A coincidência permite apagar um dos registros como duplicado.','The match allows one record to be deleted as a duplicate.')],correct:2,feedback:[b('UTC−3 acrescenta três horas para converter a UTC. Os dois registros podem representar o mesmo instante.','Add three hours to UTC−3 to convert to UTC. Both records may represent the same instant.'),b('Uma conta pode ser compartilhada ou comprometida. Identidade de conta não prova identidade humana.','An account may be shared or compromised. Account identity does not prove human identity.'),b('Preserve as fontes e o fuso original. Registre incerteza de relógio e procure evidências adicionais antes de concluir.','Preserve sources and original time zones. Record clock uncertainty and seek additional evidence before concluding.'),b('Fontes diferentes podem fornecer contexto complementar; não elimine evidência pela aparência de duplicação.','Different sources may provide complementary context; do not discard evidence because it appears duplicated.')]}
];
export function forensicQuestion(index:number,difficulty:Difficulty):Question{
 const quiz=forensicQuizzes[index%3],prefix=difficulty==='easy'?b('Observe uma pista por vez. ','Observe one clue at a time. '):difficulty==='normal'?b('Relacione a evidência ao procedimento. ','Connect the evidence to the procedure. '):b('O relatório precisa preservar limites e rastreabilidade. ','The report must preserve limits and traceability. ');
 return {prompt:b(prefix.pt+quiz.prompt.pt,prefix.en+quiz.prompt.en),options:quiz.options,correct:quiz.correct,explain:quiz.feedback[quiz.correct],hint:b('Separe integridade, origem e interpretação. O hash compara bytes; a cadeia registra o percurso; a linha do tempo depende de contexto.','Separate integrity, origin and interpretation. A hash compares bytes; custody records handling; timelines depend on context.')};
}
export const forensicQuestions={easy:[0,1,2].map(i=>forensicQuestion(i,'easy')),normal:[0,1,2].map(i=>forensicQuestion(i,'normal')),hard:[0,1,2].map(i=>forensicQuestion(i,'hard'))};
const concept=(title:ReturnType<typeof b>,text:ReturnType<typeof b>,example:ReturnType<typeof b>,action:ReturnType<typeof b>)=>({title,text,example,walkthrough:{situation:example,reasoning:text,action}});
export const forensicLesson:Lesson={id:'m25',intro:b('Imagine que uma nota foi alterada no portal da escola. Uma captura isolada não explica quem agiu nem como os registros chegaram até você. Forense digital transforma pistas em análise verificável: preservar, examinar, correlacionar e relatar sem inventar certezas. Vamos usar somente registros fictícios autorizados.','Imagine a grade was changed in the school portal. A single screenshot does not explain who acted or how records reached you. Digital forensics turns clues into verifiable analysis: preserve, examine, correlate and report without inventing certainty. We use only authorized fictional records.'),concepts:[
concept(b('Preservar antes de interpretar','Preserve before interpreting'),b('Coleta identifica a fonte, finalidade, responsável, horário e método. Trabalhe com uma cópia e proteja o original. Sistemas ligados também têm informações voláteis, como memória e sessões; desligar pode perdê-las. A decisão de coleta e contenção depende de risco, autorização e procedimento, não de uma ordem universal.','Collection identifies source, purpose, custodian, time and method. Work with a copy and protect the original. Live systems also have volatile information such as memory and sessions; shutdown can lose it. Collection and containment depend on risk, authority and procedure, not a universal order.'),b('Editar a foto de um recibo para destacá-lo muda o material analisado. Guarde a foto original e faça marcações numa cópia.','Editing a receipt photo to highlight it changes the analyzed material. Keep the original and annotate a copy.'),b('Registre Coletar com contexto, depois Criar cópia. Leia o escopo FV-25.','Use Collect with context, then Create copy. Read scope FV-25.')),
concept(b('Hash: conferir os bytes','Hash: check the bytes'),b('SHA-256 produz um resumo dos bytes. Compare com a referência protegida da coleta. Uma divergência pede investigação; coincidência não prova que o registro original é verdadeiro, completo ou de determinada pessoa. O algoritmo não substitui origem e custódia.','SHA-256 produces a summary of bytes. Compare with the protected collection reference. A mismatch needs investigation; a match does not prove the original record true, complete or authored by someone. The algorithm does not replace origin and custody.'),b('Duas cópias do mesmo recibo podem coincidir exatamente e ainda conter uma informação falsa desde a origem.','Two receipt copies can match exactly and still contain information false from the start.'),b('Confira o hash, altere a cópia e confira outra vez. Preserve a referência inicial.','Check the hash, alter the copy and check again. Preserve the initial reference.')),
concept(b('Cadeia de custódia: contar o percurso','Chain of custody: document handling'),b('A cadeia registra cada coleta e transferência: identificador da evidência, origem, responsáveis, horário com fuso, finalidade, método e proteção. Não preencha lacunas com suposições. Restrinja acesso aos registros, pois podem conter informações pessoais.','Custody records collection and transfer: evidence identifier, source, custodians, time zone, purpose, method and protection. Do not fill gaps with assumptions. Restrict access because records can contain personal information.'),b('Quando a escola entrega um documento a outro setor, o protocolo registra quem entregou, quem recebeu e para quê.','When the school transfers a document, the receipt records who handed it over, who received it and why.'),b('Entregue a Nova após verificar a cópia e leia o registro Lia → Nova.','Transfer to Nova after checking the copy and read the Lia → Nova record.')),
concept(b('Linha do tempo: contexto muda a leitura','Timeline: context changes interpretation'),b('Guarde horário e fuso originais, converta para uma base comum e registre incertezas de relógio. Eventos próximos não provam causalidade. Uma conta identifica a credencial usada; associar a ação a uma pessoa exige outras evidências.','Preserve original timestamps and time zones, convert to a common basis and record clock uncertainty. Nearby events do not prove causality. An account identifies the credential used; linking an action to a person needs more evidence.'),b('O portal mostra 10:05 UTC e o computador 07:05 UTC−3. Os números parecem diferentes, mas podem indicar o mesmo instante.','The portal shows 10:05 UTC and the computer 07:05 UTC−3. The numbers look different but may indicate the same instant.'),b('Compare as fontes exibidas e diga o que ainda falta verificar antes de afirmar a sequência.','Compare displayed sources and state what remains to check before asserting a sequence.')),
concept(b('Relatório: separar fatos e hipóteses','Report: separate facts and hypotheses'),b('Relate o escopo, método, observações, comparação de hashes, correlação e limitações. Diferencie fato observado de hipótese e inclua explicações alternativas e próximos passos. Uma análise útil permite que outra pessoa acompanhe seu raciocínio sem assumir culpa ou segurança total.','Report scope, method, observations, hash comparison, correlation and limitations. Distinguish observed fact from hypothesis and include alternative explanations and next steps. Useful analysis lets another person follow the reasoning without assuming blame or total safety.'),b('“A conta professor alterou o registro 17” é uma observação do log. “O professor fez isso” é uma hipótese que o log sozinho não comprova.','“The professor account changed record 17” is a log observation. “The teacher did it” is a hypothesis the log alone does not prove.'),b('Use origem, integridade e limites para explicar o achado. Consulte as revisões antes da missão.','Use origin, integrity and limits to explain the finding. Consult review before the mission.'))
],checklist:[b('Preservar original e analisar uma cópia verificada.','Preserve the original and analyze a verified copy.'),b('Documentar coleta e transferências sem inventar o passado.','Document collection and transfers without inventing the past.'),b('Separar integridade, veracidade, autoria e hipótese.','Separate integrity, truth, authorship and hypothesis.')],quiz:forensicQuizzes[0],sources:[{label:'NIST SP 800-86 · Digital forensics',url:'https://csrc.nist.gov/pubs/sp/800/86/final'}]};
export const forensicTeaching:TeachingUnit={mechanism:forensicLesson.intro,case:b('Lia altera a cópia de um log para adicionar uma observação. O arquivo ainda abre. Será que ela pode encaminhá-lo como cópia íntegra do original? Preveja antes de conferir.','Lia edits a log copy to add a note. The file still opens. Can she transfer it as an intact copy of the original? Predict before checking.'),reason:b('Não: o hash da cópia diverge da referência. Registre a divergência e crie outra cópia do original preservado. Anotações devem ficar separadas do material cuja integridade será comparada.','No: the copy hash differs from the reference. Record the discrepancy and create another copy from the preserved original. Notes belong separately from material whose integrity will be compared.'),limit:b('O modelo usa textos fixos, não uma imagem de disco nem memória real. Hash não prova veracidade ou autoria; a cadeia documenta apenas as ações realizadas neste cenário autorizado.','The model uses fixed texts, not a disk image or real memory. A hash does not prove truth or authorship; custody documents only actions in this authorized scenario.'),frames:[b('Coletar com origem e autorização','Collect with origin and authority'),b('Preservar o original e criar cópia','Preserve original and create a copy'),b('Comparar hashes e registrar transferências','Compare hashes and record transfers'),b('Correlacionar e relatar com limites','Correlate and report with limits')],recall:b('Sem consultar: por que hash e cadeia de custódia são complementares?','Without looking: why do hashing and chain of custody complement each other?'),answer:b('O hash compara bytes com a referência e verifica integridade. A cadeia de custódia registra origem, responsáveis e transferências. Nenhum deles sozinho prova autoria ou veracidade.','A hash compares bytes to a reference and checks integrity. Chain of custody records origin, custodians and transfers. Neither alone proves authorship or truth.'),transfer:b('Duas fontes registram 10:05 UTC e 07:05 UTC−3 com a mesma conta. O relatório pode afirmar quem agiu e a ordem exata? Explique o limite.','Two sources record 10:05 UTC and 07:05 UTC−3 with the same account. Can the report assert who acted and exact order? Explain the limit.'),transferAnswer:b('Os horários normalizados coincidem. Verifique os relógios e correlacione outras fontes. A conta não prova autoria humana e os registros não comprovam a ordem exata sem contexto adicional.','Normalized timestamps match. Check clocks and correlate other sources. The account does not prove human authorship and records do not establish exact order without additional context.')};
export const forensicGuide:ExperimentGuide={objective:b('Descobrir como uma alteração da cópia invalida a verificação e como registrar a entrega sem mudar o original.','Discover how editing a copy invalidates verification and how to record transfer without changing the original.'),limit:forensicTeaching.limit,steps:[{action:b('Tente Entregar a Nova antes da coleta. Leia o motivo do bloqueio.','Try Transfer to Nova before collection. Read why it is blocked.'),result:b('Não há coleta preservada nem cópia verificada para entregar.','There is no preserved collection or verified copy to transfer.')},{action:b('Colete com contexto, crie uma cópia e compare os hashes. Observe o original protegido.','Collect with context, create a copy and compare hashes. Observe the protected original.'),result:b('Hashes iguais verificam bytes em relação à referência, mas não identificam o autor do evento.','Matching hashes verify bytes relative to the reference but do not identify the event author.')},{action:b('Altere a cópia e tente comparar novamente. Depois tente entregar.','Alter the copy and compare again. Then try transfer.'),result:b('A divergência bloqueia a entrega. Alterar a cópia também remove a verificação anterior.','Mismatch blocks transfer. Altering the copy also invalidates prior verification.')},{action:b('Crie outra cópia, verifique e entregue a Nova. Compare a cadeia registrada.','Create another copy, verify and transfer to Nova. Compare recorded custody.'),result:b('A entrega tem responsável e horário; limitações anteriores à coleta continuam declaradas.','Transfer has custodians and time; pre-collection limitations remain declared.')}]};
