import { describe, it, expect } from 'vitest';
import { goals, lenses, lensFits, evidenceConclusion, csfFunctions, frameworkQuestion } from './frameworks';
import { initial, reward, normalizeSave } from './core';
import { lessonMission, canStudyChallenge } from './lessons';
describe('frameworks and evidence',()=>{
 it('matches each learning goal to one primary lens without claiming exclusivity',()=>{for(const g of goals){expect(lenses.filter(l=>lensFits(g.id,l.id))).toHaveLength(1);expect(lensFits(g.id,g.lens)).toBe(true)}expect(lensFits('missing','attack')).toBe(false);expect(lensFits('behavior','missing')).toBe(false)});
 it('adds execution evidence without concluding theft or attribution',()=>{expect(evidenceConclusion(false).pt).toContain('não foram confirmadas');expect(evidenceConclusion(true).pt).toContain('não comprova roubo');expect(evidenceConclusion(true).en).toContain('does not prove');expect(csfFunctions.map(f=>f.en)).toEqual(['Govern','Identify','Protect','Detect','Respond','Recover'])});
 it('distinguishes all difficulty scenarios with complete questions',()=>{for(const kind of ['purpose','evidence','risk','app'] as const){const prompts=[];for(const d of ['easy','normal','hard'] as const){const q=frameworkQuestion(kind,d);prompts.push(q.prompt.pt);expect(q.correct).toBeLessThan(q.options.length);for(const lang of ['pt','en'] as const){expect(q.options.every(o=>!!o[lang])).toBe(true);expect(q.explain[lang]).toBeTruthy();expect(q.hint[lang]).toBeTruthy()}}expect(new Set(prompts).size).toBe(3)}});
 it('keeps act prerequisites and canonical IDs while preserving fundamentals',()=>{expect(canStudyChallenge('m20',{},false)).toBe(false);expect(canStudyChallenge('m20',{m19:75},false)).toBe(true);expect(canStudyChallenge('m20',{},true)).toBe(true);expect(canStudyChallenge('m20',{},true,true)).toBe(false);for(const id of ['m20','s20a','s20b'])expect(lessonMission(id)).toBe('m20');for(const id of ['m020','s020a','m26'])expect(lessonMission(id)).toBeNull()});
 it('migrates v14 and rewards only improvements, rejecting new IDs in old saves',()=>{const old={...reward(initial,'m19',100,'hard',false),version:14,lang:'en',avatar:3,placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:22});s=reward(s,'m20',75,'easy',false);s=reward(s,'m20',100,'hard',false);s=reward(s,'s20a',100,'normal',true);expect(s.xp).toBe(450);expect(normalizeSave({...s,version:14})).toBeNull();expect(reward(s,'m20',100,'hard',false)).toEqual(s);expect(reward(s,'s20b',50,'hard',true)).toEqual(s);expect(normalizeSave(s)).toEqual(s)});
});
