import { b, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export type IncidentKind='contain'|'evidence'|'recover'|'report';
export type ResponseState={contained:boolean;evidence:boolean;fixed:boolean;tested:boolean;online:boolean};
export const newResponse=():ResponseState=>({contained:false,evidence:false,fixed:false,tested:false,online:false});
export type ResponseAction='contain'|'preserve'|'fix'|'test'|'release';
export function respond(s:ResponseState,a:ResponseAction):{state:ResponseState;ok:boolean;message:ReturnType<typeof b>}{
 const fail=(pt:string,en:string)=>({state:s,ok:false,message:b(pt,en)});
 if(a==='release'&&!(s.contained&&s.evidence&&s.fixed&&s.tested))return fail('Retorno bloqueado: contenha, preserve os registros, trate a causa e teste a recuperação. Abrir a página não prova que o acesso indevido foi removido.','Return blocked: contain, preserve records, address the cause and test recovery. Opening a page does not prove unauthorized access was removed.');
 if(a==='fix'&&!s.evidence)return fail('Antes da alteração nesta bancada, preserve os registros e sua origem. Limpar a estação pode destruir pistas. Contenção urgente pode ocorrer em paralelo à coleta.','Before modifying this bench, preserve records and provenance. Cleaning the workstation can destroy clues. Urgent containment may occur alongside collection.');
 if(a==='test'&&!s.fixed)return fail('O teste encontrou a sessão indevida ainda ativa. Trate a causa e os acessos antes de repetir o teste.','The test found the unauthorized session still active. Address the cause and access before retesting.');
 const key={contain:'contained',preserve:'evidence',fix:'fixed',test:'tested',release:'online'}[a] as keyof ResponseState;
 if(s[key])return fail('Esta etapa já foi registrada. Compare outra ação ou reinicie o caso.','This step is already recorded. Compare another action or reset the case.');
 const messages={contain:b('Estação isolada da rede de alunos por autorização IR-24; canal de gestão mantido. A sessão cloud ainda precisa ser revogada: isolamento de rede não resolve todo acesso.','Workstation isolated from student network under IR-24 authorization; management channel retained. Cloud session still needs revocation: network isolation does not resolve all access.'),preserve:b('Cópia protegida dos logs: fonte, horário UTC, coletor e hash registrados. Hash ajuda a detectar mudanças; não prova que o evento era verdadeiro.','Protected log copy: source, UTC time, collector and hash recorded. A hash helps detect changes; it does not prove an event was true.'),fix:b('Equipe autorizada corrigiu a extensão vulnerável, revogou sessões e renovou a credencial afetada. O escopo conhecido foi revisado; não é garantia sobre máquinas não examinadas.','Authorized team fixed the vulnerable extension, revoked sessions and renewed the affected credential. Known scope reviewed; this is no guarantee about unexamined machines.'),test:b('Cópia de recuperação verificada; dados e função do portal conferidos em ambiente separado. Tentativa com a sessão antiga falhou. Monitoramento definido para o retorno.','Recovery copy verified; portal data and function checked in a separate environment. Old-session attempt failed. Monitoring defined for return.'),release:b('Retorno gradual aprovado pelo responsável. Portal disponível com monitoramento; registre pendências e revisão pós-incidente.','Gradual return approved by the owner. Portal available with monitoring; record pending issues and post-incident review.')};
 return {state:{...s,[key]:true},ok:true,message:messages[a]};
}
const cases:Record<IncidentKind,[string,string][]>= {
 contain:[['Uma extensão comprometida usa a estação e uma sessão cloud. IR-24 autoriza isolar a estação. O que fazer?','A compromised extension uses a workstation and cloud session. IR-24 authorizes isolation. What should you do?'],['A escola precisa manter o portal de notas. Uma estação tem atividade indevida confirmada e sessão cloud ativa. Qual contenção tem escopo justificável?','The school needs the grades portal. One workstation has confirmed unauthorized activity and an active cloud session. Which containment has justified scope?'],['Há risco de propagação, sessão cloud ativa e coleta de memória em andamento. IR-24 permite isolamento mantendo gestão. Qual plano equilibra risco, evidência e continuidade?','There is propagation risk, an active cloud session and ongoing memory collection. IR-24 permits isolation retaining management. Which plan balances risk, evidence and continuity?']],
 evidence:[['Por que guardar logs antes de limpar a estação?','Why keep logs before cleaning the workstation?'],['Uma cópia tem hash, mas ninguém anotou fonte ou coletor. O que falta?','A copy has a hash but no source or collector was recorded. What is missing?'],['A equipe quer desligar a máquina para preservar “tudo”. Há dados voláteis e dano em andamento. Qual avaliação evita uma regra absoluta?','The team wants to power off to preserve “everything”. There is volatile data and ongoing harm. Which assessment avoids an absolute rule?']],
 recover:[['O portal abriu após restaurar. Já podemos liberar?','The portal opened after restoration. Can we release it?'],['Backup íntegro, mas a extensão vulnerável e sessões antigas permanecem. Qual plano reduz reincidência?','Backup intact, but the vulnerable extension and old sessions remain. Which plan reduces recurrence?'],['O backup passa na integridade; a sessão antiga ainda lê dados e uma dependência falha. O prazo está perto. Qual decisão é defensável?','The backup passes integrity checks; an old session still reads data and a dependency fails. The deadline is close. Which decision is defensible?']],
 report:[['O que registrar no encerramento?','What should closure record?'],['Somente a estação examinada passou nos testes. Como relatar sem exagerar?','Only the examined workstation passed tests. How do you report without exaggeration?'],['Nenhum alerta após o retorno, mas um sensor ficou ausente por 30 minutos. Como comunicar resultado e aprendizado?','No alerts after return, but one sensor was absent for 30 minutes. How do you communicate results and learning?']]
};
const choices:Record<IncidentKind,[string,string][]>= {
 contain:[['Executar contenção autorizada e proporcional, coordenar preservação e tratar a sessão cloud com a equipe.','Perform authorized proportional containment, coordinate preservation and address the cloud session with the team.'],['Desligar toda a escola sem avaliar impacto.','Shut down the entire school without assessing impact.'],['Esperar toda a investigação mesmo com dano ativo.','Wait for the whole investigation despite ongoing harm.']],
 evidence:[['Apagar logs e guardar apenas o hash.','Delete logs and retain only the hash.'],['Preservar dados com origem, horário, coletor e controle de acesso; avaliar volatilidade e risco antes de alterar.','Preserve data with source, time, collector and access control; assess volatility and risk before changes.'],['Desligar sempre, pois memória permanece intacta.','Always power off because memory remains intact.']],
 recover:[['Liberar porque a tela abriu.','Release because the page opened.'],['Usar backup como substituto da correção da causa.','Use backup instead of addressing the cause.'],['Tratar causa e acessos, verificar cópia e funções em ambiente separado, aprovar retorno gradual e monitorar.','Address cause and access, verify copy and functions separately, approve gradual return and monitor.']],
 report:[['Registrar ações, escopo, evidências, limitações, testes, responsáveis e melhorias; não preencher lacunas com certeza.','Record actions, scope, evidence, limitations, tests, owners and improvements; do not fill gaps with certainty.'],['Declarar toda a rede segura porque não houve alerta.','Declare the whole network safe because there were no alerts.'],['Publicar logs completos com dados pessoais para todos.','Publish complete logs with personal data for everyone.']]
};
const reasons:Record<IncidentKind,[string,string]>={contain:['Contenção limita dano, mas não remove a causa. Coordene autorização, impacto e evidência; ações podem acontecer em paralelo.','Containment limits harm but does not remove the cause. Coordinate authority, impact and evidence; actions may overlap.'],evidence:['Alterações podem destruir evidências. Energia desligada perde dados voláteis; preserve conforme risco e procedimento, registrando origem e acesso.','Changes can destroy evidence. Power loss loses volatile data; preserve according to risk and procedure, recording origin and access.'],recover:['Integridade da cópia, correção da causa e funcionamento são verificações distintas. Teste acessos antigos e dependências antes do retorno autorizado.','Copy integrity, addressing the cause and function are distinct checks. Test old access and dependencies before authorized return.'],report:['Silêncio do sensor não prova ausência de incidente. Declare cobertura e pendências e proteja informações sensíveis.','Sensor silence does not prove absence of incident. State coverage and pending issues and protect sensitive information.']};
export function incidentQuestion(k:IncidentKind,d:Difficulty):Question{return q(...cases[k][{easy:0,normal:1,hard:2}[d]],choices[k],{contain:0,evidence:1,recover:2,report:0}[k],reasons[k],['Separe reduzir o dano, preservar evidências e demonstrar recuperação.','Separate reducing harm, preserving evidence and demonstrating recovery.']);}
export const incidentQuestions=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,(['contain','evidence','recover'] as IncidentKind[]).map(k=>incidentQuestion(k,d))])) as Record<Difficulty,Question[]>;
function reviewCase(k:IncidentKind){const x=incidentQuestion(k,'hard');const extra=b('Liberar porque o hash garante a segurança de todo o ambiente.','Release because a hash guarantees safety across the environment.');return review([x.prompt.pt,x.prompt.en],[...x.options,extra].map(o=>[o.pt,o.en]),x.correct,[...x.options,extra].map((_,i)=>i===x.correct?reasons[k]:['Essa escolha não atende aos critérios do caso. '+reasons[k][0],'This choice does not meet the case criteria. '+reasons[k][1]]));}
export const incidentReview=reviewCase('recover');export const incidentFollowup=reviewCase('report');
