import { useEffect, useRef, useState } from 'react';
import { BookOpen, Lightbulb, Play, RotateCcw, CheckCircle2, CircleAlert, XCircle } from 'lucide-react';
import { useSave } from './core';
import { modules } from './curriculum';
import { teachingUnits } from './teachingUnits';
import { assessExplanation, explanationRubrics, type ExplanationAssessment } from './explanationValidation';
import OpenAnswerValidation from './OpenAnswerValidation';
import './learning.css';

const related:Record<string,string>={m1:'m12',m2:'m13',m3:'m8',m4:'m14',m5:'m7',m6:'m10',m7:'m5',m8:'m15',m9:'m18',m10:'m17',m11:'m19',m12:'m1',m13:'m2',m14:'m4',m15:'m8',m16:'m21',m17:'m10',m18:'m9',m19:'m12',m20:'m21',m21:'m16',m22:'m23',m23:'m22',m24:'m7',m25:'m16'};

export function CompleteExplanation({id,moving,active}:{id:string;moving:boolean;active:boolean}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const u=teachingUnits[id];
 const [frame,setFrame]=useState(0);const [playing,setPlaying]=useState(false);const [prediction,setPrediction]=useState('');const [shown,setShown]=useState(false);
 useEffect(()=>{if(!playing||!moving||!active)return;if(frame>=3){setPlaying(false);return}const t=setTimeout(()=>setFrame(n=>n+1),1800);return()=>clearTimeout(t)},[playing,moving,active,frame]);
 return <section className="learning-card" aria-label={tx('Explicação aprofundada','In-depth explanation')}>
  <div className="eyebrow"><BookOpen size={18}/>{tx('ENTENDA O PORQUÊ','UNDERSTAND WHY')}</div><h2>{tx('Vamos ligar as peças.','Let’s connect the pieces.')}</h2><p>{u.mechanism[lang]}</p>
  <div className="learning-flow" role="group" aria-label={tx('Sequência explicativa','Explanatory sequence')}>{u.frames.map((f,i)=><button key={i} className={frame===i?'current':''} aria-pressed={frame===i} onClick={()=>{setPlaying(false);setFrame(i)}}><strong>{i+1}</strong><span>{f[lang]}</span></button>)}</div>
  <div className="flow-meter" aria-hidden="true"><span style={{width:(frame+1)*25+'%'}}/></div><p className="flow-caption">{tx('Etapa','Step')} {frame+1}/4 · {u.frames[frame][lang]}</p>
  <div className="learning-actions"><button className="secondary" disabled={!moving} onClick={()=>{if(playing)setPlaying(false);else{if(frame===3)setFrame(0);setPlaying(true)}}}><Play size={16}/>{!moving?tx('Animação pausada nas preferências','Animation paused in preferences'):playing?tx('Pausar sequência','Pause sequence'):tx('Animar explicação','Animate explanation')}</button><button className="secondary" disabled={frame===3} onClick={()=>{setPlaying(false);setFrame(n=>Math.min(3,n+1))}}>{tx('Próxima etapa','Next step')}</button><button className="text-button" onClick={()=>{setPlaying(false);setFrame(0)}}><RotateCcw size={16}/>{tx('Recomeçar','Restart')}</button></div>
  <p className="learning-note">{tx('A sequência mostra o raciocínio. Toque em qualquer etapa para comparar; a bancada da aba Experimente permite testar o modelo do tema.','The sequence shows the reasoning. Select any step to compare; the Experiment tab lets you test the topic model.')}</p>
  <h3>{tx('Exemplo resolvido: primeiro, tente prever.','Worked example: first, try to predict.')}</h3><p>{u.case[lang]}</p><label className="learning-label">{tx('O que você acha que acontece, e por quê?','What do you think happens, and why?')}<textarea rows={3} maxLength={1800} value={prediction} onChange={e=>setPrediction(e.target.value)} placeholder={tx('Pode escrever uma hipótese ou responder em voz alta.','Write a prediction or answer aloud.')}/></label>
  <OpenAnswerValidation id={id} kind="prediction" text={prediction}/>
  <button className="secondary" aria-expanded={shown} aria-controls={`worked-${id}`} onClick={()=>setShown(!shown)}><Lightbulb size={16}/>{shown?tx('Ocultar raciocínio','Hide reasoning'):tx('Conferir o raciocínio do exemplo','Check the example reasoning')}</button>
  {shown&&<div className="learning-feedback" id={`worked-${id}`}><h3>{tx('Como chegar à conclusão','How to reach the conclusion')}</h3><p>{u.reason[lang]}</p><strong>{tx('Agora compare com sua previsão. O que você mudaria?','Now compare with your prediction. What would you change?')}</strong></div>}
  <aside className="learning-limit"><strong>{tx('Onde a explicação tem limites','Where the explanation has limits')}</strong><p>{u.limit[lang]}</p></aside>
 </section>;
}

export function FeynmanPractice({id}:{id:string}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const u=teachingUnits[id];
 const [draft,setDraft]=useState('');const [oral,setOral]=useState(false);const [show,setShow]=useState(false);const [checks,setChecks]=useState<boolean[]>([false,false,false]);
 const [assessment,setAssessment]=useState<ExplanationAssessment|null>(null);
 const topic=modules.find(m=>m.id===id)!.topic[lang];
 return <section id={`feynman-practice-${id}`} tabIndex={-1} className="learning-card feynman-practice" aria-label={tx('Método Feynman','Feynman method')}><div className="eyebrow">{tx('EXPLIQUE PARA APRENDER','EXPLAIN TO LEARN')}</div><h2>{tx('Método Feynman: ensine com suas palavras.','Feynman method: teach in your own words.')}</h2>
  <p>{tx('Imagine que um colega nunca estudou este tema. Explique a ideia sem depender de siglas. Quando usar um termo técnico, traduza-o e dê um exemplo. Se travar, encontrou um ponto para revisar.','Imagine a classmate has never studied this topic. Explain without relying on acronyms. Translate technical terms and give an example. Getting stuck reveals something to revisit.')}</p>
  <ol className="learning-list"><li>{tx('Escolha a ideia central e explique o que ela faz.','Choose the central idea and explain what it does.')}</li><li>{tx('Mostre como funciona no exemplo cotidiano, incluindo causa e consequência.','Show how it works in the everyday example, including cause and consequence.')}</li><li>{tx('Diga o que ela não resolve e revise sua explicação depois da comparação.','Say what it does not solve and revise your explanation after comparing.')}</li></ol>
  <details className="explanation-criteria"><summary>{tx('O que explicar para validar esta aula','What to explain to validate this lesson')}</summary><ul>{explanationRubrics[id].criteria.map((c,i)=><li key={i}>{c.label[lang]}</li>)}<li>{tx('Inclua um exemplo com causa e consequência e um limite da proteção.','Include an example with cause and consequence and a protection limit.')}</li></ul></details>
  <label className="learning-label">{tx('Como você ensinaria','How would you teach')} “{topic}”?<textarea rows={5} maxLength={3000} value={draft} onChange={e=>{setDraft(e.target.value);setAssessment(null)}} placeholder={tx('“É como… Funciona porque… Mas isso não significa que…”','“It is like… It works because… But that does not mean…”')}/></label>
  <button className="primary" disabled={!draft.trim()} onClick={()=>setAssessment(assessExplanation(id,draft))}>{tx('Validar minha explicação','Validate my explanation')}</button>
  <div aria-live="polite" aria-atomic="true">{assessment&&<section className={'explanation-assessment '+assessment.status} aria-label={tx('Resultado da validação','Validation result')}><h3>{assessment.status==='correct'?<CheckCircle2/>:assessment.status==='incorrect'?<XCircle/>:<CircleAlert/>}{assessment.status==='correct'?tx('Correta nos critérios verificados','Correct against the checked criteria'):assessment.status==='incorrect'?tx('Incorreta: revise este conceito','Incorrect: review this concept'):tx('Incompleta: complete ou esclareça','Incomplete: add detail or clarify')}</h3><p>{assessment.status==='correct'?tx('Sua explicação apresenta as ideias verificadas, um exemplo e um limite. Continue comparando com a aula: isso não garante que cada frase esteja correta.','Your explanation includes the checked ideas, an example and a limit. Keep comparing with the lesson: this does not guarantee every sentence is correct.'):assessment.status==='incorrect'?tx('Encontrei uma afirmação que pode contrariar a aula. Confira o trecho e a orientação, reescreva e valide novamente.','I found a statement that may contradict the lesson. Check the excerpt and guidance, rewrite and validate again.'):tx('Ainda não reconheci todos os pontos necessários. O texto pode estar certo, mas precisa explicar melhor os itens abaixo para esta checagem.','I have not recognized all required points. The text may be correct but needs to clarify the items below for this check.')}</p>{assessment.excerpt&&<blockquote>{assessment.excerpt}</blockquote>}{assessment.correction&&<p><strong>{tx('Como corrigir: ','How to correct: ')}</strong>{assessment.correction[lang]}</p>}<ul>{assessment.criteria.map((c,i)=><li key={i} className={c.met?'criterion-met':'criterion-missing'}><strong>{c.met?tx('✓ Identificado: ','✓ Identified: '):tx('○ A completar ou esclarecer: ','○ Add or clarify: ')}</strong>{c.label[lang]}</li>)}</ul><p>{tx('Melhore o texto acima e clique em Validar novamente. Não há perda de pontos neste treino.','Improve the text above and validate again. No points are lost in this practice.')}</p></section>}</div>
  <p className="learning-note">{tx('Checagem guiada por critérios e equívocos comuns, feita no navegador. Não é uma avaliação por IA: pode não reconhecer paráfrases ou erros diferentes dos previstos. Não avalia gramática nem atribui XP.','Browser-based checks against criteria and common misconceptions. This is not AI grading: it may miss paraphrases or errors outside the authored checks. It does not grade grammar or award XP.')}</p>
  <label className="learning-check"><input type="checkbox" checked={oral} onChange={e=>setOral(e.target.checked)}/>{tx('Já expliquei em voz alta.','I have explained it aloud.')}</label>
  <button className="secondary" disabled={!draft.trim()&&!oral} aria-expanded={show} aria-controls={`feynman-${id}`} onClick={()=>setShow(!show)}>{show?tx('Ocultar comparação','Hide comparison'):tx('Comparar minha explicação','Compare my explanation')}</button>
  {show&&<div className="learning-feedback" id={`feynman-${id}`}><h3>{tx('Uma referência para conferir seu raciocínio','A reference for checking your reasoning')}</h3><p>{u.reason[lang]}</p><p>{u.limit[lang]}</p><p>{tx('Não precisa usar as mesmas palavras. Confira se sua explicação mostra estas três partes; depois melhore o rascunho acima.','You need not use the same words. Check whether your explanation contains these three parts; then improve the draft above.')}</p>{[tx('Defini a ideia sem esconder o significado em siglas.','I defined the idea without hiding its meaning in acronyms.'),tx('Liguei ação e consequência usando um exemplo.','I connected action and consequence using an example.'),tx('Expliquei um limite ou uma conclusão que não posso tirar.','I explained a limit or a conclusion I cannot draw.')].map((label,i)=><label key={i} className="learning-check"><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(c=>c.map((v,n)=>n===i?e.target.checked:v))}/>{label}</label>)}<p role="status">{checks.filter(Boolean).length}/3 · {tx('Autoavaliação, sem nota automática. Volte ao conteúdo para preencher as lacunas.','Self-assessment, without automatic grading. Revisit the content to fill gaps.')}</p></div>}
  <p className="learning-note">{tx('O texto não é enviado. Este rascunho fica apenas no treino aberto; copie se quiser guardar. A opção oral abre a comparação, mas só o texto digitado pode ser validado.','Text is not sent anywhere. This draft stays only in the open practice; copy it to keep it. The oral option opens comparison, but only typed text can be validated.')}</p>
 </section>;
}

export function RetrievalPractice({id}:{id:string}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const u=teachingUnits[id];
 const [index,setIndex]=useState(0);const [drafts,setDrafts]=useState(['','']);const [oral,setOral]=useState([false,false]);const [revealed,setRevealed]=useState([false,false]);const [ratings,setRatings]=useState(['','']);const heading=useRef<HTMLHeadingElement>(null);
 const questions=[u.recall,u.transfer],answers=[u.answer,u.transferAnswer];const pair=modules.find(m=>m.id===related[id])!;
 function go(i:number){setIndex(i);requestAnimationFrame(()=>heading.current?.focus())}
 return <section className="learning-card retrieval-practice" aria-label={tx('Recuperação ativa de memória','Active retrieval practice')}><div className="eyebrow">{tx('LEMBRE ANTES DE RELER','RECALL BEFORE REREADING')}</div><h2>{tx('Retrieval Practice: puxe da memória.','Retrieval Practice: recall from memory.')}</h2><p>{tx('Antes de rever os conceitos ou abrir as alternativas, tente responder sem consultar. Depois compare e corrija. Errar aqui ajuda a encontrar o que revisar; este treino não vale XP.','Before revisiting concepts or opening options, try to answer without looking. Then compare and correct. Errors here reveal what to revisit; this practice does not award XP.')}</p>
  <div className="learning-actions">{questions.map((_,i)=><button className="secondary" key={i} aria-current={index===i?'step':undefined} onClick={()=>go(i)}>{i===0?tx('1. Lembrar a ideia','1. Recall the idea'):tx('2. Aplicar em outro caso','2. Apply to another case')}</button>)}</div>
  <h3 ref={heading} tabIndex={-1}>{questions[index][lang]}</h3><label className="learning-label">{tx('Minha resposta de memória','My answer from memory')}<textarea rows={4} value={drafts[index]} maxLength={2200} onChange={e=>setDrafts(d=>d.map((v,i)=>i===index?e.target.value:v))}/></label><label className="learning-check"><input type="checkbox" checked={oral[index]} onChange={e=>setOral(a=>a.map((v,i)=>i===index?e.target.checked:v))}/>{tx('Tentei responder em voz alta.','I tried to answer aloud.')}</label>
  <OpenAnswerValidation key={index} id={id} kind={index===0?'recall':'transfer'} text={drafts[index]}/>
  <button className="secondary" disabled={!drafts[index].trim()&&!oral[index]} onClick={()=>setRevealed(a=>a.map((v,i)=>i===index?true:v))}>{tx('Conferir e corrigir minha resposta','Check and correct my answer')}</button>
  {revealed[index]&&<div className="learning-feedback"><h3>{tx('Resposta comentada','Answer with reasoning')}</h3><p>{answers[index][lang]}</p><label className="learning-label">{tx('Compare o que lembrou com a resposta','Compare what you recalled with the answer')}<select value={ratings[index]} onChange={e=>setRatings(a=>a.map((v,i)=>i===index?e.target.value:v))}><option value="">{tx('Escolha sua autoavaliação','Choose your self-assessment')}</option><option value="solid">{tx('Expliquei ideia, motivo e limite','I explained idea, reason and limit')}</option><option value="partial">{tx('Lembrei parte; preciso completar','I recalled part; I need to complete it')}</option><option value="revisit">{tx('Preciso voltar à explicação','I need to revisit the explanation')}</option></select></label><p>{tx('Corrija o rascunho com outra cor no papel, ou reescreva acima. Depois tente explicar de novo sem olhar.','Correct the paper draft in another color, or rewrite above. Then explain again without looking.')}</p></div>}
  <p role="status">{ratings.filter(Boolean).length}/2 · {tx('respostas comparadas por você','answers compared by you')}</p>
  <aside className="learning-limit"><h3>{tx('Volte depois e misture os temas.','Return later and mix topics.')}</h3><p>{tx('Tente estas perguntas novamente amanhã, depois em alguns dias e na próxima semana. Se houver muita dificuldade, volte antes; os intervalos são uma sugestão de estudo, não um teste de aprovação.','Try these questions tomorrow, again in a few days and next week. If struggling, return sooner; these intervals are study suggestions, not pass requirements.')}</p><p>{tx('Compare esta aula com','Compare this lesson with')} <strong>{pair.topic[lang]}</strong>. {tx('O que uma proteção resolve que a outra não resolve? Crie um exemplo em que confundir as duas leve a uma decisão errada. Consulte o Manual do agente para alternar as aulas.','What does one protection address that the other does not? Create an example where confusing them leads to a wrong decision. Use the Agent handbook to alternate lessons.')}</p></aside>
 </section>;
}
