import { b, type Bilingual } from './core';

// One explanation per concept, in the same order as the lesson. These paragraphs
// explain the mechanism and decision, rather than repeating the example's answer.
export const conceptDepth:Record<string,Bilingual[]>={
 m23:[
 b('Um fluxo costuma ser descrito por endereços de origem/destino, portas e transporte; ferramentas podem agrupar os sentidos em uma conversa. Não confunda contagem de pacotes com bytes. Compare a mesma unidade e intervalo. Aqui 8 MB são oito milhões de bytes somados, não uma taxa medida continuamente nem um arquivo identificado.', 'A flow is commonly described by source/destination addresses, ports and transport; tools may group both directions into a conversation. Do not confuse packet counts with bytes. Compare the same unit and interval. Here 8 MB means eight million aggregated bytes, not a continuously measured rate or an identified file.'),
 b('A estação usa uma porta temporária, como 51514, para conversar com o servidor na porta 443. Na resposta, 443 vira porta de origem e 51514 vira destino. O inventário associa endereços aos participantes neste exercício; na prática, DHCP, NAT ou intermediários podem exigir registros adicionais para identificar o equipamento e o usuário.', 'The workstation uses a temporary port, such as 51514, to talk to server port 443. In the reply, 443 becomes the source port and 51514 the destination. Inventory associates addresses with participants in this exercise; in practice, DHCP, NAT or intermediaries may require additional records to identify device and user.'),
 b('Pense no filtro como uma lupa sobre dados já disponíveis. ip.src seleciona origem; ip.dst seleciona destino; ip.addr permite encontrar o endereço em qualquer sentido. Aqui a conversa também é pré-selecionada: ver duas linhas dela não prova que foram todas as conexões da estação. Em uma ferramenta real, confira transportes, portas e identificadores para não misturar conversas.', 'Think of a filter as a magnifier over available data. ip.src selects source; ip.dst selects destination; ip.addr finds the address in either direction. Here the conversation is also preselected: seeing its two rows does not prove they were all workstation connections. In a real tool, check transports, ports and identifiers to avoid mixing conversations.'),
 b('Uma operação indevida também pode usar um canal criptografado. Neste cenário, dizer “houve transferência por TLS” é observação; dizer “eram notas escolares” é uma hipótese sem confirmação. Uma consulta DNS anterior é uma pista de resolução de nome, não prova de acesso posterior. Registros do aplicativo e do endpoint ajudam a relacionar atividade, usuário e processo sem inventar conteúdo.', 'An unauthorized operation can also use an encrypted channel. In this scenario, “a TLS transfer occurred” is an observation; “it contained school grades” is an unconfirmed hypothesis. An earlier DNS lookup is a name-resolution clue, not proof of subsequent access. App and endpoint records help relate activity, user and process without inventing content.'),
 b('Uma linha de base descreve padrões esperados para aquele serviço, horário e função. O exemplo compara duas janelas iguais, mas não calcula um limiar universal de risco. B-17 foi fornecido como autorização completa somente para aquele backup. Priorize a transferência sem finalidade confirmada para obter contexto; se surgirem evidências de impacto, siga o plano de resposta e a autoridade da equipe.', 'A baseline describes expected patterns for that service, time and role. The example compares two equal windows but does not calculate a universal risk threshold. B-17 is supplied as complete authorization only for that backup. Prioritize the transfer without confirmed purpose to obtain context; if impact evidence appears, follow the response plan and team authority.'),
 b('Separe três situações no relatório: a fonte funcional não registrou o evento procurado; o filtro ocultou parte dos dados; a fonte não coletou o período. Elas exigem conclusões diferentes. Registre horário com fuso, ponto de observação e limitações. Reparar o sensor permite observar períodos seguintes, mas não recria automaticamente tráfego que nunca foi coletado.', 'Separate three situations in the report: a working source did not record the event sought; the filter hid some data; the source did not collect the period. They require different conclusions. Record time zone, observation point and limitations. Repairing the sensor enables future observation but does not automatically recreate traffic that was never collected.')],
 m1:[
 b('Reutilização é o efeito dominó: o vazamento da loja pode atingir o e-mail e, por ele, a recuperação de outras contas. Uma senha exclusiva interrompe esse caminho específico; ela ainda precisa ser longa e guardada com segurança.','Reuse creates a domino effect: a shop breach can reach email and, through it, account recovery. A unique password interrupts that specific path; it must still be long and stored safely.'),
 b('Pense no gerenciador como um chaveiro protegido. Ele ajuda a gerar e preencher senhas, mas a senha principal, os fatores adicionais e a recuperação também precisam de cuidado. Guardar uma senha vazada não a torna segura: troque-a no serviço afetado.','Think of a manager as a protected key ring. It helps generate and fill passwords, but its master password, extra factors and recovery also need care. Storing a leaked password does not secure it: replace it at the affected service.'),
 b('Fator é uma categoria de prova: algo que você sabe, tem ou é. Senha mais PIN continua na categoria “sabe”. MFA reduz alguns usos de senhas roubadas; códigos também podem ser capturados por phishing. Prefira opções resistentes a phishing quando disponíveis.','A factor is a category of proof: something you know, have or are. Password plus PIN remains in the “know” category. MFA reduces some uses of stolen passwords; phishing can also capture codes. Prefer phishing-resistant options when available.')],
 m2:[
 b('A pressão tenta encurtar sua verificação: “pague agora” transforma medo em ação. Uma entrega atrasada pode ser real; o prazo urgente não valida a cobrança. Você pode pausar, consultar seu pedido e confirmar sem fornecer um segredo.','Pressure tries to shorten verification: “pay now” turns fear into action. A delayed delivery may be real; urgency does not validate a charge. You can pause, check your order and confirm without providing a secret.'),
 b('Separe rótulo e evidência. “Equipe Entregas” é um nome editável; o domínio é outro dado a conferir. Um erro de escrita pode ser uma pista, mas mensagens perfeitas também enganam. Combine origem, pedido e contexto.','Separate label from evidence. “Delivery Team” is an editable name; the domain is another item to check. A typo may be a clue, but perfect messages also deceive. Combine source, request and context.'),
 b('Canal independente significa que a própria mensagem não escolheu sua fonte de confirmação. Abra o app já instalado ou use um contato previamente conhecido. Responder ao mesmo remetente apenas pergunta ao possível impostor se ele é confiável.','An independent channel means the message did not choose your verification source. Open an already installed app or use a previously known contact. Replying to the same sender only asks the possible impersonator whether they are trustworthy.')],
 m3:[
 b('Em https://suporte.example/nexus.example/login, a parte depois da barra é um caminho, como uma sala dentro do prédio. Ela não muda o host suporte.example. Em domínios reais, a identificação do domínio registrável depende das regras de sufixos; não conte sempre duas palavras.','In https://suporte.example/nexus.example/login, the part after the slash is a path, like a room inside a building. It does not change the host suporte.example. Real registrable domains depend on suffix rules; do not always count two labels.'),
 b('TLS protege a conversa com o destino certificado. É como transportar uma carta em um envelope protegido até o endereço escolhido: não confirma se o pedido dentro dela é honesto. Confira o host e a finalidade mesmo com HTTPS.','TLS protects the conversation with the certified destination. It is like transporting a letter in a protected envelope to the selected address: it does not establish whether the request inside is honest. Check the host and purpose even with HTTPS.'),
 b('A VPN muda quem transporta parte da sua conexão: você passa a confiar também no provedor do túnel. Ela não corrige um domínio errado, um anexo malicioso ou uma conta comprometida. Antes de enviar dados de trabalho, confira a política e a rede.','A VPN changes who carries part of your connection: you also trust the tunnel provider. It does not fix a wrong domain, malicious attachment or compromised account. Before sending work data, check the policy and network.'),
 b('O navegador e o serviço guardam informações em lugares diferentes. Limpar registros locais não apaga uma compra no servidor nem o arquivo baixado. Ao usar um computador compartilhado, sair da conta e fechar as janelas privadas continuam sendo ações distintas.','The browser and service store information in different places. Clearing local records does not erase a server-side purchase or downloaded file. On a shared computer, signing out and closing private windows remain separate actions.')],
 m4:[
 b('Minimização relaciona dado e tarefa. Para entregar um livro, endereço ajuda; cor favorita não. Já retirar o endereço impede a entrega. Pergunte “para que este campo será usado?” antes de concluir que mais ou menos dados é sempre melhor.','Minimization connects data to the task. An address helps deliver a book; a favorite color does not. Removing the address prevents delivery. Ask “what will this field be used for?” before assuming more or less data is always better.'),
 b('Público é quem pode acessar, não quem você espera que acesse. Enviar um link num grupo pequeno não restringe um link aberto. Uma foto pode revelar dados indiretos: uniforme, placa da rua ou horários ajudam a reconstruir sua rotina.','Audience means who can access, not who you expect to access. Sending an open link to a small group does not restrict it. A photo may reveal indirect data: a uniform, street sign or times can help reconstruct your routine.'),
 b('Finalidade, necessidade e transparência ajudam a avaliar o tratamento. A LGPD prevê, entre outros direitos, acesso e correção; pedidos e exceções dependem do caso. Você pode perguntar ao responsável quais dados usa, por qual motivo e por quanto tempo.','Purpose, necessity and transparency help evaluate processing. Brazil’s LGPD provides rights including access and correction; requests and exceptions depend on the case. You can ask the responsible party what data it uses, why and for how long.')],
 m5:[
 b('Uma atualização fecha falhas conhecidas, mas não decide por você se um pedido faz sentido. Desativar a proteção para abrir um “comprovante” cria uma oportunidade adicional. Confira origem e necessidade antes de executar; em equipamento de trabalho, acione o suporte.','An update closes known flaws but does not decide whether a request makes sense. Disabling protection to open a “receipt” creates another opportunity. Check source and need before executing; on work equipment, contact support.'),
 b('Contenção limita o dano enquanto a investigação esclarece o caso. Anote horário, mensagem e o que ocorreu antes do alerta. Reiniciar, apagar ou instalar ferramentas por conta própria pode mudar indícios; o plano da equipe define as ações adequadas.','Containment limits harm while investigation clarifies the case. Record the time, message and what happened before the alert. Restarting, deleting or installing tools on your own may change evidence; the team’s plan defines appropriate actions.'),
 b('Recuperar o arquivo e eliminar a causa são objetivos diferentes. Se o acesso indevido continuar ativo, uma cópia restaurada pode ser atingida novamente. A equipe verifica ambiente, credenciais, cópia e dependências e acompanha a retomada do serviço.','Recovering a file and removing the cause are different goals. If unauthorized access remains active, a restored copy may be affected again. The team checks the environment, credentials, copy and dependencies and monitors service recovery.')],
 m6:[
 b('Pense em uma nota digitada e em uma foto da lousa: o mesmo app tem necessidades diferentes conforme a função. Uma permissão autorizada continua sendo acesso a um recurso sensível; não é um certificado de confiança do aplicativo.','Think of a typed note and a photo of a board: the same app has different needs depending on the feature. An approved permission still grants access to a sensitive resource; it is not a certificate of application trust.'),
 b('Menor privilégio é liberar o suficiente para a tarefa, no alcance e tempo necessários. Se só uma foto é usada, acesso a toda a galeria pode exceder a finalidade. Se negar uma permissão quebra uma função, avalie essa função sem liberar todos os recursos.','Least privilege grants enough for the task within the necessary scope and time. If only one photo is used, full-gallery access may exceed the purpose. If denying a permission breaks a feature, evaluate that feature without granting every resource.'),
 b('Bloqueio de tela dificulta o acesso casual ao aparelho; atualizações tratam outras vulnerabilidades. São camadas complementares. Revise também os acessos de apps antigos: uma autorização necessária meses atrás pode não fazer parte do uso atual.','Screen locking makes casual device access harder; updates address other vulnerabilities. These are complementary layers. Also review old apps’ access: authorization needed months ago may no longer serve current use.')],
 m7:[
 b('Sincronização acompanha o estado atual; recuperação precisa de uma versão anterior utilizável. Se você apaga uma pasta e a exclusão sincroniza, duas pastas vazias não recuperam o trabalho. Verifique retenção, versões e prazo para desfazer alterações.','Sync follows the current state; recovery needs a usable earlier version. If a deletion syncs, two empty folders do not recover your work. Check retention, versions and how long changes can be undone.'),
 b('Separação evita falhas comuns: duas pastas no mesmo disco não resistem à perda desse disco. Uma cópia fora do local ajuda contra perda física; offline ou imutável ajuda contra alteração. Contas, chaves e prazos de retenção também precisam de proteção.','Separation avoids shared failures: two folders on one disk do not survive that disk’s loss. An off-site copy helps against physical loss; offline or immutable copies help against alteration. Accounts, keys and retention periods also need protection.'),
 b('Um teste restaura uma amostra em local apropriado e confirma que ela abre e atende à necessidade. Registre qual versão foi usada e quanto tempo levou. Uma cópia íntegra, mas sem a chave de leitura, ainda pode ser inútil.','A test restores a sample in an appropriate location and confirms it opens and meets the need. Record the version used and how long it took. An intact copy without its decryption key may still be useless.')],
 m8:[
 b('Pense no IP como endereço para encaminhar uma conversa, não como documento de identidade. Uma rede doméstica pode compartilhar um IP público entre vários aparelhos. Para investigar, combine IP, horário, conta e o contexto da conexão.','Think of an IP as an address for routing a conversation, not an identity document. A home network may share a public IP among devices. Investigate using IP, time, account and connection context together.'),
 b('O resolvedor recebe a pergunta pelo nome e devolve uma resposta. A resposta pode mudar por razões legítimas, como distribuição de carga. Uma divergência pede comparação com o inventário e a mudança aprovada, antes de concluir que houve ataque.','The resolver receives a name query and returns an answer. Answers may change for legitimate reasons such as load balancing. A difference calls for comparison with inventory and approved changes before concluding there was an attack.'),
 b('O IP ajuda a chegar ao destino; a porta ajuda a escolher o serviço. O transporte também importa: TCP/443 e UDP/443 não são a mesma identificação. Um log de tentativa informa tentativa; para afirmar acesso, procure o resultado e a fonte.','IP helps reach the destination; the port helps select the service. Transport also matters: TCP/443 and UDP/443 are different identifiers. An attempt log records an attempt; to claim access, check the outcome and source.')],
 m9:[
 b('Confidencialidade significa limitar quem consegue ler. A cifra de letras desta bancada mostra uma transformação reversível, mas tem só 26 deslocamentos: é fácil tentar todos. Ela ensina o conceito e não protege mensagens reais.','Confidentiality limits who can read. This desk’s letter cipher shows a reversible transformation but has only 26 shifts: all are easy to try. It teaches the concept and does not protect real messages.'),
 b('Compare o arquivo inteiro com uma referência obtida por canal confiável. Se alguém puder trocar arquivo e resumo no mesmo lugar, o par ainda pode combinar. Um hash igual confirma a comparação de bytes feita; não avalia o comportamento do arquivo.','Compare the whole file against a reference from a trusted channel. If someone can replace both file and digest together, the pair can still match. A matching hash confirms the byte comparison; it does not assess file behavior.'),
 b('A pública pode circular, mas você precisa saber a quem pertence. A privada fica protegida pelo titular. Em protocolos reais, diferentes mecanismos podem combinar chaves para estabelecer uma chave simétrica; o diagrama simplifica essas etapas.','A public key may circulate, but you must know who owns it. The owner protects the private key. Real protocols may combine mechanisms to establish a symmetric key; the diagram simplifies those stages.'),
 b('Assinar e cifrar resolvem perguntas diferentes: “este conteúdo corresponde à assinatura?” e “quem consegue ler?”. Um documento pode estar assinado e ser público. Mesmo após verificar a assinatura, confira se a identidade e o pedido são os esperados.','Signing and encryption answer different questions: “does this content match the signature?” and “who can read?”. A signed document may be public. Even after signature verification, check that the identity and request are expected.')],
 m10:[
 b('Autenticação reconhece o acesso a uma conta; autorização decide cada ação. Ter a chave da portaria não permite entrar em qualquer sala. Um programa aberto por sua conta pode alcançar os recursos permitidos a ela, conforme outros controles do sistema.','Authentication recognizes account access; authorization decides each action. Having a building entrance key does not open every room. A program opened under your account can reach that account’s permitted resources, subject to other system controls.'),
 b('Em 640, 6 representa leitura+gravação do dono, 4 leitura do grupo e 0 nenhuma dessas permissões para outros. O dono não “empresta” a leitura do grupo quando seus próprios bits negam. Esta bancada não inclui ACLs nem privilégios que alterem a avaliação.','In 640, 6 means owner read+write, 4 group read and 0 none of these permissions for others. The owner does not borrow group read when owner bits deny it. This desk excludes ACLs and privileges that change evaluation.'),
 b('Pense no arquivo como o conteúdo e no diretório como a lista de nomes que aponta para ele. Alterar o conteúdo exige permissões diferentes de remover uma entrada. Para entender uma negação real, confira também os diretórios do caminho.','Think of a file as content and a directory as the list of names pointing to it. Changing content requires different permissions from removing an entry. To understand a real denial, also check directories along the path.'),
 b('Elevação aumenta o que um processo pode fazer; não transforma um instalador desconhecido em confiável. Compare origem verificada, tarefa esperada e necessidade do privilégio. A simulação apenas registra a decisão, sem alterar permissões no seu computador.','Elevation increases what a process can do; it does not make an unknown installer trustworthy. Compare verified origin, expected task and need for privilege. The simulation only records the decision without changing your computer’s permissions.')],
 m11:[
 b('Use a sequência “onde estou, o que existe, o que vou ler”. Listar uma pasta não abre todos os arquivos. Mudar de pasta altera a referência dos caminhos relativos; o mesmo comando pode apontar a lugares diferentes depois disso.','Use “where am I, what exists, what will I read?”. Listing a folder does not open every file. Changing folders changes relative-path references; the same command may point elsewhere afterward.'),
 b('Aspas agrupam o nome; LiteralPath evita interpretar caracteres como colchetes como padrões curinga. São problemas distintos. Em access [review].txt, preserve o nome completo e escolha a forma literal para procurar exatamente esse arquivo.','Quotes group the name; LiteralPath avoids interpreting characters such as brackets as wildcard patterns. These are different problems. For access [review].txt, preserve the full name and choose literal addressing to locate exactly that file.'),
 b('Encontrar DENIED mostra que uma linha contém esse texto, não que todos os acessos falharam. Leia conta, sessão, ação e resultado. Para contar ocorrências ou reconstruir uma sequência, confirme primeiro se o filtro não removeu contexto relevante.','Finding DENIED shows that a line contains that text, not that all access failed. Read account, session, action and outcome. Before counting or reconstructing a sequence, check that filtering has not removed relevant context.'),
 b('Sucesso precisa vir depois da operação e depender dela. Se a leitura falha, o fluxo de erro deve explicar a falha sem afirmar que terminou bem. Teste o caminho normal e o arquivo ausente; os dois fazem parte do comportamento esperado.','Success must follow and depend on the operation. If reading fails, the error flow should explain failure without claiming completion. Test the normal path and missing file; both are part of expected behavior.'),
 b('Um comando é instrução executável, não apenas texto para copiar. Entenda alvo, efeito e privilégio antes de usar um exemplo fora do jogo. Aqui há uma lista fechada de comandos simulados; não é um terminal do seu sistema.','A command is an executable instruction, not just text to copy. Understand target, effect and privilege before using an example outside the game. Here there is a closed list of simulated commands, not a system terminal.')],
 m12:[
 b('A sessão funciona como um comprovante temporário de entrada. Fechar a interface não necessariamente invalida esse comprovante no serviço. Em dispositivo compartilhado, use a opção de sair e confira as sessões ativas conforme os recursos do serviço.','A session works like a temporary entry receipt. Closing the interface does not necessarily invalidate it at the service. On a shared device, sign out and check active sessions using the service’s available controls.'),
 b('Secure cuida do envio, não da proteção do arquivo no disco. HttpOnly dificulta leitura por scripts, mas não impede toda ação abusiva numa sessão. SameSite controla envio em certos contextos entre sites; não substitui todas as defesas contra requisições indevidas.','Secure controls transmission, not disk-file protection. HttpOnly limits script reading but does not prevent every abusive action in a session. SameSite controls sending in certain cross-site contexts; it does not replace every defense against unwanted requests.'),
 b('Pense em documentos com destinatários diferentes: o access token vai ao recurso; o ID token atende ao cliente; o refresh token vai ao servidor de autorização. Um prazo vigente não compensa finalidade, destinatário ou escopo incorretos.','Think of documents with different recipients: an access token goes to the resource; an ID token serves the client; a refresh token goes to the authorization server. A live lifetime does not compensate for wrong purpose, audience or scope.'),
 b('Ler uma claim é ler uma declaração. O receptor precisa verificar a proteção criptográfica apropriada, o emissor esperado, o destinatário e as condições de tempo. Claims visíveis não devem ser tratadas como dados secretos protegidos apenas pela assinatura.','Reading a claim means reading a statement. The receiver must verify appropriate cryptographic protection, expected issuer, audience and time conditions. Visible claims must not be treated as secrets protected merely by a signature.'),
 b('Um app de agenda que só mostra compromissos não precisa apagá-los. Compare a finalidade com cada escopo; nomes e efeitos variam entre serviços. Se não for possível limitar o pedido a uma necessidade aceitável, não autorize por conveniência.','A calendar app that only displays events does not need to delete them. Compare purpose with each scope; names and effects vary by service. If you cannot limit the request to an acceptable need, do not authorize merely for convenience.'),
 b('Sessão, concessão e token podem ter ciclos de vida separados. Revogar impede novos acessos conforme o serviço, mas dados já copiados não desaparecem. Nesta bancada, a concessão encerrada impede renovação e o token emitido permanece até sua expiração simulada.','Sessions, grants and tokens may have separate lifecycles. Revocation prevents further access according to the service, but copied data does not disappear. Here, ending the grant prevents renewal while an issued token remains until simulated expiry.')],
 m13:[
 b('Como numa carta, o nome na capa e o remetente do envelope atendem papéis distintos. Ler “Biblioteca” não autentica a origem. Identifique primeiro o domínio do From, pois ele é a referência de alinhamento no DMARC.','As with a letter, the displayed name and envelope sender serve different roles. Reading “Library” does not authenticate origin. First identify the From domain, the DMARC alignment reference.'),
 b('SPF aprovado informa autorização do servidor para o domínio avaliado. Não confirma sozinho o From mostrado ao aluno. No encaminhamento, o servidor que entrega pode mudar e afetar SPF; confira a outra rota antes de decidir sobre DMARC.','Passing SPF indicates server authorization for the evaluated domain. It does not alone confirm the From shown to the student. Forwarding may change the delivering server and affect SPF; inspect the other route before deciding DMARC.'),
 b('DKIM válido liga as partes cobertas à chave de um domínio, não à boa intenção de uma pessoa. Alterações nas partes assinadas podem quebrar a verificação. Confira também se o domínio d= alinha com o From, porque validade e alinhamento são perguntas separadas.','Valid DKIM links covered parts to a domain key, not a person’s good intentions. Changes to signed parts may break verification. Also check whether d= aligns with From: validity and alignment are separate questions.'),
 b('Leia a fórmula em duas etapas: cada rota exige aprovação E alinhamento; entre rotas, usa-se OU. Por isso DKIM alinhado pode bastar quando SPF falha. Dois passes de um domínio diferente do From não resolvem a falta de alinhamento.','Read the formula in two stages: each route needs pass AND alignment; the routes combine with OR. Aligned DKIM can therefore suffice when SPF fails. Two passes from a domain unrelated to From do not solve missing alignment.'),
 b('Política é uma orientação publicada pelo domínio; o receptor ainda aplica sua avaliação. Trocar none por reject não conserta SPF, DKIM ou alinhamento. Antes de endurecer uma política real, é preciso conhecer os envios legítimos e acompanhar os resultados.','Policy is domain-published guidance; the receiver still applies its assessment. Changing none to reject does not repair SPF, DKIM or alignment. Before tightening a real policy, understand legitimate senders and monitor outcomes.'),
 b('Autenticação de domínio e segurança do pedido são verificações complementares. Um e-mail autenticado que pede sua senha continua exigindo cuidado. Confira a ação pelo portal ou contato conhecido, sem entregar códigos nem usar a mensagem como única confirmação.','Domain authentication and request safety are complementary checks. An authenticated email asking for your password still needs care. Verify the action through a known portal or contact without sharing codes or using the message as sole confirmation.')],
 m14:[
 b('No editor online, você usa um aplicativo pronto; numa máquina virtual, administra mais camadas. A palavra “nuvem” não determina sozinha quem atualiza o sistema ou configura acesso. Identifique o produto e o modelo antes de atribuir uma tarefa.','An online editor is a ready application; a virtual machine leaves more layers for you to administer. “Cloud” alone does not determine who updates the system or configures access. Identify product and model before assigning a task.'),
 b('Responsabilidade compartilhada significa divisão de trabalho, não transferência de todo risco. O provedor pode proteger o datacenter enquanto o cliente deixa um documento público. Confira a matriz contratada: dados, identidades e configurações continuam exigindo decisões.','Shared responsibility divides work rather than transferring all risk. The provider may protect the data center while a customer makes a document public. Check the contracted matrix: data, identities and settings still require decisions.'),
 b('Ter o link equivale a saber o caminho, não necessariamente a ter autorização. Para destinatários identificados, o serviço verifica a identidade e a concessão. Um link aberto pode dispensar essa lista, ampliando o público além de quem recebeu a mensagem inicial.','Having a link means knowing the path, not necessarily being authorized. For named recipients, the service checks identity and grant. An open link may bypass that list, expanding access beyond recipients of the original message.'),
 b('Leia separadamente público, papel, prazo e delegação. Um leitor pode consultar; um editor pode modificar; delegar pode abrir novas concessões. Um prazo curto não justifica um público excessivo, e leitura ainda pode permitir cópia do conteúdo.','Read audience, role, lifetime and delegation separately. A reader can view; an editor can modify; delegation may create new grants. A short lifetime does not justify an excessive audience, and read access may still permit copying content.'),
 b('Um arquivo cifrado pode continuar acessível a quem recebeu permissão. Uma conta protegida pode apagar um documento por engano. Por isso acesso, proteção do conteúdo e recuperação precisam de controles próprios, incluindo versões, retenção e testes.','An encrypted file can remain accessible to authorized recipients. A protected account may delete a document accidentally. Access, content protection and recovery therefore need their own controls, including versions, retention and tests.'),
 b('Fechar o compartilhamento reduz novos acessos por aquela concessão. Não remove automaticamente outros links, heranças ou cópias baixadas. Registre quando a exposição começou, quem podia acessar e quais registros existem antes de afirmar que ninguém viu o arquivo.','Ending sharing reduces new access through that grant. It does not automatically remove other links, inherited access or downloaded copies. Record when exposure began, who could access and what records exist before claiming nobody viewed the file.')],
 m15:[
 b('Uma VLAN organiza uma zona, mas os caminhos entre zonas precisam de controles aplicados. Pense numa placa “somente funcionários”: ela identifica a área, mas uma porta com controle é que limita a passagem. Confira onde a política realmente é aplicada.','A VLAN organizes a zone, but inter-zone paths need enforced controls. A “staff only” sign identifies an area; a controlled door limits passage. Check where the policy is actually enforced.'),
 b('A regra precisa dizer quem inicia, para onde e usando qual serviço. Equipe → Portal em TCP/443 não autoriza Portal → Equipe nem todas as portas do portal. Uma seta e um número diferentes podem representar outra necessidade.','A rule must state who initiates, where and using which service. Staff → Portal on TCP/443 does not authorize Portal → Staff or every portal port. A different arrow or number may represent another need.'),
 b('Bloquear tudo quebra o serviço; abrir tudo amplia o risco. Comece pela tarefa: equipe consulta portal e portal consulta banco. Autorize esses caminhos e teste tanto o funcionamento esperado quanto a negação dos caminhos extras.','Blocking everything breaks the service; opening everything expands risk. Start with the task: staff use the portal and the portal uses the database. Authorize these paths and test both expected operation and denial of extra paths.'),
 b('O retorno é vinculado a uma conexão autorizada e ao estado reconhecido pelo receptor. Dizer “sou resposta” não basta. Na bancada, desmarcar reconhecimento bloqueia o retorno; marcar não cria autorização para uma conversa inicialmente proibida.','Return traffic is tied to an authorized connection and receiver-recognized state. Saying “I am a reply” is insufficient. Here, clearing recognition blocks return; enabling it does not authorize an initially forbidden conversation.'),
 b('Estar no Wi-Fi da escola não dá acesso a todas as notas. A rede decide caminhos de comunicação; o aplicativo decide operações para a identidade. Teste essas camadas separadamente para não confundir “cheguei ao portal” com “posso alterar o registro”.','Being on school Wi-Fi does not grant every grade record. The network decides communication paths; the application decides operations for the identity. Test these layers separately so “reached the portal” is not confused with “may change the record”.'),
 b('Um bloqueio pode ser uma proteção funcionando, um aplicativo mal configurado ou uma tentativa indevida. O registro não escolhe a explicação sozinho. Compare fluxo, ação, horário e mudanças aprovadas; registre como hipótese o que ainda não foi confirmado.','A block may mean protection working, a misconfigured application or an unauthorized attempt. The record alone does not select the explanation. Compare flow, action, time and approved changes; label unconfirmed explanations as hypotheses.')],
 m16:[
 b('Cada fonte enxerga parte da história: o login vê autenticação; o aplicativo vê operações; a rede vê conexões. Um registro ausente pode indicar falta de coleta. Antes de concluir, identifique a fonte, o período e os campos disponíveis.','Each source sees part of the story: login sees authentication, the application sees operations and the network sees connections. A missing record may indicate absent collection. Before concluding, identify the source, period and available fields.'),
 b('Leia a sequência inteira. Senha aceita seguida de MFA negado não é login concluído neste caso. Já uma sessão válida pode ler um recurso e ter outra ação negada. Não transforme um resultado parcial em “tudo permitido” ou “nada aconteceu”.','Read the whole sequence. An accepted password followed by denied MFA is not completed login here. A valid session may read one resource and be denied another action. Do not turn a partial outcome into “all allowed” or “nothing happened”.'),
 b('Converter o fuso muda a representação, não o instante. Um relógio atrasado exige correção ou consideração separada. Guarde o horário original e a referência usada para normalizar, para que outra pessoa possa conferir sua linha do tempo.','Timezone conversion changes representation, not the instant. A slow clock needs separate correction or consideration. Keep the original timestamp and the reference used for normalization so someone else can check the timeline.'),
 b('A sessão S43 ajuda a ligar eventos do mesmo acesso neste conjunto. O IP sozinho é mais ambíguo. Use várias chaves de correlação e explique por que cada registro pertence à sequência; proximidade no relógio não prova relação causal.','Session S43 helps connect events from one access in this dataset. IP alone is more ambiguous. Use several correlation keys and explain why each record belongs to the sequence; proximity in time does not prove causation.'),
 b('“Exportação negada” é fato sobre uma operação registrada. “Alguém tentou obter todas as notas” pode ser uma hipótese sobre intenção. “Houve outra sessão sem registro?” é uma lacuna. Escrever os três separadamente evita transmitir certezas que a evidência não sustenta.','“Export denied” is a fact about a recorded operation. “Someone tried to obtain every grade” may be a hypothesis about intent. “Was there an unlogged session?” is a gap. Separating these prevents unsupported certainty.'),
 b('Uma boa passagem permite refazer o raciocínio: fonte, período, registros relevantes, conclusão limitada e próxima verificação. Preserve os originais conforme o procedimento e compartilhe apenas com quem precisa. Copiar logs indiscriminadamente também pode expor dados.','A good handoff makes reasoning reproducible: source, period, relevant records, limited conclusion and next check. Preserve originals under the procedure and share only with those who need them. Indiscriminate log copying may also expose data.')],
 m17:[
 b('Abrir o mesmo editor duas vezes pode criar execuções distintas com o mesmo nome. Identifique a execução por PID e pelo retrato de tempo, depois confira conta, pai e tarefa. Um número diferente, por si só, não torna o processo suspeito.','Opening an editor twice may create distinct executions with the same name. Identify an execution by PID and time snapshot, then check account, parent and task. A different number alone does not make a process suspicious.'),
 b('Imagine pessoas trabalhando no mesmo caderno: threads compartilham dados e precisam coordenar alterações para não sobrescrever o trabalho. Compartilhar memória dentro do processo não significa que qualquer outro processo possa lê-la diretamente sem controles.','Imagine people working in one notebook: threads share data and must coordinate changes to avoid overwriting work. Sharing memory inside a process does not mean every other process can read it directly without controls.'),
 b('Modo de execução e privilégio da conta são dimensões diferentes. Um app iniciado por administrador normalmente ainda tem código em modo usuário. Solicitações ao sistema passam por interfaces e verificações; a bancada não executa código nem inspeciona memória real.','Execution mode and account privilege are different dimensions. An administrator-launched app normally still has user-mode code. System requests pass through interfaces and checks; the desk neither runs code nor inspects real memory.'),
 b('O contexto acompanha o processo quando ele tenta ler ou gravar. Um serviço com conta administrativa pode ter alcance excessivo para uma tarefa simples. Confira qual conta executa e quais recursos a operação precisa, sem confundir token do Windows com token de API.','Context follows a process when it tries to read or write. An administrative service account may have excessive reach for a simple task. Check the executing account and required resources without confusing a Windows token with an API token.'),
 b('O serviço de relatórios precisa ler pedidos e gravar saídas; não precisa ler notas nem modificar a entrada. Uma conta dedicada permite expressar esses limites neste modelo. O sucesso inclui a tarefa funcionar e os acessos extras continuarem negados.','The reporting service needs to read requests and write outputs; it does not need to read grades or modify inputs. A dedicated account expresses those limits here. Success includes both a working task and continued denial of extra access.'),
 b('CPU alta também pode ser atualização ou trabalho pesado. Nome conhecido também pode esconder contexto inesperado. Compare a finalidade aprovada com o comportamento observado antes de priorizar; a decisão é investigar a divergência, não declarar malware apenas pelo nome.','High CPU may also mean an update or demanding work. A familiar name may hide unexpected context. Compare approved purpose with observed behavior before prioritizing; investigate the difference rather than declaring malware from its name.')],
 m18:[
 b('Uma assinatura é um selo verificável ligado ao conteúdo e à chave, não um envelope que esconde o texto. O relatório pode ser público e assinado. Se a tarefa exige confidencialidade, também é necessário controlar quem recebe ou consegue decifrar.','A signature is a verifiable seal linked to content and key, not an envelope hiding text. A report may be public and signed. If confidentiality is required, also control who receives or can decrypt it.'),
 b('Trocar uma frase sem reassinar cria outra versão do documento. A assinatura anterior não acompanha automaticamente a edição. Um resultado incompatível pede conferir a origem da versão, sem usar o certificado ou HTTPS como substituto da verificação do conteúdo.','Changing a sentence without signing again creates a different document version. The old signature does not automatically follow the edit. A mismatch calls for checking that version’s source, not substituting a certificate or HTTPS for content verification.'),
 b('Uma assinatura matematicamente coerente com outra pessoa ainda não é a assinatura esperada da secretaria. A cadeia relaciona certificados até uma âncora confiável; finalidade indica o uso previsto. Identidade, confiança e uso precisam combinar com a tarefa.','A mathematically consistent signature from another person is still not the expected school office signature. The chain connects certificates to a trusted anchor; purpose identifies intended use. Identity, trust and usage must fit the task.'),
 b('Confira o instante e a política usados na avaliação. Validação histórica pode depender de carimbo de tempo e evidências adicionais; esta bancada só avalia o dia selecionado e estados fornecidos. “Desconhecido” não confirma que está bom nem que foi revogado.','Check the instant and policy used for evaluation. Historical validation may depend on timestamps and additional evidence; this desk only evaluates the selected day and supplied states. “Unknown” confirms neither good standing nor revocation.'),
 b('Se a chave de assinatura vaza, alguém pode produzir novos documentos que parecem vir do titular. A resposta envolve conter, substituir e avaliar o intervalo afetado conforme o plano. Publicar a chave pública é esperado; expor a privada não é.','If a signing key leaks, someone may produce new documents appearing to come from its owner. Respond by containing, replacing and assessing the affected period under the plan. Publishing the public key is expected; exposing the private key is not.'),
 b('O selo não autoriza uma transferência nem confirma que as informações são verdadeiras. Uma pessoa autorizada também pode cometer erro ou ter a chave comprometida. Depois das verificações técnicas, compare o pedido com sua tarefa e confirme ações sensíveis por canal conhecido.','The seal neither authorizes a transfer nor proves information truthful. An authorized person may err or have a compromised key. After technical checks, compare the request with your task and confirm sensitive actions through a known channel.')],
 m19:[
 b('O navegador ajuda o aluno a corrigir um erro cedo, mas pedidos podem chegar por outras interfaces. O servidor é quem aceita a operação: precisa conferir o contrato antes de salvar, mesmo se a tela também valida.','The browser helps the student fix mistakes early, but requests can arrive through other interfaces. The server accepts the operation: it must check the contract before saving, even if the screen also validates.'),
 b('O número 12 tem formato numérico, mas excede três vagas. O texto “2” parece número, porém tem outro tipo no contrato desta bancada. Definir tipos e limites evita depender de conversões implícitas ou da lista exibida pela tela.','The number 12 has numeric form but exceeds three places. The text “2” looks numeric but has a different type under this desk’s contract. Defining types and limits avoids reliance on implicit conversions or the screen’s list.'),
 b('Um identificador bem formado pode apontar para o cadastro de outra pessoa. Validar o formato não concede acesso a esse cadastro. A autorização precisa considerar a identidade, o recurso e a ação no servidor, além das regras dos campos.','A well-formed identifier may refer to another person’s record. Validating its format does not grant access to that record. Authorization must consider identity, resource and action on the server as well as field rules.'),
 b('A mensagem ao aluno explica o que fazer sem revelar detalhes internos. O registro restrito ajuda a equipe a encontrar a causa. Não anuncie inscrição concluída quando a gravação falhou; clareza e proteção precisam funcionar juntas.','The student message explains what to do without revealing internals. A restricted log helps the team locate the cause. Do not announce registration success when saving failed; clarity and protection must work together.'),
 b('O identificador de correlação liga a resposta a registros do mesmo pedido. Não precisa incluir senha, token ou todo o formulário para ser útil. Defina eventos necessários, acesso restrito e retenção conforme a finalidade de operação e investigação.','A correlation identifier links a response to records from the same request. It need not include passwords, tokens or the entire form to be useful. Define necessary events, restricted access and purpose-appropriate retention.'),
 b('Cada controle atua em um ponto diferente: validar antes de processar, parametrizar ao consultar o banco, codificar ao exibir no contexto da página. Aceitar um nome com apóstrofo não deve depender de montar SQL por concatenação de texto.','Each control acts at a different point: validate before processing, parameterize database queries and encode for the page’s output context. Accepting a name with an apostrophe should not depend on constructing SQL by concatenation.')],
 m20:[
 b('Escolha pela pergunta. Entender comportamento, organizar fases, distribuir responsabilidades e testar um portal exigem focos diferentes. Uma sigla adicionada ao relatório não melhora a análise se você não consegue explicar qual decisão ela apoia.','Choose by the question. Understanding behavior, organizing phases, assigning responsibilities and testing a portal require different focuses. Adding an acronym does not improve analysis unless you can explain the decision it supports.'),
 b('Uma técnica pode aparecer em contextos diferentes. O mapeamento deve partir do comportamento observado, com a evidência citada. Receber um anexo não confirma sua execução; não preencha uma técnica mais específica só porque ela parece compatível com a história.','A technique may appear in different contexts. Mapping should start from observed behavior with cited evidence. Receiving an attachment does not confirm execution; do not fill in a more specific technique merely because it fits the story.'),
 b('As fases ajudam a perguntar onde interromper a intrusão. Não obrigam todo caso a fornecer evidência das sete fases. Se só a entrega foi observada, exploração e instalação continuam pendentes de verificação, não etapas automaticamente concluídas.','Phases help ask where an intrusion can be interrupted. They do not require every case to supply evidence of all seven. If only delivery was observed, exploitation and installation still need verification rather than being automatically complete.'),
 b('As funções coexistem: você pode governar responsabilidades, proteger acessos e melhorar detecção ao mesmo tempo. CSF ajuda a comunicar resultados de risco e lacunas; não gera sozinho uma regra técnica nem certifica que todos os controles funcionam.','The functions coexist: you may govern responsibilities, protect access and improve detection simultaneously. CSF helps communicate risk outcomes and gaps; it does not itself generate a technical rule or certify that all controls work.'),
 b('Uma lista de riscos ajuda a priorizar perguntas; um requisito verificável permite planejar um teste e registrar evidência. Para revisar autorização do portal, defina recursos, identidades, ações esperadas e negadas. Dizer apenas “seguimos OWASP” não demonstra a verificação.','A risk list helps prioritize questions; a verifiable requirement enables a test plan and evidence. To review portal authorization, define resources, identities and expected and denied actions. Saying “we follow OWASP” does not demonstrate verification.'),
 b('Escreva três partes: registro observado, interpretação com limites e próxima ação. Quando surgir nova evidência, atualize a conclusão sem inventar o restante da cadeia. A referência organiza o raciocínio; ela não substitui a coleta.','Write three parts: observed record, bounded interpretation and next action. When new evidence appears, update the conclusion without inventing the remaining chain. The reference organizes reasoning; it does not replace collection.')],
 m21:[
 b('Um alerta é parecido com um alarme de porta: pode indicar entrada indevida, passagem autorizada ou problema do sensor. A regra disparou por um motivo; a triagem verifica contexto e impacto para decidir se o caso atende aos critérios de incidente.','An alert resembles a door alarm: it may mean unauthorized entry, an approved passage or a sensor issue. The rule triggered for a reason; triage checks context and impact against incident criteria.'),
 b('Se o SIEM recebe login mas não as ações do portal, ele não vê a história inteira. Identifique as fontes e seus campos antes de correlacionar. Um painel bem apresentado pode continuar tendo uma lacuna de coleta.','If a SIEM receives login but not portal actions, it does not see the whole story. Identify sources and fields before correlating. A well-presented dashboard can still have a collection gap.'),
 b('Um aviso “alto” sobre cópia autorizada pode ser menos urgente que uso inesperado de privilégio em dados sensíveis. Explique a ordem com ativo, comportamento, impacto e evidência. A prioridade pode mudar quando chega uma informação verificada.','A “high” warning about an approved copy may be less urgent than unexpected privileged use on sensitive data. Explain order using asset, behavior, impact and evidence. Priority can change when verified information arrives.'),
 b('Um chamado é como uma autorização de retirada: vale para uma pessoa, horário, item e operação. A autorização de copiar materiais não explica exportar notas. Compare o escopo completo e o que o registro efetivamente mostra antes de encerrar.','A ticket is like a collection permit: it covers a person, time, item and operation. Approval to copy materials does not explain exporting grades. Compare the complete scope and what the record actually shows before closing.'),
 b('Um sensor silencioso pode estar sem rede ou com coleta interrompida. Zero alertas nesse período não mede segurança. Verifique último contato, intervalo sem cobertura e fontes alternativas; descreva a falta de visibilidade sem afirmar que houve ou não ataque.','A silent sensor may have no network or interrupted collection. Zero alerts during that period does not measure safety. Check last contact, coverage gap and alternative sources; describe missing visibility without claiming an attack did or did not occur.'),
 b('Outra pessoa deve conseguir continuar sem reconstruir tudo do zero. Informe o que foi visto, por que foi priorizado, o que falta e quem fará a próxima verificação. Evite transformar uma suspeita sobre uma conta em identificação certa da pessoa que agiu.','Another person should be able to continue without rebuilding everything. State what was seen, why it was prioritized, what is missing and who will check next. Avoid turning account suspicion into certain identification of the person who acted.')],
 m22:[
 b('Pense na matéria-prima: registros estruturados, bytes de arquivo ou tráfego. Uma regra Sigma não recebe automaticamente os pacotes que a Suricata observa. A seleção da ferramenta precisa acompanhar a evidência disponível e a integração que transforma campos em condições.','Think about raw material: structured records, file bytes or traffic. A Sigma rule does not automatically receive packets observed by Suricata. Tool choice must follow available evidence and the integration mapping fields to conditions.'),
 b('Aqui o alvo é exportação inesperada, inclusive de conta não administrativa. A aprovação verificada define o que fica fora. Se o objetivo mudar, os rótulos dos testes precisam mudar também: contagem sem objetivo não informa qualidade.','Here the target is unexpected export, including nonadministrative accounts. Verified approval defines exclusions. If the goal changes, test labels must change too: counts without a goal do not indicate quality.'),
 b('Uma condição adicional com E estreita os resultados: pode retirar ruído e também casos relevantes. Uma exceção precisa atingir exatamente a atividade justificada. Excluir uma conta inteira por causa de um único trabalho aprovado cria um alcance maior que a autorização.','An additional AND condition narrows results: it may remove noise and relevant cases. An exception must target exactly the justified activity. Excluding an entire account for one approved task exceeds the authorization’s scope.'),
 b('Observe acertos, ruído, perdas e lacunas juntos. Um painel mais quieto pode estar perdendo exportações reais. Os cinco registros têm resultados esperados fornecidos para comparação; dados de produção exigem investigação para estabelecer esse contexto.','Observe hits, noise, misses and gaps together. A quieter panel may miss real exports. These five records have supplied expected outcomes; production data needs investigation to establish that context.'),
 b('R5 tem exportação conhecida, mas o campo administrativo não foi informado. Uma regra que não precisa desse campo pode avaliar a exportação; uma que o exige fica sem dado suficiente neste modelo. Lacuna depende tanto da fonte quanto da condição escolhida.','R5 has a known export but no supplied administrative field. A rule not needing that field can evaluate the export; one requiring it lacks sufficient data here. A gap depends on both the source and chosen condition.'),
 b('Guarde uma base de comparação antes de ajustar. Depois repita casos relevantes, autorizados, não administrativos e incompletos. Uma melhora em um caso não deve esconder regressão em outro. Fora da bancada, também verifique o parser e a coleta no ambiente.','Keep a baseline before adjusting. Then repeat relevant, approved, nonadministrative and incomplete cases. Improvement on one case should not hide regression on another. Outside the desk, also verify the parser and collection in the environment.')]
};
