import { DifficultySummary, LevelReview } from './DifficultyAssessment';
import { useEffect, useState, useRef, type KeyboardEvent } from 'react';
import { BookOpen, CheckCircle2, FlaskConical, Play, LogOut, Lightbulb, List, ChevronLeft, ChevronRight, Check, Terminal } from 'lucide-react';
import { useSave, type Difficulty, type Bilingual } from './core';
import { modules } from './curriculum';
import { lessons } from './lessons';
import { PixelIcon } from './PixelArt';
import LessonDemo from './LessonDemo';
import ReviewPractice from './ReviewPractice';
import ExperimentGuide from './ExperimentGuide';
import { CompleteExplanation, FeynmanPractice, RetrievalPractice } from './LearningMethods';
import { freshLessonStudy, lessonStudyKey, markLessonRead, parseLessonStudy } from './lessonStudy';
import './lesson-ux.css';

export default function Lesson({difficulty='easy',id,onClose,onStart,allowed,resume=false,sidequest=false,moving=true}:{difficulty?:Difficulty;id:string;onClose:()=>void;onStart:()=>void;allowed:boolean;resume?:boolean;sidequest?:boolean;moving?:boolean}) {
 const lang=useSave(s=>s.save.lang);const t=(text:Bilingual)=>text[lang];const tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const lesson=lessons.find(l=>l.id===id)!;const mission=modules.find(m=>m.id===id)!;const storageKey=lessonStudyKey(id);
 const [study,setStudy]=useState(()=>{try{return parseLessonStudy(storageKey?localStorage.getItem(storageKey):null,lesson.concepts.length)}catch{return freshLessonStudy()}});
 const [resumed]=useState(()=>study.step!==0||study.concept!==0||study.read.length>0||study.view==='worked');
 const [storageAvailable,setStorageAvailable]=useState(true);
 const heading=useRef<(HTMLHeadingElement|null)[]>([]);const tabs=useRef<(HTMLButtonElement|null)[]>([]);const conceptHeadings=useRef<(HTMLHeadingElement|null)[]>([]);const workedHeading=useRef<HTMLHeadingElement>(null);
 const step=study.step;
 useEffect(()=>{try{if(storageKey)localStorage.setItem(storageKey,JSON.stringify(study))}catch{setStorageAvailable(false)}},[study,storageKey]);
 const steps=[tx('Entenda','Understand'),tx('Experimente','Experiment'),tx('Revise','Review')];const StepIcon=[BookOpen,FlaskConical,CheckCircle2];
 function go(n:number,focusTab=false){setStudy(s=>({...s,step:n}));requestAnimationFrame(()=>{const target=focusTab?tabs.current[n]:heading.current[n];target?.focus();if(!focusTab)target?.scrollIntoView({block:'start',behavior:'auto'})})}
 function tabKeys(event:KeyboardEvent<HTMLButtonElement>,index:number){let next=index;if(event.key==='ArrowRight')next=(index+1)%3;else if(event.key==='ArrowLeft')next=(index+2)%3;else if(event.key==='Home')next=0;else if(event.key==='End')next=2;else return;event.preventDefault();go(next,true)}
 function selectConcept(index:number){setStudy(s=>({...s,concept:index,view:'concepts'}));requestAnimationFrame(()=>{conceptHeadings.current[index]?.focus();conceptHeadings.current[index]?.scrollIntoView({block:'start',behavior:'auto'})})}
 function showWorked(){setStudy(s=>({...s,view:'worked'}));requestAnimationFrame(()=>{workedHeading.current?.focus();workedHeading.current?.scrollIntoView({block:'start',behavior:'auto'})})}
 const startLabel=resume?tx('Voltar ao desafio','Return to challenge'):sidequest?tx('Iniciar desafio extra','Start side quest'):tx('Iniciar desafio','Start challenge');
 return <div className="lesson-page lesson-study">
  <div className="game-toolbar"><button className="text-button" onClick={onClose}><LogOut size={16}/>{resume?tx('Voltar ao desafio','Return to challenge'):tx('Voltar','Back')}</button><span>{tx('AULA GUIADA · NO SEU RITMO','GUIDED LESSON · AT YOUR OWN PACE')}</span></div>
  <div className="lesson-heading"><div><div className="eyebrow">{tx('AULA','LESSON')} {mission.label} / {tx('ANTES DA MISSÃO','BEFORE THE MISSION')}</div><h1><PixelIcon type={mission.subject} size={30}/>{t(mission.topic)}</h1><p>{t(lesson.intro)}</p></div><img className="lesson-mentor" src={import.meta.env.BASE_URL+'art/mentor-agent.png'} width="1024" height="1536" alt={tx('Nova, sua mentora','Nova, your mentor')}/></div>
  <div className="lesson-entry-action"><button className="primary" onClick={()=>go(step)}><BookOpen size={18}/>{step===0?tx('Ir direto à leitura','Jump to reading'):step===1?tx('Retomar a prática','Resume practice'):tx('Retomar a revisão','Resume review')}</button></div>
  <section className="lesson-brief" aria-labelledby={`lesson-objective-${id}`}><div className="eyebrow"><Terminal size={17}/>{tx('BRIEFING DA AULA','LESSON BRIEFING')}</div><h2 id={`lesson-objective-${id}`}>{tx('Ao final, você poderá…','By the end, you will be able to…')}</h2><ul>{lesson.checklist.map((item,i)=><li key={i}>{t(item)}</li>)}</ul><p>{tx('Seu percurso: entender a ideia → observar um exemplo → testar → explicar e recuperar da memória. Você pode consultar qualquer etapa; ler não libera pontos nem bloqueia o desafio.','Your route: understand the idea → examine an example → experiment → explain and recall. You can consult any step; reading awards no points and does not block the challenge.')}</p></section>
  <DifficultySummary difficulty={difficulty}/>
  <nav className="lesson-step-nav" role="tablist" aria-label={tx('Etapas da aula','Lesson steps')}>{steps.map((label,i)=>{const Icon=StepIcon[i];return <button ref={el=>{tabs.current[i]=el}} key={i} role="tab" id={`lesson-tab-${id}-${i}`} aria-selected={step===i} aria-current={step===i?'step':undefined} aria-controls={`lesson-panel-${id}-${i}`} tabIndex={step===i?0:-1} onKeyDown={e=>tabKeys(e,i)} onClick={()=>go(i,true)}><Icon size={18}/><span>{i+1}. {label}</span></button>})}</nav>
  <p className="lesson-save-note">{storageAvailable?<>{resumed&&<strong>{tx('Retomada: posição anterior restaurada. ','Resumed: previous position restored. ')}</strong>}{tx('Posição e marcações de leitura ficam neste navegador. Seus rascunhos e testes permanecem ao trocar abas nesta aula aberta; fechar a aula não guarda as respostas.','Reading position and marks stay in this browser. Drafts and experiments stay while switching tabs in this open lesson; closing the lesson does not save answers.')}</>:tx('Armazenamento local indisponível: posição e marcações permanecem apenas nesta aula aberta.','Local storage is unavailable: position and marks stay only in this open lesson.')}</p>
  <section className="lesson-content" role="tabpanel" id={`lesson-panel-${id}-0`} aria-labelledby={`lesson-tab-${id}-0`} hidden={step!==0}>
   <div className="lesson-section-label"><span>01 / 03</span><h2 ref={el=>{heading.current[0]=el}} tabIndex={-1}>{tx('Uma ideia de cada vez','One idea at a time')}</h2></div>
   <div className="lesson-reading-layout">
    <nav className="lesson-reading-index" aria-label={tx('Índice de conceitos e exemplo','Concept and example index')}><div className="lesson-index-label"><List size={18}/><strong>{tx('Nesta aula','In this lesson')}</strong></div><p className="lesson-read-count" role="status">{study.read.length}/{lesson.concepts.length} · {tx('marcados como lidos por você','marked as read by you')}</p><progress value={study.read.length} max={lesson.concepts.length} aria-label={tx('Conceitos que marquei como lidos, não uma medida de domínio','Concepts I marked as read, not a measure of mastery')}/><ol>{lesson.concepts.map((concept,i)=><li key={i}><button className={study.view==='concepts'&&study.concept===i?'is-current':''} aria-current={study.view==='concepts'&&study.concept===i?'location':undefined} onClick={()=>selectConcept(i)}><span className="lesson-index-number" aria-hidden="true">{study.read.includes(i)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span>{t(concept.title)}{study.read.includes(i)&&<small>{tx('Marquei como lido','I marked this as read')}</small>}</span></button></li>)}</ol><button className={'lesson-worked-link '+(study.view==='worked'?'is-current':'')} aria-current={study.view==='worked'?'location':undefined} onClick={showWorked}><Lightbulb size={17}/><span>{tx('Exemplo resolvido','Worked example')}</span></button><p className="lesson-index-note">{tx('Você escolhe o ritmo. Uma marca de leitura registra sua intenção, não comprova aprendizado.','You choose the pace. A reading mark records your intention; it does not prove learning.')}</p></nav>
    <div className="lesson-reading-main">
     <div className="lesson-reading-controls"><div role="group" aria-label={tx('Modo de leitura','Reading mode')}><button className="secondary" aria-pressed={study.mode==='focus'} onClick={()=>setStudy(s=>({...s,mode:'focus',view:'concepts'}))}>{tx('Um conceito','One concept')}</button><button className="secondary" aria-pressed={study.mode==='all'} onClick={()=>setStudy(s=>({...s,mode:'all',view:'concepts'}))}>{tx('Ler tudo','Read all')}</button></div><span>{study.view==='worked'?tx('Aplicação comentada','Worked application'):tx('Conceito','Concept')+' '+(study.concept+1)+' / '+lesson.concepts.length}</span></div>
     <div className="lesson-concepts" hidden={study.view!=='concepts'}>{lesson.concepts.map((concept,i)=><article key={i} hidden={study.mode==='focus'&&study.concept!==i}><div><div className="eyebrow">{tx('CONCEITO','CONCEPT')} {String(i+1).padStart(2,'0')}</div><h3 ref={el=>{conceptHeadings.current[i]=el}} tabIndex={-1}>{t(concept.title)}</h3><p>{t(concept.text)}</p>{concept.depth&&<p className="concept-depth">{t(concept.depth)}</p>}<div className="lesson-example"><strong><Lightbulb size={16}/>{tx('Vamos trazer para o seu dia a dia','Let’s bring this into everyday life')}</strong>{concept.walkthrough?<dl className="lesson-walkthrough"><div><dt>{tx('Imagine a situação','Picture the situation')}</dt><dd>{t(concept.walkthrough.situation)}</dd></div><div><dt>{tx('Entenda o que acontece','Understand what happens')}</dt><dd>{t(concept.walkthrough.reasoning)}</dd></div><div><dt>{tx('O que você pode fazer','What you can do')}</dt><dd>{t(concept.walkthrough.action)}</dd></div></dl>:<p>{t(concept.example)}</p>}</div><label className="lesson-reading-mark"><input type="checkbox" checked={study.read.includes(i)} onChange={()=>setStudy(s=>markLessonRead(s,i,lesson.concepts.length))}/>{tx('Marcar este conceito como lido','Mark this concept as read')}</label></div></article>)}</div>
     <div className="lesson-concept-pagination" hidden={study.view!=='concepts'}><button className="secondary" disabled={study.concept===0} onClick={()=>selectConcept(study.concept-1)}><ChevronLeft size={17}/>{tx('Conceito anterior','Previous concept')}</button>{study.concept<lesson.concepts.length-1?<button className="primary" onClick={()=>selectConcept(study.concept+1)}>{tx('Próximo conceito','Next concept')}<ChevronRight size={17}/></button>:<button className="primary" onClick={showWorked}>{tx('Aplicar no exemplo','Apply to the example')}<ChevronRight size={17}/></button>}</div>
     <div className="lesson-worked-example" hidden={study.view!=='worked'}><h3 ref={workedHeading} tabIndex={-1}>{tx('Agora conecte as ideias no exemplo','Now connect the ideas in the example')}</h3><p>{tx('Use o raciocínio que acabou de ler para fazer uma previsão. Depois confira a explicação. Se faltar alguma peça, os conceitos continuam no índice ao lado.','Use the reasoning you just read to make a prediction. Then check the explanation. If something is missing, the concepts remain in the index.')}</p><CompleteExplanation id={id} moving={moving} active={step===0&&study.view==='worked'}/><button className="primary" onClick={()=>go(1)}><FlaskConical size={18}/>{tx('Testar na bancada','Test in the lab')}</button></div>
    </div>
   </div>
  </section>
  <section className="lesson-content" role="tabpanel" id={`lesson-panel-${id}-1`} aria-labelledby={`lesson-tab-${id}-1`} hidden={step!==1}>
   <div className="lesson-section-label"><span>02 / 03</span><h2 ref={el=>{heading.current[1]=el}} tabIndex={-1}>{tx('Teste uma mudança e explique o resultado','Test a change and explain the result')}</h2></div>
   <div className="lesson-next-action"><strong>{tx('Seu próximo passo','Your next step')}</strong><p>{tx('Faça uma previsão, altere uma coisa por vez e compare com o resultado. Use o tutorial da bancada; depois explique a ideia com suas palavras.','Make a prediction, change one thing at a time and compare with the result. Follow the lab tutorial; then explain the idea in your own words.')}</p></div>
   <a className="learning-jump" href={`#feynman-practice-${id}`}>{tx('Ir à atividade Feynman: explicar com minhas palavras','Go to Feynman practice: explain in my own words')}</a><ExperimentGuide key={id} id={id}/><LessonDemo id={id}/><FeynmanPractice id={id}/>
  </section>
  <section className="lesson-content" role="tabpanel" id={`lesson-panel-${id}-2`} aria-labelledby={`lesson-tab-${id}-2`} hidden={step!==2}>
   <div className="lesson-section-label"><span>03 / 03</span><h2 ref={el=>{heading.current[2]=el}} tabIndex={-1}>{tx('Lembre, confira e corrija','Recall, check and correct')}</h2></div>
   <div className="lesson-next-action"><strong>{tx('Seu próximo passo','Your next step')}</strong><p>{tx('Tente lembrar antes de consultar. Compare sua resposta, complete as lacunas e resolva as perguntas comentadas. Seus erros aqui indicam o que revisar; não retiram XP.','Try recalling before consulting. Compare your answer, fill the gaps and answer the questions with feedback. Mistakes here show what to revisit; they do not remove XP.')}</p></div>
   <RetrievalPractice id={id}/><ReviewPractice lesson={lesson}/>{difficulty!=='easy'&&<LevelReview id={id} difficulty={difficulty}/>}<div className="lesson-checklist"><h3>{tx('Leve para o desafio','Take this into the challenge')}</h3>{lesson.checklist.map((item,i)=><p key={i}><CheckCircle2 size={17}/>{t(item)}</p>)}</div><details className="lesson-sources"><summary>{tx('Fontes e leitura complementar','Sources and further reading')}</summary>{lesson.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}</a>)}</details>
  </section>
  <div className="lesson-footer"><div className="lesson-pagination">{step>0&&<button className="secondary" onClick={()=>go(step-1)}>{tx('Etapa anterior','Previous step')}</button>}{step<2&&<button className="primary" onClick={()=>go(step+1)}>{steps[step+1]}</button>}</div><button className={step===2?'primary':'text-button'} disabled={!allowed} onClick={onStart}><Play size={16}/>{allowed?startLabel:sidequest?tx('Conclua a missão para liberar o desafio extra','Complete the mission to unlock the side quest'):tx('Conclua a missão anterior para jogar','Complete the previous mission to play')}</button></div>
 </div>;
}
