import { useEffect, useRef, useState } from 'react';
import { b, useSave } from './core';
import { configureTower, newTowerGame, startTowerWave, towerAdvance, towerSummary, trafficTypes } from './towerDefense';
import { ctfCases } from './webCtf';
import './learning.css';
import OpenAnswerValidation from './OpenAnswerValidation';

const towerSteps=[
 {title:b('1. O que você está defendendo?','1. What are you defending?'),text:b('Fluxos entram pela rede e seguem até a NEXUS. Alguns são tarefas aprovadas: portal W e backup B. Outros exigem bloqueio ou investigação. O objetivo combina proteção e continuidade: impedir administração externa proibida A, reconhecer o padrão conhecido M e encaminhar ? à triagem sem bloquear as tarefas legítimas. Não é vencer atirando em tudo.','Flows enter the network and head to NEXUS. Some are approved tasks: portal W and backup B. Others need blocking or investigation. Balance protection and continuity: stop prohibited external administration A, recognize known pattern M and route ? to triage without blocking legitimate tasks. Blocking everything does not win.')},
 {title:b('2. Como preparar a rede','2. How to prepare the network'),text:b('Escolha F, S ou T em “Escolha a defesa” e depois clique num Espaço para instalar. Cada defesa custa 25 créditos. F aplica a política TCP/22; S reconhece apenas a assinatura conhecida; T analisa o desconhecido e requer duas verificações no modelo. Remover devolve créditos. A dificuldade muda orçamento e ritmo: comece em Iniciante para comparar sem pressa.','Choose F, S or T under “Choose the defense”, then click a Slot to install. Each costs 25 credits. F applies the TCP/22 policy; S recognizes only the known signature; T handles unknown traffic and needs two checks in the model. Removal refunds credits. Difficulty changes budget and pace; begin on Beginner to compare calmly.')},
 {title:b('3. Controle o tempo e investigue','3. Control time and investigate'),text:b('A onda só começa quando você escolhe “Iniciar onda”. Pause para configurar ou consultar um fluxo. No modo manual, use “Avançar 1 segundo”; os marcadores só se movem quando você avança. Clicar num fluxo mostra os dados que o jogo disponibiliza. Velocidade 2× apenas acelera o tempo; não revela conteúdo TLS nem altera a finalidade de um fluxo.','A wave starts only when you choose “Start wave”. Pause to configure or inspect a flow. In manual mode, use “Advance 1 second”; markers move when you advance. Clicking a flow reveals available game data. 2× only speeds time; it does not reveal TLS content or change flow purpose.')},
 {title:b('4. Demonstração: bloquear tudo ajuda?','4. Demo: does blocking everything help?'),text:b('Antes de executar, preveja: o firewall amplo vai proteger o servidor e manter o portal funcionando ao mesmo tempo? Compare abaixo duas configurações com a mesma onda e o mesmo orçamento. A demonstração usa as regras do minigame, mas não registra XP.','Before running, predict: will a broad firewall protect the server and keep the portal working? Compare two configurations with the same wave and budget below. The demo uses the minigame rules without recording XP.')},
 {title:b('5. Leia o relatório, não só a integridade','5. Read the report, not just integrity'),text:b('A nota é a proporção de fluxos tratados corretamente: entrega legítima, bloqueio correto ou encaminhamento à triagem. Bloquear W/B é falso positivo; deixar ameaça passar ou não tratar o desconhecido reduz a qualidade. Integridade alta não basta se você interrompeu o serviço. Para aprovação, termine as ondas do modo escolhido com pelo menos 70. O treino curto tem uma onda e recompensa máxima própria; repetir só concede a melhoria do melhor resultado.','Score is the proportion of correctly handled flows: legitimate delivery, correct blocking or triage routing. Blocking W/B is a false positive; missed threats or untreated unknowns reduce quality. High integrity is insufficient if service was disrupted. Finish the selected mode with at least 70 to pass. Short practice has one wave and its own reward cap; repeats award only an improvement over the best result.')},
 {title:b('6. Ensine a estratégia para outro agente','6. Teach the strategy to another agent'),text:b('Sem olhar o mapa, explique por que F, S e T têm funções diferentes. Depois responda: “Se todos os fluxos TLS fossem bloqueados, quais tarefas legítimas poderiam parar?” Confira: TLS não indica finalidade; o backup autorizado também pode estar cifrado. Sua justificativa deve mencionar política, visibilidade e continuidade. Agora você pode abrir o treino curto e aplicar esse raciocínio.','Without looking at the map, explain why F, S and T have different roles. Then answer: “If every TLS flow were blocked, which legitimate tasks might stop?” Check: TLS does not indicate purpose; an approved backup can also be encrypted. Mention policy, visibility and continuity. You can now apply this reasoning in short practice.')}
];
const ctfSteps=[
 {title:b('1. O que é uma flag?','1. What is a flag?'),text:b('Uma flag é um marcador de caso resolvido, não uma senha para adivinhar. Neste CTF você investiga três casos fictícios do portal NEXUS. Precisa observar a falha, explicar sua causa e escolher uma correção que atue no servidor ou no contexto adequado. Cada flag aparece depois de validar o achado; não há campo para atacar um site real.','A flag marks a solved case; it is not a password to guess. This CTF investigates three fictional NEXUS portal cases. Observe the flaw, explain its cause and select a fix at the server or appropriate context. Each flag appears after validating the finding; there is no field for attacking a real site.')},
 {title:b('2. Leia identidade, regra e resultado','2. Read identity, policy and result'),text:b('GET significa pedir um recurso; o caminho identifica o recurso; session informa a identidade simulada. HTTP 200 diz que houve uma resposta, não que o acesso era permitido. No primeiro caso, Lia só pode consultar o boletim 17. Ver a resposta de Rui (18) como Lia viola a regra. No segundo, a função de secretaria é necessária; esconder o menu não é negar o acesso no servidor.','GET requests a resource; the path identifies it; session provides the simulated identity. HTTP 200 means a response was returned, not that access was permitted. In case one, Lia may read only report 17. Rui’s report 18 returned to Lia violates the policy. Case two requires the office role; hiding the menu is not server denial.')},
 {title:b('3. Use os controles na ordem do raciocínio','3. Use controls in reasoning order'),text:b('Execute e compare as solicitações à esquerda. Em “Evidência observada”, selecione a resposta que demonstra o acesso ou resultado indevido, não somente uma resposta bem-sucedida. Escolha causa e correção e clique “Validar achado e capturar flag”. Uma escolha incorreta recebe explicação e pode ser revista. No terceiro caso, diferencie texto exibido de marcação interpretada; a saída deve ser tratada conforme o contexto HTML.','Run and compare left-side requests. Under “Observed evidence”, select the response demonstrating improper access or output, not just success. Select cause and fix, then “Validate finding and capture flag”. Incorrect choices receive explanations and can be revised. Case three distinguishes displayed text from interpreted markup; output handling depends on HTML context.')},
 {title:b('4. Demonstração: a correção preserva o acesso legítimo?','4. Demo: does the fix preserve legitimate access?'),text:b('Antes de comparar, preveja a resposta ao boletim próprio e ao do colega. Alterne o controle de autorização do modelo abaixo e confira ambos. A correção deve permitir Lia→17 e negar Lia→18 sem devolver dados privados. A demonstração não captura flag nem altera sua pontuação.','Predict responses for the own and other student report before comparing. Toggle model authorization below and check both. The fix should allow Lia→17 and deny Lia→18 without private data. This demo does not capture a flag or change your score.')},
 {title:b('5. Como pontuação e pistas funcionam','5. How scoring and hints work'),text:b('A nota começa em 100. Consultar explicações e comparar solicitações é livre. Só decisões enviadas incorretas e pistas opcionais descontam: Iniciante −3 por erro e pista gratuita; Intermediário −5 por erro e −3 por pista; Avançado −8 por erro e −5 por pista. Rever a mesma pista não desconta de novo. Resolva todos os casos do modo e alcance 70 para aprovação; treino curto tem um caso. Não existe cronômetro.','Score starts at 100. Explanations and request comparison are free. Only incorrect submissions and optional hints deduct: Beginner −3 per error and free hints; Intermediate −5 per error and −3 per hint; Advanced −8 per error and −5 per hint. Rechecking the same hint does not deduct again. Solve every case in the mode and reach 70 to pass; short practice has one case. There is no timer.')},
 {title:b('6. Explique a falha sem decorar a flag','6. Explain the flaw without memorizing a flag'),text:b('Feche a resposta e explique: quem pediu, qual recurso recebeu, qual regra foi violada e como retestar a correção? Confira: autenticação identifica Lia; autorização decide se pode ler cada objeto. IDs difíceis de adivinhar e botão escondido não substituem essa checagem. No relatório final, relacione evidência, causa e correção; a flag sozinha não explica o aprendizado.','Close the answer and explain: who requested what, what resource was returned, which rule was violated and how should the fix be retested? Check: authentication identifies Lia; authorization decides whether she may read each object. Hard-to-guess IDs and hidden buttons do not replace checks. In the final report, connect evidence, cause and fix; a flag alone does not explain learning.')}
];

export function prepareTutorialTower(broad:boolean){let s=newTowerGame('easy',true);s=configureTower(s,0,'firewall',broad);s=configureTower(s,1,'signature');s=configureTower(s,2,'review');s=configureTower(s,3,'review');return startTowerWave(s)}
export function TowerTutorialDemo({moving}:{moving:boolean}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const [broad,setBroad]=useState(false);const [game,setGame]=useState(()=>prepareTutorialTower(false));const [running,setRunning]=useState(false);const r=towerSummary(game);
 useEffect(()=>{if(!running||!moving||game.phase==='finished')return;const t=setInterval(()=>setGame(s=>towerAdvance(s,10)),500);return()=>clearInterval(t)},[running,moving,game.phase]);
 function reset(value:boolean){setBroad(value);setRunning(false);setGame(prepareTutorialTower(value))}
 return <div className="tutorial-demo"><h3>{tx('Uma onda, duas políticas','One wave, two policies')}</h3><p>{tx('F → S → T → T · 100 créditos usados. Compare os fluxos W/B/A/M/? na mesma sequência; escolher outra política reinicia só esta demonstração.','F → S → T → T · 100 credits used. Compare W/B/A/M/? in the same sequence; choosing another policy resets only this demo.')}</p><div className="learning-actions"><button className="secondary" aria-pressed={!broad} onClick={()=>reset(false)}>{!broad?'✓ ':''}{tx('Firewall seletivo','Selective firewall')}</button><button className="secondary" aria-pressed={broad} onClick={()=>reset(true)}>{broad?'✓ ':''}{tx('Bloquear tudo','Block everything')}</button></div>
  <div className="tutorial-lane" aria-label={tx('Fluxos da onda demonstrativa','Demo wave flows')}>{game.packets.map(p=><span key={p.id} style={{left:`${Math.min(94,p.position/1100*94)}%`,background:trafficTypes[p.type].color}}>{trafficTypes[p.type].symbol}</span>)}</div><p>{tx('Entrada → F → S → T → T → NEXUS','Entry → F → S → T → T → NEXUS')}</p><p>{game.phase==='finished'?tx('Onda encerrada. Compare os resultados ou reinicie para testar outra política.','Wave complete. Compare results or reset to test another policy.'):tx('Avance o modelo para acompanhar os fluxos; cada símbolo representa um tipo de comunicação.','Advance the model to follow flows; each symbol represents a communication type.')}</p>
  <div className="learning-actions"><button className="secondary" disabled={!moving||game.phase==='finished'} onClick={()=>setRunning(!running)}>{running&&moving?tx('Pausar demonstração','Pause demo'):tx('Animar onda','Animate wave')}</button><button className="secondary" disabled={running&&moving||game.phase==='finished'} onClick={()=>setGame(s=>towerAdvance(s,50))}>{tx('Avançar 5 segundos do modelo','Advance 5 model seconds')}</button><button className="secondary" onClick={()=>reset(broad)}>{tx('Reiniciar demonstração','Reset demo')}</button></div>
  <p role="status">{tx('Entregues','Delivered')}: {r.delivered} · {tx('Bloqueios corretos','Correct blocks')}: {r.blocked} · {tx('Triagem','Triage')}: {r.reviewed} · {tx('Legítimos bloqueados','Legitimate blocked')}: {r.falsePositives} · {tx('Sem tratamento','Untreated')}: {r.missed}</p><p>{tx('Seletivo: preserve W e B, bloqueie A, reconheça M e encaminhe ? à triagem. Amplo: observe os legítimos bloqueados; servidor preservado não significa serviço disponível. T significa encaminhamento, não confirmação de ataque.','Selective: preserve W and B, block A, recognize M and route ? to triage. Broad: observe legitimate blocks; preserving a server does not ensure available service. T means routing, not confirmed attack.')}</p>
 </div>;
}
function CtfTutorialDemo(){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const [fixed,setFixed]=useState(false);const [probe,setProbe]=useState('');const p=ctfCases[0].probes.find(p=>p.id===probe);
 return <div className="tutorial-demo"><h3>{tx('Lia consulta boletins fictícios','Lia reads fictional reports')}</h3><label className="learning-check"><input type="checkbox" checked={fixed} onChange={e=>setFixed(e.target.checked)}/>{tx('Servidor verifica autorização para cada boletim','Server checks authorization for every report')}</label><div className="learning-actions">{ctfCases[0].probes.slice(0,2).map(p=><button className="secondary" key={p.id} aria-pressed={probe===p.id} onClick={()=>setProbe(p.id)}>{probe===p.id?'✓ ':''}{p.request}</button>)}</div><div className="learning-feedback" role="status"><strong>{tx('Resultado observado','Observed result')}</strong><p className={fixed&&p?.id==='other'?"error-message":undefined}>{!p?tx('Escolha uma solicitação para comparar.','Choose a request to compare.'):fixed&&p.id==='other'?tx('403 Forbidden · Lia não tem permissão. Nenhum boletim privado retornado.','403 Forbidden · Lia lacks permission. No private report returned.'):p.response[lang]}</p></div><p>{tx('Compare os dois pedidos com o controle desligado e ligado. O 200 do boletim próprio é esperado; o 200 com conteúdo alheio viola a regra. Negar sem retornar conteúdo privado e preservar o pedido legítimo demonstra a correção no modelo.','Compare both requests with the control off and on. A 200 for the own report is expected; a 200 containing someone else’s data violates policy. Denying without private content while preserving legitimate access demonstrates the model fix.')}</p></div>;
}
export default function MinigameTutorial({kind,moving,onClose,onPlay,inProgress=false}:{kind:'tower'|'ctf';moving:boolean;onClose:()=>void;onPlay:()=>void;inProgress?:boolean}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const [step,setStep]=useState(0);const [notes,setNotes]=useState('');const title=useRef<HTMLHeadingElement>(null);const steps=kind==='tower'?towerSteps:ctfSteps;
 useEffect(()=>{title.current?.focus();title.current?.scrollIntoView({block:'start'})},[]);
 const text=steps[step].text[lang];const divider=lang==='pt'?'Confira:':'Check:';const prompt=step===5?text.split(divider)[0]:text;const reference=step===5?text.split(divider)[1]:undefined;
 function go(i:number){setStep(i);requestAnimationFrame(()=>{title.current?.focus();title.current?.scrollIntoView({block:'start'})})}
 return <section className="minigame-tutorial"><button className="text-button" onClick={onClose}>{inProgress?tx('Voltar à partida','Return to round'):tx('Voltar aos minigames','Back to minigames')}</button><div className="eyebrow">{tx('TUTORIAL GUIADO · SEM XP','GUIDED TUTORIAL · NO XP')}</div><h1>{kind==='tower'?'Tower Defense':'CTF Web'} · {tx('Aprenda a jogar','Learn to play')}</h1><p>{tx('Siga as etapas, teste a demonstração e explique sua decisão antes de começar. Você pode voltar a este tutorial durante a partida.','Follow the steps, test the demo and explain your decision before starting. You can return to this tutorial during a round.')}</p><nav className="learning-actions" aria-label={tx('Etapas do tutorial','Tutorial steps')}>{steps.map((s,i)=><button className="secondary" key={i} aria-current={step===i?'step':undefined} onClick={()=>go(i)}>{s.title[lang]}</button>)}</nav><article className="learning-card"><h2 ref={title} tabIndex={-1}>{steps[step].title[lang]}</h2><p>{prompt}</p>{step===3&&(kind==='tower'?<TowerTutorialDemo moving={moving}/>:<CtfTutorialDemo/>)}{step===5&&<label className="learning-label">{tx('Minha explicação para outro agente','My explanation to another agent')}<textarea rows={4} maxLength={2500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={tx('Explique objetivo, decisão e motivo. Pode responder em voz alta.','Explain goal, decision and reason. You can answer aloud.')}/></label>}{step===5&&<OpenAnswerValidation id="tutorial" kind={kind} text={notes}/>} {reference&&<details className="learning-feedback"><summary>{tx('Conferir referência depois de responder','Check the reference after answering')}</summary><p>{reference}</p></details>}<div className="learning-actions">{step>0&&<button className="secondary" onClick={()=>go(step-1)}>{tx('Etapa anterior','Previous step')}</button>}{step<5&&<button className="primary" onClick={()=>go(step+1)}>{tx('Próxima etapa do tutorial','Next tutorial step')}</button>}</div></article><button className="primary" onClick={onPlay}>{inProgress?tx('Retomar minha partida','Resume my round'):tx('Começar partida completa','Start full round')}</button><p className="learning-note">{tx('As demonstrações ficam separadas da partida. Elas não gastam seus créditos, não registram notas e não alteram seu progresso.','Demos are separate from the round. They do not spend your credits, record scores or change your progress.')}</p></section>;
}
