import {useEffect,useRef,useState} from 'react';
import {Check,Lightbulb,Send,Terminal} from 'lucide-react';
import {useSave,type Difficulty,type Bilingual} from './core';
import {networkCases,investigationScore,newDiagnostic,diagnosticGoals,diagnosticScore,runDiagnostic} from './network';
import {PixelIcon} from './PixelArt';

export function LogInvestigation({difficulty,onFinish}:{difficulty:Difficulty;onFinish:(score:number)=>void}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const c=networkCases[difficulty];
 const [selected,setSelected]=useState<string[]>([]);const [hypothesis,setHypothesis]=useState<number|null>(null);const [action,setAction]=useState<number|null>(null);const [review,setReview]=useState(false);const [hint,setHint]=useState(false);const score=investigationScore(c,selected,hypothesis,action);
 return <section className="challenge-panel investigation-panel"><div className="challenge-label"><PixelIcon type="browsing" size={22}/>{tx('INVESTIGAÇÃO DE LOGS','LOG INVESTIGATION')}</div><h2>{tx('Siga o caminho da conexão.','Follow the connection path.')}</h2><p>{c.brief[lang]}</p>
 <details className="network-guide"><summary>{tx('Guia rápido: IP, DNS e portas','Quick guide: IP, DNS and ports')}</summary><div className="network-primer"><div><strong>IP</strong><span>{tx('Endereço para entregar pacotes.','Address for delivering packets.')}</span></div><div><strong>DNS</strong><span>{tx('Consulta registros de um nome.','Looks up records for a name.')}</span></div><div><strong>{tx('PORTA','PORT')}</strong><span>{tx('Distingue serviços, sem garantir confiança.','Distinguishes services without guaranteeing trust.')}</span></div></div></details>
 <div className="inventory-note"><strong>{tx('REFERÊNCIA DA NEXUS','NEXUS BASELINE')}</strong><p>{c.inventory[lang]}</p></div>
 <h3>{tx('1. Selecione as evidências do desvio','1. Select evidence of the divergence')}</h3><p className="log-instructions">{tx('Marque os eventos que sustentam a hipótese de alteração DNS não autorizada. Deixe os demais registros como contexto, sem marcação.','Mark events supporting the unauthorized DNS change hypothesis. Leave the other records unmarked as context.')}</p>
 <div className="evidence-list">{c.rows.map((r,i)=><button key={r.id} disabled={review} aria-pressed={selected.includes(r.id)} className={'evidence-row '+(selected.includes(r.id)?'selected ':'')+(review?(r.clue?'clue':'normal'):'')} onClick={()=>setSelected(selected.includes(r.id)?selected.filter(id=>id!==r.id):[...selected,r.id])}><span className="selection-box">{selected.includes(r.id)&&<Check size={15}/>}</span><span className="evidence-content"><code><span className="log-number">{String(i+1).padStart(2,'0')}</span>{r.line}</code>{review&&<span className="evidence-explanation"><strong>{r.clue?tx('PISTA','CLUE'):tx('CONTEXTO','CONTEXT')}</strong> · {r.why[lang]}</span>}</span></button>)}</div>
 <fieldset className="investigation-options" disabled={review}><legend>{tx('2. Qual hipótese os logs sustentam?','2. Which hypothesis do the logs support?')}</legend>{c.hypotheses.map((option,i)=><label key={i} className={review&&i===c.correctHypothesis?'answer-correct':''}><input type="radio" name="hypothesis" checked={hypothesis===i} onChange={()=>setHypothesis(i)}/><span>{option[lang]}{review&&i===c.correctHypothesis&&<strong className="expected-answer">✓ {tx('Hipótese esperada','Expected hypothesis')}</strong>}</span></label>)}</fieldset>
 <fieldset className="investigation-options" disabled={review}><legend>{tx('3. Qual resposta é proporcional?','3. What is a proportionate response?')}</legend>{c.actions.map((option,i)=><label key={i} className={review&&i===c.correctAction?'answer-correct':''}><input type="radio" name="response" checked={action===i} onChange={()=>setAction(i)}/><span>{option[lang]}{review&&i===c.correctAction&&<strong className="expected-answer">✓ {tx('Resposta esperada','Expected response')}</strong>}</span></label>)}</fieldset>
 {hint&&<div className="hint"><Lightbulb size={18}/>{c.hint[lang]}</div>}
 {review&&<div className={'feedback '+(score>=70?'good':'')} role="status"><strong>{tx('Análise revisada','Analysis reviewed')} · {score}/100</strong><p>{c.explain[lang]}</p><p>{tx('A nota combina seleção de evidências (50), hipótese (25) e resposta (25). Marcar tudo reduz a precisão.','The score combines evidence precision and recall (50), hypothesis (25) and response (25). Marking everything reduces precision.')}</p></div>}
 <div className="challenge-actions"><button className="text-button" onClick={()=>setHint(!hint)}><Lightbulb size={16}/>{tx('Consultar dica','View hint')}</button><button className="primary" disabled={hypothesis===null||action===null} onClick={()=>review?onFinish(score):setReview(true)}>{review?tx('Concluir investigação','Finish investigation'):tx('Revisar análise','Review analysis')}</button></div><p className="log-footnote">{tx('Endereços e registros são exemplos fictícios. Nenhuma rede é acessada.','Addresses and records are fictional examples. No network is accessed.')}</p>
 </section>;
}

export function NetworkDiagnostic({difficulty,onFinish}:{difficulty:Difficulty;onFinish:(score:number)=>void}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const [state,setState]=useState(newDiagnostic);const [entries,setEntries]=useState<{command:string;output:Bilingual;warning?:boolean}[]>([]);const [input,setInput]=useState('');const [hint,setHint]=useState(false);const log=useRef<HTMLDivElement>(null);const field=useRef<HTMLInputElement>(null);const goals=diagnosticGoals(state,difficulty);
 useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[entries]);
 function execute(command:string){if(!command.trim()||command.length>100)return;if(command.trim().toLowerCase()==='clear'){setEntries([]);setInput('');return}const r=runDiagnostic(state,command,difficulty);setState(r.state);setEntries([...entries.slice(-29),{command:command.trim(),output:r.output,warning:r.warning}]);setInput('');field.current?.focus()}
 return <section className="challenge-panel lab-panel"><div className="challenge-label"><Terminal size={20}/>{tx('DIAGNÓSTICO DE REDE','NETWORK DIAGNOSTIC')}</div><h2>{tx('Restaure a rota de confiança.','Restore the trusted path.')}</h2><p>{tx('A workstation-14 usa um resolver diferente do aprovado. Compare o inventário, investigue o destino e valide a correção no laboratório.','Workstation-14 uses a different resolver from the approved one. Compare the inventory, investigate the destination and validate the correction in the laboratory.')}</p><div className="lab-objectives">{goals.map((g,i)=><div key={i} className={g.done?'complete':''}><span>{g.done?'✓':'□'}</span>{g.label[lang]}</div>)}</div>
 <div className="lab-console"><div className="lab-console-header"><span>NEXUS://NETWORK-LAB</span><span>{tx('ESTAÇÃO FICTÍCIA','FICTIONAL WORKSTATION')}</span></div><div ref={log} className="lab-log" role="log" aria-live="polite" aria-relevant="additions"><div className="lab-intro">{tx('Comece com inventory. Consulte help para ver as ações disponíveis.','Start with inventory. Read help for available actions.')}</div>{entries.map((entry,i)=><div className="lab-entry" key={i}><div className="lab-command"><span>agent@nexus $</span> {entry.command}</div><div className={'lab-output '+(entry.warning?'warning-output':'')}>{entry.output[lang]}</div></div>)}</div><form className="lab-input" onSubmit={e=>{e.preventDefault();execute(input)}}><span>$</span><input ref={field} aria-label={tx('Comando do laboratório','Laboratory command')} value={input} onChange={e=>setInput(e.target.value)} placeholder={tx('Digite inventory ou help','Type inventory or help')} maxLength={100} autoComplete="off" spellCheck={false}/><button aria-label={tx('Executar ação fictícia','Run fictional action')} disabled={!input.trim()}><Send size={17}/></button></form></div>
 {difficulty==='easy'&&<div className="lab-shortcuts">{['inventory','resolve portal.nexus.example','configure-dns approved','verify','report'].map(command=><button key={command} onClick={()=>execute(command)}>{command}</button>)}</div>}
 <p className="lab-safety">{tx('Apenas ações fictícias desta lista são aceitas. Tentar configurar DNS não aprovado reduz 15 pontos. Consultas e dicas não penalizam.','Only fictional actions from this list are accepted. Trying to configure unapproved DNS deducts 15 points. Queries and hints are not penalized.')}</p>
 {hint&&<div className="hint"><Lightbulb size={18}/>{`inventory → resolve portal.nexus.example${difficulty!=='easy'?' → connect portal.nexus.example 443':''}${difficulty==='hard'?' → collect':''} → configure-dns approved → verify → report`}</div>}
 <div className="challenge-actions"><button className="text-button" onClick={()=>setHint(!hint)}><Lightbulb size={16}/>{tx('Consultar dica','View hint')}</button><button className="primary" disabled={!goals.every(g=>g.done)} onClick={()=>onFinish(diagnosticScore(state,difficulty))}>{tx('Encerrar diagnóstico','Finish diagnostic')}</button></div></section>;
}
