import {describe,it,expect} from 'vitest';
import {networkCases,investigationScore,evidenceScore,newDiagnostic,runDiagnostic,diagnosticGoals,diagnosticScore} from './network';
import {initial,reward,normalizeSave,type Difficulty} from './core';
describe('network investigations',()=>{
 for(const d of ['easy','normal','hard'] as Difficulty[]){
  it(`scores evidence, hypothesis and response in ${d}`,()=>{const c=networkCases[d];const picks=c.rows.filter(r=>r.clue).map(r=>r.id);expect(investigationScore(c,picks,c.correctHypothesis,c.correctAction)).toBe(100);expect(investigationScore(c,[],c.correctHypothesis,c.correctAction)).toBe(50);expect(evidenceScore(c.rows,c.rows.map(r=>r.id))).toBeLessThan(50);expect(evidenceScore(c.rows,[...picks,...picks,'unknown'])).toBe(50);expect(investigationScore(c,picks,null,null)).toBe(50);for(const lang of ['pt','en'] as const){expect(c.rows.every(r=>!!r.why[lang])).toBe(true);expect(c.hypotheses.every(h=>!!h[lang])).toBe(true);expect(c.actions.every(a=>!!a[lang])).toBe(true)}});
  it(`finishes a closed diagnostic in ${d}`,()=>{let s=newDiagnostic();expect(diagnosticScore(s,d)).toBe(0);const commands=['inventory','resolve portal.nexus.example',...(d!=='easy'?['connect portal.nexus.example 443']:[]),...(d==='hard'?['collect']:[]),'configure-dns approved','verify','report'];for(const cmd of commands){const before={...s};const r=runDiagnostic(s,cmd,d);expect(s).toEqual(before);expect(r.output.pt).toBeTruthy();expect(r.output.en).toBeTruthy();s=r.state}expect(diagnosticGoals(s,d).every(g=>g.done)).toBe(true);expect(diagnosticScore(s,d)).toBe(100)});
 }
 it('blocks correction and reporting before required investigation',()=>{let s=newDiagnostic();expect(runDiagnostic(s,'configure-dns approved','hard').state.configured).toBe(false);for(const cmd of ['inventory','resolve portal.nexus.example','connect portal.nexus.example 443'])s=runDiagnostic(s,cmd,'hard').state;expect(runDiagnostic(s,'configure-dns approved','hard').state.configured).toBe(false);expect(runDiagnostic(s,'report','hard').state.reported).toBe(false);expect(runDiagnostic(s,'verify','hard').state.verified).toBe(false)});
 it('penalizes unapproved changes while leaving unknown commands inert',()=>{let s=newDiagnostic();for(const cmd of ['inventory','resolve portal.nexus.example'])s=runDiagnostic(s,cmd,'easy').state;expect(runDiagnostic(s,'powershell Remove-Item *','easy').state).toBe(s);s=runDiagnostic(s,'configure-dns arbitrary','easy').state;expect(s.configured).toBe(false);expect(s.errors).toBe(1);for(const cmd of ['configure-dns approved','verify','report'])s=runDiagnostic(s,cmd,'easy').state;expect(diagnosticScore(s,'easy')).toBe(85)});
 it('migrates v2 progress and round trips new rewards without farming',()=>{const legacy={...reward(initial,'m7',100,'hard',false),version:2};const migrated=normalizeSave(legacy)!;expect(migrated.version).toBe(22);expect(migrated.xp).toBe(200);let s=reward(migrated,'m8',100,'normal',false);s=reward(s,'s8a',100,'hard',true);expect(s.xp).toBe(400);expect(reward(s,'m8',100,'normal',false)).toEqual(s);expect(normalizeSave(JSON.parse(JSON.stringify(s)))).toEqual(s);expect(normalizeSave({...s,version:2})).toBeNull()});
});
