import {b,type Bilingual,type Difficulty} from './core';
import {q,type Question} from './content';
export const networkQuestions:Record<Difficulty,Question[]>={
 easy:[q('O que um endereço IP identifica no contexto de uma rede?','What does an IP address identify in a network?', [['Um endereço usado para entregar pacotes a uma interface','An address used to deliver packets to an interface'],['Uma senha de acesso','An access password'],['A identidade comprovada de uma pessoa','A person’s verified identity']],0,['IP ajuda a endereçar pacotes. Não comprova quem está usando o dispositivo.','IP helps address packets. It does not prove who is using the device.'],['Pense no destino de uma entrega.','Think about a delivery destination.']),q('Qual é o papel do DNS ao abrir portal.nexus.example?','What does DNS do when opening portal.nexus.example?',[['Criptografar todos os arquivos do computador','Encrypt every file on the computer'],['Consultar registros do nome, como seu endereço IP','Look up name records, such as its IP address'],['Garantir que o site é confiável','Guarantee that the site is trustworthy']],1,['DNS consulta registros de nomes. A resposta não substitui a verificação do serviço e da conexão.','DNS looks up name records. The answer does not replace service and connection verification.'],['Nome e endereço são informações diferentes.','Name and address are different pieces of information.']),q('Um log mostra conexão à porta TCP 443. O que concluir?','A log shows a connection to TCP port 443. What can you conclude?',[['É definitivamente um ataque','It is definitely an attack'],['É definitivamente um site legítimo','It is definitely a legitimate site'],['É uma porta usual de HTTPS; compare serviço, destino e contexto','It is a usual HTTPS port; compare service, destination and context']],2,['A porta sugere um serviço, mas não prova que ele é seguro ou malicioso.','A port suggests a service but does not prove it is safe or malicious.'],['Uma pista precisa de contexto.','A clue needs context.'])],
 normal:[q('O portal deveria resolver para 192.0.2.10, mas uma estação recebe 203.0.113.90. Qual é a próxima verificação?','The portal should resolve to 192.0.2.10, but one workstation gets 203.0.113.90. What should you check next?',[['Investigar resolver, mudanças autorizadas e registros da estação','Investigate the resolver, authorized changes and workstation records'],['Declarar todos os IPs externos maliciosos','Declare all external IP addresses malicious'],['Desativar a validação de certificado','Disable certificate validation']],0,['Compare com o inventário autorizado. Divergência pede investigação; IP externo sozinho não prova um ataque.','Compare with the approved inventory. Divergence calls for investigation; an external IP alone does not prove an attack.'],['Compare observado e esperado.','Compare observed and expected behavior.']),q('Por que registrar protocolo e porta junto ao IP?','Why record protocol and port alongside the IP?',[['Porque a porta identifica o dono do computador','Because the port identifies the computer owner'],['Porque ajudam a distinguir a comunicação e o serviço esperado','Because they help distinguish the communication and expected service'],['Porque substituem o horário do evento','Because they replace the event timestamp']],1,['IP, protocolo, porta e horário ajudam a correlacionar eventos. Não são autenticação.','IP, protocol, port and time help correlate events. They are not authentication.'],['Compare os elementos de uma conexão.','Compare the elements of a connection.']),q('Um backup autorizado usa HTTPS e envia muitos dados. Como tratar esse registro?','An approved backup uses HTTPS and sends lots of data. How should you treat that record?',[['Marcar como exfiltração só pelo volume','Mark it as exfiltration just because of the volume'],['Apagar para reduzir o ruído','Delete it to reduce noise'],['Comparar origem, destino, janela e autorização antes de classificar','Compare source, destination, schedule and authorization before classifying']],2,['Atividade volumosa também pode ser legítima. Preserve o registro e valide o contexto.','High-volume activity can also be legitimate. Preserve the record and validate context.'],['Procure o plano de backup.','Look for the backup plan.'])],
 hard:[q('Dois logs mostram o mesmo IP em horários diferentes. Isso identifica a mesma pessoa?','Two logs show the same IP at different times. Does that identify the same person?',[['Sim, IP nunca muda de usuário','Yes, an IP never changes users'],['Sim, basta a porta de origem','Yes, the source port is enough'],['Não; correlacione tempo, dispositivo, NAT e autenticação','No; correlate time, device, NAT and authentication']],2,['Endereços podem ser compartilhados ou reassociados. Correlação precisa de contexto e limites de atribuição.','Addresses may be shared or reassigned. Correlation needs context and attribution limits.'],['Um endereço não é uma identidade.','An address is not an identity.']),q('Uma conexão à porta 53 é necessariamente uma consulta DNS legítima?','Is a connection to port 53 necessarily a legitimate DNS query?',[['Não; avalie protocolo, conteúdo disponível e resolver autorizado','No; assess protocol, available content and the approved resolver'],['Sim, a porta garante legitimidade','Yes, the port guarantees legitimacy'],['Sim, se o IP for externo','Yes, if the IP is external']],0,['DNS costuma usar UDP/TCP 53, mas a porta não autentica o destino nem garante o conteúdo.','DNS commonly uses UDP/TCP 53, but the port does not authenticate the destination or guarantee the content.'],['Porta conhecida não substitui análise.','A known port does not replace analysis.']),q('Há uma alteração de DNS sem chamado, uma resposta divergente e erro TLS na mesma estação. Qual conclusão é proporcional?','There is a DNS change without a ticket, a divergent answer and a TLS error on the same workstation. What is a proportionate conclusion?',[['Um único erro de login prova que toda a rede caiu','One failed login proves the whole network is down'],['Há evidência de configuração DNS não autorizada; preserve e investigue o alcance','There is evidence of an unauthorized DNS configuration; preserve and investigate scope'],['É seguro ignorar o erro TLS','It is safe to ignore the TLS error']],1,['Eventos correlacionados sustentam a hipótese de configuração não autorizada. Ainda não provam roubo de credenciais.','Correlated events support the unauthorized-configuration hypothesis. They still do not prove credential theft.'],['Separe o que está nos logs do que ainda é hipótese.','Separate what is in the logs from what remains a hypothesis.'])]
};
export interface LogRow{id:string;line:string;clue:boolean;why:Bilingual}
export interface NetworkCase{brief:Bilingual;inventory:Bilingual;rows:LogRow[];hypotheses:Bilingual[];correctHypothesis:number;actions:Bilingual[];correctAction:number;hint:Bilingual;explain:Bilingual}
const row=(id:string,line:string,clue:boolean,pt:string,en:string):LogRow=>({id,line,clue,why:b(pt,en)});
const actions=[b('Ignorar o aviso TLS e tentar entrar novamente','Ignore the TLS warning and try signing in again'),b('Suspender o acesso suspeito, preservar os logs e avisar a equipe para corrigir o DNS aprovado','Suspend suspect access, preserve logs and notify the team to restore approved DNS'),b('Apagar os logs e bloquear toda a empresa','Delete logs and block the entire company')];
const commonExplain=b('O resolver mudou sem autorização e o portal passou a apontar para fora do inventário. Os registros sustentam essa divergência, mas não provam roubo de credenciais. Preserve as evidências, interrompa o acesso suspeito e siga o processo de resposta.','The resolver changed without authorization and the portal pointed outside the inventory. The records support that divergence but do not prove credential theft. Preserve evidence, stop suspect access and follow the response process.');
const easyRows=[
 row('e1','09:00 | workstation-14 | DNS=192.0.2.53 | CHANGE=approved',false,'Configuração aprovada: é a referência inicial.','Approved configuration: this is the starting baseline.'),
 row('e2','09:04 | workstation-14 | DNS=203.0.113.53 | CHANGE=no-ticket',true,'O resolver mudou e não há autorização registrada.','The resolver changed and no authorization is recorded.'),
 row('e3','09:05 | workstation-14 | portal.nexus.example → 203.0.113.90',true,'O portal resolveu para um endereço diferente do inventário.','The portal resolved to an address different from the inventory.'),
 row('e4','09:05 | workstation-14 → 203.0.113.90:443/TCP | TLS=name-mismatch',true,'O erro de nome no certificado reforça a divergência; não deve ser ignorado.','The certificate name mismatch reinforces the divergence; it should not be bypassed.'),
 row('e5','09:06 | workstation-02 → 192.0.2.53:53/UDP | DNS=approved',false,'Consulta ao resolver aprovado de outra estação.','A query to the approved resolver from another workstation.'),
 row('e6','09:06 | workstation-02 → 192.0.2.10:443/TCP | TLS=valid',false,'A outra estação segue o endereço esperado do portal.','The other workstation uses the expected portal address.')
];
const baseInventory=b('Inventário autorizado: workstation-14 (192.0.2.14); DNS 192.0.2.53; portal.nexus.example → 192.0.2.10, HTTPS TCP 443. Nenhuma mudança de DNS aprovada nesta janela.','Approved inventory: workstation-14 (192.0.2.14); DNS 192.0.2.53; portal.nexus.example → 192.0.2.10, HTTPS TCP 443. No DNS change approved in this window.');
export const networkCases:Record<Difficulty,NetworkCase>={
 easy:{brief:b('Uma estação deixou de abrir o portal da NEXUS. Compare os registros com o inventário e encontre a sequência que merece investigação.','A workstation stopped opening the NEXUS portal. Compare records with the inventory and find the sequence that needs investigation.'),inventory:baseInventory,rows:easyRows,hypotheses:[b('Configuração DNS não autorizada na workstation-14','Unauthorized DNS configuration on workstation-14'),b('Toda conexão HTTPS é um ataque','Every HTTPS connection is an attack'),b('Falha geral em todas as estações','A general failure on every workstation')],correctHypothesis:0,actions,correctAction:1,hint:b('Procure a mudança sem chamado, a resposta fora do inventário e o erro de certificado da mesma estação.','Look for the change without a ticket, the answer outside the inventory and the same workstation’s certificate error.'),explain:commonExplain},
 normal:{brief:b('O painel tem tráfego normal e um backup autorizado. Identifique os registros relacionados ao desvio de DNS sem acusar toda conexão externa.','The panel contains normal traffic and an approved backup. Identify records related to the DNS divergence without flagging every external connection.'),inventory:b(baseInventory.pt+' Backup autorizado: backup-01 → 198.51.100.20:443, entre 09:00 e 09:15.',baseInventory.en+' Approved backup: backup-01 → 198.51.100.20:443, between 09:00 and 09:15.'),rows:[easyRows[0],row('n2','09:03 | backup-01 → 198.51.100.20:443/TCP | 240 MB | JOB=BK-42',false,'Volume e destino externo combinam com o backup autorizado.','Volume and external destination match the approved backup.'),...easyRows.slice(1,4),easyRows[5]],hypotheses:[b('Exfiltração comprovada pelo volume do backup','Exfiltration proven by backup volume'),b('Desvio de resolução na workstation-14; investigar alteração do resolver','Resolution divergence on workstation-14; investigate the resolver change'),b('A porta 443 está errada e deve ser trocada por 80','Port 443 is wrong and should be replaced with 80')],correctHypothesis:1,actions,correctAction:1,hint:b('O backup tem autorização. Correlacione mudança de resolver, resposta DNS e conexão posterior da workstation-14.','The backup is authorized. Correlate the resolver change, DNS answer and subsequent workstation-14 connection.'),explain:commonExplain},
 hard:{brief:b('Há manutenção e uma tentativa de login malsucedida no mesmo período. Construa uma hipótese usando a sequência da estação afetada, sem extrapolar os registros.','Maintenance and a failed login occurred in the same period. Build a hypothesis using the affected workstation’s sequence without going beyond the records.'),inventory:b(baseInventory.pt+' Manutenção CHG-91 autorizada apenas em workstation-02; backup BK-42 autorizado em backup-01 → 198.51.100.20:443.',baseInventory.en+' Maintenance CHG-91 approved only on workstation-02; backup BK-42 approved on backup-01 → 198.51.100.20:443.'),rows:[row('h1','08:59 | workstation-02 | CHG-91 | DNS=192.0.2.53',false,'A manutenção tem chamado e usa o resolver aprovado.','The maintenance has a ticket and uses the approved resolver.'),row('h2','09:00 | workstation-14 | AUTH=failed | COUNT=1',false,'Uma tentativa isolada não estabelece a causa da alteração de DNS.','One failed attempt does not establish the cause of the DNS change.'),easyRows[1],row('h4','09:04 | 192.0.2.14 → 203.0.113.53:53/UDP | QUERY=portal.nexus.example',true,'A origem corresponde à estação; a consulta usa o resolver não aprovado.','The source matches the workstation; the query uses the unapproved resolver.'),easyRows[2],row('h6','09:05 | 192.0.2.14 → 203.0.113.90:443/TCP | TLS=name-mismatch',true,'A conexão segue a resposta divergente e falha na validação do nome.','The connection follows the divergent answer and fails name validation.'),row('h7','09:07 | backup-01 → 198.51.100.20:443/TCP | JOB=BK-42',false,'Destino e tarefa coincidem com o backup autorizado.','Destination and job match the approved backup.'),easyRows[5]],hypotheses:[b('O login malsucedido prova roubo de todas as senhas','The failed login proves theft of all passwords'),b('A manutenção da workstation-02 autoriza qualquer alteração','Maintenance on workstation-02 authorizes any change'),b('A sequência da workstation-14 sustenta alteração DNS não autorizada; alcance ainda desconhecido','The workstation-14 sequence supports an unauthorized DNS change; scope is still unknown')],correctHypothesis:2,actions,correctAction:1,hint:b('Ligue 192.0.2.14 à workstation-14. O chamado de outra estação não autoriza sua mudança. IP, porta e horário precisam ser lidos juntos.','Link 192.0.2.14 to workstation-14. A different workstation’s ticket does not authorize its change. Read IP, port and time together.'),explain:commonExplain}
};
export function evidenceScore(rows:LogRow[],selected:string[]){const picks=new Set(selected.filter(id=>rows.some(r=>r.id===id)));const positives=rows.filter(r=>r.clue).length;const tp=rows.filter(r=>r.clue&&picks.has(r.id)).length;return positives+picks.size===0?0:Math.round(50*(2*tp)/(positives+picks.size))}
export function investigationScore(c:NetworkCase,selected:string[],hypothesis:number|null,action:number|null){return evidenceScore(c.rows,selected)+(hypothesis===c.correctHypothesis?25:0)+(action===c.correctAction?25:0)}
export interface DiagnosticState{inventory:boolean;resolved:boolean;connected:boolean;collected:boolean;configured:boolean;verified:boolean;reported:boolean;errors:number}
export const newDiagnostic=():DiagnosticState=>({inventory:false,resolved:false,connected:false,collected:false,configured:false,verified:false,reported:false,errors:0});
export function diagnosticGoals(s:DiagnosticState,d:Difficulty){return [
 {done:s.inventory,label:b('Consultar inventário','Read inventory')},{done:s.resolved,label:b('Comparar resolução DNS','Compare DNS resolution')},...(d!=='easy'?[{done:s.connected,label:b('Testar serviço HTTPS','Test HTTPS service')}]:[]),...(d==='hard'?[{done:s.collected,label:b('Preservar registros','Preserve records')}]:[]),{done:s.configured,label:b('Restaurar DNS aprovado','Restore approved DNS')},{done:s.verified,label:b('Validar o serviço','Validate service')},{done:s.reported,label:b('Registrar relatório','Record report')}
 ]}
export function diagnosticScore(s:DiagnosticState,d:Difficulty){return diagnosticGoals(s,d).every(g=>g.done)?Math.max(0,100-s.errors*15):0}
export function runDiagnostic(s:DiagnosticState,raw:string,d:Difficulty):{state:DiagnosticState;output:Bilingual;warning?:boolean}{
 const input=raw.trim().toLowerCase().replace(/\s+/g,' ');const out=(pt:string,en:string,state=s,warning=false)=>({state,output:b(pt,en),warning});
 if(input==='help')return out('Ações fictícias: inventory | resolve portal.nexus.example | connect portal.nexus.example 443 | collect | configure-dns approved | verify | report | status | clear.','Fictional actions: inventory | resolve portal.nexus.example | connect portal.nexus.example 443 | collect | configure-dns approved | verify | report | status | clear.');
 if(input==='status')return out(`DNS: ${s.configured?'approved':'divergent'} | verificação: ${s.verified?'OK':'pending'} | relatório: ${s.reported?'complete':'pending'}`,`DNS: ${s.configured?'approved':'divergent'} | verification: ${s.verified?'OK':'pending'} | report: ${s.reported?'complete':'pending'}`);
 if(input==='inventory')return out(baseInventory.pt,baseInventory.en,{...s,inventory:true});
 if(input==='resolve portal.nexus.example')return out(`Resolver: ${s.configured?'192.0.2.53':'203.0.113.53'} | portal.nexus.example → ${s.configured?'192.0.2.10':'203.0.113.90'}. Compare com inventory.`,`Resolver: ${s.configured?'192.0.2.53':'203.0.113.53'} | portal.nexus.example → ${s.configured?'192.0.2.10':'203.0.113.90'}. Compare with inventory.`,{...s,resolved:true});
 if(input==='connect portal.nexus.example 443')return out(s.configured?'TCP 443: conectado ao serviço esperado. TLS: nome válido.':'TCP 443: conectado ao destino divergente. TLS: nome incompatível. Não ignore a validação.',s.configured?'TCP 443: connected to expected service. TLS: valid name.':'TCP 443: connected to divergent destination. TLS: name mismatch. Do not bypass validation.',{...s,connected:true});
 if(input==='collect'){if(!s.inventory||!s.resolved)return out('Consulte o inventário e a resolução antes de preservar o diagnóstico.','Read inventory and resolution before preserving the diagnosis.',s,true);return out('Registros do diagnóstico preservados em cópia fictícia.','Diagnostic records preserved in a fictional copy.',{...s,collected:true})}
 if(input.startsWith('configure-dns ')){
  if(!s.inventory||!s.resolved||(d!=='easy'&&!s.connected)||(d==='hard'&&!s.collected))return out('Cumpra os objetivos de investigação e preservação antes da correção.','Meet investigation and preservation objectives before correction.',s,true);
  if(input!=='configure-dns approved')return out('Resolver não aprovado. O laboratório rejeitou a alteração; 15 pontos de redução. Use configure-dns approved.','Unapproved resolver. The laboratory rejected the change; 15-point deduction. Use configure-dns approved.',{...s,errors:s.errors+1},true);
  return out('DNS aprovado restaurado apenas na estação fictícia. Valide com verify.','Approved DNS restored only on the fictional workstation. Validate with verify.',{...s,configured:true});
 }
 if(input==='verify'){if(!s.configured)return out('Corrija a configuração aprovada antes de validar a recuperação.','Restore approved configuration before validating recovery.',s,true);return out('DNS → 192.0.2.10 | HTTPS TCP 443 | TLS válido. Serviço esperado validado; nenhuma autenticação real foi realizada.','DNS → 192.0.2.10 | HTTPS TCP 443 | valid TLS. Expected service validated; no real authentication was performed.',{...s,verified:true})}
 if(input==='report'){if(!s.verified)return out('Valide o serviço com verify antes de encerrar o relatório.','Validate service with verify before completing the report.',s,true);return out('Relatório fictício: desvio DNS corrigido e serviço validado. Causa e alcance precisam de investigação adicional. Nenhuma mensagem enviada.','Fictional report: DNS divergence corrected and service validated. Cause and scope need further investigation. No message sent.',{...s,reported:true})}
 return out('Ação desconhecida. Consulte help. Nenhum comando real foi executado.','Unknown action. Read help. No real command was executed.',s,true);
}
