import { b, type Bilingual } from './core';
import { teachingUnits } from './teachingUnits';
import { explanationRubrics, normalizeExplanation, type ExplanationAssessment } from './explanationValidation';

export type OpenAnswerKind='prediction'|'recall'|'transfer'|'tower'|'ctf';
type Part={label:Bilingual;pattern:RegExp};
export type OpenAnswerRubric={parts:Part[];reference:Bilingual;wrong?:RegExp};
const p=(pt:string,en:string,pattern:RegExp):Part=>({label:b(pt,en),pattern});
const r=(parts:Part[],wrong?:RegExp)=>({parts,wrong});
type LessonChecks=Record<'prediction'|'recall'|'transfer',ReturnType<typeof r>>;
// Each question has its own expected reasoning. Brief recall answers do not inherit
// the Feynman exercise's length, example or limitation requirements.
const checks:Record<string,LessonChecks>={
m25:{prediction:r([p('Identifique a divergência do hash da cópia.','Identify the copy hash mismatch.',/hash.{0,75}(diverg|differ)/),p('Crie outra cópia do original preservado.','Create another copy from the preserved original.',/(copia|copy).{0,75}(original|preserv)/)]),
recall:r([p('Hash compara bytes com uma referência.','A hash compares bytes with a reference.',/hash.{0,85}(bytes|referencia|reference)/),p('Custódia documenta origem e transferências.','Custody documents origin and transfers.',/(cadeia|custody).{0,90}(origem|transfer|origin|custodian)/)]),
transfer:r([p('Verifique os relógios e correlacione fontes.','Check clocks and correlate sources.',/(verifi|check).{0,50}(relog|clock)/),p('A conta não comprova autoria humana.','The account does not establish human authorship.',/(conta|account).{0,55}(nao|not).{0,50}(autoria|authorship)/)],/conta.{0,35}(prova autoria|identifica com certeza)|account.{0,35}(proves authorship|certainly identifies)/)},
 m24:{prediction:r([p('Isolar não revoga a sessão cloud.','Isolation does not revoke the cloud session.',/(nao|not).{0,80}(revog|sess|revoke|session)|sessao.{0,40}(ativa|funciona)|session.{0,40}(active|works)/),p('Trate causa e acessos e teste antes do retorno.','Address cause and access and test before return.',/(test|verific|check).{0,90}(sess|acesso|func|session|access|function)/)]),
 recall:r([p('Contenção limita dano ou expansão.','Containment limits harm or spread.',/(conten|contain).{0,70}(dano|expans|harm|spread)/),p('Recuperação restaura e verifica dados ou funções.','Recovery restores and verifies data or functions.',/(recuper|recovery|restaur|restore).{0,90}(test|verific|dado|func|data|check)/)]),
 transfer:r([p('Revogue ou bloqueie a sessão antiga.','Revoke or block the old session.',/(revog|bloqu|revoke|block).{0,65}(sess|acesso|session|access)/),p('Teste antes do retorno aprovado e monitorado.','Test before approved monitored return.',/(test|verific|check).{0,70}(func|dado|data)|monitor|aprov|approv/)],/hash.{0,30}(garante seguranca|guarantees safety)/)},

 m1:{
  prediction:r([p('A senha antiga ainda pode abrir o e-mail.','The old password may still open email.',/(email|e-mail).{0,65}(continua|ainda|antiga|still|old)|(?:antiga|old).{0,65}(email|e-mail)|(?:sim|yes).{0,90}(email|e-mail)/),p('Trocar a senha na loja não altera outras contas; troque a senha reutilizada.','Changing the shop password does not change other accounts; replace reused passwords.',/(troca|changing).{0,65}(nao modifica|nao altera|does not change)|(?:substitu|troc|replace|change).{0,65}(reutiliz|outros|reused|other)/)],/(trocar|troca|changing).{0,30}(loja|shop).{0,40}(tambem troca|tambem muda|also changes).{0,20}(email|e-mail)/),
  recall:r([p('Senha e PIN são algo que você sabe.','Password and PIN are something you know.',/(dois|ambos|senha|pin|both|password).{0,65}(sabe|know|conhec)/),p('MFA combina categorias de fatores, não dois segredos da mesma categoria.','MFA combines factor categories, not two secrets in one category.',/(mfa.{0,60}(categoria|categor|fator|factor)|mesma categoria|same category)/)],/(senha|password).{0,15}pin.{0,35}(sao dois fatores|are two factors)/),
  transfer:r([p('Recuse o pedido inesperado e confira a conta por acesso oficial.','Decline the unexpected request and check the account through official access.',/(recus|rejeit|neg|declin|reject|deny).{0,85}(oficial|official|verific|check)/),p('A aprovação poderia dar acesso a outra pessoa.','Approval could give another person access.',/(aprova|approv|pedido|request).{0,85}(acesso|access|outra pessoa|someone else)|(?:outra pessoa|someone else).{0,85}(senha|password)/)],/(aprovo|aprovar|approve).{0,60}(encerrar|resolver o aviso|stop the notification)/)
 },
 m2:{
  prediction:r([p('A compra e o logo não confirmam a origem.','The purchase and logo do not confirm origin.',/(nao|not|does not).{0,55}(confirm|origem|confiav|trust)|logo.{0,55}(copiad|copied)/),p('Confira a entrega no app oficial ou em contato conhecido.','Check delivery in the official app or through a known contact.',/(app oficial|official app|contato conhecido|known.{0,15}contact|canal independente|independent channel)/)]),
  recall:r([p('A confirmação usa uma fonte independente.','Verification uses an independent source.',/(fonte|canal|source|channel).{0,40}independente?|independent.{0,25}(source|channel)/),p('O telefone da mensagem pode levar ao próprio golpista.','The message phone number may reach the same scammer.',/(numero|telefone|number|phone).{0,80}(mesma pessoa|golp|scam|nao confirma|cannot|independent)/)]),
  transfer:r([p('Confirme o pagamento por canal conhecido e procedimento.','Verify payment through a known channel and procedure.',/(confirm|verific|check|verify).{0,80}(canal|channel|procedimento|procedure)/),p('Uma conta conhecida pode estar comprometida.','A known account may be compromised.',/(conta|account).{0,65}(tomad|compromet|compromis|taken)/)])
 },
 m3:{
  prediction:r([p('O host é suporte.example; nexus/login é caminho.','The host is suporte.example; nexus/login is a path.',/suporte\.example.{0,90}(caminho|path)|(?:host|dominio|domain).{0,40}suporte\.example/),p('HTTPS não torna esse destino a NEXUS nem garante legitimidade.','HTTPS does not turn that destination into NEXUS or ensure legitimacy.',/(nao|not|does not).{0,90}(nexus|legitim|transform|honest)|https.{0,60}(trajeto|transporte|connection|transport)/)]),
  recall:r([p('HTTPS protege os dados em trânsito ou a conexão.','HTTPS protects data in transit or the connection.',/(protege|protect).{0,50}(transito|transporte|conexao|transit|transport|connection)/),p('Não comprova honestidade do destino ou segurança do conteúdo.','It does not establish destination honesty or content safety.',/(nao|not|does not).{0,75}(honest|segur|safe|legitim|arquivo|file)/)]),
  transfer:r([p('VPN, modo anônimo e HTTPS não corrigem destino fraudulento.','VPN, private mode and HTTPS do not fix a fraudulent destination.',/(nao|not|do not|does not).{0,75}(corrig|fraud|destino|destination|senha|password)/),p('Confira host e pedido por canal oficial.','Check the host and request through an official channel.',/(confir|verific|check|verify).{0,90}(host|origem|oficial|origin|official)/)])
 },
 m4:{
  prediction:r([p('Compartilhe só os dados necessários para a escala.','Share only data needed for the schedule.',/(dados|data|visao|view).{0,65}(necessari|necessary|needed)|(?:so|somente|only).{0,50}(escala|schedule)/),p('Limite quem recebe; dados de saúde não servem à tarefa.','Limit recipients; health data does not serve the task.',/(limit.{0,40}(acesso|access)|saude.{0,40}nao|health.{0,40}(not|doesn)|grupo responsavel|responsible group)/)]),
  recall:r([p('Outros atributos combinados podem identificar alguém.','Other combined attributes may identify someone.',/(atributo|attributes|turma|idade|age).{0,90}(identific|identify|combin)/),p('Avalie o risco de reidentificação no contexto.','Assess contextual reidentification risk.',/(reidentifica|reidentif|risco.{0,40}(contexto|identific)|risk.{0,40}(context|identif))/)]),
  transfer:r([p('Peça uma finalidade e necessidade claras.','Ask for a clear purpose and need.',/(finalidade|purpose).{0,55}(necessidade|need|necessity)|(?:necessidade|need|necessity).{0,55}(finalidade|purpose)/),p('Ofereça só o necessário ao público autorizado.','Offer only what is needed to authorized recipients.',/(necessari|necessary|needed).{0,65}(autoriz|authorized)|(?:autoriz|authorized).{0,65}(necessari|necessary|needed)/)])
 },
 m5:{
  prediction:r([p('O backup conectado à estação suspeita também fica exposto.','A backup attached to the suspect device is also exposed.',/(backup|copia|copy).{0,90}(expo|risco|infect|risk)|(?:expo|infect).{0,50}(copia|backup)/),p('Contenha, avise e recupere num ambiente confiável.','Contain, report and recover in a trusted environment.',/(rede|network).{0,90}(comuni|report|equipe|team)|(?:recuper|recover).{0,65}(confiav|limpo|trusted|clean)/)]),
  recall:r([p('Contenção limita propagação e impacto.','Containment limits spread and impact.',/(conter|contem|contencao|contain).{0,65}(propaga|impacto|spread|impact)/),p('Recuperação restaura operação confiável após verificar o ambiente.','Recovery restores trusted operation after verifying the environment.',/(recuper|recover).{0,80}(restaur|operacao|ambiente|restore|operation|environment)/)]),
  transfer:r([p('Ausência de alerta não prova segurança.','Absence of an alert does not prove safety.',/(ausencia|absence|no alert|nao alertou).{0,75}(nao|not|segur|safe)|(?:nao|not).{0,35}(prova|prove).{0,25}(segur|safe)/),p('Verifique origem e necessidade sem executar o anexo.','Verify origin and need without running the attachment.',/(verifi|verify|check).{0,65}(origem|origin|necessidade|need)|sem executar|without running/)],/(executo|executar|run it).{0,45}(ver o que acontece|see what happens)/)
 },
 m6:{
  prediction:r([p('Contatos e acessibilidade não são necessários à lanterna.','Contacts and accessibility are unnecessary for a flashlight.',/(acess|contato|contact|permission).{0,75}(nao|not|necessari|necessary)|lanterna.{0,60}(nao|not)/),p('Negue acessos sem finalidade e avalie a origem.','Deny purposeless access and review origin.',/(negue|negar|deny|decline|recus).{0,90}(funcao|origem|function|origin|necessari|necessary)/)]),
  recall:r([p('Cada permissão aumenta o que o app pode observar ou fazer.','Each permission expands what the app can observe or do.',/(acesso|permiss|permission).{0,80}(aumenta|observar|fazer|observe|do|expand)/),p('Conceda apenas o necessário para a tarefa.','Grant only what the task needs.',/(necessari|necessary|needed).{0,70}(tarefa|task|solicit|requested)|(?:tarefa|task).{0,70}(necessari|necessary|needed|need)/)]),
  transfer:r([p('Compare localização durante o uso com acesso permanente.','Compare while-in-use location with permanent access.',/(durante o uso|during use|while.{0,12}use).{0,70}(permanente|permanent|always)|permanente.{0,70}durante/),p('Escolha o escopo que atende à viagem e revise o segundo plano.','Choose the scope needed for the trip and review background use.',/(escopo|scope).{0,60}(tarefa|task)|segundo plano|background/)])
 },
 m7:{
  prediction:r([p('A cópia de ontem pode preservar o estado anterior.','Yesterday’s copy may preserve the previous state.',/(copia|copy|backup).{0,65}(ontem|yesterday|anterior|previous)/),p('Teste restauração e integridade; considere mudanças posteriores.','Test restoration and integrity; consider later changes.',/(restaur|restore).{0,90}(test|verifi|confir|check)|(?:test|verifi).{0,70}(restaur|restore)|alteracoes posteriores|later changes/)]),
  recall:r([p('Sincronização alinha estados e pode propagar uma falha.','Synchronization aligns states and may propagate failure.',/(sincroniz|sync).{0,70}(alinh|falha|exclus|align|fail|delet)/),p('Backup preserva pontos de recuperação.','Backups preserve recovery points.',/backup.{0,70}(ponto|recuper|point|recovery)/)]),
  transfer:r([p('O teste não passou só porque o arquivo abre.','Opening the file alone does not mean the test passed.',/(nao|not|no).{0,75}(apenas|so|arquivo|file|pass|bytes)|(?:nao|not|no)[.:]?$/),p('A recuperação inclui chaves, acesso e dependências.','Recovery includes keys, access and dependencies.',/(recuper|recovery).{0,90}(chave|key|dependenc|acesso|access)|(?:chave|key).{0,60}(dependenc|acesso|access)/)])
 },
 m8:{
  prediction:r([p('A consulta DNS respondeu; não prova sozinha falha de resolução.','The DNS query answered; it does not alone prove resolution failure.',/(consulta|query|dns).{0,80}(resposta|answer|respondeu|resolved)|nao.{0,60}resolucao/),p('Confira destino esperado e alcance do serviço.','Check the expected destination and service reachability.',/(confir|verific|check).{0,90}(destino|destination|servico|service)/)]),
  recall:r([p('DNS consulta nomes; IP endereça a comunicação.','DNS looks up names; IP addresses communication.',/dns.{0,80}(nome|name|record|registro)|ip.{0,55}(endereco|endereca|address)/),p('Porta e protocolo distinguem serviços; não provam confiança.','Port and protocol distinguish services; they do not prove trust.',/(porta|port).{0,80}(servico|service)|(?:identidade|identity|confianca|trust).{0,80}(verifi|check)/)]),
  transfer:r([p('O serviço responde, mas a validação da conexão tem problema.','The service responds but connection validation has a problem.',/(alcance|reach|responde|respond).{0,80}(servico|service|validacao|validation)|validacao.{0,60}problema/),p('Confira destino e reporte sem ignorar o alerta.','Check the destination and report without ignoring the warning.',/(nao|not|sem|without).{0,40}(ignor|bypass)|confir.{0,35}destino|check.{0,35}destination/)],/(ignoro|ignorar|ignore).{0,35}(para resolver|to fix)/)
 },
 m9:{
  prediction:r([p('Hash coincidente compara bytes com uma referência.','A matching hash compares bytes with a reference.',/(coincid|match|byte).{0,75}(referencia|reference)|referencia.{0,75}byte/),p('A referência precisa de uma fonte confiável.','The reference needs a trusted source.',/(fonte|source).{0,35}(confiav|trusted)|(?:referencia|reference).{0,65}(desconhecid|untrusted|escolhida|chosen)/)]),
  recall:r([p('A chave privada assina e a pública verifica.','The private key signs and the public key verifies.',/(privada|private).{0,50}(assina|sign).{0,80}(publica|public).{0,50}(verific|verif)/),p('Assinatura não esconde o conteúdo; cifragem fornece confidencialidade.','Signatures do not hide content; encryption provides confidentiality.',/(assinatura|signature|signing).{0,65}(nao|not).{0,40}(confidencial|confidential|esconde|hide)|(?:cifr|encrypt).{0,60}(conteudo|content|confidencial|confidential)/)]),
  transfer:r([p('Hash é calculado sobre bytes, não só nome ou tamanho.','A hash is calculated over bytes, not just name or size.',/hash.{0,75}(byte|conteudo|content)/),p('Use o mesmo algoritmo e referência confiável.','Use the same algorithm and trusted reference.',/(mesmo algoritmo|same algorithm).{0,70}(referencia|reference)|(?:referencia|reference).{0,35}(confiav|trusted)/)])
 },
 m10:{
  prediction:r([p('Escrita a todos concede alteração a quem só deveria ler.','Write for everyone lets readers modify content.',/(amplia|alter|modif|write|writ).{0,85}(ler|read|pessoa|people|conteudo|content)/),p('Restrinja leitura/escrita por função e teste também negação.','Restrict read/write by role and also test denial.',/(leitura|read).{0,85}(escrita|writ)|(?:teste|test).{0,80}(negad|denied|restri)/)]),
  recall:r([p('Teste positivo só demonstra que a tarefa funciona.','A positive test only shows the task works.',/(demonstra|shows|demonstrates|permitido|allowed).{0,75}(tarefa|task|funciona|works)/),p('Teste negativo verifica que acesso desnecessário é impedido.','A negative test checks unnecessary access is prevented.',/(teste negativo|negative test|acessos desnecessarios|unnecessary access|restricao|restriction)/)]),
  transfer:r([p('O grupo adicional pode conceder escrita efetiva.','An additional group may grant effective write access.',/(pode|may|can|possibly).{0,65}(acesso efetivo|effective access|editar|edit)|(?:grupo|group).{0,65}(escrita|writ)/),p('Avalie grupos, herança e regras do sistema.','Review groups, inheritance and system rules.',/(grupo|group).{0,80}(heranca|inheritance|regras|rules)/)])
 },
 m11:{
  prediction:r([p('Confira caminho e LiteralPath para o nome com colchetes.','Check the path and LiteralPath for the bracketed name.',/(caminho|path).{0,85}literalpath|literalpath.{0,85}(caminho|path|nome|name)/),p('Verifique o alvo e anuncie sucesso só após operação confirmada.','Verify the target and announce success only after confirmed operation.',/(sucesso|success).{0,80}(verific|confirm|antes|before)|(?:liste|list|test).{0,60}(alvo|target|dados|data)/)]),
  recall:r([p('LiteralPath evita interpretar o nome como curinga.','LiteralPath avoids treating a name as a wildcard.',/(caractere|nome|name).{0,80}(curinga|wildcard)|literalpath.{0,80}(literal|curinga|wildcard)/),p('Não verifica sozinho caminho, autorização ou segurança.','It does not itself verify the path, authorization or safety.',/(nao|not|does not).{0,80}(caminho|autoriz|segur|path|authoriz|safe)/)]),
  transfer:r([p('A mensagem de sucesso depende da operação verificada.','The success message depends on verified operation.',/(mensagem|message|resultado|result).{0,80}(depend|verific|verified)|sucesso.{0,70}(apos|depois|verific)|success.{0,70}(after|verified)/),p('Trate a falha e interrompa passos dependentes.','Handle failure and stop dependent steps.',/(trat|handl).{0,50}(falha|fail|erro|error)|(?:interrom|stop).{0,60}(passo|step|depend)/)])
 },
 m12:{
  prediction:r([p('Logout não revoga necessariamente o aplicativo.','Logout does not necessarily revoke the app.',/(sair|logout|signing out).{0,110}(nao|not|necessar)|(?:nao|not).{0,60}revog/),p('Revise integrações e revogue pelos controles oficiais.','Review integrations and revoke through official controls.',/(revog|revoke).{0,75}(consentimento|consent|aplicativo|app)|(?:controles oficiais|official controls).{0,75}(integr|revog|revoke)/)]),
  recall:r([p('ID token e access token têm finalidades/destinatários diferentes.','ID and access tokens have different purposes/recipients.',/(finalidade|purpose|destinatario|recipient|audience).{0,65}(difer|differ)|(?:difer|differ).{0,65}(finalidade|purpose|destinatario|audience)/),p('A API valida o token de acesso adequado ao recurso.','The API validates the access token appropriate to the resource.',/api.{0,80}(valid|token)|identidade.{0,80}autorizacao|identity.{0,80}authoriz/)]),
  transfer:r([p('Vigência não concede permissão para apagar.','An unexpired token does not grant deletion permission.',/(nao|not|does not|no).{0,75}(permiss|escopo|scope|acao|action)|(?:leitura|read).{0,70}(apagar|delete)/),p('Valide prazo, destinatário e escopo da ação.','Validate expiry, recipient and action scope.',/(prazo|expiry|lifetime|validity).{0,80}(destinatario|audience|recipient).{0,80}(escopo|scope)/)])
 },
 m13:{
  prediction:r([p('DKIM aprovado e alinhado basta para DMARC neste caso.','Passing aligned DKIM is enough for DMARC here.',/dkim.{0,70}(aprovad|pass).{0,50}(alinh|align)|dkim.{0,70}(alinh|align).{0,50}(aprovad|pass)|aligned passing dkim/),p('A condição usa OU, não exige os dois caminhos.','The condition uses OR, not both paths.',/(operador.{0,30}ou|ou.{0,25}nao e|or.{0,25}not and|one.{0,20}(path|route)|um.{0,20}caminho)/)]),
  recall:r([p('SPF precisa passar e alinhar com o From.','SPF must pass and align with From.',/spf.{0,70}(passa|pass).{0,45}(alinh|align)/),p('Ou DKIM passa e alinha com o From.','Or DKIM passes and aligns with From.',/(ou|or).{0,30}dkim.{0,60}(passa|pass).{0,45}(alinh|align)/)]),
  transfer:r([p('DMARC pass autentica o domínio, não autoriza o pedido.','DMARC pass authenticates the domain, not the request.',/(autenticacao|authentication).{0,70}(dominio|domain)|(?:nao|not).{0,55}(autoriz|authoriz)/),p('Não compartilhe o código; confirme por canal conhecido.','Do not share the code; verify through a known channel.',/(nao compartilhe|do not share|don t share).{0,60}(codigo|code)|confirm.{0,70}(canal|channel)/)])
 },
 m14:{
  prediction:r([p('Público e papel de editor estão amplos demais.','The audience and editor role are too broad.',/(publico|audience).{0,80}(papel|role|pessoas|people)|(?:papel|role).{0,65}(alterac|chang|edit)/),p('Restrinja identidade, leitura e prazo; teste acessos.','Restrict identity, read access and expiry; test access.',/(identidade|identity).{0,80}(leitura|read).{0,65}(prazo|lifetime|expiry|duration)|test.{0,65}(acess|access|allowed|denied)/)]),
  recall:r([p('Público é quem; papel são as ações.','Audience is who; role is which actions.',/(publico|audience).{0,55}(quem|who).{0,75}(papel|role).{0,55}(acoes|actions)/),p('Prazo indica até quando, sem corrigir outras dimensões.','Lifetime indicates until when without fixing other dimensions.',/(prazo|lifetime).{0,70}(quando|when)|(?:dimensao|dimension).{0,80}(outra|other)/)]),
  transfer:r([p('Expiração limita acesso futuro pela concessão.','Expiration limits future access under the grant.',/(expir|expiration).{0,75}(futuro|future|acesso|access)/),p('Não apaga cópias já obtidas.','It does not erase copies already obtained.',/(nao|not|does not).{0,65}(copia|copie|copy)|copies.{0,65}(remain|keep|obtained)/)])
 },
 m15:{
  prediction:r([p('Qualquer serviço também abre administração desnecessária.','Any service also opens unnecessary administration.',/(abre|open|caminho|path).{0,75}(nao necessario|unnecessary|administracao|administration|22)/),p('Restrinja protocolo/porta e teste portal e administração.','Restrict protocol/port and test portal and administration.',/(restrin|restrict).{0,75}(protocolo|porta|protocol|port)|test.{0,80}(portal|administracao|administration)/)]),
  recall:r([p('Compare origem e destino.','Compare source and destination.',/(origem|source).{0,45}(destino|destination)/),p('Compare protocolo e porta.','Compare protocol and port.',/(protocolo|protocol).{0,45}(porta|port)/)]),
  transfer:r([p('Retorno reconhecido pertence a conexão já autorizada.','A recognized reply belongs to an already authorized connection.',/(estado|state).{0,85}(autorizad|authorized)|(?:retorno|reply).{0,85}(conexao|connection)/),p('Uma nova conexão inversa precisa ser avaliada pela política.','A new reverse connection needs policy evaluation.',/(nova conexao|new connection).{0,75}(politica|policy|avaliad|evaluated)/)])
 },
 m16:{
  prediction:r([p('09:01 UTC−03 é 12:01 UTC, não três horas de intervalo.','09:01 UTC−03 is 12:01 UTC, not a three-hour gap.',/12:01.{0,20}utc/),p('A distância é um minuto e ainda exige correlação.','The gap is one minute and still needs correlation.',/(um minuto|one minute)|(?:compare|correla).{0,60}(sessao|session)/)]),
  recall:r([p('Some três horas para obter 12:01 UTC.','Add three hours to get 12:01 UTC.',/12:01.{0,20}utc/),p('Preserve fuso original e confira o relógio.','Preserve the original timezone and check the clock.',/(fuso original|original.{0,15}(zone|timezone)|confianca.{0,30}relogio|clock.{0,40}(check|trust)|check.{0,40}clock)/)],/09:01.{0,25}(e|is|vira|becomes).{0,15}06:01/),
  transfer:r([p('Proximidade e conta iguais não provam uma só atividade.','Close times and the same account do not prove one activity.',/(nao|not|no).{0,80}(correla|campos|fields|paralel|parallel|prova|prove)|(?:ligacao|link).{0,40}(hipotese|hypothesis)/),p('Correlacione outros campos e separe a hipótese.','Correlate other fields and separate the hypothesis.',/(correla).{0,45}(campos|fields)|(?:ligacao|link).{0,45}(hipotese|hypothesis)/)])
 },
 m17:{
  prediction:r([p('Use conta dedicada, leitura na entrada e escrita na saída.','Use a dedicated account, input read access and output write access.',/(conta dedicada|dedicated account)|(?:leitura|read).{0,45}(entrada|input).{0,80}(escrita|writ)/),p('Teste o relatório e a negação de alterações indevidas.','Test report generation and denial of improper changes.',/(test|confir).{0,90}(negad|denied|alterac|chang)/)]),
  recall:r([p('Processo tem contexto e recursos.','A process has context and resources.',/(processo|process).{0,70}(contexto|context|recursos|resources)/),p('Threads executam nesse contexto e compartilham recursos.','Threads run in that context and share resources.',/threads?.{0,85}(compartilh|share|contexto|context)/)]),
  transfer:r([p('Nome e pouca CPU não comprovam legitimidade.','Name and low CPU do not prove legitimacy.',/(nome|name|cpu).{0,80}(nao|not).{0,45}(legitim|prova|prove)/),p('Compare origem, finalidade, conta e comportamento.','Compare origin, purpose, account and behavior.',/(origem|origin).{0,70}(finalidade|purpose).{0,70}(conta|account)|comportamento|behavior/)])
 },
 m18:{
  prediction:r([p('Assinatura matemática não basta diante de revogação e contexto.','A mathematical signature is insufficient without revocation/context checks.',/(nao|not).{0,80}(aprovacao|approval|confianca|trust)|(?:estado|status).{0,70}(dia|date|consult)/),p('Conexão protegida não resolve confiança no documento.','A protected connection does not resolve document trust.',/(conexao|connection).{0,60}(nao|not).{0,55}(documento|document|trust|confianca)/)]),
  recall:r([p('HTTPS protege a conexão com o host.','HTTPS protects the connection to the host.',/https.{0,60}(conexao|connection|host)/),p('A assinatura depende de conteúdo, chave e confiança próprios.','A signature depends on its own content, key and trust.',/(assinatura|signature).{0,80}(chave|key).{0,65}(confianca|trust)/)]),
  transfer:r([p('Rotação não desfaz abuso ou falsificações anteriores.','Rotation does not undo previous abuse or forgery.',/(nao|not).{0,75}(desfaz|undo|anteriores|prior)|(?:troca|rotation|replacement).{0,70}(futuro|future)/),p('Investigue o intervalo de comprometimento e as evidências.','Investigate the compromise interval and evidence.',/(intervalo|interval).{0,65}(compromet|compromise)|(?:investig).{0,85}(evidencia|evidence)/)])
 },
 m19:{
  prediction:r([p('O servidor valida tipo, faixa e opção antes de gravar.','The server validates type, range and option before writing.',/(servidor|server).{0,90}(tipo|type|faixa|range|valid)/),p('Rejeite o pedido fora da regra e comunique a falha.','Reject out-of-rule requests and communicate failure.',/(rejeit|reject).{0,85}(regra|rule|pedido|request)|(?:mensagem|message).{0,65}(log|referencia|reference)/)]),
  recall:r([p('Requisições podem ignorar a checagem da tela.','Requests can bypass screen checks.',/(pedido|request).{0,85}(outros clientes|other clients|sem|without|bypass)/),p('O servidor é a fronteira que valida antes de processar.','The server is the boundary that validates before processing.',/(fronteira|boundary).{0,65}(servidor|server)|(?:servidor|server).{0,75}(process|gravar|write|valid)/)]),
  transfer:r([p('Dado válido não concede permissão.','Valid data does not grant permission.',/(validad|valid).{0,65}(nao|not).{0,50}(permiss|permission)/),p('Verifique autorização para identidade, ação e objeto.','Check authorization for identity, action and object.',/(?:autoriz|authoriz).{0,85}(identidade|identity|acao|action|objeto|object)/)])
 },
 m20:{
  prediction:r([p('ATT&CK descreve comportamento; CSF organiza risco/recuperação.','ATT&CK describes behavior; CSF organizes risk/recovery.',/att&ck.{0,90}(comportamento|behavior)|csf.{0,90}(risco|risk|recuper|recovery)/),p('As referências se complementam e não provam ataque sozinhas.','References complement each other and do not independently prove attacks.',/(complement)|(?:nao|not).{0,65}(prova|prove|ataque|attack)/)]),
  recall:r([p('ATT&CK auxilia descrição do comportamento adversário.','ATT&CK supports describing adversary behavior.',/att&ck.{0,85}(comportamento|behavior)/),p('NIST CSF organiza resultados de gestão de risco.','NIST CSF organizes risk management outcomes.',/(nist|csf).{0,85}(risco|risk|gestao|management)/)]),
  transfer:r([p('Mapeamento organiza hipótese, não confirma incidente.','Mapping organizes a hypothesis, not a confirmed incident.',/(mapeamento|mapping).{0,70}(hipotese|hypothesis)|(?:nao|not).{0,55}(confirma|confirm|basta|enough)/),p('Verifique evidência, contexto, alternativas e impacto.','Check evidence, context, alternatives and impact.',/(verifi|check).{0,90}(evidencia|evidence|contexto|context)|(?:alternativ).{0,35}(impacto|impact)/)])
 },
 m21:{
  prediction:r([p('A exportação merece atenção pelo impacto potencial, não só quantidade.','The export merits attention for potential impact, not just count.',/(exportacao|export).{0,75}(impacto|impact|legitim)|quantidade.{0,55}nao/),p('Correlacione autorização, sessão, recurso e destino sem afirmar vazamento.','Correlate authorization, session, resource and destination without claiming a leak.',/(autorizacao|authorization).{0,80}(sessao|session)|(?:correla).{0,50}(registro|log)/)]),
  recall:r([p('Registre fatos/fontes e hipótese separada.','Record facts/sources and a separate hypothesis.',/(fatos|facts).{0,65}(fontes|sources|hipotese|hypothesis)/),p('Inclua impacto, lacunas e próxima ação proporcional.','Include impact, gaps and a proportional next action.',/(impacto|impact).{0,75}(lacuna|gap).{0,80}(acao|action)/)]),
  transfer:r([p('Confirme escopo e horário do teste.','Confirm test scope and time.',/(confir|verify|check).{0,75}(escopo|scope|horario|time)/),p('Documente a decisão e procure eventos fora do teste.','Document the decision and look for events outside the test.',/(document).{0,50}(decisao|decision)|(?:evento|event).{0,80}(fora|outside)/)])
 },
 m22:{
  prediction:r([p('Exceção ampla pode esconder eventos fora do teste.','A broad exception may hide events outside the test.',/(excecao|exception).{0,85}(escond|hide)|(?:conta|account).{0,65}(fora|outside)/),p('Delimite origem/prazo e teste alerta, legítimo e caso sem campos.','Bound source/expiry and test alerts, legitimate cases and missing fields.',/(origem|source).{0,65}(prazo|time|expiry)|(?:test).{0,100}(campo|field|legitim)/)]),
  recall:r([p('Caso perdido era avaliável, mas não foi detectado.','A missed case was evaluable but not detected.',/(perdido|missed).{0,100}(avaliacao|evaluable|detect)/),p('Caso não avaliável não tinha os dados necessários.','An unevaluable case lacked required data.',/(nao avaliavel|unevaluable).{0,100}(dados|data|campo|field)/)]),
  transfer:r([p('Compare ruído reduzido com relevantes perdidos e cobertura.','Compare reduced noise with relevant misses and coverage.',/(ruido|noise).{0,100}(perdid|missed|cobertura|coverage)/),p('Menos alertas pode significar menos visibilidade, não menos risco.','Fewer alerts may mean less visibility, not less risk.',/(menos alertas|fewer alerts).{0,100}(visibilidade|visibility|risco|risk)/)])
 },
 m23:{
  prediction:r([p('Volume e cifragem não confirmam finalidade.','Volume and encryption do not confirm purpose.',/(volume|cifr|encrypt).{0,80}(nao|not).{0,55}(finalidade|purpose|confirm)/),p('Confira janela e direções, além do contexto.','Check the window and directions as well as context.',/(janela|window).{0,90}(resposta|response|direcao|direction)|(?:confir|check).{0,100}(cobertura|coverage|tempo|time)/)]),
  recall:r([p('TLS informa transporte protegido; volume informa quantidade.','TLS indicates protected transport; volume indicates quantity.',/tls.{0,80}(transporte|transport).{0,80}volume|volume.{0,65}(quantidade|quantity)/),p('Finalidade exige contexto; backup legítimo também pode usar TLS.','Purpose needs context; legitimate backups can also use TLS.',/(finalidade|purpose).{0,80}(contexto|context)|backups?.{0,40}(legitim|authorized)/)]),
  transfer:r([p('Confira janela, as duas direções e cobertura do sensor.','Check the window, both directions and sensor coverage.',/(janela|window).{0,85}(direcoes|directions|sensor)/),p('Relate ausência só na amostra, sem extrapolar ao sistema.','Report absence in the sample without extrapolating to the system.',/(amostra|sample).{0,85}(sem|without|extrapol)|(?:ausencia|absence).{0,50}(amostra|sample)/)])
 }
};
export const tutorialReferences={
 tower:b('F aplica a política TCP/22; S reconhece a assinatura maliciosa conhecida em conteúdo visível; T encaminha o desconhecido à triagem. Bloquear todo TLS pode parar o backup autorizado e outras tarefas legítimas. TLS não indica finalidade; preserve a continuidade e confirme o contexto.','F applies the TCP/22 policy; S recognizes a known malicious signature in visible content; T routes unknown traffic to triage. Blocking all TLS may stop approved backups and other legitimate tasks. TLS does not indicate purpose; preserve continuity and verify context.'),
 ctf:b('Lia pediu o boletim de Rui (18) e recebeu conteúdo alheio sem permissão. Autenticação identifica Lia; falta autorização por objeto no servidor. A correção verifica a permissão a cada pedido. Reteste Lia→17 permitido e Lia→18 negado sem dados privados.','Lia requested Rui’s report (18) and received another student’s content without permission. Authentication identifies Lia; server-side object authorization is missing. The fix checks permission for every request. Retest Lia→17 allowed and Lia→18 denied without private data.')
};
const tutorialChecks={
 tower:r([p('Diferencie firewall, assinatura e triagem.','Distinguish firewall, signature and triage.',/(politica|policy).{0,100}(assinatura|signature).{0,100}(triagem|triage)/),p('Bloquear TLS também pode parar backup legítimo e disponibilidade.','Blocking TLS may also stop legitimate backups and availability.',/(bloquear|blocking).{0,60}tls.{0,100}(backup|legitim)|tls.{0,75}(nao|not).{0,35}(finalidade|purpose)/)],/tls.{0,45}(sempre malicioso|always malicious)|bloquear tudo.{0,45}(garante|vence)/),
 ctf:r([p('Identifique Lia, boletim alheio e autorização ausente.','Identify Lia, another student’s report and missing authorization.',/lia.{0,100}(rui|18|alheio|another).{0,100}(permissao|permission|autoriz|authoriz)/),p('Reteste acesso próprio permitido e alheio negado sem dados.','Retest own access allowed and other access denied without data.',/(retest).{0,100}(17|proprio|own).{0,100}(18|alheio|other)/)],/(esconder|hide).{0,30}(botao|button).{0,40}(resolve|fixes).{0,25}(autorizacao|authorization)/)
};
export function getOpenAnswerRubric(id:string,kind:OpenAnswerKind):OpenAnswerRubric{
 if(kind==='tower'||kind==='ctf')return {...tutorialChecks[kind],reference:tutorialReferences[kind]};
 const u=teachingUnits[id],c=checks[id]?.[kind];if(!u||!c)throw new Error('Unknown open question');
 return {...c,reference:kind==='prediction'?u.reason:kind==='recall'?u.answer:u.transferAnswer};
}
export function assessOpenAnswer(id:string,kind:OpenAnswerKind,text:string):ExplanationAssessment{
 const rubric=getOpenAnswerRubric(id,kind);const raw=text.slice(0,3000);const normal=normalizeExplanation(raw);
 const criteria=rubric.parts.map(part=>({label:part.label,met:part.pattern.test(normal)}));
 criteria.push({label:b('Responda em uma frase explicativa, não apenas com termos soltos.','Answer in an explanatory sentence, not just isolated terms.'),met:normal.split(' ').length>=6&&/\b(e|sao|porque|pois|nao|pode|precisa|deve|para|como|a|o|na|no|do|da|um|uma|is|are|because|not|can|may|must|should|to|the|and|of|for|if|it|my|check|record|compare|assess)\b/.test(normal)});
 const sentences=raw.split(/[!?;\n]+|\.(?=\s|$)/).map(s=>({raw:s.trim(),normal:normalizeExplanation(s)}));
 const patterns=[rubric.wrong,...(explanationRubrics[id]?[explanationRubrics[id].mistake.pattern]:[])].filter((v):v is RegExp=>!!v);
 const mistake=sentences.find(s=>patterns.some(pattern=>{const match=pattern.exec(s.normal);if(!match)return false;return !/\b(nao|not|nunca|never|sem|without|rather than|errado|wrong|falso|false|mito|myth|incorreto|incorrect|evite|avoid)\b/.test(s.normal.slice(0,match.index)+match[0])}));
 return {status:mistake?'incorrect':criteria.every(c=>c.met)?'correct':'incomplete',criteria,correction:mistake?rubric.reference:null,excerpt:mistake?.raw||null};
}
