import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import type { Lesson } from './lessons';
import { review } from './reviewQuestions';

export interface ProcessRecord {id:string;name:string;account:string;parent:string;cpu:number;context:Bilingual;why:Bilingual}
export function processTask(d:Difficulty){
 const common:ProcessRecord[]=[
 {id:'410',name:'navegador',account:'Nova',parent:'desktop · 100',cpu:36,context:b('Nova abriu três abas para pesquisar. A leitura de sua pasta de downloads é esperada.','Nova opened three tabs for research. Reading her downloads folder is expected.'),why:b('O consumo de CPU acompanha a tarefa descrita. Isso dá contexto, mas não certifica que o programa seja seguro.','CPU usage matches the described task. This adds context but does not certify the program as safe.')},
 {id:'520',name:'relatorios',account:'svc-relatorios',parent:'gerenciador-servicos · 200',cpu:2,context:b('Serviço aprovado: lê pedidos e grava relatórios. A conta é dedicada; não precisa da pasta de notas.','Approved service: reads requests and writes reports. Its account is dedicated; it does not need the grades folder.'),why:b('A execução em segundo plano atende a uma finalidade conhecida. Serviço não precisa ser administrador só por ser serviço.','Background execution serves a known purpose. A service does not need administrator rights merely because it is a service.')},
 {id:'630',name:'editor',account:'Nova',parent:'desktop · 100',cpu:0,context:b('Documento aberto e sem edição neste instante. Continua existindo um processo mesmo sem uso visível de CPU.','Document open with no editing at this instant. A process still exists even without visible CPU use.'),why:b('Processos podem esperar por entrada ou trabalho. CPU zero neste retrato não significa que o aplicativo foi encerrado.','Processes can wait for input or work. Zero CPU in this snapshot does not mean the app has closed.')}
 ];
 const suspicious:Record<Difficulty,ProcessRecord>={
 easy:{id:'740',name:'leitor-pdf',account:'Nova',parent:'navegador · 410',cpu:1,context:b('Após abrir um anexo, esse processo pediu alterar a configuração de proteção. A tarefa autorizada era apenas ler o PDF.','After opening an attachment, this process requested changing protection settings. The authorized task was only reading a PDF.'),why:b('O pedido excede a leitura do documento. Preserve o contexto e reporte; um nome familiar não autoriza a mudança.','The request exceeds document reading. Preserve context and report; a familiar name does not authorize the change.')},
 normal:{id:'741',name:'atualizador',account:'Nova',parent:'leitor-pdf · 740',cpu:4,context:b('Surgiu após o anexo e solicitou cadastrar um serviço no início do sistema. Não existe atualização aprovada neste atendimento.','Appeared after the attachment and requested registering a service at startup. No update is approved in this support task.'),why:b('Pai, horário e ação pedida justificam investigar. O nome atualizador e a baixa CPU não comprovam legitimidade nem malware.','Parent, timing and requested action justify investigation. The updater name and low CPU prove neither legitimacy nor malware.')},
 hard:{id:'742',name:'relatorios',account:'Nova',parent:'leitor-pdf · 740',cpu:0,context:b('Tem o mesmo nome do serviço aprovado, mas outro PID, conta e origem. Tentou ler a pasta de notas após o anexo; essa leitura foi negada.','Has the approved service’s name but a different PID, account and origin. Attempted to read the grades folder after the attachment; this read was denied.'),why:b('O contexto difere do serviço PID 520. Há uma tentativa negada a investigar; não há prova de leitura concluída ou de quem estava ao teclado.','Context differs from service PID 520. There is a denied attempt to investigate; no proof of completed reading or who was at the keyboard.')}
 };
 return {records:d==='easy'?[common[0],suspicious[d],common[1]]:[...common,suspicious[d]],target:suspicious[d].id};
}
export type Resource='input'|'output'|'grades';
export type Operation='read'|'write';
export interface ServiceConfig {account:'dedicated'|'admin';inputRead:boolean;outputWrite:boolean;gradesRead:boolean}
export const initialService:ServiceConfig={account:'admin',inputRead:false,outputWrite:false,gradesRead:false};
export const leastService:ServiceConfig={account:'dedicated',inputRead:true,outputWrite:true,gradesRead:false};
export const resourceNames:Record<Resource,Bilingual>={input:b('Pedidos · entrada','Requests · input'),output:b('Relatórios · saída','Reports · output'),grades:b('Notas dos alunos · restrito','Student grades · restricted')};
export function serviceAccess(c:ServiceConfig,resource:Resource,operation:Operation){
 if(c.account==='admin')return true;
 if(resource==='input')return operation==='read'&&c.inputRead;
 if(resource==='output')return operation==='write'&&c.outputWrite;
 return operation==='read'&&c.gradesRead;
}
export function serviceCorrect(c:ServiceConfig){return c.account==='dedicated'&&c.inputRead&&c.outputWrite&&!c.gradesRead}
export const osScore=(scores:boolean[])=>scores.length?Math.round(scores.filter(Boolean).length/scores.length*100):0;
const make=(pt:string,en:string,options:[string,string][],correct:number,explain:[string,string],hint:[string,string]):Question=>q(pt,en,options,correct,explain,hint);
export function osQuestion(kind:'boundary'|'response',d:Difficulty):Question{
 if(kind==='boundary'){
  if(d==='easy')return make('Executar um editor como administrador coloca seu código em modo kernel?','Does running an editor as administrator put its code in kernel mode?', [['Sim; administrador e kernel são a mesma coisa.','Yes; administrator and kernel are the same.'],['Não; privilégios da conta e modo de execução são conceitos diferentes.','No; account privileges and execution mode are different concepts.'],['Só quando o uso de CPU passa de 50%.','Only when CPU use exceeds 50%.']],1,['O editor continua sendo uma aplicação em modo usuário. Elevação amplia capacidades autorizadas, sem transformar o aplicativo no núcleo do sistema.','The editor remains a user-mode application. Elevation broadens authorized capabilities without turning the app into the OS kernel.'],['Separe quem pode fazer uma ação de onde o código executa.','Separate who can perform an action from where code runs.']);
  if(d==='normal')return make('Duas threads do mesmo processo editam dados. Elas têm isolamento de memória como dois processos diferentes?','Two threads in one process edit data. Are they memory-isolated like two separate processes?', [['Sim; cada thread sempre tem um espaço totalmente separado.','Yes; each thread always has a completely separate space.'],['Não; threads do mesmo processo compartilham seu espaço de memória e exigem coordenação.','No; threads in one process share its address space and require coordination.'],['Sim; desde que cada thread tenha um nome diferente.','Yes; provided each thread has a different name.']],1,['Threads são caminhos de execução dentro do processo. Elas compartilham recursos; isso não é a mesma separação entre espaços virtuais de processos distintos.','Threads are execution paths within a process. They share resources; this differs from separation between distinct processes’ virtual address spaces.'],['Imagine dois cozinheiros trabalhando na mesma cozinha.','Picture two cooks working in the same kitchen.']);
  return make('Um processo de usuário pede ler outro processo. A separação de memória garante que nenhuma forma de acesso autorizado seja possível?','A user process requests reading another process. Does memory separation guarantee no authorized access can exist?', [['Sim; até um depurador autorizado fica impossibilitado.','Yes; even an authorized debugger cannot access it.'],['Não; o sistema pode oferecer mecanismos controlados. É preciso verificar direitos e contexto, sem presumir acesso livre.','No; the OS can provide controlled mechanisms. Check rights and context without assuming unrestricted access.'],['Não; todo processo pode escrever livremente na memória de todos os outros.','No; every process can freely write to all others’ memory.']],1,['Espaços virtuais separados evitam acesso direto livre, mas não eliminam interfaces autorizadas do sistema. Isolamento não é garantia absoluta contra todo tipo de acesso.','Separate virtual spaces prevent unrestricted direct access but do not eliminate authorized OS interfaces. Isolation is not an absolute guarantee against all access.'],['Pense na diferença entre uma barreira e uma porta controlada.','Think about the difference between a boundary and a controlled doorway.']);
 }
 const question=d==='hard'?['O retrato mostra a tentativa negada de ler notas. Qual conclusão e resposta cabem nas evidências?','The snapshot shows a denied attempt to read grades. What conclusion and response fit the evidence?']:['O processo pediu uma ação fora da tarefa aprovada. O que fazer com segurança?','The process requested an action outside the approved task. What is a safe response?'];
 return make(question[0],question[1],[['Registrar PID, conta, origem, horário e resultado; reportar e seguir o plano de contenção da equipe.','Record PID, account, origin, time and outcome; report and follow the team’s containment plan.'],['Encerrar qualquer processo que use CPU, inclusive os serviços essenciais.','Terminate every process using CPU, including essential services.'],['Apagar registros e declarar que todas as notas foram roubadas.','Delete records and declare all grades stolen.']],0,['Preserve contexto para análise e use o procedimento autorizado. Uma tentativa negada não prova acesso concluído. PID e nome sozinhos não identificam malware ou uma pessoa.','Preserve context for analysis and use the authorized procedure. A denied attempt does not prove completed access. PID and name alone identify neither malware nor a person.'],['Escolha uma resposta que preserve evidências e respeite o que foi observado.','Choose a response that preserves evidence and respects observations.']);
}
export const osQuestions:Record<Difficulty,Question[]>={easy:[osQuestion('boundary','easy'),osQuestion('response','easy'),osQuestion('boundary','normal')],normal:[osQuestion('boundary','normal'),osQuestion('response','normal'),osQuestion('boundary','easy')],hard:[osQuestion('boundary','hard'),osQuestion('response','hard'),osQuestion('boundary','normal')]};
export const osReview=review(['Um serviço gera relatórios, e um processo de mesmo nome tentou ler notas. O que permite separar as duas execuções e reduzir o acesso do serviço legítimo?','A service generates reports, and a process of the same name attempted to read grades. What separates the executions and reduces the legitimate service’s access?'],[['Usar o nome como identidade e dar administração às duas execuções.','Use the name as identity and give both executions administration.'],['Comparar PID, conta, origem, horário e ação; manter conta dedicada com apenas os acessos necessários.','Compare PID, account, origin, time and action; keep a dedicated account with only necessary access.'],['Escolher a execução com menor CPU e confiar nela sem outras verificações.','Choose the lower-CPU execution and trust it without further checks.'],['Remover a permissão das notas, mas manter a conta administrativa do modelo.','Remove the grades permission but keep the model’s administrative account.']],1,[['Nomes podem se repetir. Ampliar privilégios aumenta as possibilidades de ação sem verificar a finalidade.','Names can repeat. Broadening privileges increases possible actions without checking purpose.'],['O contexto distingue as execuções neste retrato. A conta dedicada e permissões exatas limitam a tarefa sem tomar o nome como prova.','Context distinguishes executions in this snapshot. A dedicated account and exact permissions constrain the task without treating its name as proof.'],['Uso de recursos indica atividade, não confiança. Um processo suspeito também pode estar ocioso.','Resource use indicates activity, not trust. A suspicious process can also be idle.'],['Neste modelo, a conta administrativa mantém acesso amplo independentemente desses seletores. Troque a conta e confira os testes.','In this model the administrative account keeps broad access regardless of these toggles. Change the account and check the tests.']]);
export const osFollowup=review(['Um editor elevado travou. Uma colega diz que ele virou kernel e que todas as suas threads tinham memória isolada. Como corrigir as duas ideias?','An elevated editor crashed. A colleague says it became kernel code and all its threads had isolated memory. How do you correct both ideas?'],[['Elevação amplia permissões, sem transformar o editor em kernel; threads do mesmo processo compartilham seu espaço de memória.','Elevation broadens permissions without turning the editor into kernel code; threads in one process share its address space.'],['Todo aplicativo elevado vira kernel, mas suas threads compartilham memória.','Every elevated app becomes kernel code, but its threads share memory.'],['O editor continua em modo usuário, mas cada thread tem sempre um espaço separado.','The editor remains user mode, but every thread always has a separate space.'],['Um travamento prova malware e não exige verificar o contexto.','A crash proves malware and requires no context check.']],0,[['Você separa privilégio de modo de execução e thread de processo. O travamento, sozinho, não define a causa.','You separate privilege from execution mode and thread from process. The crash alone does not identify the cause.'],['A parte das threads cabe no modelo, mas elevação não transforma código de aplicação em kernel.','The thread part fits the model, but elevation does not turn application code into kernel code.'],['A parte do modo usuário está correta; as threads compartilham recursos e memória do processo.','The user-mode part is correct; threads share their process’s resources and memory.'],['Falha tem várias causas possíveis. Preserve informações e investigue antes de atribuir malware.','Failure has multiple possible causes. Preserve information and investigate before attributing malware.']]);
