import { describe, it, expect } from 'vitest';
import { processTask, serviceAccess, serviceCorrect, leastService, initialService, osScore } from './osInternals';
import { initial, normalizeSave, reward } from './core';
import { canStudyChallenge, lessonMission } from './lessons';
describe('OS process and service simulation',()=>{
 it('distinguishes context from name and CPU in each snapshot',()=>{for(const d of ['easy','normal','hard'] as const){const task=processTask(d);expect(new Set(task.records.map(p=>p.id)).size).toBe(task.records.length);expect(task.records.some(p=>p.id===task.target)).toBe(true);expect(task.records.find(p=>p.cpu===36)?.id).not.toBe(task.target)}const task=processTask('hard');expect(task.records.filter(p=>p.name==='relatorios')).toHaveLength(2);expect(task.records.find(p=>p.id===task.target)?.account).toBe('Nova')});
 it('permits required work and denies unrelated actions',()=>{expect(serviceCorrect(leastService)).toBe(true);expect(serviceAccess(leastService,'input','read')).toBe(true);expect(serviceAccess(leastService,'output','write')).toBe(true);expect(serviceAccess(leastService,'grades','read')).toBe(false);expect(serviceAccess(leastService,'input','write')).toBe(false);expect(serviceAccess(leastService,'output','read')).toBe(false)});
 it('rejects excessive or incomplete configurations including administrative bypass',()=>{for(const c of [{...leastService,account:'admin' as const},{...leastService,inputRead:false},{...leastService,outputWrite:false},{...leastService,gradesRead:true}])expect(serviceCorrect(c)).toBe(false);expect(serviceAccess(initialService,'grades','read')).toBe(true);expect(serviceAccess(initialService,'input','write')).toBe(true);expect(serviceAccess({...leastService,gradesRead:true},'grades','read')).toBe(true)});
 it('requires the previous common-core mission and separates reinforcement',()=>{expect(canStudyChallenge('m17',{},false)).toBe(false);expect(canStudyChallenge('m17',{m16:75},false)).toBe(true);expect(canStudyChallenge('m17',{},true)).toBe(true);expect(canStudyChallenge('m17',{m16:100},true,true)).toBe(false);expect(canStudyChallenge('m17',{m17:75},false,true)).toBe(true);for(const id of ['m17','s17a','s17b'])expect(lessonMission(id)).toBe('m17')});
 it('migrates v11 without losing identity and rejects new IDs in old versions',()=>{const old={...reward(initial,'m16',100,'hard',false),version:11,avatar:3,lang:'en',placement:true};const migrated=normalizeSave(old)!;expect(migrated).toEqual({...old,version:22});const save=reward(migrated,'m17',100,'hard',false);expect(save.xp).toBe(400);expect(normalizeSave({...save,version:11})).toBeNull();expect(normalizeSave(save)).toEqual(save)});
 it('pays only improvements and no failed attempts',()=>{let s=reward(initial,'m17',75,'easy',false);expect(s.xp).toBe(75);s=reward(s,'m17',100,'hard',false);expect(s.xp).toBe(200);expect(reward(s,'m17',100,'hard',false)).toEqual(s);expect(reward(s,'s17b',50,'hard',true)).toEqual(s);expect(osScore([true,true,false,true])).toBe(75);expect(osScore([true,false])).toBe(50);expect(osScore([])).toBe(0)});
});
