import { b, type Bilingual, type Difficulty } from './core';
import { q, type Question } from './content';
import type { Lesson } from './lessons';

export type Mode = [number,number,number];
export type Actor = 'owner'|'group'|'other';
export const accessBits=[4,2,1] as const;
export const actorNames=['Nova','Orion','Visitante'] as const;
export const permissionNames=[b('Ler','Read'),b('Gravar','Write'),b('Executar','Execute')];
export const classNames=[b('Dono','Owner'),b('Grupo equipe','Team group'),b('Outros','Others')];
export function symbolic(mode:Mode){return mode.map(n=>`${n&4?'r':'-'}${n&2?'w':'-'}${n&1?'x':'-'}`).join('')}
export function togglePermission(mode:Mode,row:number,bit:number):Mode{if(!Number.isInteger(row)||row<0||row>2||!accessBits.includes(bit as 4|2|1))return [...mode];const next:Mode=[...mode];next[row]^=bit;return next}
export function selectedClass(owner:boolean,inGroup:boolean):number{return owner?0:inGroup?1:2}
export function permits(mode:Mode,actor:Actor,bit:number){return accessBits.includes(bit as 4|2|1)&&!!(mode[actor==='owner'?0:actor==='group'?1:2]&bit)}
export function matchesMode(mode:Mode,target:Mode){return mode.length===3&&mode.every((n,i)=>n===target[i])}
export function permissionScore(answers:boolean[]){return answers.length?Math.round(100*answers.filter(Boolean).length/answers.length):0}
export type MatrixTask={kind:'matrix';file:string;purpose:Bilingual;target:Mode;hint:Bilingual};
export type PermissionTask=MatrixTask|{kind:'decision';question:Question};
function matrix(file:string,pt:string,en:string,target:Mode):MatrixTask{return {kind:'matrix',file,purpose:b(pt,en),target,hint:b('Confira a necessidade de cada classe. r = 4, w = 2, x = 1; some apenas os bits necessários em cada linha.','Check what each class needs. r = 4, w = 2, x = 1; sum only the required bits in each row.')}}
export const mainMatrices:Record<Difficulty,MatrixTask[]>={
 easy:[matrix('relatorio.txt','Nova prepara o relatório. Orion só precisa lê-lo. Visitantes não devem ter acesso.','Nova prepares the report. Orion only needs to read it. Visitors must have no access.',[6,4,0]),matrix('verificar.sh','O script foi verificado. Nova precisa ler, atualizar e tentar execução direta. Orion precisa ler e tentar executar. Visitantes não têm acesso.','The script was verified. Nova needs to read, update and attempt direct execution. Orion needs to read and attempt execution. Visitors have no access.',[7,5,0])],
 normal:[matrix('revisao.txt','Nova e a equipe de Orion revisam e alteram o texto. Visitantes não têm acesso. Este arquivo é um documento, não um programa.','Nova and Orion’s team review and edit the text. Visitors have no access. This file is a document, not a program.',[6,6,0]),matrix('rotina.sh','Só Nova precisa ler, atualizar e tentar executar a rotina verificada. Orion e visitantes não precisam dela.','Only Nova needs to read, update and attempt execution of the verified routine. Orion and visitors do not need it.',[7,0,0])],
 hard:[matrix('chave-exemplo.txt','O segredo fictício só pode ser lido e atualizado pela dona Nova. Ela também pertence ao grupo equipe; isso não deve mudar sua classe de acesso.','The fictional secret may only be read and updated by owner Nova. She is also in the team group; that must not change her access class.',[6,0,0]),matrix('auditoria.sh','A rotina já aprovada está congelada nesta fase. Nova e Orion precisam ler e tentar executar, sem alterar conteúdo. Visitantes não precisam de acesso.','The approved routine is frozen during this phase. Nova and Orion need to read and attempt execution, without changing content. Visitors need no access.',[5,5,0])]
};
export const extraMatrices:Record<Difficulty,MatrixTask[]>={
 easy:[matrix('guia-publico.txt','Nova mantém o guia público. Orion e visitantes podem ler; ninguém precisa executar este documento.','Nova maintains the public guide. Orion and visitors may read; nobody needs to execute this document.',[6,4,4]),matrix('nota-reservada.txt','Nova deve ler e atualizar a nota. Orion e visitantes não precisam de acesso.','Nova must read and update the note. Orion and visitors do not need access.',[6,0,0])],
 normal:[matrix('arquivo-congelado.txt','Nova e Orion podem ler o documento congelado. Ninguém precisa gravar ou executar; visitantes não têm acesso.','Nova and Orion may read the frozen document. Nobody needs write or execute access; visitors have no access.',[4,4,0]),matrix('ferramenta-equipe.sh','Nova mantém a ferramenta verificada; Orion apenas lê e tenta executá-la. Visitantes não têm acesso.','Nova maintains the verified tool; Orion only reads and attempts execution. Visitors have no access.',[7,5,0])],
 hard:[matrix('rotina-privada.sh','Nesta fase, Nova só precisa ler e tentar executar a rotina verificada, sem atualizar. Orion e visitantes não têm acesso.','In this phase, Nova only needs to read and attempt execution of the verified routine, without updating it. Orion and visitors have no access.',[5,0,0]),matrix('plano-equipe.txt','Nova e Orion precisam ler e atualizar o plano. Visitantes não têm acesso; não há necessidade de execução.','Nova and Orion need to read and update the plan. Visitors have no access; execution is unnecessary.',[6,6,0])]
};
export const permissionQuestions:Record<Difficulty,Question[]>={
 easy:[
 q('Qual conta usar para ler e-mail e editar um texto no Windows?','Which account should you use to read email and edit text on Windows?',[['Conta padrão; elevar só quando uma tarefa verificada precisar','Standard account; elevate only when a verified task needs it'],['Administrador para todos os aplicativos','Administrator for every app'],['Desativar UAC para evitar perguntas','Disable UAC to avoid prompts']],0,['Tarefas comuns normalmente não precisam de privilégios administrativos. A elevação deve ter uma finalidade verificada.','Everyday tasks normally do not need administrative privileges. Elevation should have a verified purpose.'],['A tarefa exige alterar o sistema ou só seus documentos?','Does the task require changing the system or only your documents?']),
 q('Um instalador inesperado pede elevação. Qual é a resposta segura?','An unexpected installer requests elevation. What is a safe response?',[['Aprovar para descobrir o que faz','Approve to discover what it does'],['Cancelar e conferir a necessidade e a origem pelo canal conhecido','Cancel and check the need and source through the known channel'],['Enviar sua senha para quem mandou o arquivo','Send your password to whoever sent the file']],1,['O pedido de elevação não comprova legitimidade. Pare e confirme a tarefa e a origem antes de conceder privilégios.','An elevation request does not prove legitimacy. Stop and confirm the task and source before granting privileges.'],['Você estava esperando esta instalação?','Were you expecting this installation?']),
 q('Retirar uma permissão direta de leitura no Windows garante que Orion perdeu acesso?','Does removing a direct Read permission in Windows guarantee that Orion lost access?',[['Sim, grupos nunca contam','Yes, groups never count'],['Sim, se o arquivo tiver outro nome','Yes, if the file has a different name'],['Não; confira grupos, herança e acesso efetivo','No; check groups, inheritance and effective access']],2,['Orion pode receber acesso por outras entradas, inclusive grupos e herança. Confira o resultado efetivo com as ferramentas apropriadas.','Orion may receive access through other entries, including groups and inheritance. Check effective access with appropriate tools.'],['Quais outros caminhos concedem acesso?','What other paths grant access?'])],
 normal:[
 q('Um editor consegue alterar seus documentos sem administrador. O que manter?','An editor can change your documents without administrator privileges. What should you keep?',[['Execução sempre elevada','Always elevated execution'],['Execução comum, com o acesso necessário aos documentos','Normal execution with the required document access'],['UAC desativado permanentemente','UAC permanently disabled']],1,['Privilégios administrativos não são necessários só porque o app grava arquivos. Limite a tarefa ao acesso que ela exige.','Administrative privileges are not needed just because an app writes files. Limit the task to the access it requires.'],['Permissão de um documento e privilégio administrativo são coisas diferentes.','Document permission and administrative privilege are different things.']),
 q('A equipe confirmou uma atualização pelo canal oficial. Qual cuidado acompanha a elevação?','The team confirmed an update through the official channel. What care accompanies elevation?',[['Conferir o aplicativo e a finalidade, elevar a tarefa necessária e voltar ao uso comum','Check the application and purpose, elevate the necessary task and return to normal use'],['Passar todos os programas a administrador','Make every program run as administrator'],['Aprovar futuros pedidos sem olhar','Approve future prompts without checking']],0,['Uma tarefa verificada pode precisar de elevação. Isso não justifica ampliar privilégios de outros programas ou ignorar pedidos futuros.','A verified task may need elevation. That does not justify expanding other programs’ privileges or ignoring future prompts.'],['Qual processo precisa do privilégio e por qual motivo?','Which process needs the privilege, and why?']),
 q('Você retirou a entrada direta de Orion, mas o grupo Revisores ainda pode ler a pasta. O que investigar?','You removed Orion’s direct entry, but the Reviewers group may still read the folder. What should you investigate?',[['Se Orion está nesse grupo e quais permissões chegam por herança','Whether Orion is in that group and which permissions are inherited'],['Só a extensão do arquivo','Only the file extension'],['Aumentar todos para controle total','Give everyone full control']],0,['Entradas de grupo e permissões herdadas podem continuar autorizando acesso. Analise o acesso efetivo antes de concluir que a retirada funcionou.','Group entries and inherited permissions may continue to authorize access. Analyze effective access before concluding that removal worked.'],['Remover uma entrada não remove necessariamente todas as autorizações.','Removing one entry does not necessarily remove every authorization.'])],
 hard:[
 q('Um processo padrão recebeu permissão de gravar seu relatório. Isso significa que tem controle administrativo do Windows?','A standard process was granted Write access to your report. Does that mean it has administrative control of Windows?',[['Sim, toda gravação é administração','Yes, all writing is administration'],['Não; acesso ao objeto e privilégios de sistema são distintos','No; object access and system privileges are distinct'],['Sim, se o relatório for grande','Yes, if the report is large']],1,['Autorização para um objeto não transforma automaticamente o processo em administrador. Avalie separadamente permissões e privilégios.','Authorization for an object does not automatically turn a process into an administrator. Evaluate permissions and privileges separately.'],['Qual recurso foi autorizado?','Which resource was authorized?']),
 q('A atualização verificada terminou. A equipe propõe manter todo o navegador elevado. O que responder?','A verified update finished. The team proposes keeping the entire browser elevated. What should you say?',[['Aceitar: a atualização tornou tudo seguro','Accept: the update made everything safe'],['Desativar o controle de elevação','Disable elevation control'],['Retomar o uso comum; o privilégio era para a tarefa específica','Return to normal use; the privilege was for the specific task']],2,['O privilégio de uma instalação não deve virar contexto permanente de navegação. Mantenha o uso cotidiano com os privilégios necessários.','Installation privileges should not become a permanent browsing context. Keep daily use at the privileges it needs.'],['A necessidade da tarefa anterior continua existindo?','Does the previous task’s need still exist?']),
 q('Uma mudança em uma pasta pai altera acesso de arquivos filhos. Qual procedimento é coerente?','A change on a parent folder alters access to child files. Which procedure is appropriate?',[['Validar escopo, herança e acesso efetivo dos grupos afetados','Validate scope, inheritance and effective access of affected groups'],['Supor que só a pasta pai mudou','Assume only the parent folder changed'],['Aplicar controle total para eliminar dúvidas','Apply full control to eliminate doubts']],0,['Herança pode propagar permissões. Planeje o escopo, confira as entradas aplicáveis e teste o efeito com as identidades adequadas.','Inheritance may propagate permissions. Plan scope, check applicable entries and test the effect using the relevant identities.'],['Uma pasta pode transmitir permissões aos objetos que contém.','A folder may pass permissions to the objects it contains.'])]
};
export function permissionTasks(d:Difficulty,id:string):PermissionTask[]{return id==='s10a'?extraMatrices[d]:id==='s10b'?permissionQuestions[d].slice(1).map(question=>({kind:'decision' as const,question})):[...mainMatrices[d],...permissionQuestions[d].slice(0,2).map(question=>({kind:'decision' as const,question}))]}
export const permissionsLesson:Lesson={id:'m10',intro:b('O sistema operacional controla processos e recursos. Permissões definem o que cada identidade pode fazer; use o acesso necessário à tarefa.','The operating system controls processes and resources. Permissions define what each identity may do; use the access required for the task.'),concepts:[
 {title:b('Identidade e autorização','Identity and authorization'),text:b('Entrar em uma conta identifica o usuário. A autorização decide se ele pode acessar um recurso. Programas normalmente agem no contexto da conta que os executa.','Signing in identifies a user. Authorization decides whether they may access a resource. Programs normally act in the context of the account running them.'),example:b('Orion entrou corretamente, mas só pode ler o relatório da equipe. Login válido não dá autorização para alterar tudo.','Orion signed in correctly, but may only read the team report. A valid login does not authorize changing everything.')},
 {title:b('Linux: dono, grupo e outros','Linux: owner, group and others'),text:b('No modelo básico de arquivos, use a classe do dono se ela corresponder à identidade; senão, a do grupo associado; senão, outros. As três classes não se somam. r lê, w grava conteúdo e x permite tentar execução direta.','In the basic file model, use the owner class if it matches the identity; otherwise the associated group; otherwise others. The three classes do not add together. r reads, w writes content and x allows attempting direct execution.'),example:b('rw-r-----, ou 640: dono lê/grava, grupo lê, outros não acessam. Um dono sem r não ganha leitura só porque seu grupo tem r.','rw-r-----, or 640: owner reads/writes, group reads, others have no access. An owner without r does not gain Read just because their group has r.')},
 {title:b('Arquivo e diretório têm efeitos diferentes','Files and directories have different effects'),text:b('Em diretórios Linux, r permite listar nomes, x permite atravessar o caminho e w permite alterar entradas, com outras regras aplicáveis. Gravar um arquivo não é o mesmo que excluí-lo.','In Linux directories, r allows listing names, x allows traversing the path and w allows changing entries, with other rules also applying. Writing a file is not the same as deleting it.'),example:b('Para chegar a /equipe/relatorio.txt, a travessia dos diretórios também importa. Nossa bancada mantém o caminho acessível e trabalha só com arquivos regulares.','To reach /team/report.txt, directory traversal matters too. Our workbench keeps the path accessible and works only with regular files.')},
 {title:b('Windows: grupos, herança e elevação','Windows: groups, inheritance and elevation'),text:b('Permissões de objetos podem chegar por grupos e herança. Confira acesso efetivo. Use conta padrão no cotidiano e avalie a origem e a finalidade de pedidos de elevação.','Object permissions may come through groups and inheritance. Check effective access. Use a standard account for daily tasks and evaluate the source and purpose of elevation requests.'),example:b('Remover o acesso direto de Orion pode não retirar o acesso herdado do grupo. Um instalador pedir administrador não prova que seja confiável.','Removing Orion’s direct access may not remove inherited group access. An installer asking for administrator privileges does not prove it is trustworthy.')}
],checklist:[b('Conceda só os acessos exigidos pela tarefa.','Grant only the access required by the task.'),b('Confira identidade, grupo, herança e o efeito real.','Check identity, group, inheritance and the actual effect.'),b('Verifique a necessidade e a origem antes de elevar.','Verify need and source before elevating.')],quiz:{prompt:b('Nova é dona do arquivo e também pertence ao grupo equipe. O modo é ---r----- (040). Na bancada sem privilégios especiais, ela pode ler?','Nova owns the file and also belongs to the team group. The mode is ---r----- (040). In the workbench without special privileges, may she read?'),options:[b('Sim, as classes se somam.','Yes, the classes add together.'),b('Não; a classe do dono corresponde a Nova e não permite leitura.','No; the owner class matches Nova and does not allow Read.'),b('Sim, o nome da dona garante todos os bits.','Yes, the owner’s name guarantees every bit.')],correct:1,feedback:[b('As classes não se somam. Como Nova é dona, a verificação usa a primeira classe, que não tem r.','The classes do not add together. Because Nova owns the file, the check uses the first class, which has no r.'),b('Isso. Mesmo no grupo equipe, Nova usa a classe do dono; sem r, a leitura é bloqueada neste modelo.','Correct. Even in the team group, Nova uses the owner class; without r, Read is blocked in this model.'),b('Ser dono não equivale a ter todos os acessos concedidos. O exemplo exclui privilégios especiais.','Ownership is not equivalent to having every access granted. This example excludes special privileges.')]},sources:[{label:'Linux man-pages · permissões e caminhos',url:'https://man7.org/linux/man-pages/man7/path_resolution.7.html'},{label:'Linux man-pages · modos de arquivo',url:'https://man7.org/linux/man-pages/man2/chmod.2.html'},{label:'Microsoft · controle de acesso',url:'https://learn.microsoft.com/en-us/windows/security/identity-protection/access-control/access-control'},{label:'Microsoft · UAC',url:'https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/how-it-works'}]};
