import { describe, it, expect } from 'vitest';
import { simulateForm, programmingQuestion } from './programming';
import { initial, normalizeSave, reward } from './core';
import { canStudyChallenge, lessonMission } from './lessons';
describe('secure registration model',()=>{
 it('accepts valid requests while rejecting type, range and unexpected choice before writing',()=>{expect(simulateForm('valid',true,true,true).saved).toBe(true);for(const id of ['type','range','choice']){expect(simulateForm(id,true,true,true).outcome).toBe('rejected');expect(simulateForm(id,true,true,true).saved).toBe(false);expect(simulateForm(id,false,true,true).saved).toBe(true)}});
 it('does not falsely confirm failed writes and separates public errors from minimal logs',()=>{const r=simulateForm('failure',true,true,true);expect(r.saved).toBe(false);expect(r.outcome).toBe('failed');expect(r.message.pt).toContain('DEMO-019');expect(r.log).toContain('storage_unavailable');expect(r.log).not.toMatch(/senha|token|request_body|exception/);expect(simulateForm('failure',true,false,false).message.pt).toContain('credencial');expect(simulateForm('failure',true,false,false).log).toContain('token')});
 it('keeps diagnosis failures separate from invalid-request rejection',()=>{expect(simulateForm('range',true,false,true).log).toContain('reason=schema');expect(simulateForm('valid',true,true,true).log).toContain('reason=ok')});
 it('uses distinct difficulty scenarios with bilingual explanations and hints',()=>{for(const kind of ['boundary','rules','error','log'] as const){const prompts=[];for(const d of ['easy','normal','hard'] as const){const q=programmingQuestion(kind,d);prompts.push(q.prompt.pt);expect(q.options[q.correct].en).toBeTruthy();expect(q.explain.pt).toBeTruthy();expect(q.hint.en).toBeTruthy()}expect(new Set(prompts).size).toBe(3)}});
 it('gates mission and reinforcement and migrates v13 without farming XP',()=>{for(const id of ['m19','s19a','s19b'])expect(lessonMission(id)).toBe('m19');expect(canStudyChallenge('m19',{},false)).toBe(false);expect(canStudyChallenge('m19',{m18:75},false)).toBe(true);expect(canStudyChallenge('m19',{},true)).toBe(true);expect(canStudyChallenge('m19',{},true,true)).toBe(false);const old={...reward(initial,'m18',100,'hard',false),version:13,lang:'en',avatar:3,placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:22});s=reward(s,'m19',75,'easy',false);s=reward(s,'m19',100,'hard',false);expect(s.xp).toBe(400);expect(normalizeSave({...s,version:13})).toBeNull();expect(reward(s,'m19',100,'hard',false)).toEqual(s);expect(reward(s,'s19b',50,'hard',true)).toEqual(s);expect(normalizeSave(s)).toEqual(s)});
});
