import { b, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export const formCases=[
 {id:'valid',label:b('Pedido válido','Valid request'),quantity:2,club:'robotics',failure:false},
 {id:'range',label:b('Quantidade fora do limite','Quantity out of range'),quantity:12,club:'robotics',failure:false},
 {id:'type',label:b('Tipo inesperado','Unexpected type'),quantity:'two',club:'robotics',failure:false},
 {id:'choice',label:b('Opção não oferecida','Unoffered choice'),quantity:2,club:'admin',failure:false},
 {id:'failure',label:b('Falha ao salvar','Save failure'),quantity:2,club:'robotics',failure:true}
];
export function simulateForm(id:string,server:boolean,safeError:boolean,minimalLog:boolean){
 const c=formCases.find(c=>c.id===id)||formCases[0];
 const valid=typeof c.quantity==='number'&&Number.isInteger(c.quantity)&&c.quantity>=1&&c.quantity<=3&&['robotics','art'].includes(c.club);
 const rejected=server&&!valid;const failed=!rejected&&c.failure;const outcome=rejected?'rejected':failed?'failed':'saved';
 return {valid,outcome,saved:outcome==='saved',message:rejected?b('Revise quantidade (inteiro de 1 a 3) e clube (robotics/art).','Check quantity (integer from 1 to 3) and club (robotics/art).'):failed?safeError?b('Não foi possível concluir. Use a referência DEMO-019 no suporte.','Could not complete. Use reference DEMO-019 with support.'):b('Erro interno: caminho do banco e credencial de conexão expostos [fictícios].','Internal error: database path and connection credential exposed [fictional].'):b('Inscrição salva no modelo.','Registration saved in the model.'),log:minimalLog?`event=registration outcome=${outcome} ref=DEMO-019 reason=${rejected?'schema':failed?'storage_unavailable':'ok'}`:'request_body=[nome, e-mail, senha e token fictícios] exception=[detalhes internos]'};
}
const make=(p:[string,string],o:[string,string][],correct:number,why:[string,string],hint:[string,string])=>q(...p,o,correct,why,hint);
export function programmingQuestion(kind:'boundary'|'rules'|'error'|'log',d:Difficulty):Question{
 if(kind==='boundary')return make(d==='easy'?['O formulário só verifica quantidade no navegador. O que falta?','The form checks quantity only in the browser. What is missing?']:d==='normal'?['Uma requisição chega diretamente ao servidor, sem passar pela tela. Onde aplicar as regras?','A request reaches the server directly without passing through the screen. Where should rules be enforced?']:['Um serviço interno envia quantidade=12 ao endpoint que aceita 1–3. A origem interna e o HTTPS permitem dispensar validação?','An internal service sends quantity=12 to an endpoint accepting 1–3. Do internal origin and HTTPS allow skipping validation?'],[['Manter feedback na tela e validar novamente no servidor antes de processar.','Keep screen feedback and validate again on the server before processing.'],['Confiar na tela ou no serviço interno; ambos usam HTTPS.','Trust the screen or internal service; both use HTTPS.'],['Salvar primeiro e validar somente no relatório final.','Save first and validate only in the final report.']],0,['A tela ajuda você a corrigir erros cedo, mas pode ser contornada. O servidor aplica as regras antes de usar os dados, inclusive de integrações internas. HTTPS protege transporte, não a validade do pedido.','The screen helps you fix mistakes early but can be bypassed. The server enforces rules before using data, including internal integration data. HTTPS protects transport, not request validity.'],['Quem decide de fato se o pedido será processado?','Who actually decides whether the request is processed?']);
 if(kind==='rules')return make(d==='easy'?['A inscrição aceita de 1 a 3 vagas. Recebe 12. Qual regra resolve?','Registration accepts 1 to 3 places. It receives 12. Which rule solves this?']:d==='normal'?['Quantidade="2x" e clube="admin" chegaram apesar do menu da tela. Qual plano respeita o contrato?','Quantity="2x" and club="admin" arrived despite the screen menu. Which plan respects the contract?']:['O pedido tem quantidade=2, clube=robotics e campo extra role=admin. Qual contrato evita aceitar privilégios enviados pelo cliente?','The request has quantity=2, club=robotics and an extra role=admin field. Which contract avoids accepting client-supplied privileges?'],[['Converter qualquer texto em número e copiar todos os campos.','Convert any text to a number and copy all fields.'],['Definir campos previstos, tipo inteiro, limite 1–3 e clubes permitidos; rejeitar o pedido inválido antes de salvar.','Define intended fields, integer type, range 1–3 and allowed clubs; reject invalid requests before saving.'],['Retirar pontuação dos nomes e aceitar qualquer quantidade.','Remove punctuation from names and accept any quantity.']],1,['Formato e sentido precisam combinar: ser um número não basta se está fora do limite. Menus podem ser contornados; campos extras não devem conceder privilégios. Nomes legítimos podem ter acentos e apóstrofos.','Format and meaning must match: being a number is insufficient outside the range. Menus can be bypassed; extra fields must not grant privileges. Legitimate names may have accents and apostrophes.'],['Separe tipo, intervalo, opções e campos que a operação realmente aceita.','Separate type, range, choices and fields the operation actually accepts.']);
 if(kind==='error')return make(d==='easy'?['O banco está indisponível. O que mostrar ao estudante?','The database is unavailable. What should the student see?']:d==='normal'?['Salvar falhou e a exceção contém caminho interno e credencial. Qual resposta é útil e segura?','Saving failed and the exception contains an internal path and credential. Which response is useful and safe?']:['A gravação falhou antes de confirmar a inscrição. A equipe quer retornar sucesso para reduzir chamados. Qual alternativa preserva a verdade e a segurança?','Writing failed before confirming registration. The team wants to return success to reduce support tickets. Which alternative preserves truth and security?'],[['Mostrar toda a exceção e a credencial para o aluno diagnosticar.','Show the full exception and credential for the student to diagnose.'],['Informar sucesso mesmo sem confirmação.','Report success even without confirmation.'],['Informar que não concluiu, oferecer referência de suporte e registrar contexto controlado sem segredos.','Say it did not complete, offer a support reference and record controlled context without secrets.']],2,['Uma falha precisa interromper este fluxo sem inventar sucesso. O aluno recebe uma orientação clara; a equipe investiga pelo identificador. Credenciais, stack traces e caminhos internos não pertencem à resposta pública.','A failure must stop this flow without inventing success. The student receives clear guidance; the team investigates by identifier. Credentials, stack traces and internal paths do not belong in the public response.'],['O aluno precisa saber o resultado e o próximo passo, não os segredos do servidor.','The student needs the outcome and next step, not server secrets.']);
 return make(d==='easy'?['Qual registro ajuda a investigar uma inscrição rejeitada sem guardar senha?','Which record helps investigate rejected registration without storing passwords?']:d==='normal'?['O suporte precisa relacionar o erro visto pelo aluno ao evento interno. O que registrar?','Support must relate the error seen by the student to the internal event. What should be logged?']:['A entrada contém quebras de linha e o corpo inclui token. Como registrar a falha sem criar eventos falsos ou expor segredos?','Input contains line breaks and the body includes a token. How should failure be logged without creating fake events or exposing secrets?'],[['Evento, resultado, horário e referência; campos estruturados/controlados, sem senha/token/corpo completo, com acesso e retenção definidos.','Event, outcome, time and reference; structured/controlled fields without password/token/full body, with defined access and retention.'],['Corpo completo e senha, porque logs são sempre privados.','Full body and password because logs are always private.'],['Somente “deu erro”, sem contexto nem referência.','Only “error happened”, without context or reference.']],0,['Logs precisam de contexto suficiente e proteção. Evite segredos e dados pessoais desnecessários; trate caracteres de controle de entradas antes de registrar. A referência liga as duas visões sem copiar o pedido inteiro.','Logs need sufficient context and protection. Avoid secrets and unnecessary personal data; handle input control characters before logging. A reference links the two views without copying the entire request.'],['Investigar não exige reproduzir todos os dados que o aluno enviou.','Investigation does not require reproducing every submitted field.']);
}
export const programmingQuestions=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,['boundary','rules','error'].map(k=>programmingQuestion(k as 'boundary'|'rules'|'error',d))])) as Record<Difficulty,Question[]>;
export const programmingReview=review(['O servidor valida matrícula=123 e quantidade=2. Isso permite abrir as notas de qualquer aluno e inserir o nome diretamente numa consulta SQL?','The server validates student ID=123 and quantity=2. Does this allow reading any student’s grades and inserting the name directly into an SQL query?'],[['Sim: dados válidos autorizam a operação inteira.','Yes: valid data authorizes the entire operation.'],['Não: verificar permissão para o recurso e usar consultas parametrizadas; validação de campos atende a outro objetivo.','No: check resource permission and use parameterized queries; field validation serves another purpose.'],['Basta bloquear apóstrofos em todos os nomes.','Blocking apostrophes in every name is sufficient.'],['HTTPS substitui os três controles.','HTTPS replaces all three controls.']],1,[['Validação confere o contrato, não a permissão de quem pede.','Validation checks the contract, not requester permission.'],['Você separou validade, autorização e uso seguro no banco. Para exibir texto, também é preciso codificação adequada ao contexto.','You separated validity, authorization and safe database use. Displaying text also needs context-appropriate encoding.'],['Isso prejudica nomes legítimos e não substitui parametrização.','This harms legitimate names and does not replace parameterization.'],['Proteção do transporte não define acesso nem como o servidor usa os dados.','Transport protection defines neither access nor how the server uses data.']]);
export const programmingFollowup=review(['Salvar falhou. A resposta oculta a senha, mas o log copia o corpo completo com token e usa texto livre enviado pelo aluno. Qual revisão resolve os dois riscos?','Saving failed. The response hides the password, but the log copies the full body with a token and uses student-supplied free text. Which revision addresses both risks?'],[['Somente esconder o log no menu.','Only hide the log in the menu.'],['Devolver sucesso e manter o log completo.','Return success and keep the full log.'],['Remover tokens e dados desnecessários, usar eventos estruturados com referência e tratar caracteres de controle; informar falha sem detalhes internos.','Remove tokens and unnecessary data, use structured events with a reference and handle control characters; report failure without internal details.'],['Desligar toda observabilidade permanentemente.','Permanently disable all observability.']],2,[['Logs podem ser acessados por pessoas ou sistemas; esconder a interface não elimina o conteúdo sensível.','People or systems may access logs; hiding the interface does not remove sensitive content.'],['Isso cria uma confirmação falsa e mantém a exposição no registro.','This creates false confirmation and keeps the log exposure.'],['O suporte conserva contexto útil, sem transformar logs em cópia de segredos nem aceitar linhas falsas de evento.','Support retains useful context without turning logs into a secret copy or accepting forged event lines.'],['É possível reduzir dados e proteger registros sem perder todo o contexto de investigação.','You can minimize data and protect logs without losing all investigation context.']]);
