import { describe, it, expect } from 'vitest';
import { flows, flowAllowed, rulesCorrect, flowTask, segmentScore } from './segmentation';
import { initial, normalizeSave, reward } from './core';
import { modules, questionsFor } from './curriculum';
import { lessonMission, canStudyChallenge } from './lessons';
describe('segmentation and Act 03',()=>{
 it('denies unknown or unselected exact directional flows',()=>{expect(flowAllowed(['staff-web'],'staff-web')).toBe(true);expect(flowAllowed(['staff-web'],'data-staff')).toBe(false);expect(flowAllowed(['unknown'],'unknown')).toBe(false);expect(flowAllowed([],'staff-web')).toBe(false)});
 it('requires supplied recognized state and an authorized original connection for return',()=>{expect(flowAllowed(['staff-web'],'staff-web','reply',false)).toBe(false);expect(flowAllowed(['staff-web'],'staff-web','reply',true)).toBe(true);expect(flowAllowed([],'staff-web','reply',true)).toBe(false);expect(flowAllowed(['staff-web'],'data-staff','new',true)).toBe(false)});
 it('requires all necessary rules without extras, unknown or duplicate flows',()=>{for(const d of ['easy','normal','hard'] as const){const required=flowTask(d).required;expect(rulesCorrect(required,required)).toBe(true);expect(rulesCorrect([...required].reverse(),required)).toBe(true);expect(rulesCorrect([],required)).toBe(false);expect(rulesCorrect([...required,'guest-db'],required)).toBe(false);expect(rulesCorrect([...required,required[0]],required)).toBe(false);expect(required.every(id=>flows.some(f=>f.id===id))).toBe(true)}});
 it('keeps public catalog and internal portal reinforcement purposes distinct',()=>{expect(flowTask('easy',0).required).toEqual(['guest-web']);expect(flowTask('easy',1).required).toEqual(['staff-web','app-db']);expect(segmentScore([true,true,false,true])).toBe(75);expect(segmentScore([true,false])).toBe(50)});
 it('adds a separate common core without expanding fundamentals or assessment',()=>{expect(modules.filter(m=>(m.act||1)===1)).toHaveLength(7);expect(modules.filter(m=>m.act===2)).toHaveLength(7);expect(modules.filter(m=>m.act===3&&!m.track).map(m=>m.id)).toEqual(['m15','m16','m17','m18','m19','m20']);expect(questionsFor('placement','easy')).toHaveLength(7);expect(canStudyChallenge('m15',{},false)).toBe(true);expect(canStudyChallenge('m15',{},true,true)).toBe(false);for(const id of ['m15','s15a','s15b'])expect(lessonMission(id)).toBe('m15')});
 it('migrates v9 with unchanged identity and awards only best reward differences',()=>{const old={...reward(initial,'m14',100,'hard',false),version:9,avatar:3,lang:'en',placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:21});s=reward(s,'m15',75,'easy',false);s=reward(s,'m15',100,'hard',false);s=reward(s,'s15a',100,'easy',true);expect(s.xp).toBe(450);expect(reward(s,'s15b',50,'hard',true)).toEqual(s);expect(reward(s,'m15',100,'hard',false)).toEqual(s);expect(normalizeSave({...s,version:9})).toBeNull();expect(normalizeSave(s)).toEqual(s)});
});
