import { describe,it,expect } from 'vitest';
import { newTowerGame,configureTower,startTowerWave,towerTick,towerAdvance,towerSummary,towerResult,towerMatches,routePoint } from './towerDefense';
import { initial,reward,normalizeSave, type Difficulty } from './core';
import { modules } from './curriculum';
function finish(s:ReturnType<typeof newTowerGame>){let guard=0;while(s.phase!=='finished'&&guard++<2000){if(s.phase==='planning')s=startTowerWave(s);s=towerTick(s)}expect(guard).toBeLessThan(2000);return s;}
describe('network Tower Defense',()=>{
 it('round trips the full campaign plus both action rewards at the new cap',()=>{let s=initial;for(const m of modules){s=reward(s,m.id,100,'hard',false);for(const letter of ['a','b'])s=reward(s,`s${Number(m.label)}${letter}`,100,'hard',true)}s=reward(s,'a1',100,'hard',false);s=reward(s,'a1s',100,'hard',true);expect(s.xp).toBe(7750);expect(normalizeSave(JSON.parse(JSON.stringify(s)))).toEqual(s)});
 it.each(['easy','normal','hard'] as Difficulty[])('protects service and routes unknown TLS without declaring it malicious in %s',d=>{let s=newTowerGame(d);s=configureTower(s,0,'firewall');s=configureTower(s,1,'signature');s=configureTower(s,2,'review');s=finish(s);expect(s.events).toHaveLength(21);expect(new Set(s.events.map(e=>e.id)).size).toBe(21);expect(s.health).toBe(100);expect(towerSummary(s)).toMatchObject({score:100,falsePositives:0,missed:0});expect(s.events.filter(e=>e.type==='unknown').every(e=>e.outcome==='reviewed')).toBe(true);expect(towerResult(s).passed).toBe(true)});
 it('penalizes broad blocking of legitimate traffic and unreviewed unknowns',()=>{let s=configureTower(newTowerGame('normal',true),0,'firewall',true);s=finish(s);expect(towerSummary(s)).toMatchObject({score:33,falsePositives:3,missed:1});expect(s.events.find(e=>e.type==='unknown')!.outcome).toBe('unreviewed');expect(towerResult(s).xp).toBe(0);expect(s.health).toBe(100)});
 it('distinguishes missed threats from unconfirmed transfers and never completes early',()=>{let s=newTowerGame('easy',true);expect(towerResult(s)).toMatchObject({passed:false,xp:0});s=finish(s);expect(s.health).toBe(60);expect(towerSummary(s)).toMatchObject({score:50,missed:3,delivered:3});expect(towerResult(s).passed).toBe(false)});
 it('enforces budget, refunds replacements, rejects invalid slots and finishes deterministically',()=>{let s=newTowerGame('hard');for(let i=0;i<3;i++)s=configureTower(s,i,'firewall');expect(s.credits).toBe(0);expect(configureTower(s,3,'review')).toBe(s);expect(configureTower(s,4,'review')).toBe(s);s=configureTower(s,0,'review');expect(s.credits).toBe(0);s=configureTower(s,1,null);expect(s.credits).toBe(25);expect(towerTick(s)).toBe(s);const a=startTowerWave(s);expect(startTowerWave(a)).toBe(a);let b=a;for(let i=0;i<10;i++)b=towerTick(b);expect(towerAdvance(a)).toEqual(b);const done=finish(s);expect(towerTick(done)).toBe(done);expect(configureTower(done,0,null)).toBe(done)});
 it('limits defenses to observable supplied conditions',()=>{const p={id:1,type:'unknown' as const,position:0,checks:0};expect(towerMatches({slot:0,type:'signature',broad:false,cooldown:0},p)).toBe(false);expect(towerMatches({slot:0,type:'review',broad:false,cooldown:0},p)).toBe(true);expect(routePoint(0)).toEqual({x:30,y:140});expect(routePoint(1100)).toEqual({x:770,y:140})});
 it('migrates v18 and pays only reward improvements with a separate short-mode cap',()=>{const old={...reward(initial,'m23',100,'easy',false),version:18,avatar:3,placement:true};let s=normalizeSave(old)!;expect(s).toEqual({...old,version:22});s=reward(s,'a1',100,'easy',false);expect(s.xp).toBe(200);expect(reward(s,'a1',100,'easy',false)).toEqual(s);s=reward(s,'a1',100,'hard',false);expect(s.xp).toBe(300);s=reward(s,'a1s',100,'hard',true);expect(s.xp).toBe(350);expect(normalizeSave(s)).toEqual(s);expect(normalizeSave({...s,version:18})).toBeNull();expect(normalizeSave({...s,xp:450,earned:{...s.earned,a1s:150}})).toBeNull();expect(reward(s,'a1s',100,'hard',false)).toEqual(s);expect(reward(s,'a1',100,'hard',true)).toEqual(s);expect(reward(s,'a1s',50,'hard',true)).toEqual(s);expect(reward(s,'a3',100,'hard',false)).toEqual(s)});
});
