import { useEffect, useRef, useState } from 'react';
import { useSave, type Difficulty } from './core';
import { CloudDecision } from './CloudGames';
import { conversations, trafficRows, trafficAssessment, trafficQuestion, type Direction, type TrafficKind } from './traffic';
export function TrafficLessonDemo(){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const [id,setId]=useState('portal');const [direction,setDirection]=useState<Direction>('both');const [feed,setFeed]=useState(true);const [verified,setVerified]=useState(false);
 const c=conversations.find(c=>c.id===id)!;const rows=trafficRows(id,direction,feed);const assessment=trafficAssessment(id,feed,verified);
 return <div className="bt-board traffic-board"><h2>{tx('Bancada de tráfego · Leia a conversa','Traffic bench · Read the conversation')}</h2><p>{tx('Você observa quatro conversas fictícias na janela 10:00–10:01 UTC. Cada linha resume bytes de uma direção; não é um pacote individual. Selecione uma conversa e compare os dois sentidos.','You observe four fictional conversations during 10:00–10:01 UTC. Each row summarizes bytes in one direction; it is not an individual packet. Select a conversation and compare both directions.')}</p>
 <label className="pg-field">{tx('Conversa de teste','Test conversation')}<select value={id} onChange={e=>setId(e.target.value)}>{conversations.map(c=><option key={c.id} value={c.id}>{c.name[lang]}</option>)}</select></label>
 <label className="pg-field">{tx('Filtro de exibição','Display filter')}<select value={direction} onChange={e=>setDirection(e.target.value as Direction)}><option value="both">{tx('Estação como origem OU destino','Workstation as source OR destination')}</option><option value="source">{tx('Somente origem na estação','Workstation source only')}</option><option value="destination">{tx('Somente destino na estação','Workstation destination only')}</option></select></label>
 <code className="traffic-filter">{direction==='both'?'ip.addr':direction==='source'?'ip.src':'ip.dst'} == {c.client}</code><p>{tx('Expressão ilustrativa do Wireshark, aplicada aqui somente aos resumos da conversa selecionada. Um filtro de exibição oculta linhas; não apaga a captura.','Illustrative Wireshark expression, applied here only to the selected conversation’s summaries. A display filter hides rows; it does not erase the capture.')}</p>
 <label className="lesson-toggle"><input type="checkbox" checked={feed} onChange={e=>setFeed(e.target.checked)}/>{tx('Coleta funcionando nesta janela','Collection working in this window')}</label>
 <div className={'traffic-route '+(!feed?'traffic-off':'')} aria-hidden="true"><span>PC</span><div><i/><b>→</b><b>←</b></div><span>{c.protocol}</span></div>
 <div role="status" className="lesson-observation"><strong>{feed?tx(`${rows.length} de 2 direções visíveis nesta conversa`,`${rows.length} of 2 directions visible in this conversation`):tx('Coleta ausente · não avaliável','Missing collection · cannot assess')}</strong><p>{feed?tx('O conjunto mantém oito resumos no total. A seleção e o filtro só mudam a visão. Não generalize uma conversa para toda a rede.','The dataset retains eight summaries in total. Selection and filtering only change the view. Do not generalize one conversation to the whole network.'):tx('Zero linhas nesta simulação significa falta de dados, não ausência de tráfego. Registros de janelas anteriores devem ser preservados.','Zero rows in this simulation means missing data, not no traffic. Records from earlier windows should be preserved.')}</p></div>
 <div className="traffic-rows">{rows.map((r,i)=><article key={i}><strong>{r.source} : {r.sourcePort}</strong><span>→</span><strong>{r.destination} : {r.destinationPort}</strong><p>{c.transport} · {c.protocol} · {r.bytes.toLocaleString(lang==='pt'?'pt-BR':'en-US')} {tx('bytes na janela de 60 s','bytes in the 60 s window')}</p></article>)}</div>
 {feed&&<div className="lesson-observation"><h3>{tx('Contexto e limites','Context and limits')}</h3><p>{c.context[lang]}</p>{c.protocol==='TLS'&&<p>{tx('TLS foi identificado pelo sensor fictício, não apenas pela porta 443. Sem descriptografia, a bancada não mostra nome, página, arquivo ou conteúdo enviado.','The fictional sensor identified TLS, not just port 443. Without decryption, the bench does not show a sent name, page, file or content.')}</p>}</div>}
 {id==='backup'&&<label className="lesson-toggle"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>{tx('Conferir B-17: estação .30, destino .40, backup e janela 10:00–10:01 UTC','Verify B-17: workstation .30, destination .40, backup and 10:00–10:01 UTC window')}</label>}
 <div className="bt-assessment" role="status"><strong>{tx('Conclusão provisória','Provisional conclusion')}</strong><p>{assessment==='gap'?tx('Lacuna de visibilidade. Verifique sensor, janela e outras fontes antes de concluir.','Visibility gap. Check sensor, window and other sources before concluding.'):assessment==='authorized'?tx('O contexto verificado corresponde a este backup. Não autoriza a outra transferência nem toda atividade futura da estação.','Verified context matches this backup. It does not authorize the other transfer or all future workstation activity.'):assessment==='investigate'?tx('Ainda precisa de contexto. Correlacione destino, processo, responsável e autorização. Volume alto sozinho não comprova exfiltração.','Context is still needed. Correlate destination, process, owner and authorization. High volume alone does not prove exfiltration.'):tx('Destino compatível com o inventário disponível. Isso não comprova conteúdo seguro nem ausência de outros problemas.','Destination matches available inventory. This does not prove safe content or absence of other problems.')}</p></div>
 <button className="secondary" onClick={()=>{setId('portal');setDirection('both');setFeed(true);setVerified(false)}}>{tx('Restaurar bancada','Reset bench')}</button></div>;
}
export function TrafficMission({id,difficulty,onFinish}:{id:string;difficulty:Difficulty;onFinish:(score:number)=>void}){const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;const [stage,setStage]=useState(0);const [scores,setScores]=useState<boolean[]>([]);const heading=useRef<HTMLDivElement>(null);const kinds:TrafficKind[]=id==='s23a'?['direction','visibility']:id==='s23b'?['context','coverage']:['direction','visibility','context','coverage'];const question=trafficQuestion(kinds[stage],difficulty);useEffect(()=>{if(stage){heading.current?.focus();heading.current?.scrollIntoView({block:'start',behavior:'auto'})}},[stage]);function done(ok:boolean){const all=[...scores,ok];if(stage===kinds.length-1)onFinish(Math.round(all.filter(Boolean).length/all.length*100));else{setScores(all);setStage(stage+1)}}return <section className="challenge-panel"><div className="crypto-progress" ref={heading} tabIndex={-1}><span>{tx('BLUE TEAM · TRÁFEGO E VISIBILIDADE','BLUE TEAM · TRAFFIC AND VISIBILITY')}</span><strong>{stage+1}/{kinds.length}</strong></div><div className="bar"><i style={{width:100*(stage+1)/kinds.length+'%'}}/></div><details className="bt-case"><summary>{tx('Abrir bancada de tráfego','Open traffic bench')}</summary><TrafficLessonDemo/></details><details className="lesson-sources"><summary>{tx('Preciso de uma dica','I need a hint')}</summary><p>{question.hint[lang]}</p></details><CloudDecision key={stage} question={question} onFinish={done}/></section>}
