import { describe,it,expect } from 'vitest';
import { conversations,trafficRows,trafficAssessment,trafficQuestion } from './traffic';
import { initial,reward,normalizeSave } from './core';
import { canStudyChallenge,lessonMission } from './lessons';
describe('traffic evidence and coverage',()=>{
 it('reverses endpoints on replies and hides rather than mutates data',()=>{for(const c of conversations){const all=trafficRows(c.id,'both',true);expect(all).toHaveLength(2);expect(trafficRows(c.id,'source',true)).toEqual([all[0]]);expect(trafficRows(c.id,'destination',true)).toEqual([all[1]]);expect(all[1]).toMatchObject({source:c.server,sourcePort:c.port,destination:c.client,destinationPort:c.clientPort});expect(trafficRows(c.id,'both',true)).toEqual(all)}expect(conversations).toHaveLength(4)});
 it('keeps missing collection distinct from authorization and filters',()=>{for(const c of conversations)for(const direction of ['both','source','destination'] as const){expect(trafficRows(c.id,direction,false)).toEqual([]);expect(trafficAssessment(c.id,false,true)).toBe('gap')}});
 it('does not authorize another conversation from a backup ticket or matching bytes',()=>{const upload=conversations.find(c=>c.id==='upload')!;const backup=conversations.find(c=>c.id==='backup')!;expect(upload.sent).toBe(backup.sent);expect(trafficAssessment('backup',true,false)).toBe('investigate');expect(trafficAssessment('backup',true,true)).toBe('authorized');expect(trafficAssessment('upload',true,true)).toBe('investigate');expect(trafficRows('missing','both',true)).toEqual([])});
 it('provides distinct difficulties with metadata and visibility limits',()=>{for(const k of ['direction','visibility','context','coverage'] as const){const qs=(['easy','normal','hard'] as const).map(d=>trafficQuestion(k,d));expect(new Set(qs.map(q=>q.prompt.pt)).size).toBe(3);for(const q of qs){expect(q.options[q.correct].en).toBeTruthy();expect(q.explain.pt).toBeTruthy()}}});
 it('requires the preceding mission and parent for reinforcements',()=>{expect(canStudyChallenge('m23',{},false)).toBe(false);expect(canStudyChallenge('m23',{m22:75},false)).toBe(true);expect(canStudyChallenge('m23',{},true)).toBe(true);expect(canStudyChallenge('m23',{},true,true)).toBe(false);expect(canStudyChallenge('m23',{m23:75},false,true)).toBe(true);for(const id of ['m23','s23a','s23b'])expect(lessonMission(id)).toBe('m23');expect(lessonMission('m023')).toBeNull()});
 it('preserves v17 identity and records, rejecting future IDs in historical saves',()=>{const old={...reward(initial,'m22',100,'hard',false),version:17,lang:'en',avatar:3,placement:true};let save=normalizeSave(old)!;expect(save).toEqual({...old,version:21});save=reward(save,'m23',100,'hard',false);save=reward(save,'s23a',100,'normal',true);expect(save.xp).toBe(450);expect(normalizeSave({...save,version:17})).toBeNull();expect(normalizeSave(save)).toEqual(save);expect(reward(save,'m23',100,'hard',false)).toEqual(save);expect(reward(save,'s23b',50,'hard',true)).toEqual(save);expect(reward(save,'m25',100,'easy',false)).toEqual(save)});
});
