import { b, type Difficulty } from './core';
import { q, type Question } from './content';
import { review } from './reviewQuestions';
export const conversations=[
 {id:'dns',name:b('Consulta DNS','DNS lookup'),client:'192.0.2.25',server:'192.0.2.53',port:53,clientPort:53000,transport:'UDP',protocol:'DNS',sent:90,received:180,context:b('O inventário identifica este servidor como resolvedor da escola. A consulta fictícia é portal.nexus.example; uma resposta DNS não prova que o portal foi acessado.','Inventory identifies this server as the school resolver. The fictional query is portal.nexus.example; a DNS response does not prove the portal was accessed.')},
 {id:'portal',name:b('Portal escolar','School portal'),client:'192.0.2.25',server:'192.0.2.20',port:443,clientPort:51514,transport:'TCP',protocol:'TLS',sent:1200,received:36000,context:b('Destino previsto no inventário. O sensor identificou TLS, mas não fornece conteúdo descriptografado. Não sabemos qual página ou arquivo foi solicitado.','Expected inventory destination. The sensor identified TLS but supplies no decrypted content. We do not know which page or file was requested.')},
 {id:'upload',name:b('Transferência a investigar','Transfer to investigate'),client:'192.0.2.25',server:'203.0.113.80',port:443,clientPort:51515,transport:'TCP',protocol:'TLS',sent:8000000,received:20000,context:b('Destino sem finalidade confirmada no inventário disponível. Consulte responsável, processo da estação e logs do serviço. Pode ser upload legítimo ou indevido; os bytes não identificam o arquivo.','Destination has no confirmed purpose in available inventory. Consult the owner, workstation process and service logs. It may be a legitimate or unauthorized upload; byte counts do not identify the file.')},
 {id:'backup',name:b('Backup com chamado','Backup with ticket'),client:'192.0.2.30',server:'198.51.100.40',port:443,clientPort:51516,transport:'TCP',protocol:'TLS',sent:8000000,received:20000,context:b('Existe chamado B-17. Sua existência sozinha não autoriza toda atividade desta estação; confira a correspondência completa.','Ticket B-17 exists. Its existence alone does not authorize all workstation activity; verify the full match.')}
];
export type Direction='both'|'source'|'destination';
export function trafficRows(id:string,direction:Direction,feed:boolean){const c=conversations.find(c=>c.id===id);if(!c||!feed)return [];const rows=[{source:c.client,sourcePort:c.clientPort,destination:c.server,destinationPort:c.port,bytes:c.sent},{source:c.server,sourcePort:c.port,destination:c.client,destinationPort:c.clientPort,bytes:c.received}];return rows.filter(r=>direction==='both'||(direction==='source'?r.source===c.client:r.destination===c.client));}
export function trafficAssessment(id:string,feed:boolean,verified:boolean){if(!feed)return 'gap';return id==='backup'&&verified?'authorized':id==='upload'||id==='backup'?'investigate':'expected';}
export type TrafficKind='direction'|'visibility'|'context'|'coverage';
const prompts:Record<TrafficKind,[string,string][]>= {
 direction:[['O filtro mostra somente linhas com origem na estação. Como consultar também a resposta?','The filter shows only rows originating at the workstation. How do you also consult the response?'],['A resposta sai do servidor:443 para estação:51514. Por que filtrar só origem na estação esconde metade da conversa?','The response goes from server:443 to workstation:51514. Why does filtering only workstation source hide half the conversation?'],['Um relatório com ip.src == 192.0.2.25 concluiu “nenhum servidor respondeu”. O sensor registrou tráfego nas duas direções. Qual correção testa a conclusão?','A report using ip.src == 192.0.2.25 concluded “no server replied”. The sensor recorded both directions. Which correction tests the conclusion?']],
 visibility:[['O resumo identifica TLS. Você consegue ler o arquivo enviado nesta bancada?','The summary identifies TLS. Can you read the file sent on this bench?'],['A conexão tem TCP, porta 443, identificação TLS e oito milhões de bytes enviados. Qual conclusão os dados sustentam?','The connection has TCP, port 443, identified TLS and eight million sent bytes. Which conclusion do the data support?'],['Sem descriptografia nem logs do aplicativo, o analista chama oito milhões de bytes TLS de “planilha de notas roubada”. Qual revisão respeita a evidência?','Without decryption or app logs, the analyst calls eight million TLS bytes a “stolen grades spreadsheet”. Which revision respects the evidence?']],
 context:[['Um upload e um backup enviam o mesmo volume. O que ajuda a decidir qual investigar?','An upload and a backup send the same volume. What helps decide which to investigate?'],['B-17 coincide com estação, destino, operação e janela do backup. O upload de outra estação não tem finalidade confirmada. Qual prioridade é justificável?','B-17 matches backup workstation, destination, operation and window. Another workstation’s upload has no confirmed purpose. Which priority is justified?'],['Há backup aprovado e transferência não explicada com volume idêntico em 60 segundos. Um pedido propõe excluir todos os IPs que já tiveram chamado. Qual alternativa mantém contexto sem criar ponto cego?','An approved backup and unexplained transfer have identical volume in 60 seconds. A proposal excludes every IP that ever had a ticket. Which alternative preserves context without a blind spot?']],
 coverage:[['Você desligou a coleta. A tabela vazia prova ausência de tráfego?','You turned off collection. Does an empty table prove no traffic?'],['O painel mostra zero linhas após a coleta parar. O que registrar antes de encerrar a investigação?','The panel shows zero rows after collection stops. What should you record before closing the investigation?'],['A análise cobre somente um sensor e uma janela de 60 segundos; a coleta falhou depois. Como relatar o resultado sem generalizar para a escola inteira?','Analysis covers one sensor and a 60-second window; collection then failed. How do you report the result without generalizing to the whole school?']]
};
const choices:Record<TrafficKind,[string,string][]>= {
 direction:[['Ampliar para origem OU destino na estação e comparar a mesma conversa, portas e janela.','Include workstation source OR destination and compare the same conversation, ports and window.'],['Concluir que o servidor está desligado.','Conclude the server is off.'],['Trocar TCP por UDP para criar a resposta.','Change TCP to UDP to create the reply.']],
 visibility:[['A porta 443 prova que o conteúdo é seguro.','Port 443 proves content is safe.'],['O sensor observou metadados e TLS; conteúdo e finalidade exigem outras evidências. Porta sozinha não identifica o protocolo.','The sensor observed metadata and TLS; content and purpose need other evidence. A port alone does not identify the protocol.'],['O volume revela o nome e o conteúdo do arquivo.','Volume reveals the file name and content.']],
 context:[['Bloquear todo volume alto, inclusive o backup aprovado.','Block every large transfer, including approved backup.'],['Excluir todas as conexões de estações com chamado antigo.','Exclude every connection from workstations with old tickets.'],['Correlacionar autorização específica e finalidade; priorizar o caso não explicado, preservando evidências e limites.','Correlate specific authorization and purpose; prioritize the unexplained case, preserving evidence and limits.']],
 coverage:[['Declarar a janela e o ponto de observação, registrar a lacuna, verificar o sensor e buscar fontes complementares.','State the window and observation point, record the gap, check the sensor and seek complementary sources.'],['Registrar zero ataques em toda a escola.','Record zero attacks across the whole school.'],['Apagar a captura anterior porque não representa o período inteiro.','Delete the earlier capture because it does not represent the whole period.']]
};
const why:Record<TrafficKind,[string,string]>={direction:['Origem e destino se invertem na resposta. Filtro de exibição muda o que você vê, não os registros originais. Recupere as duas direções antes de interpretar silêncio.','Source and destination reverse in replies. A display filter changes what you see, not original records. Recover both directions before interpreting silence.'],visibility:['TLS protege o conteúdo em trânsito, mas não confirma finalidade legítima. Aqui não há descriptografia. O protocolo foi fornecido pelo sensor; não foi deduzido só de 443.','TLS protects content in transit but does not confirm legitimate purpose. There is no decryption here. The sensor supplied the protocol; it was not inferred only from 443.'],context:['Mesmo volume pode ocorrer em atividades diferentes. B-17 cobre só a operação correspondente; a transferência não explicada pede contexto, não uma acusação automática de exfiltração.','Identical volume can occur in different activities. B-17 covers only the matching operation; the unexplained transfer needs context, not an automatic exfiltration accusation.'],coverage:['Não coletado é diferente de não observado numa fonte funcional. Filtros, posição do sensor e janela também limitam a conclusão; não preencha a lacuna com uma afirmação de segurança.','Not collected differs from not observed in a working source. Filters, sensor position and window also limit conclusions; do not fill the gap with a safety claim.']};
export function trafficQuestion(k:TrafficKind,d:Difficulty):Question{return q(...prompts[k][{easy:0,normal:1,hard:2}[d]],choices[k],{direction:0,visibility:1,context:2,coverage:0}[k],why[k],['Separe o que foi observado, o que foi filtrado e o que ainda precisa ser confirmado.','Separate what was observed, what was filtered and what still needs confirmation.']);}
export const trafficQuestions=Object.fromEntries((['easy','normal','hard'] as Difficulty[]).map(d=>[d,(['direction','visibility','context'] as TrafficKind[]).map(k=>trafficQuestion(k,d))])) as Record<Difficulty,Question[]>;
export const trafficReview=review(['Uma estação envia 8 MB por TLS em 60 s a destino não confirmado. Um backup aprovado envia o mesmo volume. O relatório usa só ip.src e diz que não houve respostas. Qual revisão é melhor?','A workstation sends 8 MB over TLS in 60 s to an unconfirmed destination. Approved backup sends the same volume. The report uses only ip.src and says there were no replies. Which review is best?'],[['Tratar ambos como exfiltração, pois o volume é igual.','Treat both as exfiltration because volume matches.'],['TLS elimina a necessidade de investigação.','TLS removes the need to investigate.'],['Recuperar ambas as direções, conferir o contexto de cada fluxo e investigar o não explicado sem afirmar qual conteúdo foi enviado.','Recover both directions, check each flow’s context and investigate the unexplained one without claiming which content was sent.'],['Aplicar a autorização do backup à outra estação.','Apply backup authorization to the other workstation.']],2,[['Volume não determina finalidade nem conteúdo.','Volume does not determine purpose or content.'],['Criptografia não garante que a operação foi autorizada.','Encryption does not guarantee an authorized operation.'],['Você corrigiu o filtro e separou metadados de hipótese; ainda precisa de processo, responsável e logs do aplicativo.','You corrected the filter and separated metadata from hypothesis; process, owner and app logs are still needed.'],['A autorização tem escopo específico, não se transfere por semelhança de volume.','Authorization has specific scope; it does not transfer through similar volume.']]);
export const trafficFollowup=review(['A equipe vê nenhuma linha entre 10:01 e 10:02. O sensor parou às 10:01; antes, somente saída de uma estação foi exibida. O inventário reconhece um backup, mas não outra transferência. Como relatar?','The team sees no rows between 10:01 and 10:02. The sensor stopped at 10:01; previously only workstation outbound traffic was displayed. Inventory recognizes a backup but not another transfer. How should this be reported?'],[['Sem respostas nem ataques: o painel estava vazio.','No replies or attacks: the dashboard was empty.'],['Dados insuficientes no período da falha; revisar filtro e cobertura, preservar registros anteriores e correlacionar a transferência sem contexto.','Insufficient data during failure; review filter and coverage, preserve earlier records and correlate the transfer lacking context.'],['O chamado do backup autoriza todo tráfego TLS.','The backup ticket authorizes all TLS traffic.'],['Só ler os bytes já identifica os dados enviados.','Reading bytes alone identifies the sent data.']],1,[['Silêncio pode resultar do filtro ou da coleta ausente.','Silence may result from a filter or missing collection.'],['O relato distingue ausência de observação e falta de visibilidade, sem descartar evidência disponível.','The report distinguishes lack of observation and visibility gaps without discarding available evidence.'],['Confira operação, estação, destino e janela do chamado.','Check ticket operation, workstation, destination and window.'],['Metadados não substituem conteúdo descriptografado ou registros do aplicativo.','Metadata do not replace decrypted content or app logs.']]);
