import { b, xpFor, type Bilingual, type Difficulty, type MinigameResult } from './core';
type Choice={id:string;text:Bilingual;why:Bilingual};
export type Probe={id:string;request:string;response:Bilingual;proof:boolean};
export type CtfCase={id:string;title:Bilingual;brief:Bilingual;lesson:Bilingual;hint:Bilingual;probes:Probe[];causes:Choice[];fixes:Choice[];cause:string;fix:string;flag:string;explanation:Bilingual};
export const ctfCases:CtfCase[]=[
 {id:'documents',title:b('01 · O boletim do colega','01 · A classmate’s report'),brief:b('Você está conectado como Lia (aluna 17). Cada aluno só pode consultar o próprio boletim. Compare o documento autorizado com o de Rui (aluno 18). Os dados são fictícios.','You are signed in as Lia (student 17). Students may only read their own reports. Compare the approved document with Rui’s (student 18). All data are fictional.'),lesson:b('Pense no armário da escola: saber o número de outro armário não dá direito de abri-lo. Autenticação confirma quem é você; autorização decide quais objetos você pode acessar. HTTP 200 significa que houve resposta, não que o acesso era permitido. Aqui a evidência precisa juntar identidade, proprietário e conteúdo retornado.','Think of school lockers: knowing another locker’s number does not give permission to open it. Authentication identifies you; authorization decides which objects you may access. HTTP 200 means a response succeeded, not that access was allowed. Evidence must connect identity, owner and returned content.'),hint:b('Compare GET /reports/17 e /reports/18 na mesma sessão. O proprietário mudou; o usuário não.','Compare GET /reports/17 and /reports/18 in the same session. The owner changed; the user did not.'),probes:[
 {id:'own',request:'GET /reports/17 · session=Lia',response:b('200 OK · owner=17 · Nota fictícia: 8.0. Acesso permitido pela política.','200 OK · owner=17 · Fictional grade: 8.0. Access allowed by policy.'),proof:false},
 {id:'other',request:'GET /reports/18 · session=Lia',response:b('200 OK · owner=18 (Rui) · Nota fictícia: 6.5. Sem compartilhamento autorizado.','200 OK · owner=18 (Rui) · Fictional grade: 6.5. No approved sharing.'),proof:true},
 {id:'missing',request:'GET /reports/99 · session=Lia',response:b('404 Not Found · Documento inexistente. Não comprova controle sobre documentos existentes.','404 Not Found · Document absent. Does not prove control over existing documents.'),proof:false}],
 causes:[{id:'authn',text:b('Lia não foi autenticada','Lia was not authenticated'),why:b('A sessão identifica Lia. A falha é a permissão sobre o objeto de Rui.','The session identifies Lia. The failure is permission on Rui’s object.')},{id:'object',text:b('Falta autorização por objeto (IDOR/BOLA)','Missing object authorization (IDOR/BOLA)'),why:b('A troca de ID devolveu um objeto de outro proprietário sem autorização.','Changing the ID returned another owner’s object without authorization.')},{id:'tls',text:b('O número do boletim deveria usar TLS','The report number should use TLS'),why:b('TLS protege o transporte; não decide quem pode ler o boletim.','TLS protects transport; it does not decide who may read a report.')}],
 fixes:[{id:'hide',text:b('Ocultar o link do boletim alheio','Hide the other report link'),why:b('O servidor ainda atenderia a solicitação direta.','The server would still handle a direct request.')},{id:'server',text:b('No servidor, verificar usuário e permissão para cada boletim','Check user and permission for every report on the server'),why:b('A política precisa ser aplicada a cada objeto solicitado.','Apply the policy to every requested object.')},{id:'random',text:b('Usar IDs aleatórios como único controle','Use random IDs as the only control'),why:b('IDs difíceis de adivinhar ajudam, mas não substituem autorização.','Hard-to-guess IDs help but do not replace authorization.')}],cause:'object',fix:'server',flag:'FLAG{OBJECT_PERMISSION}',explanation:b('Impacto: exposição de nota privada. Correção: verificar propriedade ou compartilhamento permitido antes de devolver o objeto. Reteste Lia→17 (permitido) e Lia→18 (negado sem conteúdo privado). Um 403 ou 404 consistente pode negar o acesso; esconder o botão não basta.','Impact: private grade disclosure. Fix: check ownership or approved sharing before returning the object. Retest Lia→17 (allowed) and Lia→18 (denied without private content). Consistent 403 or 404 responses may deny access; hiding a button is insufficient.')},
 {id:'roles',title:b('02 · A porta da secretaria','02 · The school office door'),brief:b('Lia continua aluna. Somente a secretaria pode ler a lista administrativa de matrículas. O menu oculta essa opção de Lia; confira se o servidor também aplica a regra.','Lia is still a student. Only office staff may read the administrative enrollment list. Lia’s menu hides this option; check whether the server also applies the rule.'),lesson:b('Não mostrar a porta no mapa não é trancá-la. O navegador pertence ao usuário e não é a autoridade de segurança. Controle por função (RBAC) verifica se a função de uma sessão tem a permissão necessária. A diferença para o caso anterior: aqui o recurso é reservado a uma função, não ao dono de um boletim.','Leaving a door off a map does not lock it. The browser belongs to the user and is not the security authority. Role-based access control (RBAC) checks whether a session role has the required permission. Unlike the previous case, the resource belongs to a role rather than an individual report owner.'),hint:b('Compare a lista administrativa como Lia e como secretaria. Menu escondido não comprova negação no servidor.','Compare the administrative list as Lia and office staff. A hidden menu does not prove server-side denial.'),probes:[
 {id:'menu',request:'GET /menu · session=Lia',response:b('200 OK · Menu: meus boletins. Administração oculta.','200 OK · Menu: my reports. Administration hidden.'),proof:false},
 {id:'student-admin',request:'GET /admin/enrollments · session=Lia',response:b('200 OK · role=student · Lista administrativa fictícia: Lia, Rui, Bia.','200 OK · role=student · Fictional admin list: Lia, Rui, Bia.'),proof:true},
 {id:'staff-admin',request:'GET /admin/enrollments · session=office',response:b('200 OK · role=office · Mesma lista. Uso autorizado da secretaria.','200 OK · role=office · Same list. Approved office access.'),proof:false}],
 causes:[{id:'ui',text:b('O menu precisa de uma cor diferente','The menu needs a different color'),why:b('A aparência não restringe o endpoint.','Appearance does not restrict the endpoint.')},{id:'role',text:b('Falta verificação da permissão administrativa no servidor','Missing server-side administrative permission check'),why:b('A sessão student recebeu um recurso reservado à secretaria.','The student session received an office-only resource.')},{id:'all',text:b('Todo HTTP 200 representa uma vulnerabilidade','Every HTTP 200 is a vulnerability'),why:b('A secretaria tem acesso legítimo; status sozinho não prova falha.','Office access is legitimate; status alone does not prove a flaw.')}],
 fixes:[{id:'client',text:b('Confiar no role enviado pelo navegador','Trust the role sent by the browser'),why:b('Um atributo controlado pelo cliente não concede autoridade.','A client-controlled attribute does not grant authority.')},{id:'deny',text:b('Negar por padrão e validar permissão da sessão no endpoint','Deny by default and validate session permission at the endpoint'),why:b('O servidor aplica a permissão obtida de uma sessão confiável.','The server applies permission from a trusted session.')},{id:'url',text:b('Trocar o nome da URL administrativa','Rename the administrative URL'),why:b('Conhecer a URL não deve conceder a permissão.','Knowing a URL must not grant permission.')}],cause:'role',fix:'deny',flag:'FLAG{SERVER_ROLE_CHECK}',explanation:b('Impacto: exposição da lista administrativa a alunos. Correção: centralizar autorização no servidor e negar funções sem permissão. Reteste student→admin (negado), office→admin (permitido) e visitante sem sessão (sem conteúdo). Uma identidade autenticada ainda pode não ter a permissão necessária.','Impact: administrative list disclosed to students. Fix: centralize server-side authorization and deny roles without permission. Retest student→admin (denied), office→admin (allowed) and a visitor without a session (no content). An authenticated identity may still lack the required permission.')},
 {id:'output',title:b('03 · O mural que muda o recado','03 · The noticeboard changes the message'),brief:b('O mural deveria mostrar comentários como texto. Use uma marcação inofensiva para comparar a saída atual com uma saída segura. Este laboratório nunca executa HTML inserido nem scripts.','The noticeboard should display comments as text. Use harmless markup to compare current output with safe output. This lab never executes inserted HTML or scripts.'),lesson:b('É como entregar um bilhete e alguém confundir o que está escrito com uma ordem para montar o mural. <b> é marcação de negrito. Se uma entrada vira HTML, o navegador passa a interpretar estrutura. O experimento só demonstra interpretação de marcação: isso indica uma saída insegura nesse contexto, mas não prova execução de JavaScript nem roubo de sessão.','It is like handing over a note that is mistaken for instructions to build the board. <b> is bold markup. When input becomes HTML, the browser interprets structure. This experiment only demonstrates markup interpretation: it indicates unsafe output in this context but does not prove JavaScript execution or session theft.'),hint:b('Compare a mesma entrada <b>Olá</b> nas duas saídas. No modo seguro, os sinais < e > continuam visíveis como texto.','Compare the same <b>Hello</b> input in both outputs. Safe output keeps < and > visible as text.'),probes:[
 {id:'plain',request:'POST /notice-preview · text=Olá',response:b('200 OK · Entrada: Olá · Saída: Olá. Texto comum não distingue as implementações.','200 OK · Input: Hello · Output: Hello. Plain text does not distinguish implementations.'),proof:false},
 {id:'markup',request:'POST /notice-preview · text=<b>Olá</b>',response:b('200 OK · Entrada: <b>Olá</b> · Saída simulada: Olá em negrito; tags sumiram. Trecho fornecido: preview.innerHTML = comment.','200 OK · Input: <b>Hello</b> · Simulated output: Hello in bold; tags disappeared. Supplied excerpt: preview.innerHTML = comment.'),proof:true},
 {id:'safe',request:'POST /safe-preview · text=<b>Olá</b>',response:b('200 OK · Saída literal: <b>Olá</b>. Trecho fornecido: preview.textContent = comment.','200 OK · Literal output: <b>Hello</b>. Supplied excerpt: preview.textContent = comment.'),proof:false}],
 causes:[{id:'html',text:b('Entrada não confiável vira HTML em uma saída de texto','Untrusted input becomes HTML in a text output'),why:b('O trecho innerHTML e a mudança de apresentação sustentam esse achado.','The innerHTML excerpt and presentation change support this finding.')},{id:'proven-xss',text:b('O teste já provou execução de scripts e roubo de sessão','The test proved script execution and session theft'),why:b('Não houve script. Relate somente o comportamento observado.','There was no script. Report only observed behavior.')},{id:'bold',text:b('Negrito sempre é malicioso','Bold is always malicious'),why:b('A questão é a fronteira entre dado e marcação, não o negrito em si.','The issue is the boundary between data and markup, not bold itself.')}],
 fixes:[{id:'text',text:b('Exibir como texto; se HTML for necessário, sanitizar com política adequada','Render as text; if HTML is needed, sanitize under an appropriate policy'),why:b('Use uma saída de texto segura ou sanitização apropriada ao HTML permitido.','Use a safe text sink or sanitization appropriate to allowed HTML.')},{id:'filter',text:b('Remover só a palavra script','Remove only the word script'),why:b('Uma lista curta de palavras não cobre os contextos de interpretação.','A short word list does not cover interpretation contexts.')},{id:'tls',text:b('Usar HTTPS como única correção','Use HTTPS as the only fix'),why:b('HTTPS protege transporte, não a interpretação no navegador.','HTTPS protects transport, not browser interpretation.')}],cause:'html',fix:'text',flag:'FLAG{DATA_NOT_MARKUP}',explanation:b('Achado: interpretação de HTML em campo destinado a texto, com um sink inseguro fornecido pelo cenário. Não afirme exploração XSS comprovada. Corrija com textContent neste contexto; para HTML permitido, sanitização apropriada. Reteste a marcação como texto literal e preserve comentários comuns. Codificação depende do contexto: texto, atributo, URL e JavaScript exigem decisões distintas.','Finding: HTML interpretation in a text field, with an unsafe sink supplied by the scenario. Do not claim proven XSS exploitation. Fix with textContent in this context; sanitize appropriately when HTML is allowed. Retest markup as literal text and preserve ordinary comments. Encoding is context dependent: text, attributes, URLs and JavaScript require different decisions.')}
];
export type CtfState={difficulty:Difficulty;short:boolean;stage:number;observed:string[];solved:string[];mistakes:number;hints:string[];finished:boolean;feedback:Bilingual|null};
export function newCtf(difficulty:Difficulty,short=false):CtfState{return {difficulty,short,stage:0,observed:[],solved:[],mistakes:0,hints:[],finished:false,feedback:null};}
export function probeCtf(s:CtfState,id:string):CtfState{if(s.finished||!ctfCases[s.stage].probes.some(p=>p.id===id))return s;return {...s,observed:[...new Set([...s.observed,`${s.stage}:${id}`])],feedback:null};}
export function hintCtf(s:CtfState):CtfState{const id=ctfCases[s.stage].id;if(s.finished)return s;return {...s,hints:[...new Set([...s.hints,id])],feedback:ctfCases[s.stage].hint};}
export function submitCtf(s:CtfState,evidence:string,cause:string,fix:string):CtfState{
 if(s.finished)return s;const c=ctfCases[s.stage];const p=c.probes.find(p=>p.id===evidence);
 if(!p||!s.observed.includes(`${s.stage}:${evidence}`))return {...s,feedback:b('Primeiro execute e leia a observação que pretende citar.','First run and read the observation you intend to cite.')};
 const wrong=!p.proof?b('Essa resposta não demonstra a violação descrita. Compare com a política do caso; uma resposta autorizada ou um 404 isolado não bastam.','This response does not demonstrate the stated violation. Compare it with the case policy; an authorized response or isolated 404 is insufficient.'):cause!==c.cause?c.causes.find(x=>x.id===cause)?.why:fix!==c.fix?c.fixes.find(x=>x.id===fix)?.why:null;
 if(!c.causes.some(x=>x.id===cause)||!c.fixes.some(x=>x.id===fix))return {...s,feedback:b('Escolha uma causa e uma correção antes de validar.','Choose a cause and fix before validating.')};
 if(wrong)return {...s,mistakes:s.mistakes+1,feedback:wrong};
 const solved=[...s.solved,c.id];const finished=solved.length===(s.short?1:ctfCases.length);return {...s,solved,finished,stage:finished?s.stage:s.stage+1,feedback:b('Flag validada: evidência, causa e correção coerentes.','Flag validated: consistent evidence, cause and fix.')};
}
export function ctfResult(s:CtfState):MinigameResult{const score=Math.max(0,100-s.mistakes*{easy:3,normal:5,hard:8}[s.difficulty]-s.hints.length*{easy:0,normal:3,hard:5}[s.difficulty]);const passed=s.finished&&score>=70;return {score,xp:passed?xpFor(score,s.difficulty,s.short):0,passed,correct:s.solved.length,total:s.short?1:3,feedback:[b('Uma flag só aparece depois de observar, explicar e corrigir. A nota mede decisões nesta simulação; não certifica um teste de invasão real.','A flag appears only after observing, explaining and fixing. The score measures decisions in this simulation; it does not certify a real penetration test.')]};}
