import DifficultyAssessment, { DifficultyScoreDetails } from './DifficultyAssessment';
import { combineDifficultyScore } from './difficulty';
import './game-ux.css';
import AnswerSelection from './AnswerSelection';
import { useEffect, useRef, useState } from 'react';
import { reward, useSave, type Difficulty } from './core';
import { PixelIcon } from './PixelArt';
import { ctfCases, ctfResult, hintCtf, newCtf, probeCtf, submitCtf } from './webCtf';
export default function WebCtf({difficulty,short,onBack,moving,onTutorial}:{difficulty:Difficulty;short:boolean;onBack:()=>void;moving:boolean;onTutorial:()=>void}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const [analysis,setAnalysis]=useState<number|null>(null);
 const [game,setGame]=useState(()=>newCtf(difficulty,short));const [feedbackKind,setFeedbackKind]=useState<'hint'|'submit'>('submit');const [feedbackError,setFeedbackError]=useState(false);const [probe,setProbe]=useState('');const [evidence,setEvidence]=useState('');const [cause,setCause]=useState('');const [fix,setFix]=useState('');const [findingStep,setFindingStep]=useState(0);const findingHeading=useRef<HTMLHeadingElement>(null);const paid=useRef(false);const stageHeading=useRef<HTMLHeadingElement>(null);
 const c=ctfCases[game.stage],core=ctfResult(game);const score=combineDifficultyScore(core.score,analysis??100,difficulty);const result={...core,score,passed:score>=70,xp:score>=70?Math.round(score/100*(short?50:difficulty==='easy'?100:difficulty==='normal'?150:200)):0};const observation=c.probes.find(p=>p.id===probe);const selectedEvidence=c.probes.find(p=>p.id===evidence);const selectedCause=c.causes.find(x=>x.id===cause);const selectedFix=c.fixes.find(x=>x.id===fix);const observedCount=c.probes.filter(p=>game.observed.includes(`${game.stage}:${p.id}`)).length;const ready=!!evidence&&!!cause&&!!fix;
 const nextAction=observedCount<2?tx('Execute duas solicitações e compare identidade, regra e resposta.','Run two requests and compare identity, policy and response.'):!evidence?tx('Escolha a observação que sustenta seu achado. Um HTTP 200 sozinho não explica a falha.','Choose the observation supporting your finding. An HTTP 200 alone does not explain the flaw.'):!cause?tx('Relacione sua evidência ao controle que falhou.','Connect your evidence to the control that failed.'):!fix?tx('Escolha uma correção que trate a causa e preserve o uso legítimo.','Choose a fix addressing the cause while preserving legitimate use.'):tx('Revise as três escolhas e valide seu achado. Você pode alterar qualquer etapa.','Review your three choices and validate the finding. You can change any step.');
 function goFinding(i:number){setFindingStep(i);requestAnimationFrame(()=>findingHeading.current?.focus())}
 useEffect(()=>{setProbe('');setEvidence('');setCause('');setFix('');setFindingStep(0);stageHeading.current?.focus()},[game.stage,game.finished]);
 useEffect(()=>{if(!game.finished||paid.current||(difficulty!=='easy'&&analysis===null))return;paid.current=true;const store=useSave.getState();store.set(reward(store.save,short?'a2s':'a2',result.score,difficulty,short))},[game.finished,result.score,difficulty,short,analysis]);
 function download(){const text=[tx('Relatório educativo · CTF Web NEXUS','Educational report · NEXUS Web CTF'),`${result.score}/100 · ${difficulty} · ${game.mistakes} ${tx('decisões incorretas','incorrect decisions')} · ${game.hints.length} ${tx('pistas','hints')}`,...ctfCases.filter(c=>game.solved.includes(c.id)).map(c=>`${c.title[lang]}\n${c.flag}\n${c.probes.find(p=>p.proof)!.request}\n${c.probes.find(p=>p.proof)!.response[lang]}\n${c.explanation[lang]}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='CYBER-AGENT-CTF.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className={`action-game ctf-game ${moving?'ctf-moving':''}`}><div className="action-heading"><div><div className="eyebrow">{tx('08 / CTF WEB · PORTAL NEXUS','08 / WEB CTF · NEXUS PORTAL')}</div><h1 tabIndex={-1}>{tx('Investigue. Comprove. Corrija.','Investigate. Prove. Fix.')}</h1><p>{short?tx('Treino curto · 1 caso','Short practice · 1 case'):tx('Operação completa · 3 casos','Full operation · 3 cases')} · {difficulty==='easy'?tx('Iniciante','Beginner'):difficulty==='normal'?tx('Intermediário','Intermediate'):tx('Avançado','Advanced')}</p></div><button className="text-button" onClick={onBack}>{tx('Voltar aos minigames','Back to minigames')}</button></div>
 <div className="game-briefing"><div><span className="eyebrow">{tx('SUA MISSÃO','YOUR MISSION')}</span><p>{tx('Capture cada flag conectando evidência, causa e correção. Compare à vontade: consultar a aula e executar solicitações não descontam pontos.','Capture each flag by connecting evidence, cause and fix. Compare freely: lessons and requests cost no points.')}</p></div><button className="secondary" onClick={onTutorial}>{tx('Tutorial e demonstração','Tutorial and demo')}</button></div>
 <div className="ctf-route" aria-label={tx('Progresso dos casos','Case progress')}>{ctfCases.slice(0,short?1:3).map((caseData,i)=><div key={caseData.id} className={game.solved.includes(caseData.id)?'solved':i===game.stage?'active':''}><PixelIcon type="network" size={28}/><span>{caseData.title[lang]}</span><b>{game.solved.includes(caseData.id)?tx('FLAG CAPTURADA','FLAG CAPTURED'):i===game.stage?tx('INVESTIGAR','INVESTIGATE'):tx('AGUARDANDO','WAITING')}</b></div>)}</div>
 <details className="game-help"><summary>{tx('Laboratório fictício · sem cronômetro · veja o escopo','Fictional lab · no timer · view scope')}</summary><p className="ctf-scope">{tx('Escopo autorizado: somente os três casos fictícios deste painel. As solicitações são escolhas locais, sem acessar servidores. Não há scripts, scanner ou campo para URL externa. Sem cronômetro: você pode consultar a aula e investigar no seu ritmo.','Authorized scope: only the three fictional cases in this panel. Requests are local choices without accessing servers. There are no scripts, scanner or external URL field. No timer: consult the lesson and investigate at your own pace.')}</p></details>
 {!game.finished?<><article className="action-card"><h2 ref={stageHeading} tabIndex={-1}>{c.title[lang]}</h2><p>{c.brief[lang]}</p><details className="td-guide" key={c.id}><summary>{tx('Aula rápida · Entenda antes de investigar','Quick lesson · Understand before investigating')}</summary><p>{c.lesson[lang]}</p><p>{tx('Roteiro: execute as comparações; leia identidade, resposta e regra esperada; selecione a evidência que demonstra a falha; proponha causa e correção. Consultar a aula não reduz a nota.','Workflow: run comparisons; read identity, response and expected rule; select evidence that demonstrates the flaw; propose a cause and fix. Consulting the lesson does not reduce your score.')}</p></details></article>
 <aside className="game-next-action"><strong>{tx('Próxima ação','Next action')}</strong><p>{nextAction}</p></aside><div className="ctf-workbench"><div className="ctf-console"><h2>{tx('1. Observe e compare','1. Observe and compare')}</h2><p>{tx('Cada botão mostra uma resposta simulada. O marcador “observado” ajuda a comparar sem depender da memória.','Each button shows a simulated response. The “observed” marker helps you compare without relying on memory.')}</p>{c.probes.map(p=><button key={p.id} className="ctf-request" aria-pressed={probe===p.id} onClick={()=>{setProbe(p.id);setGame(s=>probeCtf(s,p.id))}}><code>{p.request}</code><span>{probe===p.id?tx('✓ EM LEITURA','✓ READING'):game.observed.includes(`${game.stage}:${p.id}`)?tx('✓ OBSERVADO','✓ OBSERVED'):tx('EXECUTAR','RUN')}</span></button>)}<div className={"ctf-response "+(observation&&/^4\d\d/.test(observation.response[lang])?"error-message":"")} role="status"><strong>{tx('Resposta simulada','Simulated response')}</strong>{observation&&<code className="ctf-response-source">{observation.request}</code>}<p>{observation?.response[lang]||tx('Execute uma solicitação para inspecionar a resposta.','Run a request to inspect its response.')}</p>{observation?.id==='markup'&&<p className="ctf-output"><b>{tx('Olá','Hello')}</b><small>{tx('Representação fixa do resultado; a entrada não é executada.','Fixed representation of the result; input is not executed.')}</small></p>}</div>{observation&&<button className="secondary" onClick={()=>{setEvidence(observation.id);goFinding(0)}}>{tx('Citar esta observação no achado','Cite this observation in the finding')}</button>}<details className="game-help"><summary>{tx('Precisa de pista? Confira o custo antes de pedir','Need a hint? Check the cost before asking')}</summary><p>{tx('Pista por caso:','Hint per case:')} {difficulty==='easy'?tx('gratuita','free'):difficulty==='normal'?'−3':'−5'} {difficulty!=='easy'&&tx('pontos','points')}.</p><button className="secondary" onClick={()=>{setFeedbackKind('hint');setGame(hintCtf(game))}}>{game.hints.includes(c.id)?tx('Rever pista','Review hint'):tx('Pedir pista','Ask for hint')}</button>{game.feedback&&feedbackKind==='hint'&&<p className="td-status" role="status">{game.feedback[lang]}</p>}<p className="ctf-scoring">{tx('Pista única por caso:','One hint per case:')} {difficulty==='easy'?tx('gratuita','free'):difficulty==='normal'?'−3':'−5'} {difficulty!=='easy'&&tx('pontos','points')}. {tx('Decisão incorreta:','Incorrect decision:')} −{difficulty==='easy'?3:difficulty==='normal'?5:8} {tx('pontos. Repetir a pista não desconta novamente.','points. Reviewing a hint does not deduct again.')}</p></details></div>
 <form className="ctf-finding" onSubmit={e=>{e.preventDefault();if(findingStep!==2||!ready)return;setFeedbackKind('submit');const next=submitCtf(game,evidence,cause,fix);setFeedbackError(next.solved.length===game.solved.length);setGame(next)}}>
 <h2>{tx('2. Construa seu achado','2. Build your finding')}</h2><p>{tx('Uma decisão por vez. As escolhas ficam guardadas enquanto você consulta as outras etapas.','One decision at a time. Choices stay saved while you consult other steps.')}</p>
 <nav className="game-step-nav" aria-label={tx('Etapas do achado','Finding steps')}>{[tx('Evidência','Evidence'),tx('Causa','Cause'),tx('Correção','Fix')].map((label,i)=><button type="button" className="secondary" key={i} aria-current={findingStep===i?'step':undefined} onClick={()=>goFinding(i)}><span>{i+1}</span>{label}<small>{[evidence,cause,fix][i]?tx('✓ escolhida','✓ chosen'):tx('a escolher','to choose')}</small></button>)}</nav>
 <section className="ctf-finding-panel"><h3 ref={findingHeading} tabIndex={-1}>{findingStep===0?tx('Qual observação demonstra a falha?','Which observation demonstrates the flaw?'):findingStep===1?tx('Por que esse resultado aconteceu?','Why did this result occur?'):tx('Qual correção atua na causa?','Which fix addresses the cause?')}</h3>
 {findingStep===0?<><p>{tx('Cite uma resposta que você já executou. Compare o resultado com a regra, não apenas com o código HTTP.','Cite a response you have run. Compare the result with the policy, not only the HTTP code.')}</p><label>{tx('Evidência observada','Observed evidence')}<select aria-label={tx('Evidência observada','Observed evidence')} value={evidence} onChange={e=>setEvidence(e.target.value)}><option value="">{tx('Escolha uma observação executada','Choose an executed observation')}</option>{c.probes.map(p=><option disabled={!game.observed.includes(`${game.stage}:${p.id}`)} value={p.id} key={p.id}>{p.request}</option>)}</select></label>{selectedEvidence&&<div className="ctf-evidence-reference"><strong>{tx('Resposta citada','Cited response')}</strong><p>{selectedEvidence.response[lang]}</p></div>}</>:<><p>{findingStep===1?tx('Use a evidência citada para identificar o controle que faltou.','Use your cited evidence to identify the missing control.'):tx('A solução deve corrigir o controle e manter funcionando o acesso autorizado.','The solution should fix the control while keeping authorized access working.')}</p><fieldset><legend>{findingStep===1?tx('Escolha a causa','Choose the cause'):tx('Escolha a correção','Choose the fix')}</legend>{(findingStep===1?c.causes:c.fixes).map(x=><label className={'ctf-choice '+((findingStep===1?cause:fix)===x.id?'is-selected':'')} key={x.id}><input type="radio" name={findingStep===1?'ctf-cause':'ctf-fix'} value={x.id} checked={(findingStep===1?cause:fix)===x.id} onChange={()=>findingStep===1?setCause(x.id):setFix(x.id)}/><span>{x.text[lang]}</span><AnswerSelection selected={(findingStep===1?cause:fix)===x.id}/></label>)}</fieldset>{selectedEvidence&&<details className="game-help"><summary>{tx('Consultar minha evidência','Consult my evidence')}</summary><code>{selectedEvidence.request}</code><p>{selectedEvidence.response[lang]}</p></details>}</>}
 <div className="learning-actions">{findingStep>0&&<button type="button" className="secondary" onClick={()=>goFinding(findingStep-1)}>{tx('Etapa anterior','Previous step')}</button>}{findingStep<2&&<button type="button" className="primary" disabled={!([evidence,cause][findingStep])} onClick={()=>goFinding(findingStep+1)}>{findingStep===0?tx('Continuar para causa','Continue to cause'):tx('Continuar para correção','Continue to fix')}</button>}</div>
 </section>
 {findingStep===2&&<><details className="game-help"><summary>{tx('Revisar minhas três escolhas','Review my three choices')}</summary><dl className="game-finding-summary"><dt>{tx('Evidência','Evidence')}</dt><dd>{selectedEvidence?.request||tx('Ainda não escolhida','Not chosen yet')}</dd><dt>{tx('Causa','Cause')}</dt><dd>{selectedCause?.text[lang]||tx('Ainda não escolhida','Not chosen yet')}</dd><dt>{tx('Correção','Fix')}</dt><dd>{selectedFix?.text[lang]||tx('Ainda não escolhida','Not chosen yet')}</dd></dl></details><button className="primary" type="submit" disabled={!ready}>{tx('Validar achado e capturar flag','Validate finding and capture flag')}</button>{!ready&&<p>{tx('Escolha evidência, causa e correção antes de validar. Os botões numerados permitem voltar a qualquer etapa.','Choose evidence, cause and fix before validating. Numbered buttons let you return to any step.')}</p>}</>}
 {game.feedback&&feedbackKind==='submit'&&<div className={'td-status '+(feedbackError?'error-message':'')} role="status"><p>{game.feedback[lang]}</p>{feedbackError&&<p>{tx('Retome a regra do caso e confira a evidência antes de mudar sua decisão. Suas três escolhas foram preservadas.','Revisit the case policy and check the evidence before changing your decision. Your three choices were kept.')}</p>}</div>}
 <p className="ctf-scoring">{tx('Só validar uma decisão incorreta desconta','Only submitting an incorrect decision costs')} {difficulty==='easy'?3:difficulty==='normal'?5:8} {tx('pontos. Alterar escolhas antes de enviar é livre.','points. Changing choices before submitting is free.')}</p>
 </form></div></>:difficulty!=='easy'&&analysis===null?<DifficultyAssessment id={short?'a2s':'a2'} difficulty={difficulty} onFinish={setAnalysis}/>:<div className="td-report"><h2 ref={stageHeading} tabIndex={-1}>{tx('Operação concluída · Relatório','Operation complete · Report')}</h2><strong className="td-score">{result.score}/100</strong>{analysis!==null&&<DifficultyScoreDetails core={core.score} analysis={analysis}/>} <p role="status" className={result.passed?undefined:"error-message"}>{result.passed?tx('Aprovado. Melhor resultado salvo.','Passed. Best result saved.'):tx('Todos os casos resolvidos, mas a nota ficou abaixo de 70. Revise as explicações e tente novamente; sem XP nesta tentativa.','All cases solved, but the score is below 70. Review explanations and retry; no XP this attempt.')}</p><p>{game.mistakes} {tx('decisões incorretas','incorrect decisions')} · {game.hints.length} {tx('pistas usadas','hints used')} · {result.xp} XP {tx('máximos nesta tentativa. Repetições só concedem a melhoria da recompensa anterior.','maximum this attempt. Replays only grant improvements over the previous reward.')}</p><p className="game-reflection">{tx('Antes de repetir, escolha um caso resolvido e explique: quem pediu o recurso, qual regra foi violada e como retestar sem impedir o uso legítimo? Confira seu raciocínio na explicação abaixo.','Before replaying, choose a solved case and explain: who requested the resource, which policy was violated and how can you retest without blocking legitimate use? Check your reasoning against the explanation below.')}</p><div className="action-buttons"><button className="secondary" onClick={download}>{tx('Baixar relatório','Download report')}</button><button className="primary" onClick={()=>{paid.current=false;setAnalysis(null);setGame(newCtf(difficulty,short));setProbe('');setEvidence('');setCause('');setFix('');setFindingStep(0);setFeedbackError(false)}}>{tx('Jogar novamente','Play again')}</button></div></div>}

 {game.solved.length>0&&<div className="ctf-debrief"><h2>{tx('Flags e explicações dos casos resolvidos','Flags and solved-case explanations')}</h2>{ctfCases.filter(c=>game.solved.includes(c.id)).map(c=><details className="game-help" key={c.id} open={game.finished?true:undefined}><summary>{tx('✓ Resolvido','✓ Solved')} · {c.title[lang]}</summary><code>{c.flag}</code><p>{c.explanation[lang]}</p></details>)}</div>}
 <details className="td-guide"><summary>{tx('Como a nota funciona e onde estudar','How scoring works and where to study')}</summary><p>{tx('Começa em 100. Só decisões enviadas incorretas e pistas opcionais reduzem a nota; explorar respostas e consultar a aula é livre. Para aprovação e XP, resolva todos os casos do modo escolhido e alcance 70. No intermediário e avançado, uma análise contextual após os casos vale 50% da nota e precisa alcançar 70. A investigação vale os outros 50%. O avançado também exige justificar a causa. As vulnerabilidades simuladas do portal permanecem as mesmas. Nenhuma flag precisa ser digitada ou adivinhada.','Starts at 100. Only incorrect submitted decisions and optional hints reduce the score; exploring responses and consulting lessons are free. For a pass and XP, solve all cases in the selected mode and reach 70. At intermediate and advanced levels, a contextual analysis after the cases counts for 50% and must reach 70. Investigation counts for the other 50%. Advanced also requires explaining the cause. The portal’s simulated vulnerabilities remain the same. No flag needs to be typed or guessed.')}</p><p>{tx('Este é o minigame 08; o CTF final da campanha continua planejado. Testes reais dependem de autorização e escopo próprios.','This is minigame 08; the campaign’s final CTF remains planned. Real tests require their own authorization and scope.')}</p><p><a href="https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · IDOR</a> · <a href="https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · Authorization</a> · <a href="https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · Output safety</a></p></details>
 </section>;
}
