import { describe,it,expect } from 'vitest';
import { ctfCases,ctfResult,hintCtf,newCtf,probeCtf,submitCtf } from './webCtf';
import { initial,normalizeSave,reward,type Difficulty } from './core';
import { modules } from './curriculum';
function solve(s:ReturnType<typeof newCtf>){while(!s.finished){const c=ctfCases[s.stage];const p=c.probes.find(p=>p.proof)!;s=probeCtf(s,p.id);s=submitCtf(s,p.id,c.cause,c.fix)}return s;}
describe('closed Web CTF',()=>{
 it.each(['easy','normal','hard'] as Difficulty[])('requires observed findings and completes all three cases in %s',d=>{const s=solve(newCtf(d));expect(s.solved).toEqual(ctfCases.map(c=>c.id));expect(ctfResult(s)).toMatchObject({score:100,passed:true,correct:3,total:3,xp:{easy:100,normal:150,hard:200}[d]});expect(submitCtf(s,'other','object','server')).toBe(s);expect(probeCtf(s,'own')).toBe(s)});
 it('cannot award from unobserved evidence or incomplete fields; rejects invalid probes',()=>{const s=newCtf('normal');expect(probeCtf(s,'https://external.invalid')).toBe(s);expect(submitCtf(s,'other','object','server')).toMatchObject({stage:0,solved:[],mistakes:0});const p=probeCtf(s,'other');expect(submitCtf(p,'other','','')).toMatchObject({stage:0,mistakes:0});expect(ctfResult(p)).toMatchObject({passed:false,xp:0})});
 it('rejects authorized responses, incorrect causes and cosmetic fixes with useful feedback',()=>{let s=probeCtf(newCtf('normal'),'own');s=submitCtf(s,'own','object','server');expect(s).toMatchObject({stage:0,mistakes:1});s=probeCtf(s,'other');s=submitCtf(s,'other','tls','server');expect(s.mistakes).toBe(2);expect(s.feedback!.pt).toContain('TLS');s=submitCtf(s,'other','object','hide');expect(s.mistakes).toBe(3);s=solve(s);expect(ctfResult(s).score).toBe(85)});
 it('uses hints once per case and applies difficulty-specific penalties',()=>{let s=newCtf('hard');s=hintCtf(hintCtf(s));expect(s.hints).toHaveLength(1);s=solve(s);expect(ctfResult(s).score).toBe(95);expect(ctfResult(solve(hintCtf(newCtf('easy')))).score).toBe(100)});
 it('keeps short practice separate and withholds reward below the threshold',()=>{let s=probeCtf(newCtf('hard',true),'other');for(let i=0;i<4;i++)s=submitCtf(s,'other','tls','server');s=solve(s);expect(ctfResult(s)).toMatchObject({score:68,passed:false,xp:0,total:1,correct:1});expect(ctfResult(solve(newCtf('hard',true)))).toMatchObject({xp:50,correct:1,total:1})});
 it('limits the HTML claim to supplied evidence without claiming proven script execution',()=>{const c=ctfCases[2];expect(c.probes.filter(p=>p.proof)).toHaveLength(1);expect(c.probes.find(p=>p.proof)!.request).not.toContain('script');let s={...newCtf('easy'),stage:2};s=probeCtf(s,'markup');s=submitCtf(s,'markup','proven-xss','text');expect(s.solved).toEqual([]);expect(s.feedback!.pt).toContain('Não houve script')});
 it('migrates v19, rejects new ids in old versions and awards only improvements',()=>{const old={...reward(initial,'a1',100,'hard',false),version:19,avatar:3,placement:true};let s=normalizeSave(old)!;expect(s).toMatchObject({version:22,xp:200,avatar:3,placement:true});s=reward(s,'a2',100,'easy',false);expect(s.xp).toBe(300);expect(reward(s,'a2',100,'easy',false)).toEqual(s);s=reward(s,'a2',100,'hard',false);s=reward(s,'a2s',100,'hard',true);expect(s.xp).toBe(450);expect(normalizeSave(s)).toEqual(s);expect(normalizeSave({...s,version:19})).toBeNull();expect(reward(s,'a2s',100,'hard',false)).toEqual(s);expect(reward(s,'a2',100,'hard',true)).toEqual(s);expect(normalizeSave({...s,xp:550,earned:{...s.earned,a2s:150}})).toBeNull()});
 it('round trips a complete 8000 XP save including both action games',()=>{let s=initial;for(const m of modules){s=reward(s,m.id,100,'hard',false);for(const letter of ['a','b'])s=reward(s,`s${Number(m.label)}${letter}`,100,'hard',true)}for(const id of ['a1','a2']){s=reward(s,id,100,'hard',false);s=reward(s,id+'s',100,'hard',true)}expect(s.xp).toBe(8000);expect(normalizeSave(JSON.parse(JSON.stringify(s)))).toEqual(s)});
});
