import AnswerSelection from './AnswerSelection';
import { useEffect, useRef, useState } from 'react';
import { reward, useSave, type Difficulty } from './core';
import { PixelIcon } from './PixelArt';
import { ctfCases, ctfResult, hintCtf, newCtf, probeCtf, submitCtf } from './webCtf';
export default function WebCtf({difficulty,short,onBack,moving,onTutorial}:{difficulty:Difficulty;short:boolean;onBack:()=>void;moving:boolean;onTutorial:()=>void}){
 const lang=useSave(s=>s.save.lang);const tx=(pt:string,en:string)=>lang==='pt'?pt:en;
 const [game,setGame]=useState(()=>newCtf(difficulty,short));const [feedbackKind,setFeedbackKind]=useState<'hint'|'submit'>('submit');const [feedbackError,setFeedbackError]=useState(false);const [probe,setProbe]=useState('');const [evidence,setEvidence]=useState('');const [cause,setCause]=useState('');const [fix,setFix]=useState('');const paid=useRef(false);const stageHeading=useRef<HTMLHeadingElement>(null);
 const c=ctfCases[game.stage],result=ctfResult(game);const observation=c.probes.find(p=>p.id===probe);
 useEffect(()=>{setProbe('');setEvidence('');setCause('');setFix('');stageHeading.current?.focus()},[game.stage,game.finished]);
 useEffect(()=>{if(!game.finished||paid.current)return;paid.current=true;const store=useSave.getState();store.set(reward(store.save,short?'a2s':'a2',result.score,difficulty,short))},[game.finished,result.score,difficulty,short]);
 function download(){const text=[tx('Relatório educativo · CTF Web NEXUS','Educational report · NEXUS Web CTF'),`${result.score}/100 · ${difficulty} · ${game.mistakes} ${tx('decisões incorretas','incorrect decisions')} · ${game.hints.length} ${tx('pistas','hints')}`,...ctfCases.filter(c=>game.solved.includes(c.id)).map(c=>`${c.title[lang]}\n${c.flag}\n${c.probes.find(p=>p.proof)!.request}\n${c.probes.find(p=>p.proof)!.response[lang]}\n${c.explanation[lang]}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='CYBER-AGENT-CTF.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className={`action-game ctf-game ${moving?'ctf-moving':''}`}><div className="action-heading"><div><div className="eyebrow">{tx('08 / CTF WEB · PORTAL NEXUS','08 / WEB CTF · NEXUS PORTAL')}</div><h1 tabIndex={-1}>{tx('Investigue. Comprove. Corrija.','Investigate. Prove. Fix.')}</h1><p>{short?tx('Treino curto · 1 caso','Short practice · 1 case'):tx('Operação completa · 3 casos','Full operation · 3 cases')} · {difficulty==='easy'?tx('Iniciante','Beginner'):difficulty==='normal'?tx('Intermediário','Intermediate'):tx('Avançado','Advanced')}</p></div><button className="text-button" onClick={onBack}>{tx('Voltar aos minigames','Back to minigames')}</button></div>
 <button className="secondary" onClick={onTutorial}>{tx('Consultar tutorial','Consult tutorial')}</button>
 <div className="ctf-route" aria-label={tx('Progresso dos casos','Case progress')}>{ctfCases.slice(0,short?1:3).map((caseData,i)=><div key={caseData.id} className={game.solved.includes(caseData.id)?'solved':i===game.stage?'active':''}><PixelIcon type="network" size={28}/><span>{caseData.title[lang]}</span><b>{game.solved.includes(caseData.id)?tx('FLAG CAPTURADA','FLAG CAPTURED'):i===game.stage?tx('INVESTIGAR','INVESTIGATE'):tx('AGUARDANDO','WAITING')}</b></div>)}</div>
 <p className="ctf-scope">{tx('Escopo autorizado: somente os três casos fictícios deste painel. As solicitações são escolhas locais, sem acessar servidores. Não há scripts, scanner ou campo para URL externa. Sem cronômetro: você pode consultar a aula e investigar no seu ritmo.','Authorized scope: only the three fictional cases in this panel. Requests are local choices without accessing servers. There are no scripts, scanner or external URL field. No timer: consult the lesson and investigate at your own pace.')}</p>
 {!game.finished?<><article className="action-card"><h2 ref={stageHeading} tabIndex={-1}>{c.title[lang]}</h2><p>{c.brief[lang]}</p><details className="td-guide" key={c.id} open={difficulty==='easy'?true:undefined}><summary>{tx('Aula rápida · Entenda antes de investigar','Quick lesson · Understand before investigating')}</summary><p>{c.lesson[lang]}</p><p>{tx('Roteiro: execute as comparações; leia identidade, resposta e regra esperada; selecione a evidência que demonstra a falha; proponha causa e correção. Consultar a aula não reduz a nota.','Workflow: run comparisons; read identity, response and expected rule; select evidence that demonstrates the flaw; propose a cause and fix. Consulting the lesson does not reduce your score.')}</p></details></article>
 <div className="ctf-workbench"><div className="ctf-console"><h2>{tx('1. Experimente as solicitações','1. Try the requests')}</h2><p>{tx('Cada botão executa uma observação simulada. Compare todas antes de decidir.','Each button runs a simulated observation. Compare them all before deciding.')}</p>{c.probes.map(p=><button key={p.id} className="ctf-request" aria-pressed={probe===p.id} onClick={()=>{setProbe(p.id);setGame(s=>probeCtf(s,p.id))}}><code>{p.request}</code><span>{game.observed.includes(`${game.stage}:${p.id}`)?tx('OBSERVADO','OBSERVED'):tx('EXECUTAR','RUN')}</span></button>)}<div className={"ctf-response "+(observation&&/^4\d\d/.test(observation.response[lang])?"error-message":"")} role="status"><strong>{tx('Resposta simulada','Simulated response')}</strong><p>{observation?.response[lang]||tx('Execute uma solicitação para inspecionar a resposta.','Run a request to inspect its response.')}</p>{observation?.id==='markup'&&<p className="ctf-output"><b>{tx('Olá','Hello')}</b><small>{tx('Representação fixa do resultado; a entrada não é executada.','Fixed representation of the result; input is not executed.')}</small></p>}</div><button className="secondary" onClick={()=>{setFeedbackKind('hint');setGame(hintCtf(game))}}>{game.hints.includes(c.id)?tx('Rever pista','Review hint'):tx('Pedir pista','Ask for hint')}</button>{game.feedback&&feedbackKind==='hint'&&<p className="td-status" role="status">{game.feedback[lang]}</p>}<p className="ctf-scoring">{tx('Pista única por caso:','One hint per case:')} {difficulty==='easy'?tx('gratuita','free'):difficulty==='normal'?'−3':'−5'} {difficulty!=='easy'&&tx('pontos','points')}. {tx('Decisão incorreta:','Incorrect decision:')} −{difficulty==='easy'?3:difficulty==='normal'?5:8} {tx('pontos. Repetir a pista não desconta novamente.','points. Reviewing a hint does not deduct again.')}</p></div>
 <form className="ctf-finding" onSubmit={e=>{e.preventDefault();setFeedbackKind('submit');const next=submitCtf(game,evidence,cause,fix);setFeedbackError(next.solved.length===game.solved.length);setGame(next)}}><h2>{tx('2. Registre o achado','2. Record the finding')}</h2><label>{tx('Evidência observada','Observed evidence')}<select aria-label={tx('Evidência observada','Observed evidence')} value={evidence} required onChange={e=>setEvidence(e.target.value)}><option value="">{tx('Escolha a resposta que demonstra a falha','Choose the response demonstrating the flaw')}</option>{c.probes.map(p=><option disabled={!game.observed.includes(`${game.stage}:${p.id}`)} value={p.id} key={p.id}>{p.request}</option>)}</select></label><fieldset><legend>{tx('Qual é a causa?','What is the cause?')}</legend>{c.causes.map(x=><label className="ctf-choice" key={x.id}><input type="radio" name="ctf-cause" required value={x.id} checked={cause===x.id} onChange={()=>setCause(x.id)}/>{x.text[lang]}<AnswerSelection selected={cause===x.id}/></label>)}</fieldset><fieldset><legend>{tx('Qual correção atua na causa?','Which fix addresses the cause?')}</legend>{c.fixes.map(x=><label className="ctf-choice" key={x.id}><input type="radio" name="ctf-fix" required value={x.id} checked={fix===x.id} onChange={()=>setFix(x.id)}/>{x.text[lang]}<AnswerSelection selected={fix===x.id}/></label>)}</fieldset><button className="primary" type="submit">{tx('Validar achado e capturar flag','Validate finding and capture flag')}</button>{game.feedback&&feedbackKind==='submit'&&<p className={"td-status "+(feedbackError?"error-message":"")} role="status">{game.feedback[lang]}</p>}</form></div></>:<div className="td-report"><h2 ref={stageHeading} tabIndex={-1}>{tx('Operação concluída · Relatório','Operation complete · Report')}</h2><strong className="td-score">{result.score}/100</strong><p role="status" className={result.passed?undefined:"error-message"}>{result.passed?tx('Aprovado. Melhor resultado salvo.','Passed. Best result saved.'):tx('Todos os casos resolvidos, mas a nota ficou abaixo de 70. Revise as explicações e tente novamente; sem XP nesta tentativa.','All cases solved, but the score is below 70. Review explanations and retry; no XP this attempt.')}</p><p>{game.mistakes} {tx('decisões incorretas','incorrect decisions')} · {game.hints.length} {tx('pistas usadas','hints used')} · {result.xp} XP {tx('máximos nesta tentativa. Repetições só concedem a melhoria da recompensa anterior.','maximum this attempt. Replays only grant improvements over the previous reward.')}</p><div className="action-buttons"><button className="secondary" onClick={download}>{tx('Baixar relatório','Download report')}</button><button className="primary" onClick={()=>{paid.current=false;setGame(newCtf(difficulty,short));setProbe('');setEvidence('');setCause('');setFix('')}}>{tx('Jogar novamente','Play again')}</button></div></div>}

 {game.solved.length>0&&<div className="ctf-debrief"><h2>{tx('Flags e explicações dos casos resolvidos','Flags and solved-case explanations')}</h2>{ctfCases.filter(c=>game.solved.includes(c.id)).map(c=><article key={c.id}><code>{c.flag}</code><h3>{c.title[lang]}</h3><p>{c.explanation[lang]}</p></article>)}</div>}
 <details className="td-guide"><summary>{tx('Como a nota funciona e onde estudar','How scoring works and where to study')}</summary><p>{tx('Começa em 100. Só decisões enviadas incorretas e pistas opcionais reduzem a nota; explorar respostas e consultar a aula é livre. Para aprovação e XP, resolva todos os casos do modo escolhido e alcance 70. A dificuldade altera apoio e penalidades, não cria novas vulnerabilidades. Nenhuma flag precisa ser digitada ou adivinhada.','Starts at 100. Only incorrect submitted decisions and optional hints reduce the score; exploring responses and consulting lessons are free. For a pass and XP, solve all cases in the selected mode and reach 70. Difficulty changes support and penalties, not vulnerabilities. No flag needs to be typed or guessed.')}</p><p>{tx('Este é o minigame 08; o CTF final da campanha continua planejado. Testes reais dependem de autorização e escopo próprios.','This is minigame 08; the campaign’s final CTF remains planned. Real tests require their own authorization and scope.')}</p><p><a href="https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · IDOR</a> · <a href="https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · Authorization</a> · <a href="https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" target="_blank" rel="noreferrer">OWASP · Output safety</a></p></details>
 </section>;
}
